[1단계 - 영화 목록 불러오기] 헤일리(최혜림) 미션 제출합니다.
woowacourse/javascript-movie-review pull request #102
Opened 2024-03-21 08:05 UTC by healim01

안녕하세요 케빈! 만나서 반갑습니다! 😆
이번 미션도 잘 부탁드려요!! 

## 우아한테크코스 레벨1 영화관 미션

### ✅ 베포 사이트 

[영화관 미션 바로가기!](https://healim01.github.io/javascript-movie-review/dist/)

![ezgif com-video-to-gif-converter](https://github.com/woowacourse/javascript-movie-review/assets/74346290/05931af9-e4b2-4568-a026-2c6c2d1d8362)

<br>

**📍 학습 목표**
- API 연동을 위한 테스트 환경 경험
- 실제 동작하는 API를 통한 비동기 통신
- UX 경험 개선을 위한 더 보기(페이징) 구현

<br>

### ⛳️ 모듈구조
![모듈구조](https://github.com/woowacourse/javascript-movie-review/assets/74346290/5692f609-44a0-4a6e-95a5-c4a3dd22c3dd)

<br>

### ❗️ 이번 과정에서 집중해서 작업한 부분 

**컴포넌트 생성 유틸** 
반복되는 `createElement` 와 `setAttribute` 작업을 줄이기 위해 `createElementWithAttribute` 이라는 유틸을 생성하여 엘리먼트 생성과 속성 추가를 한번에 작업 할 수 있도록 작업해보았습니다! 

**스켈레톤 UI 작업** 
이번 미션에서 skeleton UI 를 추가하여 데이터가 오기 전 시간을 대기 시간이 아닌 진행 상황처럼 보일 수 있도록 작업해보았습니다. 
다만, 코드 작업을 해보았을 때 생각보다 로딩시간이 짧아서 skeleton UI가 보일 시간이 없다보니 이번 미션에서 일부러 확인을 위해 setTime 작업을 해놓았습니다. 

**debounce 작업** 
연속으로 더보기 버튼을 누르거나, 검색을 시도할 때 api 를 여러번 호출하지 않게 하도록 debouce 작업을 해보았습니다! 
이 작업을 통해 불필요한 잦은 요청을 막아 보았습니다. 

**사용자 경험 향상** 
사용자 경험 향상을 위해 전달받은 데이터 중 사진이 없는 데이터의 경우 사진이 없다고 보여줄 수 있도록 해보았습니다.
또한 검색 결과가 없는 경우, 검색 결과가 없다고 명시하거나, 오류 발생시 사용자에게 오류 메세지를 보여줄 수 있도록 하였습니다. 

<img width="700" alt="스크린샷 2024-03-21 오후 1 15 50" src="https://github.com/woowacourse/javascript-movie-review/assets/74346290/22a210ea-8b12-47fe-bdb0-0c7d8535eb1c">

<br>
<br>

감사합니다!!

2024-03-21 08:37 UTC, healim01 commented
프로세스 순서도도 참조합니다! 

![프로세스](https://github.com/woowacourse/javascript-movie-review/assets/74346290/38953b2f-329e-4954-9ce6-3928e577ea5a)

2024-03-21 16:13 UTC, JeongBin0227 commented
[배포사이트 확인]
사소하지만 정렬을 맞춰주면 좋을거 같아요
<img width="97" alt="image" src="https://github.com/woowacourse/javascript-movie-review/assets/45503248/ea2e61f9-1bda-4a22-9ade-54df36f3590b">

2024-03-21 16:14 UTC, JeongBin0227 commented
[배포사이트 확인]
반응형은 지원이 안되는걸까요??

2024-03-21 16:26 UTC, JeongBin0227 commented
[배포사이트 확인]
nit) 스크롤 중앙에서 새로고침했을때, 계속 보고있는곳을 유지하고 싶은데 어떻게 할수 있을까요?

2024-03-21 16:27 UTC, JeongBin0227 commented
[배포사이트 확인]
더보기 눌렀을때는 스켈레톤이 적용되지 않나요?

2024-03-21 16:29 UTC, JeongBin0227 commented
[배포사이트 확인]
만약 데이터가 20개가 안됐을때는 스켈레톤을 어떻게 처리할수 있을까요?

2024-03-21 16:45 UTC, JeongBin0227 requested changes
안녕하세요 헤일리~

전체적인 평은 구조를 잘 나눠주시고, 컴포넌트를 재상용할수있게 명확하게 나눠주셔서 어디에 어떤 코드가 있을지 예측이 되어서 좋았습니다! 
다만 아쉬운건 중간중간 보이는 오타와 로직상 정상동작 안할거 같은 부분이 보여서 코멘트 드렸습니다

미션하느라 고생많으셨습니다 💯

2024-03-22 05:29 UTC, healim01 commented on cypress/e2e/more-button.cy.js
> +    it("인기 영화 리스트에서 더보기 버튼을 눌렀을 경우,인기 영화 리스트에 20개 이하의 영화가 추가된다.", () => {
앗 반영해서 수정해보도록 하겠습니다~!!

2024-03-23 16:51 UTC, healim01 commented on .github/workflows/main.yml
> +
webpack 읽어보니 우테코에서 준 DotEnv 사용해서 배포되는거 같더라구요!

2024-03-23 17:05 UTC, healim01 commented on cypress/e2e/search-box.cy.js
> +        });
앗 그렇네요! 클래스 추가하도록 하겠습니다!

2024-03-23 17:06 UTC, healim01 commented on src/components/Header.ts
> +  ItemView("지금 인기 있는 영화", dataStateStore.movieData, "popular");
상수처리를 잊었네요! 텍스트들 다 상수처리하도록 하겠습니다!

2024-03-23 19:38 UTC, healim01 commented on src/app.ts
> +  SkeletonView();
스켈레톤 UI 를 먼저 `display: none` 인 상태로 처음에 랜더 해놓고 데이터가 없을 때 `block` 이후 데이터가 들어오면 다시 `none`해주는 형식으로 작업해보았습니다.
계속 데이터 호출 때마다 스캘레톤 UI 다시 생성하는 것이 비효율적이라고 생각이 들어서 이렇게 해보았던거 같습니다.

2024-03-23 19:41 UTC, healim01 commented on src/components/Header.ts
> +  await handleGetPopularMovieData(true);
넵! 해당 호출하는 함수 내부에서 실패시 에러 페이지를 보여 줄 수 있도록 작업해보았습니다!

2024-03-23 19:59 UTC, healim01 commented on src/components/MoreButton.ts
> +  debouceFunc(() => hanldeMovieData(event, listType));
debounce 변수를 함수 외부에 선언하여 사용하고 있어서 괜찮다고 생각했습니다. debounce 함수 내에서 이 변수를 활용하여 setTimeout 타이머를 설정하고 관리하다보니 매 호출마다 debounce 변수가 초기화되지 않고 이전 setTimeout 타이머를 취소할 수 있다고 판단하여 작성해보았던거 같습니다

2024-03-23 20:07 UTC, healim01 commented
안녕하세요 케빈! 
달아주신 코멘트 보고 수정을 해보았습니다! 

추천해주신 스펠링 체크 익스텐션이 이후에도 큰도움이 될거 같아요! 추천해주셔서 감사합니다!! 😊

달아주신 코멘트를 반영해서 오타 수정 및 테스트 코드 중복 코드 리팩토링을 진행하였습니다!
또한 텍스트 상수처리와 타이틀에 클래스를 추가하여 h2 로 찾는 것이 아닌 특정 클래스로 찾을 수 있도록 변경해보았습니다. 
추가적으로 작업해본 것은 스켈레톤 UI 가 사진 로드 될때도 보여지게 작업해보았습니다. 이렇게 변경하다보니 달아주신 코멘트에서 말씀하신 더보기 버튼 후 스켈레톤 작업도 수행할 수 있었던거 같습니다! 스코어 부분 정렬도 작업해두었습니다! 

반응형에 경우에는 2단계 미션에 진행되는거 같아서 2단계에서 적용해보도록 하겠습니다! 

나머지 스켈레톤 UI 랜더 작업 부분은 코멘트에 달아두었습니다!

2024-03-24 11:40 UTC, JeongBin0227 approved these changes
안녕하세요 헤일리!

피드백이 다소 많았는데, 빠르게 반영해주셔서 감사합니다. 그리고 프로세스 순서도도 같이 올려주셔서 전체적인 코드를 이해하는데 좋았습니다 👍 
수정된 코드 모두 확인하였고 코드를 보면서 질문 남겼던 부분 잘 말씀해주셔서 이를 기반으로 2단계도 같이 확인해볼수 있을거 같아요

1단계에서는 이정도 수정하고, 2단계 미션으로 진행하면 될거 같아요! 2단계 미션에서 뵙겠습니다~ 💯 고생하셨습니다 👍

2024-03-24 11:40 UTC, merged