[1단계 - 영화 목록 불러오기] 파슬리(김윤아) 미션 제출합니다.
woowacourse/javascript-movie-review pull request #110
Opened 2024-03-21 08:33 UTC by anttiey

안녕하세요 카일! 1단계 미션 구현을 완료하게 되어 PR 남깁니다 🌱

이번 미션은 특히나 학습 목표를 따라가는 걸 목표로 잡고 기능 요구 사항을 페어인 `지니` 와 함께 해결해 나가는 과정에 집중했어요. 개선이 필요하거나 이해가 되지 않는 부분에는 가감없이 피드백 주시면 감사하겠습니다 🙌🏻

# 👩🏻‍💻 개요

마지막 미션 `영화 리뷰` 1단계 영화 목록 불러오기 코드입니다.

### 배포 페이지
https://anttiey.github.io/javascript-movie-review/

### 실행 방법
```javascript
npm install

// 로컬 환경에서 실행
npm start

// E2E 테스트
npm run test-e2e
```

## ⚙️ 프로젝트 구조
<img width="602" alt="315204040-7a88fa05-b5d6-41c9-86f1-a4f7002e6b65" src="https://github.com/woowacourse/javascript-movie-review/assets/61104776/d338fe66-12ed-463d-8a45-107d53c7b74e">

## 📚 기능 요구 사항 & 해결
### 기능 요구 사항
이번 미션의 주요 목표는 웹 프론트엔드에서의 비동기에 대해 이해하고, API 통신을 처리할 때 고려해야 하는 다양한 문제를 직접 경험해보면서 해결 방법을 고민해보는 것입니다.

- [ ] API 연동을 위한 테스트 환경 경험
- [ ] 실제 동작하는 API를 통한 비동기 통신
- [ ] UX 경험 개선을 위한 더 보기(페이징) 구현

### 1. API를 통한 비동기 통신
![image](https://github.com/woowacourse/javascript-movie-review/assets/61104776/5bae0a2a-c04d-49fd-9321-d14f5f898d06)

다음과 같이 API 레이어를 3단계로 분리해 보았습니다. 

API 통신을 위한 기본적인 틀인 `apiSchema` 클래스를 구성하고 이를 활용하여 필요에 따라 다양한 API를 생성할 수 있도록 하였습니다. 대표적으로 `apiSchema` 클래스를 기반으로 영화 목록 정보를 가져오는 `MovieAPI` 클래스를 만들어 도메인에서 사용하고 있습니다.

### 2. UX 경험 개선
API 통신을 처리하다 보니 다양한 오류가 발생했습니다. 꼭 크리티컬한 오류가 아니더라도 사용자에게 다양한 방향으로 메시지를 전달할 수 있는 방법에 대해 고민하고 적용해 보았습니다.

<details>
<summary><b>검색창에 아무런 검색어도 입력하지 않은 케이스</b></summary>

<hr/>
<img width="344" alt="스크린샷 2024-03-21 오후 4 50 12" src="https://github.com/woowacourse/javascript-movie-review/assets/61104776/d472e047-2448-4d73-b8c0-5fd2b6b3a693">
<br />

검색창에 아무런 검색어도 입력하지 않고 엔터를 치거나, 검색 버튼을 누르게 되면 `Toast 메시지` 가 출력됩니다. 해당 메시지는 1초 이후 사라집니다.
</details>

<details>
<summary><b>검색 결과가 없는 케이스</b></summary>

<hr/>
<img width="996" alt="스크린샷 2024-03-21 오후 4 59 28" src="https://github.com/woowacourse/javascript-movie-review/assets/61104776/981b795d-2a59-4805-9d51-0b253e6bb814">
<br />

검색창에 검색한 단어에 대한 검색 결과가 없는 경우에는 `텅 이미지` 를 출력합니다. 사용자가 단번에 검색 결과가 존재하지 않다는 걸 파악할 수 있도록 구성했습니다.
</details>

<details>
<summary><b>API 통신 오류가 발생한 케이스</b></summary>

<hr/>
<img width="542" alt="스크린샷 2024-03-21 오후 5 04 02" src="https://github.com/woowacourse/javascript-movie-review/assets/61104776/3e369e19-02ad-4f67-84b1-57796dd006df">
<br />

API 통신 중 오류가 발생하면 `에러 모달` 을 발생시킵니다. 사용자가 시스템에 오류가 발생했다는 사실을 파악하고 `다시 시도하기` 버튼을 통해 리로드할 수 있도록 구성했습니다.
</details>

이와 함께 **`로고 클릭 시 페이지 새로고침`**, **`검색 결과가 20개 미만인 경우 더보기 버튼 제거`**, **`페이지 끝에 도달한 경우 더보기 버튼 제거`** 등 자잘한 UX를 개선해 보았습니다.

<hr />

잘 부탁드립니다 ☺️

2024-03-21 13:39 UTC, GwangYeol-Im requested changes
안녕하세요 파슬리 🌿 전반적으로 타입과 레이어 등 모든 부분에서 의미있는 코드와 구조를 작성하시려는 흔적이 보여 좋았습니다. 요구사항 외에 ux 적으로 필요하다고 생각되는 부분도 잘 보강해주신 듯 해요! 디테일한 부분에서 리뷰 남겨두었으니 확인 부탁드립니다 :)

2024-03-21 13:39 UTC, GwangYeol-Im commented on src/utils/dom/selector.ts
> +    throw new Error('[ERROR] 요소를 찾을 수 없습니다.');
에러 메시지에 selector를 넣어주면 어떤 요소를 찾을 수 없는지 더 잘 찾을 수 있을 것 같아요~

2024-03-21 13:39 UTC, GwangYeol-Im commented on src/utils/dom/eventListener/eventListener.ts
기존의 이벤트 리스너 관련 함수를 한번더 래핑하여 사용하는 이유가 있으실까요? 현재의 구현은 기존 메서드의 사용성에 제약을 주고 있고 `on`, `off`라는 명칭이 기존의 이름보다 덜 명확하다는 생각이 들어서요!

2024-03-21 13:39 UTC, GwangYeol-Im commented on src/domain/Movie/Movie.type.ts
> +  poster_path: string;
개인적인 의견일 수는 있지만, 프론트엔드 내의 코드 대부분은 스네이크 케이스를 잘 사용하지 않는 추세라고 봅니다. 카멜 케이스로 처리해줘도 괜찮을 듯 하네요! (현재 미션에는 적용 안하셔도 됩니다~)

2024-03-21 13:39 UTC, GwangYeol-Im commented on src/domain/Movie/Movie.ts
> +  constructor(private page: number, private movieType: string) {
여기서 인자로 `page`를 받는 이유가 무엇인가요? 딱히 사용되는 곳이 없어보여서요!

2024-03-21 13:39 UTC, GwangYeol-Im commented on src/domain/Movie/Movie.ts
> +    onSuccess: (data: BaseResponse<MovieDetail[]> | undefined) => void;
`onSuccess` 콜백에서 `data`가 `undefined`일 수도 있는 이유가 따로 있을까요?

2024-03-21 13:39 UTC, GwangYeol-Im commented on src/apis/movie/movie.ts
> +    return type === 'popular' ? `${process.env.BASE_URL}/movie/popular` : `${process.env.BASE_URL}/search/movie`;
url path에 해당하는 api 함수를 각각 만들어 관리하는 것이 좋지 않을까요? `/movie/popular`와 `/search/movie`는 다른 관심사를 가지고 있는 듯 한데, 어떻게 생각하시나요?

2024-03-21 13:39 UTC, GwangYeol-Im commented on src/components/movie/ErrorToast/ErrorToast.ts
> +    }, 500);
이런 부분도 상수로 관리하면 좋을 것 같아요!

2024-03-21 13:39 UTC, GwangYeol-Im commented on src/components/movie/MovieReviewBody/MovieReviewBody.ts
> +        if (data.results.length < 20) this.removeMoreButton();
여기도 상수로 관리가 필요해보이네요~

2024-03-22 07:35 UTC, anttiey commented on src/utils/dom/selector.ts
> +    throw new Error('[ERROR] 요소를 찾을 수 없습니다.');
확실히 에러 메시지에 `selector` 를 추가하면 개발자에게 훨씬 더 명확한 정보를 전달할 수 있을 것 같습니다 🙌🏻

```javascript
if (!element) {
	throw new Error(`[ERROR] ${selector} 요소를 찾을 수 없습니다.`);
}
```

위와 같이 변경해 보았어요! [b1eb0be](https://github.com/woowacourse/javascript-movie-review/pull/110/commits/b1eb0bee82604157c1d24746ad9731b386079654)

2024-03-22 07:38 UTC, anttiey commented on src/utils/dom/eventListener/eventListener.ts
`DOM` 접근과 관련된 함수를 모두 유틸 함수로 분리하면서 일관성을 위해 `eventListener` 도 함께 래핑해 주었습니다. 그렇지만 다시 보니 어차피 값을 인자로 다 넘기고 있어서 코드가 깔끔하지도 않고, 기존 메소드의 사용성도 해치는 결과가 되었네요.

`addEventListener` 를 그대로 사용하도록 코드를 변경했습니다! [026d377](https://github.com/woowacourse/javascript-movie-review/pull/110/commits/026d3775ec61939a0ec40bc8da8b0f64cc4ec4b3)

2024-03-22 07:40 UTC, anttiey commented on src/domain/Movie/Movie.ts
> +  constructor(private page: number, private movieType: string) {
원래는 인자로 `page` 값을 받아서 초깃값을 설정하고자 설계했었는데 `Movie` 안에서 초깃값을 설정하려고 변경하는 과정에서 지우는 걸 잊었네요 😅💧

필요하지 않은 인자를 삭제했습니다! [589d202](https://github.com/woowacourse/javascript-movie-review/pull/110/commits/589d20201a9b4a111f20260a0a858567895e79ab)

2024-03-22 07:42 UTC, anttiey commented on src/domain/Movie/Movie.ts
> +    onSuccess: (data: BaseResponse<MovieDetail[]> | undefined) => void;
에러가 발생하면 `API Layer` 에서 `undefined` 를 반환한다고 생각하고 타입을 설정했는데 그렇지 않네요 💦

불필요한 `undefined` 타입을 제거했습니다! [3212e97](https://github.com/woowacourse/javascript-movie-review/pull/110/commits/3212e978a3e7c23947cca4aea616e31a97033fd4)

2024-03-22 07:45 UTC, anttiey commented on src/apis/movie/movie.ts
> +    return type === 'popular' ? `${process.env.BASE_URL}/movie/popular` : `${process.env.BASE_URL}/search/movie`;
관심사 분리의 관점에서 생각해 보지 못했어요...! 🙌🏻 단순히 하나의 함수에서 관리하면 좋겠다고 생각했는데 카일의 말대로 `/movie/popular` 와 `/search/movie` 는 서로 다른 관심사를 가지고 있는 것 같네요. 지금과 같은 구조에서는 나중에 `movie` 와 관련된 새로운 API가 생겼을 때 확장하기도 힘들 것 같아요.

API 함수를 분리해 보았습니다! [ed6fb55](https://github.com/woowacourse/javascript-movie-review/pull/110/commits/ed6fb55f4e55c57adfd0d7a556515c1792644eef)

2024-03-22 07:48 UTC, anttiey commented on src/components/movie/MovieReviewBody/MovieReviewBody.ts
> +        if (data.results.length < 20) this.removeMoreButton();
피드백을 토대로 관리가 필요한 매직 넘버들을 정리하여 상수로 처리해 보았어요! ☺️

[2b7180d](https://github.com/woowacourse/javascript-movie-review/pull/110/commits/2b7180d08fe65fd5d06abd15236c853cf98614c4) [be261e7](https://github.com/woowacourse/javascript-movie-review/pull/110/commits/be261e7f5473ab414ff06ca72741a51b596190fb)

2024-03-22 07:59 UTC, anttiey commented on src/domain/Movie/Movie.type.ts
> +  poster_path: string;
지금은 `TMDB` 에서 가져오는 데이터 형식에 맞춰 타입을 작성해 주어서 `스네이크 케이스` 를 사용하게 되었는데, 스네이크 케이스와 별개로 이렇게 하나의 API에 종속된 타입을 설정해 주면 추후 변경이 발생했을 때 탄력적인 대응이 불가능할 거란 생각이 들어요. API와 독립적인 도메인 규격을 만드는 방법에 대해 고민해 보도록 하겠습니다! 🧐💡

2024-03-23 09:59 UTC, anttiey commented
피드백 주셔서 감사합니다! 다음과 같이 피드백 반영해 보았어요 ☺️🔥

### 피드백 반영 사항

- [x] 불필요한 래핑 함수를 삭제했습니다. [026d377](https://github.com/woowacourse/javascript-movie-review/pull/110/commits/026d3775ec61939a0ec40bc8da8b0f64cc4ec4b3)
- [x] 불필요한 변수 및 타입을 삭제했습니다. [589d202](https://github.com/woowacourse/javascript-movie-review/pull/110/commits/589d20201a9b4a111f20260a0a858567895e79ab) [3212e97](https://github.com/woowacourse/javascript-movie-review/pull/110/commits/3212e978a3e7c23947cca4aea616e31a97033fd4)
- [x] `Movie API` 를 관심사 별로 분리했습니다. [ed6fb55](https://github.com/woowacourse/javascript-movie-review/pull/110/commits/ed6fb55f4e55c57adfd0d7a556515c1792644eef)
- [x] 에러 메시지를 더욱 명확하게 작성했습니다. [b1eb0be](https://github.com/woowacourse/javascript-movie-review/pull/110/commits/b1eb0bee82604157c1d24746ad9731b386079654)
- [x] 관리가 필요한 매직 넘버들을 상수로 처리했습니다. [2b7180d](https://github.com/woowacourse/javascript-movie-review/pull/110/commits/2b7180d08fe65fd5d06abd15236c853cf98614c4) [be261e7](https://github.com/woowacourse/javascript-movie-review/pull/110/commits/be261e7f5473ab414ff06ca72741a51b596190fb)

### 추가 변경 사항
- [x] 클래스 및 함수의 이름을 목적에 맞도록 변경했습니다. [b10d93c](https://github.com/woowacourse/javascript-movie-review/pull/110/commits/b10d93ca6d4836c25bc72d0c27add10a353eddf1)

2024-03-25 11:16 UTC, GwangYeol-Im commented on src/domain/Movie/Movie.type.ts
> +  poster_path: string;
오호.. 현재 진행중인 단계에 비해 꽤 깊은 수준의 고민을 하고 계시는 군요! 그 부분은 일리있는 말씀이라고 생각합니다. 클라이언트에서 서버에서 내려오는 응답 구조에 바로 의존성을 갖기보다는, 서버 응답-> 클라에서 사용할 모델로 변환해주는 레이어를 두어 느슨한 의존성을 갖게하여 탄력적으로 대응하는 게 괜찮을 듯 싶습니다.

2024-03-25 11:18 UTC, GwangYeol-Im commented on src/apis/movie/movie.ts
> +    return type === 'popular' ? `${process.env.BASE_URL}/movie/popular` : `${process.env.BASE_URL}/search/movie`;
네 현재는 사용해야하는 api가 두 개라서 그렇게 느끼기 쉬웠을 것 같습니다 ㅎㅎ 나중에 react-query와 같은 비동기 상태 관리 라이브러리 등을 사용하거나 더 많은 api를 관리해야할 경우가 생기면 해당 부분 체감이 더 와닿지 않을까 싶네요!

2024-03-25 11:21 UTC, GwangYeol-Im approved these changes
안녕하세요 파슬리~ 리뷰 반영사항 모두 확인했습니다! 바로 다음 미션으로 가시면 될 듯 하여 머지할게요 ㅎㅎ 다음 미션도 기대하겠습니다. 😀

2024-03-25 11:22 UTC, merged