[1단계 - 영화 목록 불러오기] 렛서(김다은) 미션 제출합니다.
woowacourse/javascript-movie-review pull request #113
Opened 2024-03-21 08:40 UTC by llqqssttyy

안녕하세요, 지그! 영화 리뷰 미션 리뷰를 받게 된 렛서라고 합니다.
리뷰 잘 부탁드립니다!

## 실행 방법
> ✅ 이번 미션은 환경 변수 사용으로 인해 로컬 실행, 테스트가 정상 작동하지 않을 수 있습니다!
> ✅  환경 변수에 들어갈 내용을 DM으로 보내드릴테니 참고해 주세요.

```bash
# 로컬 실행
npm run start

# 테스트 실행
npm run test-e2e
```

[🔗 배포 링크](https://llqqssttyy.github.io/javascript-movie-review/)

<br/>

---

## 📍 학습 목표
- 웹 프론트엔드에서의 비동기에 대해 이해한다. 
- API 통신을 처리할 때 고려해야 하는 다양한 문제를 직접 경험해보면서 해결 방법을 고민해본다.
	- API 연동을 위한 테스트 환경 경험
	- 실제 동작하는 API를 통한 비동기 통신
	- UX 경험 개선을 위한 `더 보기`(페이징) 구현

<br/>

## 🎯 구현한 기능
### 1. 🎬 영화 목록 조회 (인기순)

- 영화 목록의 1페이지를 불러오며 `더보기` 버튼을 누르면 그 다음의 영화 목록을 불러 올 수 있다.
    - 페이지 끝에 도달한 경우에는 `더보기` 버튼을 화면에 출력하지 않는다.
    - 영화 목록은 20개씩 보여준다. 
- 영화 목록 아이템에 대한 Skeleton UI를 구현한다.

### 2. 🔎 검색

- 내가 보고 싶은 영화를 검색할 수 있다.
	- 화면 요구사항은 영화 목록 조회와 동일하다.
    - 엔터키를 눌러 검색할 수 있다.
    - 검색 버튼을 클릭하여 검색할 수 있다.
    - 검색어를 입력한 후 검색어를 모두 지우면 인기 영화 목록 조회로 돌아온다.

### 3. ⚠️ 오류

- 영화를 검색할 때 검색 결과가 없으면 오류 메세지를 출력한다.
- API 통신 결과 400, 500번대 에러가 발생한 경우 오류 메세지를 출력한다.

<br/>

---

## 📂 폴더 구조

| 폴더명          | 설명                       |
| ------------ | ------------------------ |
| components   | 컴포넌트를 관리                 |
| constants    | 상수(API 요청에 필요한 값)을 관리    |
| services     | API 요청을 관리               |
| statics/imgs | 이미지 파일을 관리               |
| stores       | 여러 컴포넌트에서 사용하는 state를 관리 |
| types        | 프로젝트에서 사용되는 type을 관리     |
| utils        | 유틸리티 함수를 관리              |

<br/>

---

## 새로 알게된 부분

- `isComposing` 프로퍼티
`<input/>` 태그의 `keydown` 이벤트를 사용하는 중 한글로 입력했을 때 해당 이벤트가 2번 발생하는 현상을 발견했습니다.
원인을 찾아 본 결과 한글은 조합 문자이기 때문에 두 가지 경우에서 keydown 이벤트가 발생하는 것을 알게 됐습니다.
- 자소를 각각 입력할 때
- 조합이 완료되었을 때

따라서 코드에 이벤트 객체의 `isComposing` 프로퍼티가 false인 경우에만 이벤트 처리 코드가 실행되도록 했습니다.

2024-03-21 12:11 UTC, zigsong requested changes
안녕하세요, 렛서! 리뷰를 맡은 지그입니다.

API 통신을 이용한 복잡한 앱을 잘 구현하셨네요 👍 

부분부분 개선할 사항들이 보여 코멘트 남겼습니다. 확인 부탁드려요!

2024-03-21 12:11 UTC, zigsong commented on src/components/Header/Header.css
> +  text-indent: -1000rem;
`text-indent`라는 속성도 있군요 😲 (작년에 추가됐군요)

2024-03-21 12:11 UTC, zigsong commented on src/components/Header/Header.css
> +  text-indent: -1000rem;
이걸 왜 `-1000rem`까지 주면서 작성해봤나, 한번 삭제해봤더니 `<button>` 태그의 textContent에 '검색'이라는 글자를 숨기려고 하신 것 같네요. 그냥 그 '검색'이라는 글자를 제거하면 안되나요? 

이런 극단적인(ㅎㅎ) CSS는 나중에 분명 사이드이펙트를 초래합니다.

2024-03-21 12:11 UTC, zigsong commented on src/components/Main/Main.ts
> +        clearItemViewForError();
- 결과가 empty한지 확인하고
- 현재 page를 확인하여 어떤 페이지부터 fetch해올지 결정하고
- 에러 처리까지 해주는 것

까지가 전부 Main의 역할일까요?

2024-03-21 12:11 UTC, zigsong commented on src/components/MovieItem/MovieItem.ts
> +}: Pick<Movie, 'title' | 'poster_path' | 'vote_average'>) => {
`Pick` utility type을 잘 활용하셨네요 ☺️

2024-03-21 12:11 UTC, zigsong commented on src/components/MovieItem/SkeletonMovieItem.ts
> +  $anchor.href = '#';
skeleton까지 굳이 `a` 태그로 만들 필요는 없을 것 같습니다. ;)

2024-03-21 12:12 UTC, zigsong commented
참고로 제가 금주 3/22(금)~3/24(일) 부재로 리뷰가 어려울 것 같습니다. 리뷰 반영해주시면 월요일에 빠르게 보도록 할게요. 미리 양해 말씀 드립니다 🙇‍♀️

2024-03-24 15:38 UTC, llqqssttyy commented on src/components/Header/Header.css
> +}
좋은 아이디어 감사합니다, 지그! 반영하여 [커밋](https://github.com/woowacourse/javascript-movie-review/pull/113/commits/c0092fa5edb8aa5266939d7314a580c1fd615f86) 올렸습니다.

2024-03-24 16:18 UTC, llqqssttyy commented on src/components/SearchInput/SearchInput.ts
> +        }),
input의 값이 다시 공백으로 돌아왔을 때 인기 영화 목록이 조회되는 것을 의도했습니다!

2024-03-25 07:45 UTC, llqqssttyy commented on src/components/SearchInput/SearchInput.ts
> +      }),
detail 객체를 사용해서 다른 컴포넌트에 값을 전달하는 목적으로 `CustomEvent`를 사용했는데, MovieList에 재렌더링 함수를 만들어 매개변수로 전달하는 방식으로 고칠 수 있을 것 같다는 생각이 듭니다.
이렇게 되면 Main 컴포넌트를 포함해서 MovieList 컴포넌트도 상당히 많은 부분이 변경되어야 할 것 같아서 시간이 조금 더 필요합니다. 양해를 구해도 될까요?🥲

2024-03-25 07:49 UTC, llqqssttyy commented on src/components/MovieList/SkeletonMovieList.ts
> +    $title.textContent = title;
현재 구현된 방식이 Skeleton 컴포넌트가 MovieList 컴포넌트(title과 ul이 있는 컴포넌트)를 완전히 대체하는 형식이라 이렇게 구현하게 되었습니다. 
저 또한 이 문제점을 인지하고 있어서 MovieList의 ul 안 내용물이 바뀌는 것으로 구현 방식을 변경해보겠습니다!

2024-03-25 07:50 UTC, llqqssttyy commented on cypress/e2e/loadMoreButton.spec.ts
> +    expect(popularMovieItems.should('have.length', 40));
컴포넌트에서 PAGE_SIZE라는 상수를 사용하고 있어서, 해당 상수를 임포트하는 것으로 변경했습니다! 
좋은 피드백 감사합니다.

([관련 커밋](https://github.com/woowacourse/javascript-movie-review/pull/113/commits/6574f06a50fe56539cb2f93b6c6e5c03735ed1df))

2024-03-25 07:51 UTC, llqqssttyy commented on cypress/e2e/popular.spec.ts
> +    cy.get('@popularMovies').its('status').should('eq', 200);
테스트 코드 안에 `STATUS_CODE`라는 상수를 만드는 것으로 변경했습니다!

([관련 커밋](https://github.com/woowacourse/javascript-movie-review/pull/113/commits/6574f06a50fe56539cb2f93b6c6e5c03735ed1df))

2024-03-25 07:52 UTC, llqqssttyy commented on src/components/MovieItem/SkeletonMovieItem.ts
> +  $anchor.href = '#';
SkeletonMovieList 컴포넌트와 동일하게 Skeleton에 어떤 내용이 들어가야 할지 좀 더 고민해봤어야 했네요🥲
a를 제거하여 커밋했습니다!

([관련 커밋](https://github.com/woowacourse/javascript-movie-review/pull/113/commits/4fbedbeec24da036f6d0612d30415af82be79749))

2024-03-26 13:03 UTC, llqqssttyy commented on src/components/Main/Main.ts
> +      })
시도해보겠습니다..!

2024-03-26 13:28 UTC, llqqssttyy commented on src/components/SearchInput/SearchInput.ts
> +    $searchInput.type = 'text';
`search`라는 type이 있는지 몰랐네요! 찾아 보니 다음과 같은 추가 기능이 있다는 사실을 알았습니다.
- esc 혹은 x 버튼을 통해 input의 값을 한꺼번에 지움(비표준인 `search` 이벤트 발생)
- 브라우저, 운영체제에 따른 스타일 차이

새로운 사실을 알아가서 기쁩니다. 감사해요 지그!

([관련 커밋](https://github.com/woowacourse/javascript-movie-review/pull/113/commits/8eea3cc64ecc5686e5c5d8e7e14ada3453668ffe))

2024-03-26 14:12 UTC, llqqssttyy commented on src/components/SearchInput/SearchInput.ts
> +    const { key } = e as KeyboardEvent;
keydown 이벤트가 빠지면서 코드에 반영되지는 않았지만 좋은 팁 알려주셔서 감사합니다!

말씀해주신 대로 다른 이벤트 핸들러에도 이벤트 타입을 명시해주었는데, target의 타입이 `EventTarget` 또는 `null`로 인식되어 에러가 발생합니다.🥲

```js
$searchBox.addEventListener('submit', (e: SubmitEvent) => {
    e.preventDefault();

    const { target } = e;
    const formData = new FormData(target); // Error: Argument of type 'EventTarget | null' is not assignable to parameter of type 'HTMLFormElement | undefined'.
```

이를 해결하기 위해서 아래 코드처럼 `as`를 사용해줘야 하는데, 이런 경우에 타입 단언을 사용하는 건 어떻게 생각하시나요?
```js
$searchBox.addEventListener('submit', (e: SubmitEvent) => {
    e.preventDefault();

    const formElement = e.target as HTMLFormElement;
    const formData = new FormData(formElement);
```

2024-03-26 14:18 UTC, llqqssttyy commented on src/components/Header/Header.css
> +  text-indent: -1000rem;
다음부터는 템플릿 코드가 합리적으로 작성되었는지 검토하는 연습을 하겠습니다.😅

textContent를 지우고, `button` 태그 안에 `img` 태그를 추가하여 스타일링하는 것으로 수정했습니다!

([관련 커밋](https://github.com/woowacourse/javascript-movie-review/pull/113/commits/cd7a648bfd0e54d127f96d0e04ae2219b7f5b95b))

2024-03-26 14:29 UTC, llqqssttyy commented
안녕하세요, 지그. 렛서입니다.
기다리셨을텐데 너무 늦게 리뷰 요청하여 죄송합니다.🥲

아직 모든 피드백을 반영하진 못했지만 지그가 기다리실 것 같아 중간 점검 차 요청 보냅니다.
아래 반영 완료한 피드백과 수정 중인 피드백을 정리했습니다. 검토에 참고해 주세요!

### 반영 완료한 피드백
- skeleton 컴포넌트에서 불필요한 태그 제거 ([↗️ 코멘트로 가기](https://github.com/woowacourse/javascript-movie-review/pull/113#discussion_r1537167227))
- 테스트 코드에서 매직 넘버 제거 ([↗️ 코멘트로 가기](https://github.com/woowacourse/javascript-movie-review/pull/113#discussion_r1537165692))
- 헤더의 `cursor` 스타일에 맞춰 클릭 시 메인 페이지로 돌아가는 인터랙션 추가 ([↗️ 코멘트로 가기](https://github.com/woowacourse/javascript-movie-review/pull/113#discussion_r1536844702))
- `input type="search"` 사용하기 ([↗️ 코멘트로 가기](https://github.com/woowacourse/javascript-movie-review/pull/113#discussion_r1539233260))
- ` text-indent: -1000rem` 제거하기 ([↗️ 코멘트로 가기](https://github.com/woowacourse/javascript-movie-review/pull/113#discussion_r1539344734))

### 반영 중인 피드백
- `Main`이 가진 책임을 다른 컴포넌트에 적절히 분배
- ErrorMessage를 DOM에 부착하는 역할 분배
- 중복 로직 제거

현재 위 피드백을 반영하기 위해 리팩토링을 하고 있습니다. 진행 상황은 다음과 같습니다.
- api 요청을 수행하는 `fetchData` 유틸리티 함수에서 `onError`, `onSuccess`, `onLoading` 세 가지 콜백 함수를 받도록 수정(완료)
- `Main`에서 데이터 패치하는 로직 및 `MovieList`의 프로퍼티로 데이터를 전달하는 로직을 제거(완료)
- `movieStore`에서 인기 영화 데이터와 검색 결과 데이터 상태를 따로 관리하도록 변경(진행 중)

2024-03-27 02:46 UTC, zigsong commented on src/components/SearchInput/SearchInput.ts
> +    const { key } = e as KeyboardEvent;
1. 우선 target의 타입이 `EventTarget` 또는 `null`로 인식될 때는, `null`일 때는 다음 동작을 하지 못하도록 early return 등을 통해 가드를 해줘야 합니다.

2. 지금 submit 이벤트의 `target`을 가져다가 `FormData`로 만드려고 한 것이 더 문제같은데요, CustomEvent로 search를 만들어 detail에 `formData.get('movie-search')`을 전달하는 대신, `<form>` 내부 `<input>`의 값을 가져다가 사용하는 방법을 알아보시는 게 좋을 것 같습니다.

2024-03-27 02:46 UTC, zigsong commented on src/components/SearchInput/SearchInput.ts
> +        }),
아하 섬세한 UX네요! 😉

2024-03-27 02:47 UTC, zigsong commented on src/components/SearchInput/SearchInput.ts
> +      }),
넵! 2단계를 진행하시면서 마저 리팩토링 진행해보시죠 💪

2024-03-27 02:48 UTC, zigsong commented on src/components/MovieList/SkeletonMovieList.ts
> +    $title.textContent = title;
요것도 2단계를 진행하시면서 같이 진행해보는 것이라고 알고 있을게요 :)

2024-03-27 02:48 UTC, zigsong commented on src/components/ErrorMessage/ErrorMessage.ts
> +  $itemView?.appendChild($errMsg);
요것도 수정하실 계획인가요? @llqqssttyy

2024-03-27 02:51 UTC, zigsong approved these changes
안녕하세요 렛서, 리뷰 잘 반영해주셔서 감사합니다! 

앱의 구조를 전반적으로 바꿔야 하는 부분들에 대해 리팩토링중이시라고 했는데,

2단계 미션을 진행하면서 함께 하는 것이 더 편할 것 같아 우선 어프루브하겠습니다.

2단계 PR에서 확인하러 오겠습니다 🤓

2024-03-27 02:52 UTC, merged

2024-03-27 05:58 UTC, llqqssttyy commented on src/components/ErrorMessage/ErrorMessage.ts
> +  $itemView?.appendChild($errMsg);
네 수정 중입니다!