[1단계 - 영화 목록 불러오기] 세인(이세민) 미션 제출합니다.
woowacourse/javascript-movie-review pull request #12
Opened 2023-03-16 08:19 UTC by semnil5202

2023-03-16 16:52 UTC, lsw1164 requested changes
안녕하세요 세인, 코드 잘봤습니다.

### 궁금한 점
> * 렌더링이 비효율적인지 궁금합니다. Skeleton UI를 API 통신동안 렌더링 해준 후 API 통신이 완료되면 받아온 데이터 값으로 영화 리스트를 렌더링 해주고 있습니다. 정확히는 렌더링했던 스켈레톤 UI를 제거한 뒤 영화 리스트를 그려주고 있는데 해당 방식이 괜찮은지 궁금합니다!


옵저버 패턴으로 구독해 놓은 메서드가 다 호출되다 보니까 렌더링이 많이 발생하고 있어요.  
(나쁘다고 생각하지 않고요ㅎㅎ 지금의 구조를 선택하면서 발생한 트레이드 오프라고 생각해요)

물론, 불필요한 렌더링을 줄이는 작업은 유의미한 시도라고 봅니다.  
다른 구현 사항과 UX 개선이 더 중요한 우선순위니까 추가로 시간이 남는다면 렌더링 조건 최적화도 더 고민해보면 좋겠어요!  


> * 구현한 미션에서 UX가 불편한 부분에 대해서 알고 싶습니다!

[스켈레톤 표시 조건 변경]
API 통신 동안만 스켈레톤 UI를 보여주고 있어요.  
이미지 로딩이 완전히 끝나지 않았다면 스켈레톤 UI가 보이는 게 좋겠죠.  
또한, 이미지 로딩 속도에 따라 일부 이미지는 빨리 로드되고 일부 이미지는 늦게 로드될 수 있습니다.  지금은 모든 이미지를 일괄적으로 처리하고 있어요.   
어떻게 개선할 수 있을까요?

2023-03-16 16:52 UTC, lsw1164 commented on src/domain/Movies.ts
> +  }
처음에 loading을 알리고 있군요.  
만약 중간에 에러가 발생하거나 함수가 종료되면 영원히 loading 중인가요?

2023-03-16 16:52 UTC, lsw1164 commented on src/components/MovieItem.ts
> +  template({ id, poster_path, title, vote_average }: any) {
any 대신 타입 지정해보면 좋을 거 같군요

2023-03-16 16:52 UTC, lsw1164 commented on src/components/MovieList.ts
> +}
1. 비동기 함수가 아닌 거 같은데 async 한정자를 써주셨군요🤔
2. 타입도 any로 돼있는데 수정하면 좋을 거 같아요!

2023-03-19 13:31 UTC, semnil5202 commented on cypress/e2e/app.cy.js
> +        expect(movieItems.length).to.equal(10);
fixture의 title 값을 활용해서 진행해보겠습니다!

2023-03-19 19:10 UTC, semnil5202 commented on src/domain/api/index.ts
> +  if (alertAPIError(fetchingData.status)) return;
여러 시도를 해보았는데 타입 문제로 쉽게 해결이 안 되네요..ㅠ

any 타입을 쓰더라도 함수를 호출하는쪽에서 타입 에러를 반환해서 이 부분은 조금 더 학습해본 후 적용해보겠습니다!!

2023-03-19 21:34 UTC, semnil5202 commented
안녕하세요 리트! 주말 잘 보내셨나요?? 😊😊

리뷰는 정말 빠르게 해주셨는데 제가 리팩토링을 너무 늦게 시작했네요 ㅠ

솔직히 주말에 열심히 놀았습니다..! 열심히 논 만큼 남은 기간동안 열심히 리팩토링해볼께요!! 😇💪

### 리팩토링 내용
- [x] 이미지 로딩에 따른 스켈레톤 UI 표시 여부
- [x] 전반적인 타입명 변경
- [x] any, object 타입 수정
- [x] private 접근제어자 설정
- [x] 초기 loading 후 일정시간 경과시 에러 alert 발생
- [x] 불필요한 async 제거
- [x] 영화 타이틀로 영화 검색 기능 검증
- [x] 영화 포스터가 없을 경우 대체 이미지로 렌더링
- [ ] api 호출부에서 예외 처리 검증 로직(alert) 분리 ([코멘트](https://github.com/woowacourse/javascript-movie-review/pull/12#discussion_r1141451222))

### 궁금한 점

#### Q1
말씀해주신 '이미지 로딩 전까지 스켈레톤 UI 표시하는 기능'을 구현하는데 생각보다 오랜 시간이 걸렸습니다.

걸린 시간에 비해 해결 방법은 약간 얼렁뚱땅의 느낌이 있습니다.. 🤔

기존의 img 태그 class에 skeleton 속성을 추가하기만 했습니다. API 통신이 끝난 후 img src가 채워지기 때문에 이전의 스켈레톤 배경 속성은 덮어씌워지기에 그렇습니다.

이런 방식도 괜찮은지 궁금합니다!

추가로 홈페이지 접속 시, 더 보기 버튼을 눌렀을 시에 20개씩 스켈레톤 UI를 렌더링하는 로직을 제거하지 않았습니다.

그 이유는 더 보기 버튼을 눌렀을 때 API 통신이 끝나야 DOM에 추가로 영화 아이템들이 그려지는데, 이 시간동안 홈페이지가 정지해있어 마치 렉이 걸린 듯한 느낌을 받았기 때문입니다. 아래 영상에서 체감이 되실까요?

#### 스켈레톤 UI를 20개씩 미리 생성할 때
https://user-images.githubusercontent.com/89172499/226210871-fc187dcf-8045-4065-b446-ddefa5e8d269.mp4

#### 스켈레톤 UI를 API 통신 후 영화리스트 갯수 만큼 생성할 때
https://user-images.githubusercontent.com/89172499/226210876-d06bae7c-620d-4d99-badb-d457ebcff85d.mp4

#### Q2
사실 초반에는 onload 이벤트를 감지하여 이미지 로딩이 모두 완료되면 스켈레톤 UI를 제거하는 방식을 사용하고 싶었습니만 제가 선택한 렌더링 방식에서는 조금 어려워보였습니다.

이번 미션에서 DOM에 렌더링하는 작업을 최소화하기 위해 각각의 영화 아이템(MovieItem)들을 모두 생성한 후 join() 하여 단 한 번의 렌더링으로 20개의 영화 아이템을 그리는 방법을 택하고 있습니다.

이 방법으로는 각각의 영화 아이템을 조작하는게 쉽지 않았습니다. MovieItem은 생성된 직후에 DOM에 그려지지 않은 상태이기에 이벤트를 달아주려면, 생성된 DOM의 각각의 li 태그를 찾아 반복문을 사용하여 이벤트를 달아줘야할 것 같았고, 이 방법은 매우 비효율적으로 보였습니다.

이번 스켈레톤 UI 뿐만 아니라 step2에서 각각의 영화 이미지를 클릭하면 세부 모달창이 띄워지는 기능을 추가할 때도 이벤트 핸들링이 걱정입니다.

그래서 렌더링의 효율을 우선시하는 설계 구조가 좋을지, 이벤트 핸들링 등 확장 및 유지보수가 용이한 설계 구조가 좋을지 고민입니다. 리트는 어떻게 생각하시나요?!

2023-03-20 15:08 UTC, lsw1164 commented on src/domain/api/index.ts
> +export const getApiPopularMovie = async <T>(
비효율적이라고 말씀하셨지만 이 부분은 반드시 수정이 필요하다고 생각해요.    
세인의 방식으로 구현한다면 api의 사용처가 어떤 타입을 반환할 지 다 알고 있어야 한다는 뜻일까요?  
그렇게 되면 반환 타입이 바뀌어도 바뀐 지 모르고 그냥 넘어가다가 나중에 알아 차리는 경우도 생길 거 같군요.

2023-03-20 15:10 UTC, lsw1164 commented on src/domain/Observable.ts
> +  }
앗 제가 타입을 헷갈렸네요 😅

2023-03-20 16:42 UTC, lsw1164 requested changes
세인, 피드백 반영 확인했어요

### 렌더링 효율 vs 확장 및 유지 보수

성능이 유저 경험에 큰 영향을 준다면 당연히 성능이 우선일 거 같아요.  
그 외 경우에는 확장 및 유지 보수를 우선순위에 두는 게 현실적인 선택이라고 생각해요.  

물론 '성급한 최적화'는 경계해야겠지만 반대로 '섣부른 비관화'를 하고 있는 건 아닌가 살펴볼 필요가 있어요. 이벤트 관리가 어려울 거로 예상하셨는데 혹시 클릭 이벤트를 각각의 돔 객체에 바인딩 해야겠다고 생각하셨을까요? 다른 방법은 없을까요?


### 버그를 발견했습니다.
검색 결과가 잘 나왔었는데, 한 번 더 엔터누르니까 검색 결과가 다 사라졌어요.
leet라고 검색해보면 재연 가능해요.  
다른 피드백은 다음 스텝에서 반영해도 괜찮지만 버그는 먼저 고치고 넘어가는 게 좋겠습니다.

2023-03-20 16:42 UTC, lsw1164 commented on src/components/MovieItem.ts
> +          class="item-thumbnail skeleton"
좋은 트릭이라고 생각해요👍👍
이미지 로딩하는 동안 스켈레톤을 보여주겠군요

2023-03-20 16:42 UTC, lsw1164 commented on src/constant/index.ts
> +    '네트워크가 불안정하거나 서버 점검중일 수 있습니다. 잠시 후 재접속을 시도해주세요.',
에러 메세지 친철하군요 👍

2023-03-21 05:05 UTC, semnil5202 commented on src/domain/api/index.ts
> +export const getApiPopularMovie = async <T>(
아하 무슨 말씀을 하시는지 정확하게 이해했습니다.

사실 제네릭을 사용할 당시 타입을 외부에서 주입 받을 때 그 '외부'가 API 서버인줄 알았는데, 함수를 호출하는 곳이었다는 것을 깨달았습니다.

따라서 `getApiPopularMovie` 와 `getApiSearchMovie`는 제네릭이 아닌 반환값 타입 명시로 변경하여 위에서 언급해주신 문제점을 해결해보겠습니다.

2023-03-21 11:51 UTC, semnil5202 commented
추가로 궁금한 점이 있습니다 리트! 나눠서 커밋까지 해놨는데 코멘트 작성하면서 까먹었네요..!

#### Q3 : 타[입을 외부에서 주입 받는 방법이군요](https://github.com/woowacourse/javascript-movie-review/pull/12#discussion_r1142266914)

처음 해당 코멘트를 읽었을 때 잘 이해하지 못했는데 리팩토링을 하면서 다시 보니 무슨 말씀을 하시는지 이해했습니다. 다음과 같은 방법으로 수정해보았는데 어떤 것이 더 좋은 방법인지 까지는 잘 모르겠습니다. (리팩토링 적용은 2번으로 되어있습니다.)
* 1번 : b4a86fad3697540a5345c767b8cc0b4904fc85f2
* 2번 : 208296f11953ad6ab426ab94730da8afbab0de93
리트는 어떻게 생각하시나요??

2023-03-21 19:11 UTC, lsw1164 commented on src/domain/Movies.ts
> +  }
https://github.com/woowacourse/javascript-movie-review/pull/12#issuecomment-1477448102 답변

네, 에러가 발생한 시점에서 이미 api 요청은 끝난다고 볼 수 있어요.  
따라서, loading을 종료하고 사용자에게 에러 상황을 안내하는 게 좋겠다고 생각했습니다.

2023-03-21 19:14 UTC, lsw1164 commented
> 



> 추가로 궁금한 점이 있습니다 리트! 나눠서 커밋까지 해놨는데 코멘트 작성하면서 까먹었네요..!
> 
> #### Q3 : [타입을 외부에서 주입 받는 방법이군요](https://github.com/woowacourse/javascript-movie-review/pull/12#discussion_r1142266914)
> 처음 해당 코멘트를 읽었을 때 잘 이해하지 못했는데 리팩토링을 하면서 다시 보니 무슨 말씀을 하시는지 이해했습니다. 다음과 같은 방법으로 수정해보았는데 어떤 것이 더 좋은 방법인지 까지는 잘 모르겠습니다. (리팩토링 적용은 2번으로 되어있습니다.)
> 
> * 1번 : [b4a86fa](https://github.com/woowacourse/javascript-movie-review/commit/b4a86fad3697540a5345c767b8cc0b4904fc85f2)
> * 2번 : [208296f](https://github.com/woowacourse/javascript-movie-review/commit/208296f11953ad6ab426ab94730da8afbab0de93)
> 
> 리트는 어떻게 생각하시나요??

명확한 타입, 2번을 선호합니다

2023-03-21 19:22 UTC, lsw1164 approved these changes
세인, 버그 픽스 확인했습니다 👍 
코멘트 남기는 건 유효해요.    
merge하고 다음 스텝 진행해주세요

2023-03-21 19:22 UTC, lsw1164 commented on src/domain/Observable.ts
> +  observer: MovieSubscriberType;
여기는 접근 제어자 필요없을까요?

2023-03-21 19:22 UTC, lsw1164 commented on src/validation/alertFetchStatus.ts
> +export default function alertFetchStatus(status: number) {
bool을 반환하는 데 어떤 의도를 전달하려는 지 모호한 거 같아요.    
에러 상황이 아니면 true인지 alert를 띄울 때 true인지?  
마치 "거기 자리 있어요?" 라고 묻는 것처럼 중의적 느낌이에요.

이런 모호한 상황이라면 차라리 void 함수가 적절하지 않을까요?

2023-03-21 19:22 UTC, merged

2023-03-22 16:23 UTC, semnil5202 commented on src/domain/Observable.ts
> +  observer: MovieSubscriberType;
private 접근 제어자로 설정해주겠습니다!

2023-03-22 16:26 UTC, semnil5202 commented on src/validation/alertFetchStatus.ts
> +export default function alertFetchStatus(status: number) {
네 저도 이 함수를 작성하면서 살짝 애매한 느낌이 있었습니다.

alert 방식보다 아예 오류 페이지를 띄워주는 방법을 고려하고 있습니다. 오류 페이지로 전환하면 [무한 loading 문제](https://github.com/woowacourse/javascript-movie-review/pull/12#discussion_r1143881984)도 해결할 수 있을 것 같습니다.

또한 UX 측면에서도 더 좋을 것 같기에 오류 페이지로 리팩토링 해보겠습니다!!