[1단계 - 영화 목록 불러오기] 리안(오혜린) 미션 제출합니다.
woowacourse/javascript-movie-review pull request #128
Opened 2024-03-21 08:54 UTC by ooherin

2024-03-21 15:31 UTC, yujo11 requested changes
안녕하세요 리안 ~ 만나서 반갑습니다~

영화 미션 함께 하게 된 유조입니다 잘 부탁드려요 ㅎㅎ

전체적으로 코드를 통일성 있고 깔끔하게 작성해주셔서 리뷰하기가 좋았네요 👍 👍 👍 

>검색 결과가 없고, 다시 검색을 하면 제대로 데이터가 로드되지 않습니다. 이 에러는 다시 고칠 예정입니다!

제가 만난 버그도 이 문제였나 싶기도 한데요. 동작이 어색한 부분이 있어 코멘트로 남겼으니 같이 확인해보시면 좋을거 같습니다 ㅎㅎ

>에러 핸들링 로직이 늘어날 경우, 다른 파일로 뺴서 처리를 하는게 맞을 까요?

에러를 어디에서 처리하는게 좋을까를 먼저 고민해보시면 좋겠습니다. 지금은 API와 에러 처리 로직이 붙어 있어 에러가 발생하는 지점과 핸들링 하는 지점의 거리가 있고 에러 핸들링을 모두 API 호출 함수에 의존하고 있는데요. API 호출 로직을 더 유연하게 사용할 수 있고 에러가 발생했을 때 빠르게 찾기 위해서 어떤 방법이 좋은지를 고민해보시면 좋을거 같아요 

>배포 관련

정확한 배경은 모르겠지만 아마 배포 했을 때의 path와 local에서 사용되는 path의 차이 때문에 발생한 문제로 보이는데요. local에서 실행할 때와 배포 되었을 때 각각 어떤 경로로 어떻게 정적 파일들을 찾아서 서빙하는지를 알아보신다면 도움이 될 수도 있겠다는 생각이 드네요

---

미션 진행하느라 고생 많으셨습니다~~ 👍 👍 👍

2024-03-21 15:31 UTC, yujo11 commented on src/components/MovieList/MovieList.ts
> +    Array.from({ length: 20 }).forEach(() => {
`20` 대신 적절한 이름을 가진 상수를 사용하면 의미를 드러내기 더 좋을거 같네용 ㅎㅎ

2024-03-21 15:31 UTC, yujo11 commented on src/components/MovieList/MovieList.ts
전체적으로 Element를 만들거나 Fragement를 만들어서 DOM에 한번만 접근할 수 있게 구현하셨군요 아주 좋네요 ㅎㅎ 👍 👍 👍 💯 💯

2024-03-21 15:31 UTC, yujo11 commented on src/components/SearchBox/SearchBox.ts
> +    this.searchBox.addEventListener('submit', (e: Event) => {
`submit` 사용 좋네요 ㅎㅎ 👍 👍

2024-03-21 15:31 UTC, yujo11 commented on src/components/Toast/Toast.ts
오 토스트를 구현하셨군요 👍👍👍 💯

2024-03-21 15:31 UTC, yujo11 commented on src/components/Toast/Toast.ts
근데 이 토스트는 어떤 상황에 노출되나요? 배포해주신 사이트에서 이것저것 사용해봤는데 한번도 보지 못 했네요

2024-03-21 15:31 UTC, yujo11 commented on src/domain/services/MovieDataLoader.ts
이것저것 눌러보는데 400을 응답 받았을 때 사용자에게 아무런 정보도 알려주지 않거나 더보기를 눌렀을 때 스켈레톤이 이상한데 노출되는 버그가 있는거 같은데 같이 수정해보셔도 좋을거 같아요 ㅎㅎ

<img width="726" alt="image" src="https://github.com/woowacourse/javascript-movie-review/assets/61097373/bd7f2929-ba49-420a-8d2f-c3d7dce832ae">

<img width="1213" alt="image" src="https://github.com/woowacourse/javascript-movie-review/assets/61097373/dd58e5cd-d201-4b1f-9606-0b7bf3f29c69">

2024-03-21 15:31 UTC, yujo11 commented on src/domain/services/MovieDataLoader.ts
> +        new Toast(error.message);
아하 여기 토스트가 있었군요 의도대로 노출되고 있는지 테스트 해보셔도 좋을거 같습니다

2024-03-21 15:31 UTC, yujo11 commented on src/domain/services/MovieFetchAPI.ts
`fetch`로직들을 따로 분리하셨군요 ㅎㅎ 아주 좋네요 👍 👍 👍

2024-03-21 15:31 UTC, yujo11 commented on src/consts/message.ts
> +};
같은 레벨에서 다른 역할(string, function)을 하는 값들이 같이 묶여있는데요. 사용을 할 때 혼란스러울 수도 있을거 같아요

배열로 보면 아래와 같은 상황처럼 느껴지는데 적절하게 분리해보는건 어떨까요?
```ts
[ "string", function(){} ]
```

2024-03-21 15:31 UTC, yujo11 commented on src/consts/Api.ts
> +};
👍 👍 👍

2024-03-21 15:31 UTC, yujo11 commented on src/domain/services/MovieDataLoader.ts
아 스크린샷을 보고 추가로 생각난건데 이미지 URL이 없을 때는 엑박이 뜨는 대신 기본 이미지를 보여주도록 설정해보셔도 좋겠네요 ㅎㅎ

2024-03-22 08:57 UTC, ooherin commented on src/components/Header/Header.ts
> +      this.logoClickEvent();
`movePopularListEvent` 로 수정했습니다! 말씀 그대로 이벤트를 예측할 수 없는 추상적인 이름이었던 것 같아요!

2024-03-22 09:04 UTC, ooherin commented on src/components/MovieItem/MovieItem.ts
> +    </li>`;
MovieItem의 경우 정적인 컴포넌트라서, `innerHTML` 을 사용해서 템플릿을 만드는 게 편리할 것 같아서 사용했습니다. 컴포넌트의 가장 상위 컴포넌트의 경우 돔으로 참조를 해야 해서 `createElement`로 만들어 주었습니다! 사용자의 입력 값을 받는 input의 경우는 XSS의 공격에 대비해서, `innerHTML` 대신 `createElement` 를 사용해 주었습니다. 
혹시 이렇게 쓰는 것보다, 하나로 통일하는 것이 좋을까요? 개인적으로 `createElement`는 코드가 길어져서, 저번 미션때 다 적용했다가 이번 미션 때는 바꿔봤는데.. 혹시 유조의 의견은 어떠신가요?

2024-03-22 09:06 UTC, ooherin commented on src/components/MovieList/MovieList.ts
> +  isLoading: boolean;
네 맞습니다! 감사합니다ㅎㅎ 리액트에서 useState 기능을 차용했습니다:)

2024-03-22 09:06 UTC, ooherin commented on src/components/MovieList/MovieList.ts
> +    Array.from({ length: 20 }).forEach(() => {
넵 매직 넘버는 사용을 지양하도록 하겠습니다! 감사합니다!

2024-03-24 15:48 UTC, ooherin commented on src/components/Toast/Toast.ts
그전에 토스트를 에러 핸들링에서 사용되도록 했는데 적용이 잘 되지 않았던 것 같습니다! 제가 미리 설명드려야 했는데, 못드려서 죄송합니다ㅠㅠ

현재는 다음과 같은 경우에 토스트가 보이도록 수정했습니다!!

1. 검색어에 아무것도 입력하지 않았을 때
2. api 요청이 실패후, 에러가 났을 때 에러 메세지가 토스트 메세지로 뜸
<img width="400" alt="스크린샷 2024-03-25 오전 12 46 27" src="https://github.com/woowacourse/javascript-movie-review/assets/125418818/63b167d7-a1a1-4341-9ed6-ad66fab8a1af">

2024-03-24 15:48 UTC, ooherin commented on src/domain/services/MovieDataLoader.ts
이미지 없을 경우 기본 이미지 설정, 스켈레톤 에러 모두 수정했습니다! 꼼꼼하게 알려주셔서 감사합니다:)

2024-03-24 15:49 UTC, ooherin commented on src/domain/services/MovieDataLoader.ts
> +        new Toast(error.message);
넵..노출이 되고 있지 않았습니다..ㅠㅠㅎㅎ

2024-03-24 15:52 UTC, ooherin commented on src/consts/message.ts
> +};
단순히 타이틀 도메인이라 묶었는데, 같은 배열에 타입이 다른 변수들이 있는 것으로 생각하니까 조금 어색하게 느껴지네요ㅎㅎ
배열이나 객체로 묶을 때 타입도 일치하는지 한번 점검해보는지 확인하는 습관을 들여야 겠어요!

2024-03-24 16:17 UTC, ooherin commented
유조 주말 잘 지내셨나요?? 정성스런 피드백 정말 감사드립니다.😄
 이번에는 유조의 피드백을 반영하면서, 시간이 부족해서 하지 못했던 기능들을 많이 추가하였습니다!

### 1. API 관련
- 기본적인 fetch 함수를 Fetch라는 클래스로 분리하였습니다. 이렇게 만든 이유는, fetch라는 패칭 함수를 관심사를 분리하여 한곳에서만 관리하기 위함인데요. 혹시 나중에 `axios` 같은 다른 패칭 라이브러리를 쓸 경우를 대비했습니다. 더불어 에러를 처리하는 `errorHandler` 로직 또한 이곳으로 이동시키고, 에러를 처리하는 로직 또한 여기로 옮겼습니다. 유조가 언급했듯이 에러를 던지고 잡는 곳의 거리가 한 클래스 안에서 가까워진 느낌이 들었고, 에러 관련 로직을 관리하는 것이 편해졌습니다!

### 2. URL 쿼리스트링 사용
- 기존에는 page, query 같이 api 패칭에 필요한 데이터를 param를 사용해서 드릴링 해주었습니다. 이는 비효율적이라는 느낌이 들어서, 제가 원래 적용하고자 했던 URL 쿼리스트링을 사용해서 로직을 수정해주었습니다. url을 수정하는 로직은 유틸로 분리하였으며, 자동으로 url이 업데이트 되지 않는 바닐라 JS 특성상 재렌더링 시마다 기존 queryString을 delete 해주어, 최대한 url을 현재 데이터와 동기화 시켜주도록 하였습니다. 또한 URL은 `consts` 의 `URL.ts`에서 관리하고 있고, endpoint의 경우 type을 만들어 유틸에 적용시켜서 실수를 방지하도록 하였습니다!

### 3. Movie 도메인 사용
- 기존에 api를 사용하려는 객체로 바꾸는 로직을 `MovieDomain` 이라는 도메인 객체를 만들어 옮겨주었습니다. 수업시간에 배웠듯이, 혹여나 다른 api를 같이 사용하게 되거나 api의 프로퍼티가 바뀌게 되더라도 이 도메인만 수정하면 되니, 의미가 있다고 생각합니다:)

### 4. 에러 핸들링
- 기존에는 단순히 에러를 토스트메세지로 처리하려고 했지만(사실 그마저도 안됐음..ㅠㅠ), 에러에 따라 UI를 다르게 하고 싶었습니다. 

<img src="https://github.com/woowacourse/javascript-movie-review/assets/125418818/648c2e97-6058-46ef-a309-7be66daf08d0" width="400px" height="200px"/>

<img src="https://github.com/woowacourse/javascript-movie-review/assets/125418818/db5c7348-0206-4ad2-98ad-46620484fd7e" width="400px" height="200px"/>

<img src="https://github.com/woowacourse/javascript-movie-review/assets/125418818/e1eaff6d-4b95-4e63-a11f-16a90b0601a5" width="400px" height="200px"/>

위와 같이 에러 코드에 따라 다른 UI와 설명을 보여주고, 하단에는 '홈 버튼', '다시 시도'  버튼으로 사용자의 에러 핸들링을 유도하였습니다. 

### 5. 에러 외에 UI 개선

위 에러 외에도 UI를 개선하였습니다! 

#### 검색 결과가 없을 때
<img src="https://github.com/woowacourse/javascript-movie-review/assets/125418818/6d0e5a60-1504-4838-abf7-ec99537211bf" width="400px"/>

#### 이미지 없을 시
<img src="https://github.com/woowacourse/javascript-movie-review/assets/125418818/080c86bf-c787-490c-ac49-7103590cf8c2" width="400px"/>

보시고 수정 사항 중에서 고칠만한 점, 그 외에 피드백 주실만한 점이 있다면 감사히 받겠습니다😁

2024-03-24 16:19 UTC, ooherin commented on src/domain/services/MovieDataLoader.ts
혹시 400 에러는 어떻게 뜨게 하신건지 여쭈어봐도 될까요??

2024-03-24 16:23 UTC, ooherin commented on src/api/Fetcher.ts
> +    if (status >= 500) {
에러를 500번대 400번대 로 크게 나누었는데, 이보다 더 세밀하게 해야 할지 아니면 이정도로도 충분한지 궁금합니다.
개인적으로 사용자의 입장에서 엄청 세세하게 에러를 나눌 필요는 없는 것 같으면서도, 개발자가 코드마다 에러 핸들링을 
다르게 처리해야 하니, 너무 뭉뜨그려 에러를 처리하는 것도 아닌 것 같고..
어디까지 에러를 분류하여 핸들링을 해줘야 하는지 감이 안잡히는 것 같습니다..! 혹시 유조는 어떤 기준으로 에러를 나누는지, 얼마나 세밀하게 에러를 처리하시는지 여쭤봐도 될까요?

2024-03-24 16:24 UTC, ooherin commented on cypress/e2e/API.cy.js
ㅠㅠ시간부족으로 e2e를 하지 못했네요...이번에 보강하였습니다!

2024-03-24 16:37 UTC, yujo11 commented on src/components/MovieItem/MovieItem.ts
> +    </li>`;
저는 하나의 코드베이스에서 하나의 컨벤션만 존재하는걸 좋아합니다

하나의 코드베이스에 여러개의 컨벤션이 공존하면 코드를 볼 때도, 코드를 수정할 때도 혼란스러움을 느끼기 쉽기 때문인데요.

단적인 예로 리안의 코드를 다른 사람이 이어서 개발한다고 했을 때 `innerHTML`을 사용하는 방식과 `createElement`를 사용하는 방식이 모두 존재해서 새로 DOM에 컨텐츠를 삽입해야 하는 경우가 생기면 어떤 방식을 따라야 할 지 혼란스러울 수 있을거 같아요 ㅎㅎ

명확한 의도를 가지고 방식을 다르게 하신거 같아 당장 하나의 방식으로 통일할 필요는 없을거 같아요 ㅎㅎ 이런 관점도 있다고 참고만 해주시면 좋겠네요 👍

2024-03-24 16:38 UTC, yujo11 commented on src/components/Toast/Toast.ts
오 UI가 완전 수려하네요 멋집니다 리안 👍 👍 👍 💯 💯 💯

2024-03-24 16:40 UTC, yujo11 commented on src/domain/services/MovieDataLoader.ts
첫 번째 리뷰를 남길 때 지속적으로 발생해서 따로 에러 재현 방법을 적어놓지는 않았는데 지금은 발생하지 않고 있네요 😅

당장은 신경쓰지 않으셔도 좋을거 같습니다!

2024-03-24 16:45 UTC, yujo11 commented on src/api/Fetcher.ts
> +    if (status >= 500) {
이 부분은 상황(애플리케이션의 목적, API 명세, 기획 의도 등)에 따라 달라지는 부분이 있어 딱 잘라서 어떤 방법을 사용한다고 말씀드리기가 어려운데요.

제 경험 상으로는 보통 프론트엔드에서 `401`, `403` 그리고 서버에서 핸들링되지 않는(서버에서 에러의 원인을 내려주지 않는) 에러 정도를 나눠서 처리하고 그 외의 영역은 서버 쪽에서 내려주는 메세지에 의존하도록 작성하게 되는거 같네용

2024-03-24 17:05 UTC, yujo11 approved these changes
안녕하세요 리안~

지난 리뷰 이후 짧은 시간 동안 코드가 굉장히 많이 변경되었군요. 추가로 정리해주신 내용도 잘 봤습니다 👍 👍 👍  반응형을 구현한 부분이나 에러에 따라 다른 UI를 보여주는 기능이 특히 인상적이었네요 ㅎㅎ 👍 👍 👍 💯 💯 💯 

기존에 남겨주신 질문과 함께 변경 된 코드에도 추가로 코멘트 남겼으니 같이 확인해주시면 좋을거 같아요! 이번 step은 여기서 이만 머지하고 다음 step으로 넘어가도 좋을거 같네요!

고생 많으셨습니다 리안~~ 👍 👍 👍

2024-03-24 17:05 UTC, yujo11 commented on src/consts/UISettings.ts
> +export const MOVIE_COUNT_PER_PAGE = 20;
👍 👍 👍

2024-03-24 17:05 UTC, yujo11 commented on src/consts/URL.ts
> +} as const;
👍 👍 👍

2024-03-24 17:05 UTC, yujo11 commented on src/consts/message.ts
> +};
`as const`를 사용한 상수와 사용하지 않은 상수에는 어떤 차이가 있나요?

2024-03-24 17:05 UTC, yujo11 commented on src/consts/message.ts
> +export const SEARCH_RESULT_TITLE = (query: string) => `"${query}" 검색 결과`;
👍 👍 👍

2024-03-24 17:05 UTC, merged

2024-03-24 17:39 UTC, ooherin commented on src/components/Header/Header.ts
> +  movePopularListEvent: () => Promise<void>;
그렇군요 컴포넌트의 범용성에 따라도 props의 명칭이 달라질 수 있겠네요!!ㅎㅎ

2024-03-24 17:39 UTC, ooherin commented on src/components/Title/Title.ts
> +    }
나중에 다른 페이지가 들어갈 것을 생각해서 `switch` 문을 써주었습니다. 개인적으로도 if문을 선호하지만, 범위가 아닌 값의 경우에 분기가 나눠진다면 switch 가 가독성이 더 좋은 것 같기도 해서요!

2024-03-24 17:41 UTC, ooherin commented on src/consts/message.ts
> +};
사실 다 해주어야 하는데, `type` 을 선언할 떄는 객체가 꼭 `as const` 로 되어있어야 리터럴로 인식이 되어 에러가 안나더라구요! 차이는 없고, `as const`를 빠트린 게 맞습니다..ㅠㅠ 다음 커밋때 반영하겠습니다!

2024-03-24 17:42 UTC, ooherin commented on src/api/Fetcher.ts
> +    console.log('params', this.params);
네네 console.log 와 주석 같은 불필요한 코드는 항상 확인하겠습니다!