[1단계 - 영화 목록 불러오기] 헤인(방세린) 미션 제출합니다.
woowacourse/javascript-movie-review pull request #130
Opened 2024-03-21 08:55 UTC by Hain-tain

안녕하세요, 브콜! 이번 미션 함께하게 된 헤인입니다. 
부족하지만 열심히 배우고 있습니다. 이번 미션동안 잘 부탁드립니다.🙇🏻‍♀️

## 📍 배포 주소 

## 📁 프로젝트 구조
- `templates`에 작성되어있던 구조를 기반으로 최대한 계층을 유지하며 구현하려고 노력했습니다. 
<img width="498" alt="스크린샷 2024-03-21 오후 5 28 01" src="https://github.com/woowacourse/javascript-movie-review/assets/157036488/8fd3fee6-5da0-483b-8391-6991c7ab31ff">

## 🤔 고민 및 질문할 점 
1. 스켈레톤 UI, 어떻게 개선할 수 있을까?
- 이번 미션에서 가장 중요하다고 생각했던 것은 비동기적으로 받아온 정보를 보여주는 과정에서 좋은 UX를 제공하는 것이라고 생각했습니다. 이를 위해 스켈레톤 UI를 활용하였습니다.  현재 로직은 아래와 같습니다.
    - 페이지가 로드되거나 '더 보기' 버튼을 누르면 스켈레톤(값이 없는 MovieItem) 20개가 무조건 생성된다.
    - 서버로부터 응답이 오면, 받은 응답 성공 여부를 확인한다.
      - 성공할 경우, 해당 MovieItem에 받은 정보들을 넣어줘서 MovieItem을 완성한다.
      - 실패할 경우, 에러 메세지를 보여주고, 만약, 정보를 불러오는 중에 실패했다면 다시 시도할 수 있도록 더 보기 버튼을 활성화 시킨다.
 - 이렇게 무조건 스켈레톤을 넣어주다보니, 정보가 빠르게 받아와지면 오히려 이 스켈레톤이 깜빡이는 것처럼 보여 UX가 좋지 않아보였습니다. (현재는 스켈레톤을 편하게 확인하기 위해 setTimeout 이 들어가 있는 상태입니다.) 또한 정보가 들어와도 이미지가 로드가 되기까지 시간이 걸리는 경우가 있어서 스켈레톤은 사라졌으나 이미지는 뜨지 않는 현상이 종종 생기기도 하였습니다. 이미지가 나오기 전에 그 빈 부분을 채워주는 것이 스켈레톤인데, 과연 이렇게 사라지는 것이 맞는가, 개선하려면 어떻게 해줘야 하는가 고민이 되었습니다.

2. 에러 핸들링, 어떻게 해줘야 하는가? 
- TMDB의 가이드에 따라, 요청의 결과로 올 수 있는 에러들을 모두 살펴보았으나 특수한 경우를 제외하고는 어떻게 에러를 처리해줘야 하는지 고민이 많이 되었습니다.
- 현재는 넓은 범위로 (400번대와 500번대) 에러를 분리하여 메세지만 다르게 출력해주고 있는 상황입니다. 혹시 더 좋은 에러핸들링 방법에 대해 공부할 수 있는 자료나 키워드가 있다면 던져주시면 감사하겠습니다.🙏

마지막으로 컴포넌트를 나누고 구현하는 데 시간이 오래 걸려, E2E 테스트를 진행하지 못하였습니다. 추후 2단계에서 보완해오도록 하겠습니다. 감사합니다.

2024-03-21 17:38 UTC, Tanney-102 requested changes
안녕하세요 헤인~
미션 진행하느라 고생하셨습니다!
createElement 함수를 아주 잘 설계해주셨네요.
마치 작은 라이브러리 하나를 보는 것 같았어요. 덕분에 전반적으로 일관된 컴포넌트가 작성된 것 같습니다.

질문에 답변드려요.

### 1. 스켈레톤 UI, 어떻게 개선할 수 있을까?
좋은 고민을 하셨네요.
확실히 빠른 네트워크 환경에서는 로딩 UI가 빠르게 깜박거리는 게 그리 좋지 않게 보일 수 있습니다. 
그런 측면에서 짧은 최소 표시 시간을 설정해 주는 것도 나쁘지 않은 방식인 것 같아요.
어쨌거나 모든 사용자 환경을 미리 알 수는 없을 것이고, 그렇기에 데이터를 가져와서 그려주는 요청에는 로딩이 필요할테니까요. 이 UI는 데이터를 가져오는 중에 주는 피드백임~ 정도만 인지시킬 수 있으면 좋을 듯 하네요.

아니면 특정 시간 동안(대략 500ms 정도?) opacity 0에서 100으로 애니메이션을 주는 방법도 있을 것 같아요. (안해봐서 얼마나 유려할지는 모르겠네요 ㅎㅎ) 그럼 너무 빠르게 컨텐츠가 바뀌어도 어느정도 투명한 상태일 거라 크게 거슬리지 않을 것 같습니다.

이런 케이스 말고 클라이언트에서 미리 변경 상태를 알 수 있는 경우 (예를 들어 좋아요 버튼을 클릭한다거나..)에는 미리 변경을 하고 나중에 에러가 있으면 롤백하는 방식을 사용하기도 하니 참고 부탁드려요.(Optimistic UI Update)

이미지가 로딩되는 동안 스켈레톤을 보여주는 것도 좋은 고민입니다.
스켈레톤을 보여주는 동안 어떻게 이미지를 fetch하지?를 고민해보시면 좋겠네요

### 2. 에러 핸들링, 어떻게 해줘야 하는가?
사실 좋은 에러처리는 에러 스펙의 합의에서 시작한다고 생각해요.
내가 아무라 에러를 잘 보여주고 싶어도 에러 자체에 정보가 없으면 뭐 방법이 없죠..!
말씀해주신 내용을 봤을 때 우선 지금은 메시지를 잘 보여주는 것만으로 충분해보입니다.

나중에 서버의 에러 스펙을 직접 합의할 수 있는 기회가 생기면 다음과 같은 내용들을 고민해보시면 좋겠습니다.
- 에러를 보여주는 상황은 언제있지?
  - 데이터를 가져올 때?
  - form submit?
  - ...
- 에러의 수준 & 각 수준에 따른 UI는 어떻게 정해볼 수 있을까?
  - 간단한 노티 => 이런건 토스트로 충분해
  - 내용이 많거나 중요하게 인지해야하는 내용 => 모달을 띄워줄까?
  - ...
- 위에 나열한 에러의 '종류', '수준' 등을 분기하기 위해 어떤 필드가 필요할까?

2024-03-21 17:38 UTC, Tanney-102 commented on src/components/utils/createElement.ts
> +  addEventListener?: Record<string, (e: Event) => void>;
동사로 시작하는 이 필드는 뭐랄까.. 그냥 함수 같은데 사실은 Record 타입이군요!

2024-03-21 17:38 UTC, Tanney-102 commented on src/components/MovieMain/MovieListBox/MovieList/MovieList.ts
> +      const movieItem = this.movieList[index];
이미 moveList가 MAX_ITEM_OF_PAGE 만큼 생성한 item들인데 여기서 또 MAX_ITEM_OF_PAGE로 반복을 해야하는 이유가 있나요?

2024-03-21 17:38 UTC, Tanney-102 commented
<img width="230" alt="Screenshot 2024-03-22 at 2 38 41 AM" src="https://github.com/woowacourse/javascript-movie-review/assets/57767891/062d304a-4fd2-42d3-a3b6-fc332442aca9">
추가로..! align이 안 맞네요

2024-03-22 15:54 UTC, Hain-tain commented on src/components/utils/createElement.ts
> +  addEventListener?: Record<string, (e: Event) => void>;
이 부분에 대해서는 페어와 정말 고민이 많았던 것 같아요! 
처음 필드의 이름을 `eventListener`로 지었었는데, 이벤트 타입도 함께 전달하여 addEventListener 를 해준다는 의미를 주고 싶었습니다. 많은 고민 끝에, 직관적으로 전달하기 위해 addEventListener 라는 매서드 명을 그대로 사용하게 되었는데 아무래도 동사로 시작하다보니 함수와 헷갈리실수도 있으실 것 같습니다.

현재 생각나는 가장 좋은 대안(`registeredEventListener`) 으로 변경해보았습니다. 혹시 더 좋은 이름/대안이 있으시면 추천해주시면 감사하겠습니다.🙏

(+) 프로그래밍을 하면서 가장 고통스러운 것은 적절한 이름을 짓는 일 같아요! 혹시 브콜은 이름을 지으실 때 규칙이나 참고하시는 것들이 있으신가요?

2024-03-22 16:11 UTC, Hain-tain commented on src/domain/getMovieListByQuery.ts
> +  video: boolean;
저도 페어와 함께 고민했던 부분입니다. 현재는 TMDB API에서 PopularMovie의 반환값이나 SearchMovie의 반환값의 형식이 같아서 인터페이스를 굳이 별도로 선언해줘야 하나? 불필요한 중복이 아닐까? 라고 생각하였습니다.

그러나 추후 TMDB에서 어떤 api 에 대한 반환값의 형식이나 일부 필드를 변경할 수도 있다고 생각하였습니다. 또는 SearchMovie는 TMDB API에서 받아오지만 PopularMovie는 다른 api 로 받아오는 방향으로 변경될수도 있다고 생각하였습니다. 추후 어느 한 쪽에 변경이 생겼을 때, 다른 쪽에 영향을 주지 않도록 각자 인터페이스로 관리하는 것이 추후 유지보수에 좋을 것이라고 판단하여, 각 파일에 각자 관리하게 되었습니다.

2024-03-22 16:18 UTC, Hain-tain commented on src/components/MovieMain/MovieListBox/MovieList/MovieList.ts
> +  movieList;
개인적으로 `$element`의 경우 필드의 이름과 `$` 프리픽스를 통해 HTMLElement라는 것을 충분히 전달하고 있다고 생각하였습니다. 또한 현재 ts에서 타입 추론을 잘 해주고 있다고 판단하여 별도로 각 필드에 대한 타입을 명시해주지는 않았습니다. 그럼에도 불구하고 코드를 보는 사람들을 위해 타입을 명시해주는 편이 좋을까요? 

<img width="353" alt="스크린샷 2024-03-23 오전 1 12 27" src="https://github.com/woowacourse/javascript-movie-review/assets/157036488/bb03dbdd-a5fd-4ff7-a4cd-75402bc0610d">

<img width="365" alt="스크린샷 2024-03-23 오전 1 12 35" src="https://github.com/woowacourse/javascript-movie-review/assets/157036488/548661f1-9255-4f60-9051-d45c200c40e3">

2024-03-22 16:44 UTC, Hain-tain commented on src/domain/getPopularMovieList.ts
> +}
아니요! 이 중에서 사용되는 필드는 4개정도입니다. (id, poster_path, title, vote_average)
그럼에도 불구하고 인터페이스로 정의하게 된 이유는 api 요청을 하는 함수의 반환 타입을 명시해주기 위해서입니다.

만약 명시해주지 않으면 아래처럼 Promise<any> 타입으로 추론하기 때문에
<img width="302" alt="스크린샷 2024-03-23 오전 12 43 14" src="https://github.com/woowacourse/javascript-movie-review/assets/157036488/085f9dc4-26d8-4124-8b49-830bc01c4534">

이렇게 명시적으로 타입을 작성하여 반환되는 값을 쉽게 예측할 수 있게 해주었습니다.
<img width="358" alt="스크린샷 2024-03-23 오전 12 43 26" src="https://github.com/woowacourse/javascript-movie-review/assets/157036488/6add396f-625a-4c0f-a6f1-70eb765d872f">

2024-03-22 16:54 UTC, Hain-tain commented on src/index.js
> +new App($app);
사실 App 같은 경우에는 인스턴스가 재사용되지도 않고, 인스턴스가 여러개 생성되지도 않습니다. 브콜의 말씀처럼 app을 실행하는 함수 호출이 필요한 것이기도 합니다.

그럼에도 불구하고 App을 클래스로 작성하게 된 이유는 아래 2가지 이유 때문입니다.

### 1. 컴포넌트를 클래스로 관리한다는 저희 팀(저와 페어)의 규칙을 준수하고 코드의 일관성을 지키기 위해서
- 현재 저희 팀(저와 페어)의 컴포넌트 관리 규칙은 "_element 생성은 generate함수로, 관리는 class로 한다_" 입니다.
- 컴포넌트는 프로젝트를 이루는 작은 단위들을 말합니다. 동시에 컴포넌트와 컴포넌트가 모이거나 결합된 것도 저는 하나의 컴포넌트라고 생각하였습니다. 따라서 App도 작은 컴포넌트들이 모여 이루는 하나의 큰 컴포넌트라고 생각하였습니다. 따라서 컴포넌트를 클래스로 관리하기 위해 App도 class 로 작성하고 관리하게 되었습니다.

### 2. App이 상태와 행동을 가져야 하기 때문에
- 현재 App 은 현재 페이지(currentPage)와 입력된 검색어(query)를 상태로 가지고 있습니다. 
- App은 최상위에 있는 객체로서 api를 호출하기도 하고, 재랜더링을 하는 등 필요한 행동을 수행하고 있습니다.
- 이 행동들을 index.js 내부에 함수로 구현할 수 있긴 하지만, App 이라는 스코프 내부에서만 사용할 수 있도록 제한해두는 것이 좋다고 생각하였습니다.

마지막으로 현재 App이 하는 일이 많다고 느껴지기는 하지만, 이 부분을 따로 나눌 수 있는 다른 구조가 생각나지 않아 지금은 현 상황을 유지한 상태입니다. 혹시 더 좋은 설계를 위한 아이디어가 있으시다면 힌트를 주시면 감사하겠습니다. 🙏

2024-03-22 16:55 UTC, Hain-tain commented on src/domain/getPopularMovieList.ts
> +  total_results: number;
네! 현재 서버에서 오는 데이터의 스키마를 인터페이스로 정의해주었습니다. api 요청을 하는 함수의 반환 타입을 명시해주기 위해서입니다.

2024-03-23 18:07 UTC, Hain-tain commented on src/components/MovieMain/MovieListBox/MovieList/MovieList.ts
> +      const movieItem = this.movieList[index];
현재 로직이 스켈레톤을 무조건 20개를 생성하도록 하고 있기 때문입니다.
현재 MovieItem을 보여주는 로직은 아래와 같습니다.
1. 페이지가 로드되거나 더 보기 버튼을 누를 경우 무조건 스켈레톤(빈 MovieItem) 20개를 생성한다.
2. 영화 정보를 요청한다. (비동기)
3. 요청에 대한 응답이 오면, 응답에서 필요한 정보들만 재가공하여 MovieItem 에 넣어준다.
4. 만약, 받아온 데이터가 20개 미만이라면 데이터가 없는 빈 스켈레톤을 지워준다.

받아온 데이터가 20개 미만이면 빈 스켈레톤을 지워줘야하기 때문에  moveList의 길이에 상관없이 무조건 MAX_ITEM_OF_PAGE만큼, 즉 20번 반복해야 한다고 생각하였습니다!

2024-03-23 18:45 UTC, Hain-tain commented on src/components/MovieMain/MovieListBox/MovieList/MovieList.ts
> +  }
1. 현재 로직은, 정보가 없는 MovieItem(스켈레톤)이었던 것에 응답으로 오는 영화의 정보들을 reRender 로 넣어주고 있습니다. 이때, `movies `가 20개보다 적을 경우에도 빈 스켈레톤을 지워주기 위해서는 무조건 20번을 순회해야 합니다. (저와 페어가 검색해본 결과, 한꺼번에 원하는 위치의 dom의 요소를 지울 수 있는 매서드가 없어서 하나씩 remove()로 지워야 했기 때문입니다.)

movies를 기준으로 업데이트를 해주어도 결국 남은 skeleton이 있는지 없는지 검사하고, 20번을 순회해야 하는것은 동일하지만 가독성이 더 좋은 것 같아 아래와 같이 코드를 수정해보았습니다.

```js
    movies.forEach((movie, index) => {
      const movieItem = this.movieList[index];
      movieItem.reRender(movie);
      return;
    });

    const restSkeletonCount = MovieList.MAX_ITEM_OF_PAGE - movies.length;

    if (restSkeletonCount) {
      Array.from({ length: restSkeletonCount }).forEach((_, index) => {
        const movieItem = this.movieList[movies.length + index];
        movieItem.$element.remove();
      });
    }
```

2. 현재 사용하고있는 TMDB API는 한 요청당(한 페이지 당) 최대 20개의 영화가 응답으로 오고있기 때문에 movies가 MAX_ITEM_OF_PAGE보다 많은 요소를 가지고 있을 수는 없습니다. 따라서 일부로 렌더가 안 되도록 의도한 것은 아니고, 그저 처음에 생긴 빈 스켈레톤을 지워주기 위하여 이와같이 코드를 작성하였습니다.

2024-03-24 10:49 UTC, Hain-tain commented
안녕하세요, 브콜! 🙇🏻‍♀️
달아주신 리뷰와 질문에 대한 답들 굉장히 인상깊게 읽었습니다.
특히 스켈레톤 UI를 개선하기 위해, Image Element의 load 이벤트에 대해 공부해보면 좋을 것 같다는 코치의 피드백을 받아 이에 대해 공부해볼 예정인데요, 이와 더불어 브콜이 말해주신 것처럼 특정 시간동안 투명도를 애니메이션으로 조정하는 방법을 적용해볼까 합니다! 

다만, 이러한 UX 개선은 필수사항은 아니기 때문에, 우선적으로 꼭 해야할 일들을 먼저 반영하고, 추후 시간적 여유가 될 때 다시 반영해보려고 합니다. 따라서 현재 E2E 테스트 작성 및 브콜이 달아주신 리뷰에 대한 반영을 우선적으로 처리하여 재리뷰 요청 보냅니다. 

(+) 로컬 환경에서의 확인 및 테스트 확인을 위해 API_KEY는 슬랙 DM으로 보내드리겠습니다. 감사합니다. ☺️🙏

2024-03-25 15:23 UTC, Tanney-102 commented on src/index.js
> +new App($app);
좋은 답변이네요~
기왕 클래스로 작성하신다면 constructor와 각 메서드의 역할과 책임을 조금 더 나눠보면 좋을 듯 합니다. 
지금은 contructor 안에서 render에 대한 책임까지 지고 있는 것 같네요~

2024-03-25 15:24 UTC, Tanney-102 commented on src/domain/getPopularMovieList.ts
> +}
넵 그런데 말씀해주신 근거는 타입이 필요한 이유일뿐 사용하지 않는 필드까지 모두 인터페이스에 포함시켜야 하는 이유가 되는지는 모르겠습니다.

2024-03-25 15:28 UTC, Tanney-102 commented on src/domain/getPopularMovieList.ts
> +  total_results: number;
api에서 받아온 필드를 앱 전반에서 '그대로' 사용할 이유는 없습니다. 변수명 컨벤션이 되었든 type narrowing이 되었든 필요하다면 어댑터 같은 걸 하나 두어서 내가 원하는 모델로 변경하는 옵션도 있었을 것 같아서 드린 질문이었습니다!

2024-03-25 15:34 UTC, Tanney-102 commented on src/components/utils/createElement.ts
> +  addEventListener?: Record<string, (e: Event) => void>;
eventListener라는 이름이 이벤트 채널에 대한 정보도 내포할 수 있다고는 생각하는데 registeredEventListener도 나쁘지 않은 것 같습니다.
따로 참고하는 건 없습니다. 최대한 함수의 동작이나 변수의 선언 목적을 예측할 수 있는 이름이 되도록 고민 하긴합니다!

2024-03-25 15:38 UTC, Tanney-102 commented on src/components/MovieMain/MovieListBox/MovieList/MovieList.ts
> +  movieList;
constructor에서 할당을 하고 있기 때문에 추론이 되는 것이 아닐까요~?
초기화 전에 먼저 타입이 있어야 하는 건 아닐지, 초기화 과정에서 할당되는 값의 타입 외 다른 타입을 유니온으로 갖게 되는 경우에는 어떻게 대응할 수 있을지 등 고려해보시면 좋겠습니다.

2024-03-25 15:39 UTC, Tanney-102 commented on src/components/MovieMain/MovieListBox/MovieList/MovieList.ts
> +  movieList;
또 타입은 코드를 읽는 사람에게 '알려주기' 위한 목적보다 해당 변수를 사용하는 코드에게 제약을 걸기 위한 목적이 큽니다. 변수로 타입을 표현하는 것으로 충분하다면 ts를 쓸 필요가 없겠죠!

2024-03-25 15:42 UTC, Tanney-102 commented on src/components/MovieMain/MovieListBox/MovieList/MovieList.ts
> +      const movieItem = this.movieList[index];
받아온 데이터가 20개 이상이면 어쩌죠?
UI 레이어에서 실제 요청 하는 movie의 수도 알고 있나요?

2024-03-25 15:45 UTC, Tanney-102 commented on src/components/MovieMain/MovieListBox/MovieList/MovieList.ts
> +  }
> 현재 사용하고있는 TMDB API는 한 요청당(한 페이지 당) 최대 20개의 영화가 응답으로 오고있기 때문에 movies가 MAX_ITEM_OF_PAGE보다 많은 요소를 가지고 있을 수는 없습니다

위 reply 에서는 TMDB의 response type이 바뀔 것도 고려하시는 것 같던데 max item 수가 바뀌는 상황도 고려되어야 하지 않을까요😁
무엇보다 '20개가 넘는 아이템이 오지 않는다'는 전제 자체로 UI 레이어에서 도메인 지식을 너무 의존하는 것 같네요..!

2024-03-25 15:47 UTC, Tanney-102 requested changes
안녕하세요 헤인!! 확인이 늦어 죄송합니다ㅜㅜ
답변 달아주신 것보고 많이 놀랐네요~!
훌륭한 고민을 많이 하시는 것 같습니다.
몇가지 더 고민해볼 포인트 남겨두었어요.
제 생각엔 머지하고 다음 스텝에서 고민해도 좋을 것 같은데, 어떠신가요~?
동의해주시면 바로 머지하겠습니다.

2024-03-25 16:04 UTC, Hain-tain commented on src/domain/getPopularMovieList.ts
> +}
오! 생각해보지 못했던 부분이네요! 사용하지 않는 필드는 인터페이스로 굳이 정의해줄 필요가 있나? 라고 물었을 때는 그렇지 않은 것 같습니다. 사용하지 않는 필드를 포함하면 오히려 이 인터페이스를 보는 사람들에게 왜 이게 있는건지 혼란스러움만 가중시킬 것 같네요! 사용하거나 필요한 부분에 대해서만 정의해줘도 좋을 것 같아요! 좋은 지적 감사합니다!! 2단계 진행할 때, 이 부분 반영하여 진행하겠습니다!

2024-03-25 16:10 UTC, Hain-tain commented on src/components/MovieMain/MovieListBox/MovieList/MovieList.ts
> +      const movieItem = this.movieList[index];
아래 브콜이 날카롭게 짚어주신대로, UI 에서 도메인 지식(20개씩 정보가 온다는 것)에 너무 의존하고 있는 것 같습니다! 모든 걸 알고 있는 상태로 코드를 짜다보니, 너무 전지적 작가 시점에서 코드를 짠 것 같아요.🤣  사실 UI 입장에서는 UI 레이어에서 실제 요청 하는 movie의 수도 모르고, 받아오는 데이터의 길이를 정확하게 알지 못하는 것이 맞는 것 같아요! UI의 관점에서 다시 고려해보도록 하겠습니다!

2024-03-25 16:11 UTC, Hain-tain commented on src/domain/getPopularMovieList.ts
> +  total_results: number;
이 부분에 대해서도 생각하지 못했던 부분인데, 서버에서 받아온 값을 그대로 사용하는 것이 아니라 우리 컨벤션에 맞게, 우리가 사용하거나 보기 쉬운 형태로 변경하여 사용한다는 것이 인상적이네요! 인터페이스를 수정하면서 함께 반영해보도록 하겠습니다!!🙏

2024-03-25 16:15 UTC, Hain-tain commented
아닙니다! 오히려 브콜이 리뷰를 남겨주신 방향을 제가 그저 질문으로만 받아드려 더 깊이 사고해보지 못했던게 아쉬운 것 같아요! 그래도 브콜이 한 번 더 짚어주신 덕분에 생각하지 못했던 부분에 대해서도 고려해보게 된 것 같습니다. 정말 감사합니다! 

(+) 1단계 머지해주시면, 2단계 작업하면서 남겨주신 리뷰들 반영하여 작업해 돌아오도록 하겠습니다! (2단계에서는 더 많이 고민하고 성장한 모습으로 돌아오겠습니다. )

늦은 시간까지 정성스럽게 리뷰 봐주셔서 감사합니다!! 🙏

2024-03-25 16:20 UTC, Tanney-102 approved these changes
고생 많으셨습니다!

2024-03-25 16:20 UTC, merged