[1단계 - 영화 목록 불러오기] 시모(심호림) 미션 제출합니다.
woowacourse/javascript-movie-review pull request #132
Opened 2024-03-21 08:55 UTC by simorimi

## 화면 보는법
``` js
npm run start
```

## e2e테스트 실행
``` js
npm run start

npm run test-e2e
```

## 배포링크
[영화 목록 불러오기](https://simorimi.github.io/javascript-movie-review/dist/)

## 미션 구현하면서 고민한 점 및 느낀점
### 컴포넌트
- 지난 미션에 이어서 컴포넌트화에 고민을 많이 하였습니다. 점심 뭐 먹지 미션을 통해 컴포넌트에 대한 개념을 어렴풋 알게 되었습니다. 그러한 경험을 바탕으로 이번 미션에서 또한 역할에 대한 명확한 분리에 대해 많은 고민을 했습니다. 명확한 분리가 나중에 조합하여 구현할 때, 에러를 많이 일으키지 않을뿐더러 에러에 대한 탐색 또한 쉽다는 것을 알게 됐기 때문입니다. 그래서 이번 미션 또한 컴포넌트를 어떻게 구현할지가 가장 오래 고민하게 되었습니다. 

- MovieHeader: 해당 헤더에서는 로고 이미지와, 검색창을 가지고 있습니다. 이에 따라 해당 html 요소를 생성하였고 해당 부분의 역할로 로고 이미지나 검색 버튼 클릭시 영화 목록을 생성하는 클래스를 호출하는 것 까지로 주었습니다. 

- SearchBox: 검색 박스의 요소를 만드는 기능을 합니다. 따로 컴포넌트화 한 이유는 검색 창의 경우 다른 곳에서 재사용할 가능성이 높다고 판단하여 따로 객체를 구현하였고 MovieHeader에서는 이를 조합하는 방법으로 진행하였습니다.

- Button: 버튼을 생성하는 컴포넌트입니다. 버튼 생성은 어느 곳에나 잘 쓰일 수 있기에 재사용성을 높이는 방식으로 구현하였습니다. 실제 검색 버튼과 더 보기 버튼에서 활용하였습니다.

- MovieItems: 영화 목록의 노드 요소들을 생성하고 조합하는 방식으로 구현한 것과 더불어 해당 부분에서는 스켈레톤을 생성하는 메서드와 스켈레톤을 실제 데이터로 바꾸는 메서드를 구현하였습니다. 이렇게 따로 구현한 이유는 우선에 스켈레톤 화면을 띄운 뒤 패치가 완료되면 데이터를 바꾸는 방식이 스켈레톤  UI를 잘 활용할 수 있는 방법이라고 생각하였습니다. 바꿀 때는 HTMLElement.replaceWith()라는 메서드를 통해 div 요소를 img나 p라는 적절한 element로 교체하는 방식으로 구현하였습니다.

- ItemView: 개인적으로 가장 뿌듯하게 짠 로직입니다. 다른 것들과 달리 해당 로직만 class로 구현하였는데 그 이유는 page 필드의 업데이트를 위해서입니다. 각 영화 목록들을 생성한 뒤에 더보기를 통하여 다음 페이지를 할당하는 방식으로 진행하는데 이 방식 자체가 클래스로 생성한 인스턴스가 추후의 일을 계속하는 형태이기에 적합하다고 생각하여 클래스로 구현하였습니다. 뿌듯했던 부분은 페이지필드 값의 업데이트를 통해
페치 데이터를 받아온 뒤 해당 페이지의 목록리스트(ul)을 mount하는 방식인데 insetAdjacetElement를 통해 더 보기 버튼 앞에 추가하는 방식으로 구현하였습니다. 이러한 할당이 전체를 제거 했다가 다시 생성하는 방식보다는 비용을 훨씬 아낄 수 있다고 생각하였기에 이렇게 구현하였습니다.

### fetch
- 개인적으로 API를 이용하여 외부 정보를 받아오는 방식의 구현은 처음이었습니다. 프로젝트의 경험이 전혀 없었기에 해당 부분이 낯설어 걱정을 한 부분이었습니다. 하지만, 단지 정보를 받아와서 json의 형식을 parse하는 과정만 있을뿐인 것을 알고서는 이전에 로컬스토리지에서 정보를 받아오는 방식과 크게 다르지 않다고 느꼈습니다. 물론 해당 개념에 대해서 이 정도의 느낌만 와 닿아 추후 추가적인 공부가 필요하겠지만 막상 겁을 먹을 것은 아니라는 생각이 들었습니다.

### Cypress
-

2024-03-21 13:20 UTC, woowahan-cron commented
사용성 리뷰 먼저 올립니다.

### 1. 더보기 버튼이 숨막혀요...

padding이나 margin 속성을 적절히 활용해서 브라우저 맨 끝에 버튼이 붙어 있지 않도록 배치하면 어떨까요?

<img width="1228" alt="image" src="https://github.com/woowacourse/javascript-movie-review/assets/112997662/a586d314-cdf2-4814-8fd8-5366a5dab7a7">


### 2. 검색 결과가 없는 경우

물론, 스켈레톤이 반짝 나타났다가 사라지는데 👀
결과에 대한 안내가 나타나지 않고 있어요.

<img width="1308" alt="image" src="https://github.com/woowacourse/javascript-movie-review/assets/112997662/a32f54e9-3fec-4153-9a7a-1eb9595dab88">

2024-03-21 14:03 UTC, woowahan-cron requested changes
안녕하세요 시모~~
제가 오랜만에 리뷰를 추가로 하게 되었습니다 ㅎㅎ
영화 리뷰까지 고생 많으셨습니다!

![image](https://github.com/woowacourse/javascript-movie-review/assets/112997662/95b2b67b-7284-4993-81a6-40170f0eb9f8)

그런데 군데군데 아쉬운 흔적들이 몇몇 보이네요 ㅠㅠ

레벨1에서는 아직까지 전문적인 용어를 사용하기보다는 근원적으로 어떻게 하면 역할과 관심사를 분리할지를 고민하는 것에 초점을 맞춰 주시면 좋을 것 같습니다.

그리고 컴포넌트 재사용의 관점에 관해 좀 더 노력을 기울이시면 더 깔끔한 코드가 되지 않을까 싶습니다 👍 이후에 달린 각각 코멘트를 면밀히 살펴보시면서 고민해 보시기 바랍니다.

2024-03-21 14:03 UTC, woowahan-cron commented on src/components/MovieItems/MovieItems.ts
> +  },
여기는 코드가 거리두기를 하고 있네요 👀
개행에 일관서응 락져가시면 좋겠어요.

2024-03-21 14:03 UTC, woowahan-cron commented on src/components/MovieItems/MovieItems.ts
전반적으로 파일을 봤을 때 Skeleton과 Skeleton에 관련되지 않은 역할을 하는 것을 구별짓기가 어렵습니다.
역할을 좀 더 나눠야 하지 않을까요?

2024-03-21 14:10 UTC, woowahan-cron commented
그리고 다른 크루들처럼 캡처 화면에 컴포넌트의 구성을 그림으로 보여주면 이해하기가 수월할 거 같아요!!

2024-03-21 15:10 UTC, uk960214 requested changes
안녕하세요 시모! 이번 미션 리뷰를 맡은 블링입니다!
크론이 미리 리뷰를 남겨주셔서 저는 그 외의 것들 위주로 가볍게만 남겼습니다!
코멘트가 그래서 아주 많아졌는데, 시모가 판단하기에 중요한 것들 먼저 작업해서 올려주시고
요청 보내주시면 덜 중요한 것들은 시간이 있을 때 처리하기 좋을 것 같아요!
그럼 기다리고 있곘습니다!

2024-03-21 15:10 UTC, uk960214 commented on src/interfaces/IButton.ts
> +interface IButton {
I- 로 시작하는 인터페이스 네이밍이 필요한 이유는 무엇인가요?

2024-03-21 15:10 UTC, uk960214 commented on src/interfaces/IButton.ts
> +  classes: string[];
classList라는 속성이 있으니 따라가는 건 어떨까요?

2024-03-21 15:38 UTC, woowahan-cron commented on src/domain/DTO/Request/sendRequest.ts
> +      page: `${page}`,
아 이거 코멘트 달까 말까 고민했는데 저 대신 달아주셨군요 👍

2024-03-22 10:23 UTC, simorimi commented on .prettierignore
> +**/*.md
prettier중 proseWrap: 'never'이 안 먹더라고요.. 그래서 해당 부분을 추가했습니다!

2024-03-23 07:34 UTC, simorimi commented on index.html
> +<!doctype html>
프리티어로 자동 저장을 넣어두니 이 부분도 저장과정에서 자연스레 고쳐줬습니다!

2024-03-23 07:40 UTC, simorimi commented on index.html
> +    <div id="app"></div>
템플릿을 참고하는 과정에서 실수를 했던 것 같습니다! 원래 기존에 #app에 있는 것들이였는데 말이죠 그래서 해당 부분을 모두 App안에 집어넣고 header의 경우 AppendChild가 아닌 prepend 메서드를 활용하여 구현하였습니다 좋은 피드백 감사합니다!

2024-03-23 07:44 UTC, simorimi commented on index.html
> +    <div id="app"></div>
심지어 App이라는 속성에 있지않아서 더보기 버튼이 숨이 막혔던 것이군요! 좀 더 꼼꼼히 확인하는 습관을 들여야겠습니다!

2024-03-23 07:50 UTC, simorimi commented on src/components/MovieItems/MovieItems.ts
> +  },
평소 가독성있는 코드가 중요하다고 생각하여 개행의 일관성을 최대한 지키려고 하는 편입니다!만 의식과는 다르게 간혹 이렇게 일관성을 못 지키는 부분이 발생하네요 조금 더 신경쓰면 좋을 것 같네요! 좋은 피드백 감사합니다 :)

2024-03-23 08:00 UTC, simorimi commented on src/components/MovieHeader/MovieHeader.ts
> +    });
개행에 있어서 조금 더 신경을 써야겠습니다! 남에게 설득력을 가지기 위해서는 일관성이 가장 중요하다고 생각하여 반영하려고 하나 이렇게 가끔 일관성에 어긋나기도 하네요 조금 더 꼼꼼할 필요가 있을 것 같네요 감사합니다!

2024-03-23 08:09 UTC, simorimi commented on src/index.js
> +  const item = new ItemView();
최초의 시작하는 세틱입니다! 최초 실행하는 경우 인기있는 영화 차트가 보여야한다고 생각하여 두었고, 헤더에서 호출하는 것은 검색을 했다가 무비아이템 로고를 클릭시 다시 인기있는 영화 차트가 보여야한다는 생각에 이렇게 표현하였습니다!

2024-03-23 08:12 UTC, simorimi commented on src/components/ItemView/ItemView.ts
> +    } else {
맞습니다 굳이 else라는 표현이 추가가 되었네요! 해당 부분은 의식없이 손부터 나갔던 것 같습니다. 무지성 코딩을 조금 더 막도록 의식해보아야하겠네요 좋은 피드백 감사합니다!

2024-03-23 08:23 UTC, simorimi commented on src/constants/INFORMATION.ts
> +const BUTTON = {
그렇네요 버튼들의 정보라는 표현이 의미전달에 더 좋을 것 같네요! 각각에 대해 사용할 때는 버튼의 정보라는 생각에 이렇게 표현했는데 사용할 때가 아닌 선언할 때의 의미에 대해서 생각해볼 필요성이 느껴집니다. 좋은 피드백 감사합니다!

2024-03-23 08:31 UTC, simorimi commented on src/interfaces/IRespondData.ts
> +interface IRespondData {
심지어 다른 인터페이스의 경우 명사형으로 지키고있는데 반해 이 부분에는 동사형으로 오해할 가능성이 큰 단어가 선택되었네요. 해당 부분은 명사형으로 바꾸는 것이 제가 봐도 설득력이 더 있다고 생각합니다! 좋은 피드백 감사합니다 :)

2024-03-23 08:48 UTC, simorimi commented on src/components/ItemView/ItemView.ts
> +    if (this.#page === movieListData.total_pages || this.#page === 500) {
500에러가 아닌 페이지가 500인 경우에 대해 더 보기 버튼을 삭제한 것인데요 왜냐하면 tmdb가 인기 영화 순위를 total로 43000개를 가지고 있으나 실제로는 500페이지까지만 정보를 가지고 올 수 있더라고요 그래서 500페이지인 경우가 제일 마지막 정보라고 판단하여 더 보기 버튼을 삭제하는 방향으로 작성하였습니다!

2024-03-23 08:50 UTC, simorimi commented on src/interfaces/IButton.ts
> +  classes: string[];
interface를 지정할 때 그게 훨씬 의미 전달이 명확할 것 같네요! 좋은 피드백 감사합니다 :)

2024-03-23 10:06 UTC, simorimi commented on src/domain/DTO/Request/sendRequest.ts
> +      page: `${page}`,
이 표현 방식이 의도가 훨씬 보여서 좋네요! 세세하게 봐주셔서 감사하고 좋은 피드백 주셔서 감사합니다 :)

2024-03-23 11:04 UTC, simorimi commented on cypress/support/commands.ts
싸이프레스에 대해 무지하다는 생각에 모르는 문서는 그냥 놔뒀던 것 같습니다 ㅠㅠ.. 살펴보니 전부 주석처리 된 파일이라 크게 필요가 없을 것으로 보이네요 추가적으로 support 하위에 실수로 e2e라는 문서도 생성했었는데 삭제에 대해서 신경을 못 쓴 것 같습니다! 조금 더 꼼꼼히 수정해야겠군요. 좋은 피드백 감사합니다 :)

2024-03-23 11:14 UTC, simorimi commented on src/domain/DTO/Request/sendRequest.ts
> +  return searchedMovies;
처음에 상수화를 했던 것은 return하는 값에 대해 명확하게 나타내주는게 좋겠다는 생각에 진행하였습니다. 그러한 방식이 가독성에 좋지 않을까라는 생각을 했었거든요. 그러나 재사용성이 없다면 굳이 상수화를 안해줘도 되겠다는 생각도 드네요. 좋은 피드백 감사합니다 :)

2024-03-23 12:01 UTC, simorimi commented on src/domain/Validator/SearchValidator.ts
> +  },
처음 의도는 공백 입력 방지와 스페이스만을 입력했을 때 두 경우를 막고자 하는 의도 였습니다. 그러나, 타입스크립트 형식에 의해서 isInputEmpty는 작동을 하지 않더라고요. 그래서 해당 부분을 고민하다가 입력값을 trim과 replace를 활용하여 다듬은 다음 해당 값이 undefined면 오류를 발생시키도록 바로 하면 되겠더라고요! 질문 덕분에 좀 더 좋은 코드로 수정할 수 있었습니다 감사합니다 :)

2024-03-23 12:06 UTC, simorimi commented on src/components/ItemView/ItemView.ts
> +    title.textContent = `${containerTitle}`;
이 또한 템프럴 리트럴을 계속 사용하던 습관에 의해 관성적으로 작용한 것 같습니다.. 생각보다 당연하다는 부분에서 실수들이 꽤 나오는 것 같군요! 사소한 부분에 대해서도 조금 더 의식하도록 습관을 가져야겠습니다! 좋은 피드백 감사합니다 :)

2024-03-23 12:20 UTC, simorimi commented on src/interfaces/IButton.ts
> +interface IButton {
타입스크립에 대한 배움이 전무하여 이전 페어 작업을 하면서 자연스럽게 인터페이스 네이밍에 대해서는 I를 붙이고 타입별칭에 대해서는 T를 붙인다는 식으로 배워 그렇구나 정도로 생각하였습니다. 그러나, 질문 덕분에 찾아보니 다른 언어와는 달리 자바스크립트에서는 관습적으로 Interface와 Type에 대해서는 Class와 유사하게 PascalCase를 쓴다는 것을 알게 되었네요! 좋은 피드백 감사합니다 :)

2024-03-23 12:38 UTC, simorimi commented on src/components/MovieItems/MovieItems.ts
> +    [...Array(OPTIONS.movieItemCount)].forEach(() => {
보여주신 아티클 잘 읽어보았습니다! 실제로 Array 생성자를 사용하게 되면 코드를 읽을 때 경우의 수를 생각하게 되니 가독성 측면에서 많이 떨어질 것이라는 생각이 드네요. 또 Array.from({length:20}) 식으로 작성하는 것이 훨씬 의미 파악에도 좋을 것이라는 생각이 듭니다! 좋은 피드백 감사합니다 :)

2024-03-23 16:35 UTC, simorimi commented on src/components/MovieItems/MovieItems.ts
스켈레톤도 movieItems를 생성하기 위하여 존재하니 역할이 여기로 가야하지 않을까라는 생각에 그렇게 구현했던 것 같습니다. 그러나, 실제로 스켈레톤을 생성하는 것과 실제 데이터로 바뀌는 메서드를 실행할 때 한 객체 안에 있지만 서로 너무 다르게 행동한다는 생각에 분리하는 것이 맞겠다는 생각이 들더군요. 실제로 구글에서 유트브에 존재하는 스켈레톤도 따로 관리한다는 정보도 알게 되니 더욱 스켈레톤 컴포넌트를 따로 관리하는게 좋아보입니다. 좋은 피드백 감사합니다 :)

2024-03-23 22:12 UTC, simorimi commented on src/components/ItemView/ItemView.ts
> +  create(itemViewTitle: string, search?: string) {
점심 뭐 먹지 step2 구현 당시 나름 의식의 흐름대로 컴포넌트 만들기 자료를 참고하였다고 생각했는데 이번 피드백들을 통하여 다시 생각해보게 되었네요. 학습이 많이 부족했던.. 제 자신을 다시 돌이켜보고 반성합니다. 다시 해당 자료를 꺼내 보면서 어떤 부분이 부족한지 최대한 파악하고 보완해보려 했습니다. 그 결과 재사용성을 높이기위해서는 이벤트 함수에 대해서는 외부에서 매개변수로 전달받는 식으로 하고 index에서 document에 붙이는 방향으로 해야겠다고 느꼈습니다. 컴포넌트를 만들고 조합하고 document에 붙인다는 의미에 대한 이해가 한발짝 앞선 것 같아 무척 좋군요! 좋은 피드백 감사합니다 :)

2024-03-23 22:15 UTC, simorimi commented on src/components/MovieHeader/MovieHeader.ts
> +    document.getElementById('app')?.appendChild(header);
만드는 것 까지가 헤더의 역할로 분류하고 조합하고 document에 붙이는 것은 index에서 하는 방향이 가장 관심사 분리에도 적합하고 재사용성에도 좋겠더라고요! 점심 뭐 먹지 자료 많은 도움 받았습니다. 좋은 피드백 감사합니다:)

2024-03-23 22:15 UTC, simorimi commented on src/components/MovieHeader/MovieHeader.ts
> +    new ItemView(inputText);
처음에는 이벤트 핸들러를 외부에서 넣어줄 생각을 못하고 계속 내부에서 해결하려고 했던 것이 큰 잘못이었던 것 같습니다. 내부에서 있게 되면 이 코드는 잘 돌아갈지라도 재사용성 측면에서는 무척 멀어진다는 것을 알게 되었습니다. 이번 미션을 통하여 컴포넌트 이해에 한발짝 다가간거 같아 좋군요 좋은 피드백 감사합니다 :)

2024-03-23 22:19 UTC, simorimi commented on src/components/MovieHeader/MovieHeader.ts
> +  setHandle(logoImgContainer: HTMLElement, searchBox: HTMLElement) {
맞습니다! 어떤 핸들을 세팅하는지 의미가 전혀 담기지 않은 걸 저도 느낄 수 있군요. header에 핸들을 세팅한다는 의미로 명시하였는데 타인이 봤을 떄는 헤더에 어떠한 세팅이 있는지 전혀 모르는데 말이죠. 해당 부분에 대한 수정과 더불어 전체적으로 역할의 분리에 힘을 쏟아봤습니다! 좋은 피드백 감사합니다 :)

2024-03-23 22:21 UTC, simorimi commented on cypress/fixtures/movie-popular.json
허허 그러게요 이 것은 왜 영어로 받았을까요.. 일관성도 없고 조금 아쉽네요. 좋은 피드백 감사합니다!

2024-03-23 22:37 UTC, simorimi commented on cypress/e2e/APITest.cy.ts
> +    cy.request('GET', popularMovieUrl).as('popularMovies');
저도 보는데 숨쉬기가 힘들군요.. 허허 일관된 개행에 조금 더 신경쓰도록 하겠습니다. 좋은 피드백 감사합니다 :)

2024-03-23 22:41 UTC, simorimi commented on cypress/e2e/FixtureTest.cy.ts
검색 결과가 없는 경우 없다는 메시지가 나타나는지 확인하는 테스트
공백 입력시 토스트 메시지 나타나는지 테스트 정도가 있어보입니다!

2024-03-24 06:28 UTC, simorimi commented on cypress/support/commands.ts
이 파일이 없으면 실행이 안더ㅣ더라고여

2024-03-24 13:17 UTC, uk960214 requested changes
두 사람의 피드백을 빠르게 반영해주시느라 수고 많으셨습니다 시모!
추가적으로 궁금한 점 남겼는데 확인부탁드립니다.
전체적으로 잘 반영해주셔서 크게 수정할 점은 없고 사소한 부분 몇가지만 더 고민해보면 좋을 것 같아요!

2024-03-24 13:17 UTC, uk960214 commented on src/components/ItemView/ItemView.ts
> +    return await fetchPopularMovies(++this.#page);
전위연산자를 사용해서 페이지를 증가시켜야만 했던 이유가 있을까요?

2024-03-24 13:17 UTC, uk960214 commented on src/domain/DTO/Request/sendRequest.ts
> +    api_key: KEY as string,
process.env의 타입이 정의가 되지 않아서 단언을 해주어야 했나보네요!
환경 변수에 대해서도 타입 선언을 해줄 수 있는 방법을 찾아보아도 좋을 것 같습니다.
(* 조금 난이도가 높을 수 있으니 우선순위는 나중으로 미루셔도 됩니다!)

2024-03-24 13:17 UTC, uk960214 commented on src/domain/DTO/Request/sendRequest.ts
이 질문에 대해서도 추가적으로 답변을 해주시면 DTO라는 네이밍을 이해하는데에 도움이 될 것 같아요!

2024-03-25 07:42 UTC, simorimi commented on src/components/ItemView/ItemView.ts
> +    if (this.#page === movieListData.total_pages || this.#page === 500) {
해당 코드를 읽고서 전혀 의도를 파악할 수 없다는 생각이 드네요! 그래서 해당 숫자를 매직넘버를 활용하면 조금 더 가독성이 좋고 타인이 봤을 때도 아 이 코드의 페이지가 인기 영화의 전체 페이지구나라고 알 수 있게 하였습니다. 좋은 피드백 감사합니다

2024-03-25 07:53 UTC, simorimi commented on src/interfaces/Button.ts
> +interface Button {
일관성이 없고 실제 수정 하다가 default 값이 변경되는 문제를 겪기도 했습니다. 그리고 제가 다시 봐도 클래스명과 똑같으니 충분히 헷갈리겠더라고요. 의도를 담고 작성한 저도 이렇게나 혼란이 있는데 타인들은 어떨까라는 생각도 듭니다. 그리고 또 다른 인터페이스의 경우 data로 잘 표기했는데 이것만 다르더라고요! 그것에 관해서도 일관성이 없었던 것 같습니다. 좋은 피드백 감사합니다 :)

2024-03-25 14:58 UTC, simorimi commented on src/components/ItemView/ItemView.ts
> +    return await fetchPopularMovies(++this.#page);
처음 의도했던 것은 패치 정보에서 증가된 페이지 값을 받아 온 다음 해당 페이지와 토탈페이지를 비교하는 로직이 자연스럽다고 생각하여 사용했습니다. 후위 연산자를 사용하게 된다면 들어가는 페이지 값과 나와서 토탈페이지와 비교하는 값이 달라지기에 전위 연산자를 의도하였습니다. 그러나 해당 코드들이 읽기에 썩 쉽게 읽힌다는 생각이 잘 안 들더라고요. 그래서 해당 코드를 패치 부분이 아니라 마운트를 할 당시 페이지를 증가시킨 다음 로직을 진행하는게 읽기에 자연스럽지 않나 생각이 드네요. 더보기 버튼을 누를 때 마운트 메서드를 적용하는데 더보기를 한다는 행위가 다음 페이지를 의미하니 마운트 메서드를 동작할 때 후위 연산자를 통해 페이지 수를 증가한 뒤 다음 로직들을 진행하는게 의미 전달에 더 와닿겠다는 생각이 드네요. 좋은 피드백 감사합니다.
 그나저나 해당 로직을 후위연산자로 바꾸는 과정에서 오류를 발견해서 좋았네요. (오류를 발견하고 해결해서 좋았으나.. 발견할 때까지 시간은 다소 걸렸습니다 ㅠㅠ) 검색창에 엔터키를 누를 때 한글의 경우 두번 연속 엔터가 되어 처음에 후위 연산자로 수정했을 떄는 정상 작동을 하지 않더라고요. 알고보니 한글을 입력하고 keydown 이나 keyup의 경우 enter 키와 같이 사용하게 되면 IME문자이기에 중복으로 발생하는 것으로 확인 되더라고요 그래서 MDN 문서에서 권유하는 방식으로 if (event.isComposing) {
        return;
      }를 사용했습니다만.. 되지가 않았습니다. 그래서 권하는 방식은 아니지만 keypress를 사용했습니다..

2024-03-25 22:32 UTC, simorimi commented on src/domain/DTO/Request/sendRequest.ts
솔직히 설명드리겠습니다. 당시 상황을 설명 드리자면, 페어와 폴더명과 파일명을 고민하던중 페어가 제시한 의견이 '보통 이런 경우에는 DTO를 쓴다'였습니다. 그 말을 듣고서는 제가 모르는 것이 많다고 생각했기에 관례적으로 그렇게 쓰는구나라고 생각했고 관례적으로 쓴다면 그게 의사소통 적으로 좋겠다는 생각에 해당 개념에 대한 이해없이 소위 말하는 무지성으로 사용하였습니다! 어설프게 제대로 알지 못하면서 쓴 점에 대해 반성하는 계기가 되었네요. DTO에 대해서 살펴 본 결과 데이터 전송 객체로 비지니스 로직과 달리 순수한 데이터만을 가지고 있는 것에 대해서 설명하더라고요. 그러나 이러한 것들이 도메인 로직에 있다는 점이 잘못 되었고 해당 폴더의 경우 떡하니 비지니스 로직을 담고 있는 점이 해당 개념과 다르다는 생각이 들었습니다. 페어 활동 하면서 무조건 적으로 동의 보다는 설명과 설득을 요구하는 과정이 조금 더 필요하다는 생각이 들었네요! 좋은 피드백 감사합니다:)

2024-03-25 22:51 UTC, simorimi commented on src/domain/DTO/Request/sendRequest.ts
> +    api_key: KEY as string,
해당 부분에 대해서는 나중에 보완하도록 하겠습니다! 이번 미션 학습 목표인 비동기에 대한 학습도 아직 부족하다고 판단합니다. 그래서 우선순위에 대해서 조금 미루도록 하겠습니다! 좋은 피드백 감사합니다:)

2024-03-25 23:53 UTC, uk960214 approved these changes
피드백이 정말 다양하게 많았는데, 열심히 반영해주셔서 감사합니다!
2단계에서는 어떤 더 발전된 모습을 보여주실지 기대가 됩니다.
남은 2단계도 화이팅해서 다음 리뷰요청에서 뵙겠습니다!
화이팅하세요!! 💪

2024-03-25 23:53 UTC, uk960214 commented on src/constants/INFORMATION.ts
> +};
```suggestion
const BUTTONS: Record<string, ButtonData> = {
  search: {
    innerText: '검색',
    classList: ['search-button'],
  },
  showMore: {
    innerText: '더 보기',
    classList: ['btn', 'primary', 'full-width'],
  },
};
```

로도 수정할 수 있을 것 같아요! (요것도 하지만 우선순위는 나중인것으로..)

2024-03-25 23:53 UTC, uk960214 commented on src/domain/DTO/Request/sendRequest.ts
솔직한 답변 감사합니다!
저는 특히 디렉토리와 파일 네이밍은 개발자가 어떤 구조를 표현하고자 했는지 드러나는 아주 중요한 부분이라고 생각하는데요,
변수와 함수의 네이밍 뿐 아니라 이런 부분도 더 잘 챙기면 전체 코드 자체를 훨씬 더 잘 파악하는데 도움이 될 것 같아요!
이 기회로 앞으로 더 잘 신경써주실 것이라 믿습니다!!

2024-03-25 23:54 UTC, merged