[2단계 - 상세 정보 & UI/UX 개선하기] 버건디(전태헌) 미션 제출합니다.
woowacourse/javascript-movie-review pull request #140
Opened 2024-03-27 01:42 UTC by brgndyy

2024-03-27 02:01 UTC, brgndyy commented on src/components/Header/render.ts
웹 화면 사이즈일때 `form`안에 있는 버튼이 기존에는 `submit`버튼이었다가 모바일 환경으로 바뀌었을때, 단순 `toggle`버튼으로 역할이 바뀌어야하더라구요..!

그래서 아예 둘다 일단 dom에 띄워주고 `absolute`로 겹쳐준 후에, `display : 'none'`을 사용해서 조작해주었는데요.

사용자가 개발자도구로 살펴보았을때, 요소창에는 나타나있는 상태입니다..!

모바일 환경일때 => 웹 환경의 `form`을 지워주고 모바일 환경에 맞는 `form`을 새롭게 만들어준다.
웹 환경일때 => 모바일 환경의 `form`을 지워주고 웹 환경에 맞는 `form`을 새롭게 만들어준다.

이렇게 직접 DOM에 접근하는 방식보다는 더 비용적으로 낫지 않을까? 싶어서 이런 방식으로 구현해본것인데요

제가 놓친 부분이 있다면 말씀 주시면 감사하겠습니다 🙇

2024-03-28 01:02 UTC, zigsong commented
안녕하세요 버건디, 2차 리뷰는 오늘 저녁에 하도록 하겠습니다!

2024-03-28 02:22 UTC, woowahan-cron commented
## 사용성 리뷰

1. PC버전에서 포스터 이미지 비율이 깨집니다.
   - <img width="1860" alt="image" src="https://github.com/woowacourse/javascript-movie-review/assets/112997662/902c073d-c648-4210-a27f-12606f1d65d7">
2. 영화 줄거리 정보가 없는 경우 모달 창의 크기가 일관성이 맞지 않습니다.
   - <img width="2552" alt="image" src="https://github.com/woowacourse/javascript-movie-review/assets/112997662/f1117f5f-139e-4439-a569-02eb32ef3f37">
   - <img width="2426" alt="image" src="https://github.com/woowacourse/javascript-movie-review/assets/112997662/a7d84b5a-eb87-48d6-88f2-6aeb71045396">

2024-03-28 02:43 UTC, brgndyy commented
수정사항 현재 로컬에서는 반영해놓은 상태인데, 리뷰어분께 리뷰 받은 후에 수정 사항 반영해서 추가 push 하도록 하겠습니다!

2024-03-28 02:44 UTC, brgndyy commented
> 안녕하세요 버건디, 2차 리뷰는 오늘 저녁에 하도록 하겠습니다!

감사합니다!

2024-03-28 02:44 UTC, brgndyy commented
> ## 사용성 리뷰
> 1. PC버전에서 포스터 이미지 비율이 깨집니다.
>    
>    * <img alt="image" width="1860" src="https://private-user-images.githubusercontent.com/112997662/317568734-902c073d-c648-4210-a27f-12606f1d65d7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE1OTQxMjIsIm5iZiI6MTcxMTU5MzgyMiwicGF0aCI6Ii8xMTI5OTc2NjIvMzE3NTY4NzM0LTkwMmMwNzNkLWM2NDgtNDIxMC1hMjdmLTEyNjA2ZjFkNjVkNy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzI4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMyOFQwMjQzNDJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00M2ZhZWRmNDk4MWUwZjlmM2EyOGVhMjQwNWVkMTA2ODJkMWZkYWY0MDRlNzI1NmM4MGNjNmRlNWM1MGZhMDUxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.mi1P-henpojKL6WPeOtge_kjdaWtKB6Zky0KcNBtF7M">
> 2. 영화 줄거리 정보가 없는 경우 모달 창의 크기가 일관성이 맞지 않습니다.
>    
>    * <img alt="image" width="2000" src="https://private-user-images.githubusercontent.com/112997662/317568663-f1117f5f-139e-4439-a569-02eb32ef3f37.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE1OTQxMjIsIm5iZiI6MTcxMTU5MzgyMiwicGF0aCI6Ii8xMTI5OTc2NjIvMzE3NTY4NjYzLWYxMTE3ZjVmLTEzOWUtNDQzOS1hNTY5LTAyZWIzMmVmM2YzNy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzI4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMyOFQwMjQzNDJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jNzhkMDY4MjI1NDljNzg1ZWMyNjM0OTU3ODQ5NWIzZmJjZTIzY2NmNGRiZjYyNTI2MjY3MDY2NmIzMTUxMzJkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.GnV0Imr3mimoeYJeaFZFF1ojVNvDcHi9wZ_d5C-wKrA">
>    * <img alt="image" width="2000" src="https://private-user-images.githubusercontent.com/112997662/317568823-a7d84b5a-eb87-48d6-88f2-6aeb71045396.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE1OTQxMjIsIm5iZiI6MTcxMTU5MzgyMiwicGF0aCI6Ii8xMTI5OTc2NjIvMzE3NTY4ODIzLWE3ZDg0YjVhLWViODctNDhkNi04OGYyLTZhZWI3MTA0NTM5Ni5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzI4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMyOFQwMjQzNDJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05NWZmMWFmOTJmYzVjZjc5MDY1NDRjNzdmMDFlYTRlOGFkMmU2ZDMzN2VkYTBmMTgzMmE2NWEyOTVhNTY4MzAxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.QfGq-q0H4dTRaG8SEbG7Mlsv1rflKMUeF4eorvZg720">

수정사항 현재 로컬에서는 반영해놓은 상태인데, 리뷰어분께 리뷰 받은 후에 수정 사항 반영해서 추가 push 하도록 하겠습니다! 
짚어주셔서 감사합니다 🙇

2024-03-28 04:26 UTC, woowahan-cron requested changes
![image](https://github.com/woowacourse/javascript-movie-review/assets/112997662/1a464a72-959b-4546-9cf7-6f04bc9ffab8)

안녕하세요 버건디!
지그가 오기 전에 아주 가볍게 리뷰해 봤습니다!

영화 리뷰 미션 어떠셨나요?
"이번 미션에서는 실제로 서버 API와 통신하여 받아 온 데이터를 렌더링하면 되겠구나" 하고 생각하셨겠지만, 생각보다 사용자를 위한 처리가 많아지다 보니까 번거로움도 많이 느껴지셨을 것 같아요.

내일 수업 시간에 다룰 공통 피드백을 제외하고는 제가 리뷰하고 싶은 부분들 코멘트로 간략히 남겼습니다.

## 피드백 종합

1. 전체적으로 개행의 일관성을 맞춰주시면 좋겠어요.
2. 함수/메서드 이름을 지을 때는 품사가 어떻게 되는 것이 적절할지 고민해 주시면 좋겠어요
3. 함수의 이름이 handle 또는 handler가 들어가는 것이 적절한지 고민해 주시면 좋겠어요.
4. 어떤 오류를 던져야 할지, 어떤 오류를 무시해도 되는 경우를 구분해 보는 것도 좋을 것 같아요.
5. 오류를 마주하게 되는 것이 사용자인지, 개발자인지도 구분해 보면 좋을 것 같아요

기타 나머지 피드백은 아래의 코멘트를 참고해 주세요!
앞으로의 리뷰는 지그와 함께해 주시고 지그가 알아서 Merge해 주실 때까지 진행해 주시면 됩니다🙂
레벨1 마지막까지 최선을 다해서 끝내 봅시다 아자아자!!!!

![image](https://github.com/woowacourse/javascript-movie-review/assets/112997662/88a84f68-9385-4d21-9bd1-a86644f32847)

2024-03-28 04:26 UTC, woowahan-cron commented on src/components/Header/render.ts
> +  return boxContainer;
```suggestion
  const boxContainer = createElement('div', {
    className: 'box-container',
  });
  const input = createElement('input', {
    type: 'search mobile',
    placeholder: '검색',
    className: 'mobile-search-input',
  });
  const searchButton = createMobileSearchButton();
  const mobileSubmitButton = createMobileSubmitButton();
  
  boxContainer.appendChild(input);
  boxContainer.appendChild(searchButton);
  boxContainer.appendChild(mobileSubmitButton);

  return boxContainer;
```

선언부 밑에 개행이 하나 더 있으면 좋겠네요!

2024-03-28 04:26 UTC, woowahan-cron commented on src/components/Header/render.ts
> +  return mobileSearchBox;
```suggestion
  const mobileSearchBox = createElement('form', {
    className: 'mobile-search-form mobile',
    id: 'searchForm',
  });
  const boxContainer = createMobileSearchBarContent();
  mobileSearchBox.appendChild(boxContainer);
  
  return mobileSearchBox;
```

일관성 맞춰주세요!

2024-03-28 04:26 UTC, woowahan-cron commented on src/components/Modal/renderModalContent.ts
> +};
```suggestion
const createNoneInfo = () => createElement('h2', { textContent: '영화 정보가 존재하지 않아요!' });
```

간단하게 선언해도 괜찮지 않을까요?

2024-03-28 04:26 UTC, woowahan-cron commented on src/components/Modal/renderModalContent.ts
> +  return infoContainer;
```suggestion
  const infoContainer = createElement('div', {
    className: 'info-container',
  });

  if (genres && vote_average && overview && star_rating) {
    const movieGenreAndVoteAverage = createGenreAndVoteAverage(genres, vote_average);
    const movieOverView = createMovieDetailOverview(overview);
    const starRating = createMovieDetailStarRating(star_rating);

    infoContainer.appendChild(movieGenreAndVoteAverage);
    infoContainer.appendChild(movieOverView);
    infoContainer.appendChild(starRating);
  }
  
  return infoContainer;
```

개행 일관성 피드백입니다

2024-03-28 04:26 UTC, woowahan-cron commented on src/components/MovieContainer/MovieContainer.ts
> +  renderMovieItemDetailModalHandler();
```suggestion
  const dataFromServer = await movieFetcherWithLoadingOrErrorState.fetchData(API_ENDPOINT.POPULAR(), {
    headers: API_OPTION.headers,
  });
  const { results } = dataFromServer;
  const data = MovieStorageService.addData(results);
  
  renderHandler(data);
  initializeInfiniteScroll();
  renderMovieItemDetailModalHandler();
```

선언부 밑에 개행이 있으면 조금 숨 쉴 여유가 있을 것 같아요!
대체로 급하게 제출해서 그런지 일관성이 지켜지지 못한 부분들이 더러 있네요 ㅜㅜ

2024-03-28 04:26 UTC, woowahan-cron commented on src/components/MovieItem/eventHandler.ts
> +  openModalHandler();
여기도! (handler, 함수 이름에 관한 피드백)

2024-03-28 04:26 UTC, woowahan-cron commented on src/components/MovieItem/eventHandler.ts
> +  const li = event.target.closest('li');
```suggestion
  if (!(event.target instanceof Element)) return;
  
  const li = event.target.closest('li');
```

1. 여기서 개행을 주는 것이 낫지 않을까요?
2. 그런데 event.target Element 객체를 받지 못하면 return해서 핸들러 함수를 실행하지 않으면 될까요?
   - 이 함수를 사용하는 사람은 개발자일 것 같은데 오류를 터뜨리는 것이 더 낫지 않을까 싶습니다. (제 생각)
      - 개발자가 event.target 객체가 Element가 아니어서 return된 경우를 빠르게 알아차릴 수 있을까요?

2024-03-28 04:26 UTC, woowahan-cron commented on src/components/Modal/Modal.ts
![Mar-28-2024 13-15-27](https://github.com/woowacourse/javascript-movie-review/assets/112997662/e1f2c0a2-87b6-4cda-bba2-7a19cec7d79a)

모달 창을 띄우면 영화 포스터가 로드되기 전에 별점의 별이 먼저 뜨던데 의도하신 걸까요?

2024-03-28 04:26 UTC, woowahan-cron commented on src/services/LocalStorageService.ts
> +    localStorage.setItem(LOCAL_STORAGE.KEY, JSON.stringify(data));
### 🎙️ 코드 인터뷰

<img width="743" alt="image" src="https://github.com/woowacourse/javascript-movie-review/assets/112997662/8030e6c6-11dc-4b8c-a2c2-d60634aecb20">

스토리리지를 보니까 로드하고 있는 모든 영화를 로컬스토리지에 저장하고 있던데 의도가 무엇인가요?

2024-03-28 04:26 UTC, woowahan-cron commented on src/services/MovieFetcherWithLoadingOrErrorState.ts
> +      this.showErrorComponent(errorComponent);
여긴 한 줄로 퉁쳐도 괜찮지 않을까요?!

2024-03-28 04:26 UTC, woowahan-cron commented on src/components/Modal/renderModalContent.ts
> +import defaultImageSrc from '../../../templates/star_filled.png';
왜 defaultImageSrc가 별인가요?

2024-03-28 05:11 UTC, brgndyy commented on src/components/ErrorComponent/render.ts
> +    return '죄송합니다. 현재 찾을 수 없는 페이지를 요청 하셨습니다.';
현재 크론 말씀처럼 해당 미션은 1페이지 짜리이기도 하고 이미 엔드포인트들이 정해져있기 때문에 현재 상황에서는 단일 에러 처리만 해주어도 괜찮을거라고 생각하긴 하는데요.

하지만 제가 확장성 관점에서 만약에 라우트 경로가 하나라도 추가 된다면, 404 에러 같은경우는 발생할 확률이 굉장히 크다고 생각했습니다. 

예를 들어서 현재는 바로 모달로 영화정보를 띄워주는데, 이러한 방법이 아니라 영화이름으로 값을 받아서 새롭게 페이지를 처리해주어야한다면 ? 같은 가정을 들수가 있을거 같습니다.

정리해보면, 분기별로 에러처리를 해주는것이 현재 상황에서 오버엔지니어링이라는 관점도 맞지만, 여기서 404 에러 같은 범용성 높을수밖에 없는 에러를 대비해주는 것이 그렇게 큰 비용이 들지는 않겠다고 판단했습니다. 

제가 잘못 짚고 있는 부분이 이나 따로 말씀 주실 부분이 있으시다면 말씀 주시면 감사할거 같아요 !  🙇

2024-03-28 05:58 UTC, brgndyy commented on src/components/ErrorComponent/render.ts
> +const getTargetErrorMessage = (errorStatus: number) => {
이번에서 이 status에 따라서 분기별로 에러 컴포넌트를 렌더링 해주는것을 의도해보았는데요.

`MovieFetcherWithLoadingOrErrorState` 내에서 에러를 받았을때, 해당 에러 status 를 받아서 컴포넌트를 렌더링해주는것이 크론께서 말씀해주신 `실질적인 오류 처리 로직` 이라고 생각했고 

ErrorComponent 에서는 해당 status를 받아서 렌더링만 해주면 되는 부분이라 생각해서 Error 컴포넌트는 렌더링만 담당한다고 판단했어요! 

만약에 `실질적인 에러 처리` 라고 범주로 잡는 부분이 에러 컴포넌트 렌더링까지라면

```javascript
  onErrorChanged(error: HttpError | null) {
    if (error.status === 404) {
     // 404관련 에러 컴포넌트 렌더링
    }
   if(error.status ===503){
   // 503 관련 에러 컴포넌트 렌더링
}
  }
```

이런식으로 아예 에러 코드에 맞도록 컴포넌트 렌더링 자체를 `MovieFetcherWithLoadingOrErrorState` 내에서 분기처리를 해주는 방법이 생각납니다.

제가 잘못 짚고 있거나, 말씀 주실 부분이 있으시다면 말씀주시면 감사하겠습니다 !

2024-03-28 05:59 UTC, brgndyy commented on src/components/Header/eventHandler.ts
> +export const keywordSubmitHandler = (searchType: SearchType) => {
맞는 말씀입니다! 
짚어주셔서 감사해요! 더 고심해서 네이밍 해보도록 하겠습니다 !

2024-03-28 06:04 UTC, brgndyy commented on src/components/Header/eventHandler.ts
> +  window.scroll(0, 0);
현재 이 헤더 배너가 루트 페이지로 라우팅 해주는 기능을 한다고 생각해보았는데요.

만약 저 스크롤을 위로 올려주지 않는다면, 단순히 페이지만 새로고침 될뿐, 스크롤은 위로 올라가지 않는 현상이 발생했습니다.

만약에 다른 라우트 페이지에서 헤더 배너를 클릭하면 홈페이지로 새롭게 이동하듯이, 그러한 기능을 한번 구현하려고 해보았어요! 

잘못 짚고 있거나 말씀 주실 부분 있으시다면 말씀 주시면 감사하겠습니다 🙇

2024-03-28 06:06 UTC, woowahan-cron commented on src/components/ErrorComponent/render.ts
> +    return '죄송합니다. 현재 찾을 수 없는 페이지를 요청 하셨습니다.';
찾을 수 없는 페이지가 발생한다면 그것은 사용자 귀책일지, 프로덕트 귀책일지도 고민해 보시면 좋을 것 같습니다!
보여주는 메시지는 사용자를 대상으로 하고 있는데 404 에러가 발생하는 경우는 사용자의 귀책이라기보다 프로덕트의 귀책에 가깝지는 않을까? 해서요.

2024-03-28 06:06 UTC, brgndyy commented on src/components/Header/Header.ts
>    reloadPageHandler();
```
조금 더 복잡한 이벤트나 일을 처리한다면 handler는 블랙박스가 될 것 같아요.
```

라는 말씀이 제대로 이해가 잘 안가는데, 혹시 더 설명 부탁드려도 될까요 ?

제가 판단했을때는 해당 헤더 배너 이미지를 `클릭` 해야만  `reloadPage`라는 함수가 실행 된다는 의미에서, 

그리고 이 **헤더 배너에 이벤트 리스너를 부착해주어야지만 해당 함수가 바인딩 되기 때문에** 이렇게 함수명을 지은것인데요.

제가 잘못 생각하고 있는 부분이 있을까요 ?

2024-03-28 06:07 UTC, woowahan-cron commented on src/components/ErrorComponent/render.ts
> +const getTargetErrorMessage = (errorStatus: number) => {
오호. 스코프 상으로는 createErrorElement 함수 밖에 있어서 관심사가 분리되었다고도 볼 수 있지만요.
디렉터리의 이름은 ErrorComponent이고 render.ts 파일이다 보니 이곳에 getTargetErrorMessage라는 함수가 있는 것이 적절한가에 관한 물음이었어요!

2024-03-28 06:08 UTC, woowahan-cron commented on src/components/Header/Header.ts
>    reloadPageHandler();
아래의 코드를 보시면 이해되실 거 같습니다.

```js
something.addEventListener('click', () => clickHandler(123));
something.addEventListener('click', () => showImage(123));
```

2024-03-28 06:09 UTC, brgndyy commented on src/components/MovieItem/eventHandler.ts
> +  const li = event.target.closest('li');
1. 이번에 미션 기준을 10줄로 잡고 함수를 구현하다보니까, 개행 부분을 일부러 줄인 부분들이 많이 있습니다..! 이미 구현을 끝낸 함수가 11-12줄인경우 개행만 줄여주면 된다는 생각에 그렇게 된것 같아요.

2. 
맞는 말씀이에요! 사실 요소를 찾고나서 해당 요소가 없으면 예외처리를 해주는게 더 맞는 동작이라고 생각합니다. 함수가 10줄이라는 생각에 예외처리 또한 저 함수 안에 들어가야한다는 생각에 기반해서 놓친거 같습니다. 짚어주셔서 감사해요! 한번 더 고심해보도록 하겠습니다~!  🙇

2024-03-28 06:11 UTC, brgndyy commented on src/components/Modal/Modal.ts
이번에 이미지 관련해서 `onLoad` 함수 구현할때 한번 테스트겸 넣어본것인데 놓쳤습니다.

적절한 이미지로 수정하도록 하겠습니다.

짚어주셔서 감사합니다 🙇

2024-03-28 06:16 UTC, brgndyy commented on src/services/LocalStorageService.ts
> +    localStorage.setItem(LOCAL_STORAGE.KEY, JSON.stringify(data));
별점 기능을 구현할때 레이어 구성자체를 

1. tmdbapi에서 데이터를 받아온다.
2. 별점 속성을 추가해주는 포맷팅 함수에 받아온 데이터를 넣어주어서, `star_rating` 프로퍼티를 추가해준다.
3. 해당 데이터를 통해서 별점 기능을 구현한다.

라고 생각하고 구현해본것인데요.

어차피 받아오는 데이터에 무조건 별점 기능이 존재해야한다고 생각해서 이렇게 구현한것인데, 혹시 제가 잘못 짚은 부분이 있을까요 ?

2024-03-28 06:16 UTC, brgndyy commented on src/services/MovieFetcherWithLoadingOrErrorState.ts
> +      this.showErrorComponent(errorComponent);
이또한 함수 10줄 라인 제한으로 인해서, 아예 메인태그에 바인딩 해주는 함수, 즉 직접적으로 렌더링 시켜주는 함수로 따로 빼보았어요!

잘못 짚고 있는 부분이 있다면 말씀 주시면 감사하겠습니다 🙇

2024-03-28 06:17 UTC, brgndyy commented on src/components/Modal/renderModalContent.ts
> +import defaultImageSrc from '../../../templates/star_filled.png';
위에 답변 한 부분이 있어서 그 답변으로 대체하겠습니다. 수정하겠습니다 🥲

2024-03-28 06:25 UTC, brgndyy commented on src/components/Header/Header.ts
>    reloadPageHandler();
`reloadPageHandler` 함수 내부 코드가 

## - reloadPageHandler
```javascript
export const reloadPageHandler = () => {
  const headerBanner = document.querySelector('h1');
  if (!isHTMLElement(headerBanner)) return;

  headerBanner.addEventListener('click', reloadPage);
};
```
이렇게 되어있고 

## - reloadPage
```javascript
const reloadPage = () => {
  window.scroll(0, 0);
  window.location.reload();
};
```

`reloadPage`라는 페이지를 리로딩해주는 실질적인 함수와 이 함수를 바인딩 해주는 함수가 나뉘어져 있다고 판단했는데요..! 

크론의 코드 예시를 보아도 차이점을 잘 모르겠습니다... 🥲

제 능력 부족인거 같은데, 혹시 더 설명 부탁드려도 될까요 ?

2024-03-28 07:43 UTC, woowahan-cron commented on src/components/Header/Header.ts
>    reloadPageHandler();
이름에 굳이 'handler'라는 키워드를 붙이지 않고 함수의 이름에 자신의 역할을 분명히 드러내는 것이 좋지 않을까 하는 이야기였습니다.
그래서 reloadPageHandler()의 경우에도 핸들러라는 이름이 꼭 붙어야하는지가 의문이었습니다 🤔

2024-03-28 07:45 UTC, woowahan-cron commented on src/services/LocalStorageService.ts
> +    localStorage.setItem(LOCAL_STORAGE.KEY, JSON.stringify(data));
제 피드백의 의도는 별점 기능을 말씀드린 것이 아니라
localstorage에 영화 정보에 관한 JSON데이터가 모조리 담기던데.. (불러와서 쓰고 있나요?)
이것이 적절한지에 관한 물음이었습니다.

2024-03-28 07:46 UTC, woowahan-cron commented on src/services/MovieFetcherWithLoadingOrErrorState.ts
> +      this.showErrorComponent(errorComponent);
```suggestion
      this.showErrorComponent(ErrorComponent(error.status));
```
요걸 말씀드린거였습니다!

2024-03-28 07:57 UTC, brgndyy commented on src/components/Header/Header.ts
>    reloadPageHandler();
아하 이해했습니다~ 짚어주셔서 감사해요 크론 !🙇

2024-03-28 08:00 UTC, brgndyy commented on src/services/LocalStorageService.ts
> +    localStorage.setItem(LOCAL_STORAGE.KEY, JSON.stringify(data));
네 맞습니다.

그래서 데이터가 업데이트 될때, 중복된 데이터들은 제외하는 작업을 거치고 set을 해주고 있습니다.

결국 데이터의 흐름이 api 에서 받은 데이터 포맷팅 => 로컬스토리지에 저장 => 사용 의 형태를 띄우고 있습니다.

저는 `결국 모든 데이터들은 디테일 모달을 띄워줄때, 별점 프로퍼티가 필요하다` 라는 판단으로 구현해본것인데요. 

이러한 흐름에 잘못된 부분이 있을까요 ?

2024-03-28 08:04 UTC, brgndyy commented on src/services/MovieFetcherWithLoadingOrErrorState.ts
> +      this.showErrorComponent(errorComponent);
말씀 감사합니다.

저 함수가 10줄 제한 라인에 걸리지도 않고, 라인 수에 관한 여유가 많다고 생각이 들었어요.

그래서  오히려 명시적으로 컴포넌트라는 변수를 하나 만들어줌으로써 다른 사람이 볼때의 가독성을 높이지 않나? 라는 생각도 드는데요! 

이 부분에 관해서 한번 여쭤봐도 될까요 ~?

`변수를 따로 하나 만들어줌으로써 불필요한 메모리를 차지한다.` 라는 관점이신걸까요 ?

2024-03-28 08:06 UTC, brgndyy commented on src/components/ErrorComponent/render.ts
> +const getTargetErrorMessage = (errorStatus: number) => {
헉 맞는 말씀이네요.

짚어주셔서 감사합니다 🙇

그러면 아예 이 `getTargetErrorMessage` 부분을 

`MovieFetcherWithLoadingOrErrorState` 에서 실행 해준후에 에러 컴포넌트로 반환 받은 값 자체를 주입해준다면, 더 나은 관심사 분리가 된걸까요 ?

2024-03-28 08:08 UTC, brgndyy commented on src/components/ErrorComponent/render.ts
> +    return '죄송합니다. 현재 찾을 수 없는 페이지를 요청 하셨습니다.';
```
보여주는 메시지는 사용자를 대상으로 하고 있는데 404 에러가 발생하는 경우는 사용자의 귀책이라기보다 프로덕트의 귀책에 가깝지는 않을까? 
```

이 부분이 아직 이해가 안되어서 한번 더 여쭈어봅니다! 

만약에 라우트가 여러개 존재할때 (a, b, c라는 경로가 존재하는 경우), 

사용자가 `d`라는 임의의 경로를 직접 입력해서 들어가서 404 페이지를 띄워준다면, 이 또한 프로덕트의 귀책으로 바라보아야할까요 ?

저는 이 부분은 사용자의 귀책이라 판단하고 404 라는 status를 생각해준 것이긴 한데요! 

더 공부할 부분 말씀 주시면 감사하겠습니다 🙇

2024-03-28 09:57 UTC, brgndyy commented on src/components/MovieItem/eventHandler.ts
> +  openModalHandler();
짚어주셔서 감사합니다!

2024-03-28 12:16 UTC, zigsong commented on src/components/ShowMoreButton/infiniteScrollHandler.ts
> +const MAX_PAGE_NUMBER = 10;
매직넘버가 될 뻔한 값을 상수로 잘 선언해주셨네요 👍

2024-03-28 12:16 UTC, zigsong commented on src/components/ShowMoreButton/infiniteScrollHandler.ts
> +};
인피니트 스크롤을 구현해보신적이 있나 싶을 정도로, 괜찮은 방법으로 잘 구현하셨습니다 👏

2024-03-28 12:16 UTC, zigsong commented on src/components/ErrorComponent/render.ts
> +    return '죄송합니다. 현재 찾을 수 없는 페이지를 요청 하셨습니다.';
의견을 덧붙이자면, 

사용자가 존재하지 않는 임의의 경로를 검색하여 들어오는 경우는 고의가 아닌 경우 거의 없을 것이고, 사용자가 특정 페이지 주소를 저장하거나 즐겨찾기를 해두었는데 페이지의 라우팅 구조가 바뀌었을 때 사용자 입장에서는 '원래 저장해둔 주소가 왜 존재하지 않는다고 뜨지?' 라고 생각할 수도 있습니다. 

그리고 혹시~ 사용자가 존재하지 않는 임의의 경로를 일부러 검색하여 들어오는 경우에도 `현재 찾을 수 없는 페이지를 요청 하셨습니다.`는 사용자가 '잘못 요청'했다는 뉘앙스이므로 사용자 관점에서 올바른 에러 메시지는 아닐 수 있어요. 

아무튼 서비스를 제공하는 것은 사용자가 아닌 개발자의 책임에 가깝습니다. 404 페이지가 뜬다면, 사용자 친화적인 에러 메시지와 함께, 리다이렉트 주소를 제공하는 등의 추가 조치가 이뤄지면 더 좋을 것 같긴 하네요 :D

2024-03-28 12:16 UTC, zigsong commented on src/components/Header/eventHandler.ts
> +function createMovieItemsWithCheck(results: TotalMovieItemProps[], keyword: string) {
무엇을 `check`한다는 것인가요?

2024-03-28 12:16 UTC, zigsong commented on src/components/MovieItem/eventHandler.ts
> +  openModalHandler();
`openModalHandler()` 이외의 modal과 관련한 로직은 모두 `Modal` 컴포넌트 안에 있는데, 이 함수만 `MovieItem`에 있는 것이 조금 어색합닌다. `renderMovieItemDetailModal()`이 무엇을 리턴하고자 하는지 의미도 명확하지 않고요.

2024-03-28 12:16 UTC, zigsong commented on src/components/MovieItem/render.ts
> +  };
img 태그의 `onerror` 핸들러도 잘 활용하셨네요 👍

2024-03-28 12:16 UTC, zigsong commented on src/constants/api/messages.ts
>    FAIL_FETCH: '데이터를 받아오는데에 실패했어요!',
크론도 문과생이신가요? 저도 항상 거슬렸지만 그냥 모른척하고 넘어가긴 했는데... ㅋㅋㅋㅋ 왠지 감동이에요

2024-03-28 12:16 UTC, zigsong commented on src/services/LocalStorageService.ts
> +      return JSON.parse(data);
비동기 호출로 데이터를 받아오더라도, 별개의 이유로 로컬스토리지에서 가져온 데이터를 파싱하는 과정에서 에러가 발생할 수 있습니다.

> 그리고 또한 이 비동기 호출로 데이터를 받아오는 과정에서 에러가 발생했다면, 에러를 throw를 해주어서 최상단에서 catch로 잡아서 에러를 대처해주고 있다고 판단했어요!

최상단에서 catch로 에러를 잡더라도, 이 에러가 
- 비동기 호출에서의 에러인지
- 파싱 에러인지

를 구분할 수 있어야 합니다.

2024-03-28 12:16 UTC, zigsong commented on src/services/addStarRatePropertyFromOriginalData.ts
> +  }));
사용자가 별점을 매기지 않았을 때 기본으로 10점을 주는 이유는 무엇인가요?

2024-03-28 12:16 UTC, zigsong commented on src/services/getAllMovieGenres.ts
> +};
이 비동기 함수는 에러핸들링을 안해줘도 되나요?

2024-03-28 12:16 UTC, zigsong commented on src/components/Modal/modalContentEventHandler.ts
> +  const numericStarRate = Number(currentStarRate) as StarRate;
넵 알겠습니다! 다만 이 정도의 `as` 단언은 크게 크리티컬하지 않다고 생각합니다

2024-03-28 12:17 UTC, zigsong requested changes
안녕하세요 버건디, 2단계를 빠르게 완성해주셨네요! 😲

우선, 코멘트에 남긴 이유로 컴파일에러로 인해 로컬에서 실행이 불가합니다. 

현재는 코드와 배포 버전으로만 확인하고 리뷰를 했어요. 

제가 갑자기 일정에 치여 첫 리뷰를 조금 급하게 남겼는데, 필요하시면 추가 코멘트 남겨주신다면 주말에 한번 더 자세히 리뷰하도록 하겠습니다.

2024-03-28 12:19 UTC, zigsong commented on src/components/Header/render.ts
앗 이 코멘트를 못보고 따로 또 해당 부분에 코멘트를 남겼었네요.

그런데 2가지 궁금한 점이 있는데요,

- 현재 배포버전의 모바일 화면에서도 toggle로 뜨지 않습니다
- 모바일이든, PC든 모두 `.web-search-form`으로 뜨고 있는데요,

뭔가 잘못 올리신 걸까요? 확인 부탁드려요!

2024-03-28 12:46 UTC, brgndyy commented on src/components/ErrorComponent/render.ts
> +    return '죄송합니다. 현재 찾을 수 없는 페이지를 요청 하셨습니다.';
```
현재 찾을 수 없는 페이지를 요청 하셨습니다.는 사용자가 '잘못 요청'했다는 뉘앙스
```

에 대해서는 생각해보지 못한 부분이었는데요. 짚어주셔서 감사합니다. 

사용자 친화적인 관점에 대해서 한번 더 고심해보도록 하겠습니다 🙇

2024-03-28 12:54 UTC, woowahan-cron commented on src/components/ErrorComponent/render.ts
> +const getTargetErrorMessage = (errorStatus: number) => {
오. 이 부분은 공통 피드백의 오류 핸들링에서 다룰 내용으로 봐도 좋을 것 같습니다.

2024-03-28 12:55 UTC, woowahan-cron commented on src/constants/api/messages.ts
>    FAIL_FETCH: '데이터를 받아오는데에 실패했어요!',
공무원 국어를 공부하다 보니 띄어쓰기를 외우게 되었습니다..ㅋㅋ

2024-03-28 12:59 UTC, woowahan-cron commented on src/services/LocalStorageService.ts
> +    localStorage.setItem(LOCAL_STORAGE.KEY, JSON.stringify(data));
로컬스토리지에 담긴 별점을 제외한 나머지 정보(영화 제목, 장르 아이디, 포스터 이미지 등등)를 코드 어딘가에서 활용하고 있는지에 대한 질문이었습니다!

2024-03-28 13:08 UTC, woowahan-cron commented on src/services/MovieFetcherWithLoadingOrErrorState.ts
> +      this.showErrorComponent(errorComponent);
버건디가 이야기해주신 그 관점이 될 수도 있지만, 그보다는 꼭 필요한 선언으로 보이지는 않았기 때문이었어요. 
선언한다면, 또는 선언하지 않는다고 하면 ErrorComponent를 넘긴다는 것을 개발자가 쉽게 알아차릴 수 있을까?라는 관점에서 고민할 때 둘 다 yes라면 보다 간결한 것이 좋지 않을까 하는 부분에 중점을 두었습니다.

2024-03-28 13:26 UTC, woowahan-cron commented on src/components/MovieContainer/MovieContainer.ts
> +  renderMovieItemDetailModalHandler();
> 대체로 급하게 제출해서 그런지 일관성이 지켜지지 못한 부분들이 더러 있네요 ㅜㅜ
위와 관련된 표현은 사과를 드려야 겠습니다.
“버건디가 급하게 제출했다“로 단정지은 듯한 말투로 오해를 사게 됐네요.

### 급하게 제출했다는 의미
- 기능 요구사항을 충족하지 못했는데 PR부터 올렸다 (X)
- 1등으로 PR을 올려야 하니 급한 마음으로 검토를 소홀히하고 PR을 올렸다 (X)
- "조금 더 고민하면서 다듬을 시간이 필요했는데 일신상의 사유로 (크론이 생각하기에) 아쉬운 상태에서 PR을 올렸다"가 타당할 것 같아요. 조금 더 상대방의 입장에서 이 표현이 어떻게 받아들여질지 고민했어야 했는데 저야말로 급하게 리뷰를 단 것 같아 죄송한 마음입니다. 본의 아니게 버건디의 마음가짐에 대해서도 알게 됐지만, 저는 버건디가 1등으로 PR을 올려야 한다거나 기능 요구사항을 충족하지 못했지만 일단 PR부터 올렸다고 생각하는 것은 아니었어요. 위에서 말씀해 주신 대로 지금 시점에 PR을 올리고 리뷰로 많은 포인트를 챙기면서 개선해 나가는 과정을 제가 강조하고 있기 때문이기도 하고요.

### 코드 리뷰와 피드백이라는 의미

&nbsp;&nbsp;저도 처음에는 "피드백"과 "리뷰"는 나에 대한 부족한 부분을 "지적한다"는 의미로 받아들였었는데요. 그게 아닌 것 같더라구요. 제가 드리는 피드백도 "지적"이 아니라 버건디와 다른 관점에서 고민해 봤는데 이건 어떠신가요? 라고 하는 제안 정도로 받아들여 주세요. 마치 UDP처럼요! 아무래도 버건디는 현직 경험이 없지만, 코치나 리뷰어는 현직 경험이 있으시니까 리뷰를 받을 때마다 남다른 "무게감"이 느껴지실 수도 있을 것 같은데요. 리뷰어나 저의 입장에서는 사실 피드백은 "제안"에 가깝습니다(정말 꼭 고쳐야 할 것 같은 코드를 포인트로 짚었다고 할지라도요). 

&nbsp;&nbsp;리뷰어님들은 버건디에게 코드 리뷰를 통해 피드백을 할 수 있는 포인트를 찾고 그것을 통해 버건디가 개선해 나가며 성장하는 것을 보면서 보람을 느끼실 겁니다. 저도 피드백을 통해서 버건디가 코드를 개선해 나가며 성장하는 모습에 희열을 느끼고 싶었어요. 그런데 이건 제가 정말 고쳐야 하는 것이지만, 제가 욕심이 많습니다😓. 리뷰 포인트를 짚어주면서 보람을 느낌과 동시에 여기에서 아쉬운 점이 보이면 제 마음이 좀 더 다급해지는 것도 있는 것 같아요. 이러한 저의 욕심이 한 문장으로 드러났는데 이것이 버건디의 심기를 불편하게 만들었다면 다시 한 번 더 사과드리겠습니다🙏. 어쩌면 미션 포인트를 잘 지켰다고 이야기해드리는 긍정적인 피드백을 드리는 것이 크루들에게 도움이 될 수도 있을 텐데 앞선 욕심 때문에 항상 피드백 포인트를 짚어 드리다가 시간 관계상 긍정적인 리뷰 포인트는 자연스럽게 스킵하게 되는 것 같아요. (~크루들에게 욕심을 부리지 말라고 하면서 저는 욕심을 부리고 있네요...~)

그리고 버건디도 충분히 열심히 하고 있다는 것을 느끼고 있습니다 🙂
제가 급한 마음을 좀 억누르고 욕심을 자제해보겠습니다.
그러니까 앞으로의 미션도 영화리뷰처럼 해주시면 좋을 것 같습니다!

2024-03-28 15:00 UTC, woowahan-cron commented on src/services/LocalStorageService.ts
> +    localStorage.setItem(LOCAL_STORAGE.KEY, JSON.stringify(data));
넵넵 좋습니다! 코드를 꼼꼼하게 확인 못한 저의 귀책입니다 😂 👍👍👍

2024-03-29 00:19 UTC, brgndyy reviewed
안녕하세요 지그 수정사항 반영해서 올려보아요

1. 코멘트에 남긴 이유로 컴파일에러로 인해 로컬에서 실행이 불가합니다. 

=> 아마 컨플릭트로 인해, 로컬에서 커밋하고 푸시까지 했는데 반영이 안된듯합니다 🥲

현재 다시 반영해서 push 해보았습니다. 

바쁘실때인데도 불구하고 시간내서 로컬 환경까지 확인해주시려했는데, 불편끼쳐드려 죄송합니다.

2. 배포버전의 모바일 화면에서도 toggle로 뜨지 않습니다.

일단 제가 확인했을때는 배포 환경에서 요소가 잘 잡히는 상황인데요! 해당 내용 코멘트에 스크린샷과 함께 남겨보았습니다.

혹시나 아직도 문제가 발생하신다면 말씀 부탁드립니다.

그 외에 수정사항 반영 해보았어요! 

시간 되실때 천천히 확인 부탁드립니다. 좋은 하루 되세요 🙇

2024-03-29 00:19 UTC, brgndyy commented on src/components/Modal/renderModalContent.ts
> +import defaultImageSrc from '../../../templates/skeleton.png';
디폴트 이미지 변경하였습니다!

2024-03-29 00:21 UTC, brgndyy commented on src/components/Header/Header.ts
>    reloadPageHandler();
이벤트 함수명 `on`이라는 단어로 대체해서 변경해보았는데, 혹시 한번 더 피드백 부탁드려도 될까요 ?

2024-03-29 00:22 UTC, brgndyy commented on src/components/Modal/Modal.ts
디폴트 이미지 변경해놓았습니다 :)

2024-03-29 00:22 UTC, brgndyy commented on src/services/MovieFetcherWithLoadingOrErrorState.ts
> +      this.showErrorComponent(errorComponent);
해당 사항 수정해놓았습니다!

2024-03-29 00:23 UTC, brgndyy commented on src/services/addStarRatePropertyFromOriginalData.ts
> +  }));
일단 UX 적으로 `별점을 매기지 않은 상태가 존재해야한다` 라는것이 알맞을거 같아서 별점 매기지 않은 상태를 디폴트 값으로 수정해서 반영해놓았습니다

2024-03-29 00:31 UTC, brgndyy commented on src/components/Header/eventHandler.ts
> +export const keywordSubmitHandler = (searchType: SearchType) => {
`onSearchMovieByKeyword` 라는 함수명으로 교체해보았는데, 아직 이부분이 해당 함수에 대해서 명확히 설명하는가? 에 대한 부분이 애매모호 하다고 생각이 되아요!

해당 함수명에 대한 추가적인 피드백 부탁드리고 싶습니다 🙇

2024-03-30 01:15 UTC, zigsong commented on src/components/Header/render.ts
요소는 잡히는데, 제가 말씀드린 것은 모바일에서도 `.web-search-form`만 화면에 표시된다는 것이었습니다. 모바일에서 토글 버튼으로 표시되지 않고 있어요 

|피그마

![image](https://github.com/woowacourse/javascript-movie-review/assets/44080404/2d7511a0-4e7f-4745-a89f-b1a7d1db4f65)

개발 화면 
<img width="413" alt="image" src="https://github.com/woowacourse/javascript-movie-review/assets/44080404/0126f9b0-63d3-403b-aa16-9a0794562e81">

2024-03-30 01:16 UTC, zigsong commented on src/components/ShowMoreButton/infiniteScrollHandler.ts
> +    textContent: '데이터가 존재하지 않습니다!',
이렇게 수정해주신 것 같은데요, 그냥 아무 메시지를 보여주지 않고 검색된 결과 아이템까지만 보여주는 것이 더 와닿는 UI인 것 같습니다 

<img width="1129" alt="image" src="https://github.com/woowacourse/javascript-movie-review/assets/44080404/4f3b25e3-6056-4e19-a478-86ead516ea28">

2024-03-30 01:17 UTC, zigsong commented on src/services/LocalStorageService.ts
> +      return JSON.parse(data);
@brgndyy 요것은 수정 예정이신 건가요?

2024-03-30 01:19 UTC, zigsong commented on src/components/MovieContainer/MovieContainer.ts
> +  renderMovieItemDetailModalHandler();
두 분 말씀 읽으면서 크론도, 버건디도 각자의 역할을 너무 멋있게 해주고 계신 것 같아 감동 받았습니다 😲 

저도 코치님과 크루분들께 도움이 되도록 성실히 리뷰 남기겠습니다! 😊

2024-03-30 01:23 UTC, zigsong commented on src/components/Header/Header.ts
> +import { mobileToggleButtonHandler, mobileInputEnterHandler } from './eventHandler';
@brgndyy 다시 최신화해서 로컬에서 실행해보았는데요, 

API 응답은 잘 내려오는데 화면에 아무것도 그려지지 않고 있네요 🤔 

<img width="1724" alt="image" src="https://github.com/woowacourse/javascript-movie-review/assets/44080404/81ec41da-a723-4af3-bd12-75b96919e40f">

2024-03-30 01:24 UTC, zigsong commented on src/components/Header/eventHandler.ts
> +    event.preventDefault();
수정해주셨는데요, `event.preventDefault();`는 `searchKeywordSubmit()` 내부가 아닌 

```jsx
form.addEventListener('submit', (event) => {
    event.preventDefault();
    searchKeywordSubmit();
}
```

이렇게 되어야 맞습니다.

1. `submit`의 기본동작을 막고
2. 대신 `searchKeywordSubmit()`을 하겠다

의 의미가 되어야 하니까요.

2024-03-30 01:26 UTC, zigsong commented on src/components/MovieItem/eventHandler.ts
> +  openModalHandler();
제가 의도한 방향대로 잘 수정해주셨네요 👍

2024-03-30 02:05 UTC, zigsong requested changes
안녕하세요 버건디, 리뷰를 다시 남기러 왔습니다! 

크론의 리뷰와 제 리뷰를 꼼꼼히 읽고 의견 남겨주셔서 감사해요. 

그런데 아직 실행되지 않는 내용이나 수정할 수 있는 부분들이 있어 코멘트 남겼습니다.

귀찮으시더라도 한번만 더 같이 힘내보아요! 💪

2024-03-30 02:05 UTC, zigsong commented on src/components/MovieItem/eventHandler.ts
> +const getMovieTitleEventPhaseHandler = async (event: Event, ul: Element) => {
`eventPhase`라는 단어는 어떤 의미인가요?

2024-03-30 02:05 UTC, zigsong commented on src/components/MovieItem/eventHandler.ts
> +const ulTagAddEventListener = (ul: Element) => {
함수의 이름에는 `ul` 등의 HTML 태그명이 어울리지 않습니다. 

`ul`만 보고서는 의미상으로 '무엇'을 클릭했는지 알 수 없으니까요

2024-03-30 02:05 UTC, zigsong commented on src/components/MovieItem/render.ts
>      textContent: formatToDecimalPlaces(vote_average, 1),
이 PR의 변경사항에는 잡히지 않았지만, `formatToDecimalPlaces()`를 호출하는 곳에서는 모두 첫 번째 인자를 `number` 타입의 값만 넘겨주고 있는데요, `formatToDecimalPlaces()` 선언부에서 첫 번째 인자를 `targetValue: number | string`로 두어서 함수 내부에서 굳이 한번 더 조건문이 필요했던 것 같습니다. `number | string`이 아닌 그냥 `number`로만 두셔도 될듯 합니다.

2024-03-30 06:27 UTC, brgndyy commented on src/services/MovieFetcher.ts
> +  }
말씀 정말 감사합니다 🙇

2024-03-30 08:45 UTC, brgndyy commented on src/components/MovieItem/eventHandler.ts
> +const ulTagAddEventListener = (ul: Element) => {
맞는 말씀이에요! 

네이밍 부분에서 유야무야 넘어갔다는 생각이 들어서 반성하게 되네요

짚어주셔서 감사합니다 지그 🙇

2024-03-30 08:45 UTC, brgndyy commented on src/components/MovieItem/render.ts
>      textContent: formatToDecimalPlaces(vote_average, 1),
와 전혀 깨닫지 못했던 부분인데.. 짚어주셔서 감사합니다 

맞는 말씀이에요! 바로 반영하겠습니다 🙇

2024-03-30 08:45 UTC, brgndyy commented on src/components/Header/render.ts
<img width="496" alt="스크린샷 2024-03-30 오후 5 35 32" src="https://github.com/woowacourse/javascript-movie-review/assets/109535991/0ab9aa41-bf47-4891-b135-3766071fc016">

지금 현재 피그마가 390px 일때, 토글 버튼만 나오도록 되어있는데요..!

저도 390px 일때 인풋창이 사라지고 토글버튼만 등장하고 있습니다! 

<img width="1428" alt="스크린샷 2024-03-30 오후 5 43 18" src="https://github.com/woowacourse/javascript-movie-review/assets/109535991/00e5df2b-8724-42e9-b926-5f2070813536">

다만, 제가 지금 현재 발견한 부분은 헤더 배너 이미지가 토글 버튼을 눌러야지만 사라졌어야했는데, 390px 사이즈로 들어왔을때 바로 사라지도록 구현을 해놨었네요.!

저는 지그의 말씀을 `390px 사이즈가 되어도 아직 웹버전용 폼이 렌더링 된다` 라고 해석을 했는데, 현재 390px 일때 모바일 폼이 렌더링이 되고 있는데요..!

제가 말씀을 잘못 이해한걸까요 ? 

만약 잘못 이해했다면 다시 한번 설명 주시면 감사하겠습니다 🙇

2024-03-30 08:48 UTC, brgndyy commented on src/components/Header/eventHandler.ts
> +    event.preventDefault();
와와.. 맞는 말씀이네요

짚어주셔서 감사합니다 🙇

2024-03-30 08:59 UTC, brgndyy commented on src/components/Header/eventHandler.ts
> +};
저도 그것을 의도 하고 `onSearchMovieByKeyword` 함수에서 `searchType` 인자를 받아서 분기별로 submit 처리를 해주려고 했는데요!

어떤 이유에선지 웹화면의 form 제출은 발생하는데, 모바일은 제출 이벤트가 먹히지 않아서, 일단 인풋에 엔터키 이벤트를 적용시켜보았습니다! 

------

말씀 듣고 원인을 찾아보니, 토글 버튼에 `type="button"` 이 있으면 form 이벤트가 정상적으로 작동하고
단순히 `button`태그만 존재하면 `form`이벤트가 작동하질 않네요! 

## - 작동함

<img width="467" alt="스크린샷 2024-03-30 오후 5 57 00" src="https://github.com/woowacourse/javascript-movie-review/assets/109535991/fd6d4b53-7edd-4328-a7a6-bca9b60cfa3e">

## - 작동 안함

<img width="497" alt="스크린샷 2024-03-30 오후 5 57 23" src="https://github.com/woowacourse/javascript-movie-review/assets/109535991/8a935ae3-ee7f-410e-99d8-1acc6f56528d">


지금 이 `type`의 유무에 따라서 `form` 이벤트의 작동 여부가 결정 되는거 같습니다!

저는 `form`에 `submit` 버튼만 있으면 되는줄 알아서 버튼 하나에만 `type="submit"`을 지정해준거였는데.. 

해결은 했지만 아직 이해가 잘 가지 않네요 🥲

검색 키워드라도 제공해주신다면 한번 공부해보겠습니다!

2024-03-30 09:09 UTC, brgndyy commented on src/components/Header/Header.ts
> +import { mobileToggleButtonHandler, mobileInputEnterHandler } from './eventHandler';
현재 깃허브에 업로드 된 파일과 실제 파일 대조 해보면서 확인해보겠습니다! 

불편 끼쳐드려서 죄송합니다 🥲

2024-03-30 10:01 UTC, brgndyy commented on src/components/Modal/renderModalContent.ts
> +  }) as HTMLImageElement;
2. 그리고 또 다른 별개로 한번 여쭈어 보고싶은 부분이 있는데요! 

![화면 기록 2024-03-30 오후 6 55 36](https://github.com/woowacourse/javascript-movie-review/assets/109535991/4213f1c9-411b-4a3b-8774-1d2964a7b011)


지금 현재 영상을 보시면, 느린 3g 환경에서 디테일 모달이 렌더링 될때, 별 이미지만 늦게 렌더링 되는 모습이 보이는데요..! 

이게 지금 웹팩 빌드후에 `ttp://localhost:8080/6328741810b732410eec.png`  이경로, 즉 빌드 파일 내부에서 이미지를 가져오는 것처럼 보이는데.. (아니라면 짚어주시면 감사하겠습니다!)

이러한 경우에는 저 별 이미지가 얼른 렌더링 될수 있도록, 즉 디테일 모달이 렌더링 될때 동시에 렌더링 될수 있도록 성능 개선을 해줄수 있는 방법은 없는걸까요..!? 

백엔드에서 받아와서 렌더링을 해주는것도 아니고, 로컬 파일 내에서 빌드해서 가져오는건데 왜 이런 문제가 발생하는건지 여쭙고 싶어요!

2024-03-30 10:30 UTC, brgndyy commented on src/services/LocalStorageService.ts
> +      return JSON.parse(data);
현재 제가 '에러에 대한 기준' 이 완벽하게 잡히지 않아서, 어떤것이 그냥 Error 이고 어떤것이 'HttpError' 인가? 에 대한 구분이 흐릿하다는 생각이 들어요 지그!

혹시 지그가 생각하는 기준에 대해서 한번 여쭈어봐도 될까요?

저는 어차피 'HttpError'가 기본적인 Error 클래스를 상속받고 있으니까 이것 또한 Error 클래스이고, 여기서 추가적인 'status' 값을 지정해줌으로써 구체성을 높인다. 라고 생각했는데요!

혹시 제가 더 생각해보아야할 부분이나, 공부해볼 필요가 있는 부분에 대해서 말씀 주시면 감사할거 같습니다🙇

2024-03-30 14:33 UTC, brgndyy commented on src/components/ShowMoreButton/infiniteScrollHandler.ts
> +    textContent: '데이터가 존재하지 않습니다!',
반영하겠습니다! 짚어주셔서 감사합니다 🙇

2024-03-30 16:14 UTC, brgndyy commented on src/components/MovieItem/eventHandler.ts
> +const getMovieTitleEventPhaseHandler = async (event: Event, ul: Element) => {
`getMovieTitleFromMovieId` 라는 함수명으로 교체해보았는데요.

`'무엇'을 클릭했을때 '무엇'을 얻어온다.` 라는 함수명으로 작성하는게 제일 확실할거 같은데,  100퍼센트 만족스럽지는 않다는 생각이 듭니다! 

추가로 생각해본 함수명들은 `getMovieTitleFromMovieItem` 이나 `getMovieTitleByClickingMovieListItem` 인데.. 이 함수명들도 괜찮을까? 라는 의구심이 계속 듭니다.

혹시 지그가 함수명을 지을때의 기준을 한번 여쭈어봐도 될까요 ?

저 같은 경우에 짧게 하는것보다 오히려 많이 길어지더라도, 일단 상세하게 남겨놓자. 라는 주의이긴 한데, 너무 상세하면 또 가독성을 해친다는 말씀도 있더라구요..!

2024-03-31 07:08 UTC, brgndyy commented
> 안녕하세요 버건디, 리뷰를 다시 남기러 왔습니다!
> 
> 크론의 리뷰와 제 리뷰를 꼼꼼히 읽고 의견 남겨주셔서 감사해요.
> 
> 그런데 아직 실행되지 않는 내용이나 수정할 수 있는 부분들이 있어 코멘트 남겼습니다.
> 
> 귀찮으시더라도 한번만 더 같이 힘내보아요! 💪

@zigsong 

안녕하세요 지그! 

수정사항 반영해서 올려봅니다.

일단 로컬 환경에서 실행이 안되거나 하는 부분들이, step1때 생성해놨던 `LoadingOrErrorState` 모듈이 삭제 되지 않고 다른 비동기 함수에서 임포트 되고 있었어서 그랬던거 같다라고 예상이 되는데요.

일단 제 로컬에서 아예 새로운 빈 폴더를 만든 후에,

현재 제 step2 브랜치에 업로드된 파일 그대로 복사 붙여넣기해서, 새롭게 실행 해보았을때는 정상적으로 실행이 되고 있습니다!

혹시나 안된다면 다시 한번 살펴보도록 하겠습니다.

------

그리고 이전에 리뷰 해주신 부분에서 궁금한 부분들은 일단 대댓글을 남겨두고, 수정사항에 반영되지 않은 부분도 있습니다! 

이는 아직 제가 더 궁금한 부분이 있어서 대댓글만 남겨두고, 아직 반영은 하지 않은 것인데요.

혹시 반영해야할 부분이 있다면 말씀 부탁드립니다

좋은 주말 되세요 🙇

2024-03-31 23:12 UTC, zigsong commented on src/components/MovieContainer/MovieContainer.ts
> +  renderMovieItemDetailModal();
앗 제가 말씀드린 의도는 `MovieContainer.ts`냐, `renderMovieContainerComponents.ts`냐의 문제가 아니라,

`renderMovieItemDetailModal()`을 `MovieItem()` 컴포넌트에서 띄워줄 수는 없었는지, 하는 문제였습니다

2024-03-31 23:18 UTC, zigsong commented on src/components/Modal/renderModalContent.ts
> +  }) as HTMLImageElement;
아하 `createElement()`가 HTML 기본 제공 함수가 아니라 버건디가 직접 선언한 함수였군요. 

`document.createElement()`로 호출하였다면 이렇게 자동 추론이 되었을 테지만, 지금과 같은 상황에서는 제네릭의 사용도 괜찮아 보입니다. 

![image](https://github.com/woowacourse/javascript-movie-review/assets/44080404/048677e2-8427-4242-b3e9-fda8b1c4ccb0)

2024-03-31 23:21 UTC, zigsong commented on src/components/Modal/renderModalContent.ts
> +  }) as HTMLImageElement;
별 이미지가 느리게 뜨는 문제는, 'webpack에서 image 처리하는 법' 등의 키워드로 검색하시면 많이 나옵니다. (`file-loader`, `asset/resource` 설정 등)

미션을 빨리 끝내셨으니 webpack의 여러 설정들에 대해 공부해보시는 것도 좋겠네요!

2024-03-31 23:23 UTC, zigsong commented on src/components/Modal/modalContentEventHandler.ts
> +    const error = new HttpError(ERROR_MESSAGE.INVALID_STAR_RATE, 400);
- '사용자가 개발자도구에서 값을 조작하는 경우'는 해당 사용자의 매우 의도적인 케이스이므로 프론트 개발단에서 다루지 않습니다. 그런 식으로 모든 개발자도구 조작을 막으면, 거의 모든 코드에 대응 작업을 해줘야겠죠? 
- '사용자의 잘못된 요청'을 나타내는 400 에러는 위와 같은 '개발자도구 조작'이 아니라, '서버 API 호출 시 잘못된 형식으로 요청한 경우'를 의미합니다.

따라서 사실상 에러핸들링을 해주지 않아도 될 뿐더러, `HttpError`는 더더욱 아닙니다. 말씀하신 사용자의 동작에서 `Http` 통신이 이루어지진 않으니까요.

2024-03-31 23:27 UTC, zigsong commented on src/components/MovieItem/eventHandler.ts
> +const getMovieTitleEventPhaseHandler = async (event: Event, ul: Element) => {
> 오히려 많이 길어지더라도, 일단 상세하게 남겨놓자.

에는 저는 반대합니다.

- 함수명이 많이 길어진다는 것은 함수가 하나의 역할만 하지 않고 있기 때문에 이 경우 단일 동작을 하는 여러 개의 함수로 분리되어야 하고,
- 함수는 그 세부 구현 사항은 외부에 노출하지 않고, 외부에서 쉽게 알 수 있는 간단한 네이밍으로 호출만 하면 그 내부에서 동작을 알아서 해줘야 합니다. 이를테면 자바스크립트의 빌트인 함수들을 들 수 있겠습니다. `Array.prototype.map()` 함수의 경우, `map()` 함수 내부적으로는 배열의 모든 요소를 돌며, 호출부에서 넘겨준 콜백 함수를 적용합니다. 하지만 함수의 네이밍은 `loopEveryElementAndApplyCallback()`이 아닌 `map()`이죠. 

`getMovieTitleEventPhaseHandler()`에서처럼, 사용자가 굳이 알지 않아도 되는 내부 동작(`EventPhase`) 까지 함수명에 명시해줄 필요는 없습니다.

2024-03-31 23:29 UTC, zigsong commented on src/components/Header/eventHandler.ts
> +};
확인을 해보고 싶은데, 아직도 로컬에서 실행이 되지 않아 어렵습니다.

배포 링크를 최신화해주시거나 하면 다시 확인해보겠습니다.

2024-03-31 23:33 UTC, zigsong commented on src/components/Header/eventHandler.ts
> +};
저에게는 아직도 모바일 토글 버튼이 뜨지 않지만 문제 상황을 다시 읽어봤는데요, 

`button` 태그의 `type`의 기본 속성이 무엇인지 알아보면 왜 의도대로 동작하지 않았는지 아실 수 있을 것 같습니다.

결론만 말씀드리면, 토글 버튼에 `type="button"`을 반드시 기재해주어야 하고, 웬만하면 토글 버튼은 `<form>` 태그 바깥에 위치해두세요. (CSS를 이용하거나 해서)

2024-03-31 23:35 UTC, zigsong approved these changes
안녕하세요, 버건디! 크론과 제가 동시에 리뷰를 해 리뷰가 상당히 많아졌는데, 하나하나 꼼꼼히 읽어보시고 반영하시느라 고생 많으셨습니다.

이번 미션의 핵심 요구조건들은 정상적으로 반영이 되었고, 나머지들은 버건디가 앞으로 개발 공부를 해나가시면서 반영하실 수 있을 것이라 생각되어 리뷰는 여기서 마치겠습니다. (다른 크루들도 리뷰를 해야 해서요 😉)

버건디는 조금 이른 방학이 시작되겠군요? 즐겁고 알찬 시간 보내시길 바랄게요! 수고하셨습니다 👏

2024-03-31 23:35 UTC, merged

2024-04-01 03:57 UTC, brgndyy commented on src/components/Header/eventHandler.ts
> +};
결국 아직도 로컬에서 실행이 되는 문제가 해결이 안됐네요.. 🥲🥲

신경써주셨는데 해결 못해서 죄송합니다.

말씀 주신 부분 한번 혼자서라도 수정해보겠습니다! 짚어주셔서 감사합니다 🙇

2024-04-01 03:58 UTC, brgndyy commented on src/components/Modal/renderModalContent.ts
> +  }) as HTMLImageElement;
와와 좋은 키워드 제공 감사합니다!! 🙇

2024-04-01 03:59 UTC, brgndyy commented on src/components/Modal/modalContentEventHandler.ts
> +    const error = new HttpError(ERROR_MESSAGE.INVALID_STAR_RATE, 400);
말씀을 듣고 `HttpError` => HTTP 통신 과정에서 발생하는 에러

라고 기준점을 잡아보았어요! 

마지막까지 공부해볼만한점 제공해주셔서 감사합니다 🙇

2024-04-01 04:00 UTC, brgndyy commented on src/components/MovieItem/eventHandler.ts
> +const getMovieTitleEventPhaseHandler = async (event: Event, ul: Element) => {
`map` 함수를 예로 드니까 확실히 이해가 되네요.

자세한 설명 정말 감사합니다 지그 🙇