.
woowacourse/javascript-movie-review pull request #141
Opened 2024-03-27 02:36 UTC by jinyoung234

.

2024-03-27 04:44 UTC, woowahan-cron commented
리뷰어님이 확인하실 수 있게 배포 링크도 같이 올려 주세요!

2024-03-27 04:46 UTC, jinyoung234 commented
> 리뷰어님이 확인하실 수 있게 배포 링크도 같이 올려 주세요!

아 아직 PR을 다 작성하지 못해서 완료하는대로 함께 첨부하겠습니다!! 감사합니다 :)

2024-03-28 07:40 UTC, woowahan-cron requested changes
지니! 이번에도 거의 일찍 제출해 주셨네요 👍
서버 API 통신을 하면서 많은 요구사항이 있었을 텐데 거침없이 진행해 주시다니 
그동안 고생 많으셨습니다.

![image](https://github.com/woowacourse/javascript-movie-review/assets/112997662/7ba81c6d-14de-41ac-992c-bbb576878b51)


## 사용성 리뷰

### 모달창 리뷰

![Mar-28-2024 15-47-31](https://github.com/woowacourse/javascript-movie-review/assets/112997662/aafdfe03-e5fe-4f49-a717-a6dc3166e0f7)

모달창을 띄우면 이미지가 로드되면서 아래와 같이 영화 소개 영역이 덜컹거리며 우측으로 이동되는 현상이 보입니다. 이런 현상을 어떻게 개선해 보면 좋을까요?

<img width="452" alt="image" src="https://github.com/woowacourse/javascript-movie-review/assets/112997662/91418c40-f7d2-464b-b473-ba283f71695e">

### 무한 스크롤 리뷰

무한 스크롤에 관해서 지니가 많은 고민을 해주셨더라구요!
성능을 최적화하는 관점까지 고민해 보라고 하는 것은 이번 레벨1의 목표는 아니었습니다.🙂
스크롤 이벤트보다 더 나은 방법이 어떤 것들이 있는지와 Intersection Observer를 이용하면 어떤 이점을 얻을 수 있는지 정도만 고민하셨더라도 충분히 목표를 달성했다고 생각합니다.

<img width="1799" alt="image" src="https://github.com/woowacourse/javascript-movie-review/assets/112997662/5d555ffc-7661-4a5d-83f1-9ede01836ab4">

다만, 무한 스크롤을 하는 입장에서 아직 다음 페이지에 대한 서버 요청을 받아오고 있는데 사용자가 스크롤링을 하게 된다면 서버에 다다음 페이지, 다다다음 페이지를 계속해서 요청할 수 있습니다. 이것이 적절한지 고민해 보시면 좋겠어요
 
- 사용자 입장: (스크롤 막대가 짧아지는 것을 인식하지 못한 채) 아직 이미지가 다 불러와지지 않았나? 왜  안 불러와지지?
- 서버 입장: 아직 요청에 대한 응답도 다 못했는데 다음껄 바로 요청한다고? 이런 사용자가 여러 명이 된다면 어떡하지...?

## 피드백 종합

개인적으로 아쉬움이 많이 남았던 것 같아요!
학습 목표에 잘 집중하고 있었는지를 고민해 보시면 좋겠습니다.

### 1. 웹 컴포넌트의 사용

사용 자체가 나쁘다고 생각지는 않습니다. 다만, 아래의 조건을 만족하는지 고민해 보셨으면 좋겠습니다.
  - 웹 컴포넌트를 써야한다거나 복잡한 컴포넌트를 설계해야 하는 요구사항이 복잡하지 않았는데 굳이 써야 하는가?
  - 학습 목표에 집중하자고 강의에서도 피드백을 드렸었는데 꼭 에너지를 분산시켜야 했었는가?
  - 그렇다면, 관심사의 분리가 명확하게 되었고 클래스나 함수, 메서드의 이름을 통해 목적이나 역할이 분명히 드러나게 코드를 작성했는가? 

### 2. 일관성

[async 함수](https://github.com/woowacourse/javascript-movie-review/pull/141/files#diff-5446e4d4a982932b2e2e8bb14a9620d51c964203d230a413a026e8a281ee1435R60)로 선언된 내부에서 await 키워드를 사용해서 처리하는 곳도 있고 마지막에 가서는 await 키워드를 사용하지 않고 바로 return해버리는 경우도 있었습니다(fetchMovieData). 저는 이 코드를 읽다가 `.json()` 함수는 Promise 객체를 반환하는 것으로 알고 있었는데 왜 await 키워드를 붙이지 않고 바로 반환하지? 라고 생각했습니다. 나중에 이 코드를 가져다 쓰는 곳에 가서야 Promise Chaining(then 키워드)를 사용한다는 것을 알았습니다. 협업하는 관점에서 일관성이 맞춰지지 않았다면 빠르게 코드를 고칠 수 있을까요?


### 3. 관심사와 역할의 분리

`src/apis/movie/movie.ts` 파일에 존재하는 MovieAPI 클래스를 예로 들 수 있을 것 같아요.
API 엔드포인트를 관리하면서 동시에 서버에 요청도 하고 오류 처리도 하고 있습니다.
오류 처리에 관한 부분도 다루고 있어요.
당연히 영화 리뷰 기능을 구현하는 데 모두 필요한 기능이라고 생각하는데 MovieAPI를 외부에서는 어떻게 사용하면 좋을지 감이 잘 오지 않습니다. 지니가 이 클래스를 설계하신 의도나 배경에 관해 알지 못하니 저는 어떻게 관심사를 분리하라고 조언을 드릴지 조금 어렵네요. 이 부분도 남들이 보더라도 명확하게 지니의 의도나 클래스의 역할, 관심사를 파악할 수 있도록 재구성해 보시는 것이 좋을 것 같네요!


기타 리뷰는 코멘트를 참고해 주세요.



---

학습 목표에 집중할 수 있는 분량으로 조절해서 미션을 설계하고 있는데 스스로 난도를 높이면서까지 에너지를 분산시키고 학습 목표를 다 챙기지 못한다면 레벨1 과정을 경험하는 데 의미가 있을지?도 고민해 보시면 좋겠습니다!

제가 다하지 못한 리뷰는 리뷰어님이 다 챙겨주실 겁니다!!
그럼 더 좋은 프로덕트 만드시길 🙏 바라겠습니다 🎉

2024-03-28 07:40 UTC, woowahan-cron commented on src/apis/movie/movie.ts
클래스 하나만 선언되어 있는데 파일의 이름은 movie.ts이군요!
그런데 또 다른 파일은 (/src/domain/Movie/Movie.ts) 클래스의 이름과 동일하고 대소문자도 맞춰져 있습니다.
지니가 명명하고자 하는 네이밍의 일관된 규칙이 있나요?
네이밍을 하는 컨벤션에 관해서도 설명해 주신다면 도움이 될 것 같네요!

2024-03-28 07:40 UTC, woowahan-cron commented on src/components/common/Modal/Modal.ts
> +  private handleClickBackdrop(event: MouseEvent, $modal: HTMLDialogElement) {
"handle"이라는 이름이 들어가는 것이 적절할까요?
함수의 이름만으로는 "백드롭을 클릭했을 때 다룬다"정도로밖에 표현이 되지 않습니다.
누구나 상식적으로 유추한다면 모달창을 닫는 결과를 유추할 수는 있겠지만, 보다 명시적으로 확인할 수 있는 이름을 짓는 것이 더 적절하지 않을까요?

2024-03-28 07:40 UTC, woowahan-cron commented on src/components/movie/ModalCloseButton/ModalCloseButton.ts
😞 이번 미션에서 웹 컴포넌트의 유용함을 느끼라고 할 정도로 복잡한 컴포넌트를 설계해야 하는 요구사항은 그 어디에도 없었습니다.
일관성을 유지하기 위해서 버튼을 웹 컴포넌트로 작게 쪼개셨는데 이게 과연 맞는가 하는 생각이 드는데요...
웹 컴포넌트를 제외하고 다른 개념이나 신경쓰지 못한 부분을 레벨1에서 보다 더 많이 챙기는 것이 중요하지 않을까 합니다..
다 와서 이런 이야기 해 봐야 소용은 없겠지만요.

그래서 코드를 읽어 보니 관심사의 분리가 명확하게 분리되지 않은 부분들이 있는데 웹 컴포넌트를 같이 학습하면서 레벨1의 본질적인 부분에 신경쓰지 못하고 에너지가 분산된 것은 아닌가 하는 아쉬움이 남습니다...

2024-03-28 07:40 UTC, woowahan-cron commented on src/components/movie/MovieListCard/MovieListCard.ts
> +  private handleClickCard(event: Event) {
카드를 클릭하면 어떤 일이 벌어지는지 메서드/함수 이름만 보고서라도 알 수 있어야 하지 않을까요?

2024-03-28 07:40 UTC, woowahan-cron commented on src/components/movie/MovieListCard/MovieListCard.ts
> +    });
제가 생각한 의도는 다음과 같습니다.

1. 사용자가 영화 목록 카드 아이템을 클릭한다.
2. 클릭하게 되면 fetchMovieDetail 함수를 실행해서 모달 창에서 보여 줄 영화 상세 정보를 서버에서 불러온다.
3. 성공/실패에 따라 적절한 모달 창을 열어 내용을 채운다.

사용자에게 모달 창을 띄우기 전에 정보를 가져와서 보여준다는 경험을 고려한 것 같은데요.
저는 영화 목록 아이템이 이런 역할까지 담당해야 하는가? 조금 의문이 남습니다.

컴포넌트라고 한다면, "재사용"이 가능해야 하는데...
이 카드를 다른 프로젝트에서 들고 가서 끼운다면 유연하게 수정할 수 있는지도 고민해 보시면 좋습니다.

2024-03-28 08:13 UTC, jinyoung234 commented on src/apis/movie/movie.ts
>      const movieDetails = response.json();
json 메서드가 Promise 객체를 반환한다는 사실을 생각하지 못했던거 같습니다. 

일관성을 고려해본다면 크론의 코멘트가 맞다고 생각합니다. 😀

2024-03-28 08:23 UTC, jinyoung234 commented on src/components/movie/ModalCloseButton/ModalCloseButton.ts
> +  private handleModalCloseButton() {
<img width="1142" alt="image" src="https://github.com/woowacourse/javascript-movie-review/assets/87177577/85e2814b-ed67-4ee7-a133-eef672a3516c">
(출처 - [poiemaweb](https://poiemaweb.com/js-event))

이벤트 내부의 콜백 함수를 이벤트 핸들러 함수로 알고 있습니다. (위 그림을 참고하시면 좋을듯 합니다.)

따라서 핸들러 함수라는 것을 명시하기 위해 모든 이벤트 핸들러 함수는 `handle~`라는 네이밍을 통해 일관성을 부여하려고 했습니다.

원래는 handleClickModalCloseButton으로 네이밍을 지어서 ModalCloseButton이 실행되었을 때 로직을 실행시키는 의미로써 네이밍했었습니다.

근데 생각해보니 handleCloseModal이라는 네이밍도 괜찮다고 생각하는데 크론의 의견이 궁금합니다.

2024-03-28 08:56 UTC, jinyoung234 commented on src/components/movie/MovieList/MovieList.ts
> +    if (this.props?.movieItemDetails.length === 20) {
맞는거 같습니다. 피드백 반영해놓겠습니다 :)

2024-03-28 08:57 UTC, jinyoung234 commented on src/components/movie/MovieListCard/MovieListCard.ts
> +    const $anchor = createElement({ tagName: 'a', attributeOptions: {} });
`attributeOptions`까지 지워야 했었는데 코멘트 반영해놓겠습니다!

2024-03-28 08:57 UTC, jinyoung234 commented on src/components/movie/MovieListCard/MovieListCard.ts
> +            this.src='https://www.themoviedb.org/assets/2/v4/glyphicons/basic/glyphicons-basic-38-picture-grey-c2ebdbb057f2a7614185931650f8cee23fa137b93812ccb132b9df511df1cfac.svg';
코멘트 반영해놓겠습니다!

2024-03-28 09:02 UTC, jinyoung234 commented on src/apis/movie/movie.ts
<img width="723" alt="image" src="https://github.com/woowacourse/javascript-movie-review/assets/87177577/780460dd-d15d-4910-adad-0f5fb48e1a06">

저번 자동차 경주 미션 때 다음과 같은 리뷰를 받게 되었습니다.

그래서 하나의 인스턴스를 생성하는 경우 이 리뷰를 지키고자 했습니다.

다만, api layer에 경우 초기에 인스턴스 없이 함수로 구성 했다가 클래스 형태로 변경 했고 그 과정에서 컨벤션이 어긋난거 같습니다.

(/src/apis/Movie/Movie.ts)가 적절했을거 같습니다.

2024-03-28 09:06 UTC, jinyoung234 commented on src/components/movie/ModalCloseButton/ModalCloseButton.ts
웹 컴포넌트의 사전적 의미는 다음과 같습니다.

> 웹 컴포넌트는 그 기능을 나머지 코드로부터 캡슐화하여 재사용 가능한 커스텀 엘리먼트를 생성하고 웹 앱에서 활용할 수 있도록 해주는 다양한 기술들의 모음입니다.

웹 컴포넌트는 3가지의 기술을 집약한 형태인데요.

1. custom elements
2. shadow dom
3. template & slot

따라서 저는 웹 컴포넌트의 3가지 기술 중 그 어느 곳도 사용한 적이 없는데 이런 리뷰를 받은 것이 조금 의문입니다. 🥲

2024-03-28 09:14 UTC, jinyoung234 commented on src/components/movie/MovieListCard/MovieListCard.ts
> +    });
<img width="702" alt="image" src="https://github.com/woowacourse/javascript-movie-review/assets/87177577/9c325116-aac2-41e2-9193-d1cac75f1c0b">

점심 뭐 먹지 미션에 있는 2단계 공통 피드백 자료를 인용해보았습니다.

저는 MovieListCard 컴포넌트의 경우 영화 리뷰 미션에서 사용하는 `도메인`컴포넌트로 바라보았습니다.

따라서, 다른 프로젝트에서 재사용 될 수 있는 가능성을 고려해보지 않았습니다.

또한, 현재 컴포넌트의 경우 `검색` 영화 목록과 `인기순` 영화 목록 모두 재사용이 가능한 형태입니다.

즉, 현재의 프로젝트에서 재사용이 가능한 형태입니다.

따라서 저는 현재 형태가 적절하다고 생각했습니다.

2024-03-28 09:27 UTC, jinyoung234 commented on src/components/movie/MovieReviewDetailModal/MovieReviewDetailModal.ts
> +              this.props?.genres || '장르 없음'
1. 크론이 코멘트 주신거 처럼 아래와 같은 형태로 개선해 볼 수 있을거 같습니다.
```ts
if (!this.props) return '';

const { genres = '장르 없음', overview = '설명이 존재하지 않습니다.' } = this?.props;

<section id="modal-review-detail-section" class="modal-review-detail-section">
          <div class="movie-description-container text-body">
            <p class="movie-description-title"><span id="movie-genre" class="movie-genre">${genres}</span> <img class="movie-title-image" src="${FilledStar}" /> <span id="movie-score" class="movie-score">${
      this.props?.score
    }</span></p>
            <p id="movie-description-body" class="movie-description-body">${overview}</p>
```

2. 명시적으로 선언하면 더 좋은 이유는 현재 반환하는 template이 컴포넌트의 형태를 결정 짓기 때문에 실질적으로 반환하는 곳에서 명시적으로 선언된 변수가 의도를 파악하기 쉽고 가독성이 좋아지기 때문 입니다.

2024-03-28 09:37 UTC, woowahan-cron commented on src/components/movie/ModalCloseButton/ModalCloseButton.ts
앗 이런 😓 제가 좀 더 세심하게 봤어야 했는데..
수업을 준비하면서 피드백을 해줄 수 있는 부분이 어디 있나 훑어보면서
지니가 추상 클래스로 구현한 Component와 혼동했어요.
조금이나마 마음이 상하셨을 텐데 죄송해요 🙏

2024-03-28 09:38 UTC, woowahan-cron commented on src/components/movie/ModalCloseButton/ModalCloseButton.ts
> +  private handleModalCloseButton() {
굳이 핸들러(Handler)라는 키워드를 붙여 줄 이유가 있을까요?

2024-03-28 12:23 UTC, iborymagic commented
질문에 대한 답변입니다.

> 무한 스크롤을 개선하는 과정

지니가 스크롤 이벤트가 너무 자주 발생한다는 것에 대해 불편함을 느꼈고, 그것에 대한 해결책들을 고민해보신 것 같습니다. 사실 해결 과정이 적절했는지에 대한 판단을 제가 내려드리기는 좀 애매하고, 지니가 제시해주신 객관적인 자료들로 보았을 때 적절하게 문제를 잘 해결하셨다는 것을 알 수 있었습니다.

실제로 지니가 스크롤 이벤트의 발생 횟수를 직접 측정해보면서 그것을 개선하는 과정을 직접 자료로서 보여주셨는데, throttle과 intersectionObserver 등 여러 방법들을 시도해보면서 측정 결과를 비교해보고 더 나은 방법을 선택하신 것 같아요. 이러한 고민과 측정, 문제 해결의 과정은 실제로 현업에서 일을 할 때에도 아주 중요합니다. 이렇게 객관적인 자료, 혹은 측정 결과를 내세우는 습관을 들이면 이러이러한 작업을 하고싶다~ 하고 다른 팀원들을 설득하기도 쉽고, 나중에 지니의 커리어에도 틀림없이 많은 도움이 될거에요. 그래서 개인적으로는 아주 좋은 경험을 하신 것 같다고 생각합니다. 👍

> 컴포넌트 캡슐화

지니가 생각하신 부분에 저도 대부분 공감합니다. 사실 상황에 따라서 너무 다른 부분이기도 하고, 막상 저 스스로도 명확하게 '이걸 기준으로 한다'라는 게 명확히 떠오르진 않네요. 컴포넌트를 설계하는 과정에서 이러이러한 기능이 필요하겠구나, 혹은 팀원들에게 설계를 리뷰하면서 제가 놓친 부분이 이런 게 있었구나 하면서 채워가는 것 같습니다. 그래도 대략적으로나마 말씀드리자면, 컴포넌트를 설계할 때는 주로 외부에서 해당 컴포넌트에 어떤 기능을 기대할 것인가를 위주로 생각합니다. 그리고 그걸 내부의 상태나 로직을 숨기면서 최대한 간단한 인터페이스로 내보내려고 하는 것 같습니다.

예를 들면, 외부의 관점에서 봤을 때 '모달 컴포넌트'에 기대하는 기능은 일단 당연히 모달을 열고 닫는 기능일 거에요. 어떤 모달을 만들어도 모달은 항상 open, close 해주는 동작이 필요할건데, 그걸 외부 여기저기서 일일이 구현해주는 것보다는 당연히 모달의 내부 기능으로 만들어놓고, 외부로 드러내주면 훨씬 사용이 간편하겠구나. 하는 정도라고 간단히 생각해볼 수 있겠죠. (컴포넌트를 render하는 기능도 마찬가지겠죠?)

아, 그리고 event handler를 등록할 때 외부에서 로직을 주입해주고 싶다면, onClick 함수 같은 걸 props로 받아서 내부에서 다른 로직들과 함께 등록해주는 방법이 있겠네요.

> Response Type과 Interface Type

사실 안티패턴이라고 하긴 하는데, 실제로 보면 많이들 쓰고 있긴 합니다.. 😅 
지니도 어느 정도 느끼셨겠지만, 실제로 일을 하다 보면 네이밍에 생각보다 많은 시간이 소요된다는 걸 느낄 때가 많습니다. 그 비용을 줄일 수 있게, interface를 추가해야하거나 할 때 최대한 고민 없이 바로바로 네이밍을 할 수 있는 컨벤션이 있다는 게 중요한 것 같아요. 뭐가 됐든, `~Interface`이건 `I~`이건 간에 모든 팀원들이 고민 없이 사용할 수 있고, 읽는 데에 문제가 없다면 그걸로 충분하다고 생각합니다.

물론 위의 내용은 저의 개인적인 생각이긴 합니다만, 실제로 저도 `~Response`, `~Request`, `~Props` 이런 이름 많이 씁니다 😄

2024-03-28 12:24 UTC, iborymagic requested changes
안녕하세요 지니~ 굉장히 빠르게 구현해주셨네요. 고생 많았습니다. 👏👏

UX에 관해 많은 것들을 고민하셨다는 게 느껴졌고, 고민에 대한 해결 과정도 흥미롭게 읽
었습니다. 이미지가 없는 경우까지 대비해두셨다는 것도 인상깊었어요.

코멘트로 질문에 대한 답변과 함께 자잘한 리뷰들 남겨놨습니다.
확인해주시고, 리뷰 반영이 완료되면 다시 리뷰 요청 주세요~

2024-03-28 12:24 UTC, iborymagic commented on src/components/movie/MovieScoreBoard/MovieScoreBoard.ts
> +  } as const;
요런 상수들은 컴포넌트 밖으로 빼도 좋을 것 같아요.

2024-03-28 12:38 UTC, woowahan-cron commented on src/apis/movie/movie.ts
> +  }
제가 말씀드리고 싶었던 것은 API엔드포인트에 좀 더 초점을 맞추고 싶었고 이는 함수로 구성되어 있긴 하지만, 전체적인 틀로 봤을 때 선언에 더 가깝지 않을까? 하는 생각이 들더라고요! (함수를 리터럴 객체나 상수로 반환하라는 이야기가 아닙니다. 이건 또 다른 이야기)

서버 개발자와 협업하면서 API 스펙을 확인하기 위해서는
클래스의 중간 부분에 API 스펙이 섞여 있으면 그때 그때 확인하기 어렵지 않을까요?
클래스의 스코프 바깥에만 보내주더라도 충분히 잘 읽힐 것 같아요.

지금 3개의 API를 사용하고 있는데 추가될 것이 없어서 여기에 포함해도 될 것이라고 판단했다면 그 나름의 근거도 좋습니다.👍
다만, 앞으로의 앱은 이보다 더 많은 API를 사용할 것이고 추가/수정이 잦을 텐데 변화에 유연하기 위해서는 어떤 고민을 해볼 수 있을지를 피드백 포인트로 던져 드리고 싶었을 뿐이에요.

그리고 나머지 관심사에 관해서는 고민이 됩니다.
제가 코드를 구성하는 세계관이 지니와는 다를 수 있으니까요.
저의 세계관 관점에서 말씀드리면 MovieAPI클래스는 생각보다 많은 일을 하고 있다는 생각이 들었는데..
이건 내일 공통 피드백에서 오류 핸들링과 관련된 피드백을 수강하신다면 조금 더 깊게 고민해 볼 수 있을 것 같아서 여기까지만 물음을 던져두겠습니다🤗

2024-03-28 12:39 UTC, woowahan-cron commented on src/apis/movie/movie.ts
음 그럼 MovieAPI 클래스 이름도 변경이 필요하겠군요? 이름은 지니가 한번 더 고민해 주세요!

2024-03-28 12:42 UTC, woowahan-cron commented on src/components/movie/MovieListCard/MovieListCard.ts
> +    });
제가 짚어드리고 싶었던 포인트는 다음과 같습니다.

1. 영화 목록 카드 아이템이 모달 창에 띄울 정보인 "영화 상세 정보" API를 호출해서 불러오고 이걸 모달에 전달해 주는 것까지가 역할로 보는 것이 타당할까요?
2. 1번이 타당하다면, 다른 페이지나 프로젝트에서는 클릭하면 영화 상세 정보가 아니라 다른 동작을 해야 한다면 `handleClickCard`라고 하는 메서드를 직접 수정해 줘야 할 텐데요. 이것을 재사용이 가능한 형태"라고 볼 수 있을까요?

2024-03-28 13:18 UTC, jinyoung234 commented on src/components/movie/MovieListCard/MovieListCard.ts
> +    });
크론이 생각하는 재사용성을 말한 목적에 대해 이제 이해하게 된 것 같습니다.

더 좋은 방법을 고민해보고 반영해보겠습니다!

2024-03-28 13:21 UTC, jinyoung234 commented on src/apis/movie/movie.ts
> +  }
이런 숨은 목적이 있었군여,,, 비동기 통신에 대해 아직 익숙하지 않은 제 탓도 있는거 같습니다. 🥲

크론이 리뷰 주신 내용도 충분히 이해되는 것 같습니다.

내일 피드백 내용 듣고 방향성에 대해 좀 더 고민해보겠습니다!! 👍

2024-03-29 03:52 UTC, jinyoung234 commented on cypress/e2e/movieReview.cy.ts
> +    it('ㅋㅋ를 입력했을 때 "텅" 이미지와 함께 더 이상 영화 결과를 제공하지 않는다.', () => {
저도 리뷰어님 의견에 동의합니다.

1. 'ㅋㅋ'를 검색했을 때 언젠간 Movie API에 추가될 수 있다는 점
2. "ㅋㅋ 를 입력하면 왜 영화 결과를 제공하지 않을까?" 라는 의문이 들 수 있다는 점

이 2가지 관점에서 볼 때 적절하다고 생각이 들어 리뷰 반영해보겠습니다!

2024-03-29 03:52 UTC, jinyoung234 commented on src/components/movie/MovieReviewBody/MovieReviewBody.util.ts
> +};
피드백 반영해놓겠습니다 😀

2024-03-29 03:53 UTC, jinyoung234 commented on src/components/movie/MovieScoreBoard/MovieScoreBoard.util.ts
> +};
사용자 정의 타입 가드 방법을 찾다 보니 `is` 키워드를 발견하게 되었던거 같습니다. 👍

2024-03-29 03:54 UTC, jinyoung234 commented on src/domain/Movie/Movie.ts
> +  }
저도 공감합니다.

promise를 사용했던 이유는 프로미스 체이닝에서 제공되는 catch 절을 사용할 수 있다는 장점이 있다고 생각했습니다.

하지만 

1. try-catch를 사용함으로써 개선이 가능하다는 점
2. 일관성이 깨진다는 점

에서 봤을 때 리뷰어님 코멘트를 반영하는 것이 맞다고 생각들어 반영해보겠습니다 :)

2024-03-29 03:55 UTC, jinyoung234 commented on src/components/movie/MovieLogo/MovieLogo.ts
> +  }
기본적인 동작을 캡슐화 시키고 필요한 부분에 대해 override 해도 괜찮은거 같습니다. 😀

피드백 반영해보겠습니다!

2024-03-29 04:00 UTC, jinyoung234 commented on src/components/movie/MovieReviewBody/MovieReviewBody.ts
>    }
이유라고 하면 현재 컴포넌트에서` ErrorFallbackModal` 인스턴스를 사용하고 있지 않기 때문인데요.

```
//App.ts

protected createComponent() {
  const $app = createElement({ tagName: 'div', attributeOptions: { id: 'app' } });
  const $main = createElement({ tagName: 'main' });

  new MovieReviewHeader($main);
  this.movieReviewBody = new MovieReviewBody($main, { movieType: 'popular' });

  $app.appendChild($main);

  new ErrorFallbackModal($app);

  new MovieReviewDetailModal($app);

  return $app;
}
```

App 내에서 ErrorFallbackModal이 Body보다 늦게 렌더링 되기 때문에 현재 open을 넣어줄 수 없던 문제도 있었던거 같습니다. 🥲

조금 더 고민해보고 코멘트 반영해보겠습니다!

2024-03-29 04:00 UTC, jinyoung234 commented on src/components/movie/MovieScoreBoard/MovieScoreBoard.ts
> +  } as const;
코멘트 반영해놓겠습니다. 😀

2024-03-31 21:15 UTC, jinyoung234 commented
@woowahan-cron @iborymagic 안녕하세요 :) 리뷰 최대한 반영 후 다시 PR 요청 드려봅니다!

# cron 리뷰
## 변경점
### 모달 사용성 개선

https://github.com/woowacourse/javascript-movie-review/assets/87177577/61434faf-2ed1-481f-b370-f098d383127a

이미지 내 wrapper를 추가함으로써, 덜컹거리는 현상을 개선해보았습니다.

- [fix(MovieReviewDetailModal): 모달이 덜컹거리는 현상 개선](https://github.com/woowacourse/javascript-movie-review/pull/141/commits/3c07465eaee3623c956484606893a142073d3ed3)

### 무한 스크롤 개선

영화 목록이 나오기 전 스크롤 위치에 도달하면 다시 영화 목록을 가져오는 현상을 개선해보았습니다.

https://github.com/woowacourse/javascript-movie-review/assets/87177577/721cce00-ba13-47c6-8e75-a64f871f58b1

- [refactor(MovieReviewBody): 무한 스크롤 개선](https://github.com/woowacourse/javascript-movie-review/pull/141/commits/6d972364bc46117320496f6a0547bc403efd13fd)

### 일관성

크론이 코멘트 주신 내용을 듣고 비동기 처리에 대한 일관성에 대해 고민해보고 async-await를 활용하는 방법으로 리팩터링 해보았습니다.

- [refactor(MovieAPI): 일관성을 위해 response.json에 await 추가](https://github.com/woowacourse/javascript-movie-review/pull/141/commits/7e392c3388f84ba4086d06ca4479c1b553c9f95f)
- [refactor(Movie): MovieFetcher에서 데이터 패칭 하는 방식 변경](https://github.com/woowacourse/javascript-movie-review/pull/141/commits/180bc38870f13edb082549f156347345e3a170b7)
- [refactor(MovieDetail): 데이터 패칭 방식 방식 변경](https://github.com/woowacourse/javascript-movie-review/pull/141/commits/03954990c36b020b49afc322ed507335c015876f)

추가적으로 apis 디렉터리 들의 네이밍 일관성 또한 챙겨보려고 했습니다.

- [refactor(apis): api 레이어 내 디렉터리 및 파일 네이밍 변경](https://github.com/woowacourse/javascript-movie-review/pull/141/commits/d1aaa70cdae4e8f218a51dcab6156386c063d8d4)

### 관심사 및 역할 분리

querystring 및 endpoint를 만드는 로직을 외부로 분리함으로써, MovieFetcher 내 데이터 패칭 관련 로직만 있을 수 있도록 코드를 리팩터링 해보았습니다.

- [refactor(MovieAPI): 불필요한 관심사 분리](https://github.com/woowacourse/javascript-movie-review/pull/141/commits/47f000f245469e2c8ab5760a8fa46b74288b982c)

### 핸들러 함수 네이밍 수정

핸들러 함수의 네이밍의 가독성을 조금 더 개선해보았습니다.

- [refactor: 핸들러 함수 네이밍 수정](https://github.com/woowacourse/javascript-movie-review/pull/141/commits/516192552ffc843485d0e8f76892c7fdcd0c842b)

### MovieListCard의 역할 분리 및 재사용성 고려
해당 컴포넌트의 재사용성에 대해 고민하기 위해 onClick 함수를 외부에서 주입 받는 형태로 리팩터링 해보았습니다!

- [refactor(MovieListCard): MovieListCard 내 onClick props 추가](https://github.com/woowacourse/javascript-movie-review/pull/141/commits/4acc0242d1e81019a2d19e3b433bc68d04191b29)
- [refactor(MovieListCard): 모달 렌더링 하는 방법 변경](https://github.com/woowacourse/javascript-movie-review/pull/141/commits/c3c1d0524bd6a1e8adfaf7b53ec3dd4344f5e82d)

# 피터 리뷰
## 변경점
### 테스트 명세 변경
리뷰어님의 코멘트를 듣고 그대로 변경하면 될 거 같아 그대로 리뷰 반영해보았습니다!

- [refactor(e2e): 검색 결과 확인 테스트 내 명세 수정](https://github.com/woowacourse/javascript-movie-review/pull/141/commits/3103b894da14ebe83fe0e10d641a03f96afd767d)

### rerender 함수 추가 

불필요한 책임이 존재하던 부분(ex - MovieReviewBody)을 rerender 라는 정적 팩토리 메서드 형태로 분리함으로써 개선해보려고 했습니다. 

- [refactor(MovieReviewBody): ErrorFallbackModal을 여는 방법 변경](https://github.com/woowacourse/javascript-movie-review/pull/141/commits/dfca709b72cdb6d6aa9785798e2c87e0e21a7561)

### 컴포넌트 내 반복되는 로직 캡슐화

render 함수 로직이 반복되는 것을 보고 Component 내 render 함수에 해당 로직을 추가 후 로직이 다른 부분에 대해선 override 하는 형태로 코드를 개선해보았습니다.

- [refactor(Component): 반복되는 로직 캡슐화](https://github.com/woowacourse/javascript-movie-review/pull/141/commits/ff5cf1461b578c0ff0c1e0b76672be063b258b42)

그 밖에 static 상수 분리, Promise 로직 async-await으로 마이그레이션 등의 작업을 진행했습니다.

# 궁금한 점

## 이미지 로딩을 개선할 수 있는 방법

어쩌다보니 리뷰 반영이 조금 늦어지게 됬는데, 가장 애를 먹었던 부분 중 하나였습니다.

https://github.com/woowacourse/javascript-movie-review/assets/87177577/3233b898-0814-4bf8-b296-1d2995b772f4

개발자 도구 내 네트워크 탭에서 캐시 사용 중지, 느린 3g로 설정 후 모달을 클릭하면 모달 내 이미지가 늦게 로딩 되어 깜빡이는 현상을 확인할 수 있었습니다.

이것을 개선해보기 위해 이미지 프리로딩(onload) 속성을 활용해보려고 했지만, 이미지 무한 생성 및 cypress 환경 내 문제 발생으로 인해 코드를 롤백하게 되었습니다.

크루들끼리 이야기를 해볼땐 사용자가 임의로 '`캐시 사용 중지`를 누르지 않기 때문에, 캐싱 된 이미지가 보여지게 되면 크게 이슈가 될 일은 아니지 않나?'라는 결론이 나오게 되었지만 그래도 의문이 완전히 해소 되지 못했습니다.

혹시 현업에서는 이런 현상을 어떻게 개선하고 있는지 궁금합니다.

2024-04-01 14:09 UTC, iborymagic commented
사실 slow 3G면 느린 게 당연하지 않나 싶습니다. 😅 

느린 환경에서 이미지를 불러와야하기 때문에 딜레이를 감안할 수밖에 없겠죠. 그래서 말씀하신 대로 캐싱을 활용해야 하고, 가능할 경우 preloading을 활용하는 것도 방법입니다. (다만, 모달 내에서 필요한 이미지를 위해 다른 이미지들의 우선순위를 낮추는 건 조금 이상한데, 어떻게 활용하려고 하셨던 걸까요?) 그 밖에는 서버와 논의하여 리사이징, 압축, 확장자 변경 등을 통해 이미지 자체를 최적화하는 방법이 있겠죠. 방식은 너무나도 다양한데, 자세한 내용을 직접 알려드리기보단, 조금만 검색해도 관련 내용이 많이 나오기때문에 직접 찾아보시는 걸 추천드립니다.  

(그리고 일단, 실제로 어플리케이션을 개발할 때는 아마 다른 곳에서 제공하는 API, 특히 이미지를 화면에 곧이곧대로 가져다 쓰는 일은 거의 없을 것 같아요.)

2024-04-01 14:17 UTC, iborymagic commented
안녕하세요 지니! 2단계 미션 마무리 하시느라 고생 너무 많았습니다.
리뷰를 반영하려고 열심히 고민하시고 노력한 것이 느껴져서 보기 좋았네요.
사용성이 개선된 것도 좋았고, 리뷰도 잘 반영해주신 것 같아서 이만 머지하겠습니다.
고생 많으셨어요! 방학 잘 보내세요~ 🤗

2024-04-01 14:17 UTC, iborymagic approved these changes
안녕하세요 지니! 2단계 미션 마무리 하시느라 고생 너무 많았습니다.
리뷰를 반영하려고 열심히 고민하시고 노력한 것이 느껴져서 보기 좋았네요.
사용성이 개선된 것도 좋았고, 리뷰도 잘 반영해주신 것 같아서 이만 머지하겠습니다.
질문 남겨주신 부분은 코멘트 확인해주세요.
고생 많으셨어요! 방학 잘 보내세요~ 🤗

2024-04-01 14:18 UTC, merged