[2단계 - 상세 정보 & UI/UX 개선하기] 쿠키(김진호) 미션 제출합니다.
woowacourse/javascript-movie-review pull request #142
Opened 2024-03-29 10:43 UTC by jinhokim98

안녕하세요 유조! 2단계 미션 pr입니다.
아래 링크로 접속하면 step2 버전의 영화 리뷰를 이용할 수 있습니다.

![영화 리뷰](https://jinhokim98.github.io/javascript-movie-review/dist/)

## 파일 구조
![image](https://github.com/woowacourse/javascript-movie-review/assets/81083461/e716a2e4-fd61-4388-9422-083355be2d3d)

메인에서 헤더와 영화 리스트, 모달, 영화 상세를 만들어 놓습니다.
헤더는 로고와 검색어를 갖고
영화 리스트는 fallback을 가지며, list api로부터 데이터를 받아서 영화 아이템을 만듭니다.
모달 상세 컴포넌트 틀을 만들어 놓고, 영화 리스트에서 영화 한 개를 선택하면 detail api, voteMovies, StarRating을 불러와서 정보를 채운 후, 모달을 오픈합니다.
모달 리스트 하단에 더보기 공간을 붙여서 더보기 공간이 관측되면 다음 페이지를 보여주는 방식으로 무한스크롤을 구현했습니다.

## 이번 미션에서 집중한 점

이번 미션에서는 UI/UX를 개선하는 것이 주 목적이라고 생각해서 UX를 중점으로 개선했습니다.

1. 리스트에서 이미지 호버 시 이미지 zoom으로 내가 지금 어디를 포커싱하고 있는지 강조했습니다.
2. 별점 컴포넌트에서 별점을 호버할 때 현재 어디 점수를 호버하고 있는지를 보여주고 클릭 했을 때 그 값이 유지하며, 다시 이동할 때 그 값으로 이동하고 다시 마우스를 움직이면 선택한 값으로 유지해서, 사용자에게 더 나은 ux를 제공하려했습니다.
3. 모달 뒷 배경을 넣음으로써 심심해보일 수 있는 검은 배경을 생동감있게 보일 수 있도록 했습니다.
4. 무한스크롤이므로 처음 페이지로 되돌아가기가 어려울 것 같아서 맨 위로 버튼을 넣었습니다.
5. 헤더를 상단에 고정시켜서 스크롤을 내리다가도 검색할 수 있도록 개선했습니다.
6. 반응형 4개 3개 2개로 그리드 칼럼이 조정될 때, 이미지 크기를 고정시키는 것이 아니라 같이 꽉 차도록 해서 리스트의 빈 공간을 최소화했습니다. 주 기능인 영화 리뷰 사이트답게 영화로 꽉 찬 경험을 제공하고 싶었습니다.

2024-03-29 18:26 UTC, yujo11 requested changes
안녕하세요 쿠키~~

오랜만에 다시 만나니 반갑네용 ㅎㅎ 

이전에도 코드가 통일성 있게 작성되어 있다는 생각이 들었는데 step2를 진행하면서도 이런 통일성을 지속적으로 유지해주고 계셔서 좋았네요 ㅎㅎ 👍 

stpe2 자체의 요구사항만으로만 보면 구현할 부분이 많지 않았는데 쿠키가 생각해서 사용성을 고려해 구현하신 부분이 정말 좋았어요 ㅎㅎ 일반적으로 웹사이트를 사용할 때 기대되는 부분들이 대부분 충족되어 있어 조금 놀라기도 했네요 👍 👍 👍 💯 💯 💯  (이건 소소한 부분인데 영화를 클릭하고 Modal이 나오기까지 시간이 조금 걸리는데 이 때 영화정보를 Loading 하고 있는거 같아요. 이 때 사용자가 올바르게 click 을 했다는 인지를 할 수 있게 Loading 상태와 그에 따른 UI도 고려해보시면 좋을거 같네용 ㅎㅎ )

다른 크루들보다 빠르게 제출했는데도 이 정도 퀄리티를 고민하고 구현하신 부분이 놀랍네요 ㅎㅎ 프론트엔드 이전에 Client 개발자로 사용자와 맞닿아 있는 부분을 앞으로도 계속 고민해보시면 쿠키만의 강점을 가질 수 있겠다는 생각도 들었습니다

step2 진행하느라 고생 많으셨습니다 쿠키~~ 코멘트 남긴 내용 확인해보시고 다시 리뷰요청 부탁드려요 ~ 👍 👍 👍

2024-03-29 18:26 UTC, yujo11 commented on src/components/Fallback/Fallback.ts
> +    NONE: '조건에 맞는 영화가 없어요 :(',
여기를 보면 방금 위에 단 코멘트에 어느정도 답변이 되는거 같군요 ㅎㅎ

2024-03-29 18:26 UTC, yujo11 commented on src/api/PopularMovies.ts
> +    if (popularMovies.results.length === 0) throw new Error('NONE');
Error가 발생하는 상황이 아닌 response를 받은 상황에서 response의 Happy/Bad case에 따라 처리하는 위치가 달라지는거 같은데  이렇게 처리하신 이유가 궁금합니다

2024-03-29 18:26 UTC, yujo11 commented on src/components/Image/Image.ts
>      if (typeof onImageClick !== 'undefined') img.addEventListener('click', onImageClick);
parameter가 추가 됨에 따라 추가적인 validation 로직을 구축하신 점 아주 좋네용 ㅎㅎ 👍

2024-03-29 18:26 UTC, yujo11 commented on src/components/Modal/Modal.ts
> +  onEscapeKeydown() {
이름을 보면 특정 key가 입력되었을 때 trigger 되는 callback 함수의 이름처럼 생겼는데 실제 하는 동작은 EventListenr를 등록하는 동작이라 조금 어색하게 느껴지는거 같아요.

이 부분을 개선해 볼 수 있을까요?

2024-03-29 18:26 UTC, yujo11 commented on src/components/Modal/Modal.ts
> +  }
이미 알고 계실 수도 있지만 Modal의 배경 영역은 `dimmed`라는 용어로도 많이 사용되니 참고하시면 좋을거 같네용 ㅎㅎ

2024-03-29 18:26 UTC, yujo11 commented on src/components/MoreSpace/MoreSpace.ts
> +    const observer = new IntersectionObserver(
`InetersectionObserver`를 이용해 구현하신 이유가 궁금하네용

2024-03-29 18:26 UTC, yujo11 commented on src/components/MoreSpace/MoreSpace.ts
> +    moreSpace.textContent = '더 보여줄거지롱';
👀

2024-03-29 18:26 UTC, yujo11 commented on src/components/MovieItems/MovieItems.ts
> +    }
쿠키는 어떤 상황에서 `if - else` 문을 사용하고 어떤 상황에서 ealry return을 사용하시나요? 궁금해서 질문 드립니다 ㅎㅎ

2024-03-29 18:26 UTC, yujo11 commented on src/components/StarRating/EachStar.ts
> +class EachStar {
`EachStar`라는 이름이 각각의 별 아이콘을 나타내는걸까요?

2024-03-29 18:26 UTC, yujo11 commented on src/utils/debounce.ts
요건 사용하고 있는 함수일까요?

2024-03-29 18:26 UTC, yujo11 commented on src/utils/debounce.ts
debounce와 throttle은 어떤 차이가 있고, 어떤 이유 때문에 debounce를 구현해두신건지도 궁금하네용

2024-03-29 18:26 UTC, yujo11 commented on src/types/StarRate.ts
> +} as const;
1, 3, 5, 7, 9 는 빠져있는 이유가 있나요? 궁금해서 질문 드립니다 ㅎㅎ

2024-03-29 18:26 UTC, yujo11 commented on src/types/StarRate.ts
> +export function verifyRate(number: number) {
이거는 함수고

2024-03-29 18:26 UTC, yujo11 commented on src/types/StarRate.ts
> +export const MENT_BY_RATE: Record<Rate, string> = {
이 아래는 type으로 쓰이는거 같은데 같은 모듈(파일)에 두신 이유가 있을까요?

2024-04-01 06:15 UTC, zigsong commented on src/types/StarRate.ts
> +} as const;
지나가다가 남겨용 

![image](https://github.com/woowacourse/javascript-movie-review/assets/44080404/8db723c3-e3f6-40e7-a307-53b8a6642d1a)

2024-04-02 04:47 UTC, jinhokim98 commented on 면담.md
ㅋㅋㅋ 준이랑 면담하다가 여기에다가 면담 내용 적고 실수로 커밋해버려서요ㅋㅋㅋㅋ
핵심 내용의 0.0.0.0.0.1을 구현해보라는 내용이었습니다ㅋㅋㅋ

2024-04-02 04:48 UTC, jinhokim98 commented on cypress/e2e/error.cy.ts
>      it('Access Token이 잘못된 경우 "접근 권한이 없어요 :(" 라는 문구와 함께 fallback screen을 출력한다.', () => {
아하 비슷한 내용 수정해볼게요!

2024-04-02 04:49 UTC, jinhokim98 commented on src/api/MatchedMovies.ts
> +    if (matchedMovies.results.length === 0) throw new Error('NONE');
원래는 api 결과가 빈 리스트라면 빈 화면을 따로 보여주는 방식으로 구현했는데, 빈 값을 처리하기 위한 함수와 에러처리의 함수와 비슷한 기능이어서 빈 값일 때 에러를 터뜨리는 방식으로 변경싴ㅆ습니다!

2024-04-02 04:51 UTC, jinhokim98 commented on src/api/PopularMovies.ts
> +    if (popularMovies.results.length === 0) throw new Error('NONE');
위의 코멘트와 비슷한 답인데, 빈 값을 보여주는 fallback과 에러를 보여주는 fallback이 기능이 동일해서 하나로 합치고자 빈 값도 에러로 처리하면 좋을 것 같아서 이렇게 처리했습니다!

2024-04-02 04:53 UTC, jinhokim98 commented on src/components/Modal/Modal.ts
> +  onEscapeKeydown() {
esc를 누를 때 모달을 닫는 기능을 만들다가 esc key가 down 됐을 때를 기다리는 기능인데 on이라고 지으니 그렇게 보이네요! 개선해보겠습니다!

2024-04-02 04:54 UTC, jinhokim98 commented on src/components/Modal/Modal.ts
> +  }
아하~ 네 dimmed 맞아요! 들어봤습니다!

2024-04-02 04:58 UTC, jinhokim98 commented on src/components/MoreSpace/MoreSpace.ts
> +    const observer = new IntersectionObserver(
무한 스크롤을 구현할 때 스크롤 이벤트를 사용하는 방식과 IntersectionObserver를 이용하는 방식 두 가지가 있다고 들었습니다. 스크롤 이벤트를 사용하면 간단하게 짤 수 있지만 스크롤 할 때마다 스크롤 이벤트가 발생하는 단점이 있습니다. IntersectionObserver를 사용하면 관찰대상이 관측될 경우에 특정 동작을 실행할 수 있고, 비동기적으로 관찰하기 때문에 메인 스레드에 영향을 주지 않는다고 해서 IntersectionObserver를 사용해서 구현했습니다!

2024-04-02 05:01 UTC, jinhokim98 commented on src/components/MovieItems/MovieItems.ts
> +    }
if else는 함수 내의 수행결과가 if else 케이스 전부 다 기능이 작동되어야 할 때 사용하고 있습니다.
early return은 예외의 상황에서 함수가 미리 끝나야 할 경우에 사용하고, 즉 예외의 케이스를 걸러낼 땐 early return을 사용합니다.
위의 경우에는 if else 케이스에 따라 둘 다 동작이 필요해서 if else를 사용했습니다

2024-04-02 05:02 UTC, jinhokim98 commented on src/components/StarRating/EachStar.ts
> +class EachStar {
네네 맞아요! 각각 별이라는 의미를 짓고 싶어서 Each를 사용했습니다

2024-04-02 05:10 UTC, jinhokim98 commented on src/utils/debounce.ts
step1을 리팩토링 한 후에 다른 크루들의 리뷰를 보다가 더보기 버튼을 여러 번 눌렀을 때 여러 번 실행된다는 리뷰를 보고 추가했었습니다. 그래서 더보기 버튼에 적용하기 위해서 사용했었고, 지금은 사용하고 있지 않네요🥲

debouncing은 버튼이나 입력을 할 때 특정 시간이 지난 후에 기능이 실행되도록 하는 기법이고, 사용자가 버튼을 여러 번 눌렀을 때, 요청이 두 번, 세 번 되지 않도록 하는 기법입니다.
throttle은 이벤트가 연속으로 발생되는 상황에서 특정 시간마다 함수가 실행되도록 하는 기법으로, 이벤트가 연속으로 일어나는 상황에서 요청을 여러 번 보내지 않도록 하는 기법입니다.

2024-04-02 05:10 UTC, jinhokim98 commented on src/types/StarRate.ts
> +} as const;
지그가 정리해준 것처럼 2,4,6,8,10점을 구현하는 것이 기능 요구사항이었습니다!

2024-04-02 05:14 UTC, jinhokim98 commented on src/types/StarRate.ts
> +export const MENT_BY_RATE: Record<Rate, string> = {
Rate에 대한 기준이 0 | 2 | 4 | 6 | 8 | 10 인데 이 수가 변한다고 생각했을 때, verifyRate함수를 바꿔줘야 할텐데 다른 곳에 있다면 찾기 어려울 것 같아서 이렇게 작성했습니다!

2024-04-03 02:45 UTC, jinhokim98 commented on cypress/e2e/init.cy.ts
> +  context('Flow: 처음 페이지에 접근했을 때 영화 모드 검증', () => {
반영해봤습니다! [dfd4cca](https://github.com/woowacourse/javascript-movie-review/pull/142/commits/dfd4ccae0c8bdfb5e8ff49cfaec81ab724e765db)

2024-04-03 02:49 UTC, jinhokim98 commented
안녕하세요 유조! 좋은 하루 보내고 계신가요?
제가 요즘에 우테코 크루들의 정보를 담는 크루위키 서비스를 만들고 있어서;; 리뷰 반영이 조금 늦었습니다ㅜ

유조가 질문해주신 내용에 대해 코멘트로 답을 달았고, 반영한 내용에는 커밋을 달았습니다
추가로 모달을 열 때 커서를 로딩으르 표현하는 기능을 넣어서, 로딩 중이라는 것을 사용자에게 보여주는 기능을 추가했습니다. [26f5779](https://github.com/woowacourse/javascript-movie-review/pull/142/commits/26f5779b1abc99def131661e2c5e4e01cf79682e)

2024-04-03 05:45 UTC, yujo11 commented on src/components/MoreSpace/MoreSpace.ts
> +    const observer = new IntersectionObserver(
크 멋진 설명이네요 👍

2024-04-03 05:57 UTC, merged

2024-04-03 05:57 UTC, yujo11 approved these changes
안녕하세요 쿠키~

재밌는 서비스를 만들고 계시는군요 ㅎㅎ 완성 되면 저도 사용해보고 싶네요

쿠키가 남겨준 답변들 잘 확인했고 코멘트 반영해주신 부분도 잘 확인 했습니다 ㅎㅎ 👍  👍  👍 

Modal을 열 때 Loading 상태로 변하는 부분은 제 환경에서는 작동하지 않아 확인을 못 해 아쉽네요

이번 미션은 이만 merge하고 다음 레벨로 넘어가도 좋을거 같습니다!

앞으로의 여정도 응원하겠습니다! 고생 많으셨어요 쿠키~~ 👍 👍 👍

2024-04-03 05:57 UTC, yujo11 commented on cypress/e2e/error.cy.ts
> +    it('"접근 권한이 없어요 :(" 라는 문구와 함께 fallback screen을 출력한다.', () => {
context와 중복되는 내용을 모두 제거해주셨군요 ㅎㅎ 👍 👍 👍

2024-04-03 05:57 UTC, yujo11 commented on cypress/e2e/error.cy.ts
> +    it('"접근 권한이 없어요 :(" 라는 문구와 함께 fallback screen을 출력한다.', () => {
변경사항을 커밋 단위로 보고 있는데 커밋이 조금더 구체적이어도 좋을거 같아요

ex) 테스트코드 리팩터링 -> 테스트 코드에서 context와 중복되는 test case명 수정

2024-04-03 05:57 UTC, yujo11 commented on src/components/Modal/Modal.ts
> +  private setEscapeKeyDownListener() {
👍 👍 👍

2024-04-03 05:57 UTC, yujo11 commented on src/components/Modal/Modal.ts
> +    modal.appendChild(this.createModalDimmedLayer());
👍 👍 👍

2024-04-03 05:57 UTC, yujo11 commented on src/index.ts
> +  });
오 커서로 구현해주셨군요 ㅎㅎ 좋은 방법이네요 👍 👍 👍 

혹시 이 내용도 배포가 되었을까요? 제 환경에서는 커서가 변하지 않고 있네용