[2단계 - 상세 정보 & UI/UX 개선하기] 헤일리(최혜림) 미션 제출합니다.
woowacourse/javascript-movie-review pull request #143
Opened 2024-03-29 10:44 UTC by healim01

안녕하세요 케빈! 잘지내셨나요? 
step2 로 돌아왔습니다! 

### ✅ 베포 사이트 

[영화관 미션 바로가기!](https://healim01.github.io/javascript-movie-review/dist/)

![전체](https://github.com/woowacourse/javascript-movie-review/assets/74346290/20cd2c49-37a4-48e0-ac02-43c0fe0abdd6)

<br>

**📍 학습 목표**
- 상세 정보 조회, 별점 매기기
- UI/UX 개선 하기 

<br>

### ❗️ 이번 과정에서 집중해서 작업한 부분 

**디테일 모달 추가**
카드로만 보여주던 영화 정보를 모달을 통해 영화의 장르와 설명을 추가적으로 보여주었습니다. 
모달 내 이미지가 로드될 때에도 스켈레톤 UI 를 사용하여 사용자 경험을 향상시키려고 노력했고, 영화 요약 정보가 없는 부분이 꽤 있어서 영화 정보가 없을 시 정보가 제공되지 않았다고 멘트를 작성하여 보여주었습니다. 
또한 모달을 다이머 클릭, `esc` 클릭, 닫힘 버튼 클릭시 모두 닫힐 수 있도록 작업했습니다. 

**사용자의 별점 추가** 
사용자가 영화에 대한 별점을 달 수 있도록 작업했으며 로컬스토리지를 사용하여 새로고침을 하여도 정보가 저장될 수 있도록 했습니다. 
디자인 정렬 일관성을 유지하기 위해서 별점 컨테이너 내부 데이터가 변해도 위치가 변하지 않도록 작업했습니다. 

**더보기 버튼에서 무한 스크롤로** 
영화 목록에서 더보기 버튼을 눌렀을 때 페이징하는 방식에서 무한 스크롤 방식으로 변경하는 것이 기능 요구사항이었습니다! 
Intersection Observer 사용해서 이를 구현해보았고 로딩되는 과정에서 진행했던 스켈레톤 UI 이외에 로딩 UI 도 추가해보았습니다!

**반응형 작업** 
이번에 저번에 말씀해주셨던 반응형 작업도 요구사항이라 진행해보았습니다! PC 버전, 태블릿 버전과 모바일 버전을 준비해보았습니다! 
	
**기타 UX 작업** 
새로운 데이터가 로드될 때 기존에 있던 스크롤 위치가 아니라 맨 위로 자동으로 올라갈 수 있도록 해보았습니다. 

<br>

잘부탁드립니다!
즐거운 주말 보내세요! 😆

2024-03-30 04:00 UTC, JeongBin0227 commented
> 이번에 저번에 말씀해주셨던 반응형 작업도 요구사항이라 진행해보았습니다! PC 버전, 태블릿 버전과 모바일 버전을 준비해보았습니다!

저는 개인적으로 반응형작업할때 https://responsively.app/ 툴을 자주 쓰는데 정말 좋습니다 추천드려요~

2024-03-30 04:06 UTC, JeongBin0227 commented
> 또한 모달을 다이머 클릭, esc 클릭, 닫힘 버튼 클릭시 모두 닫힐 수 있도록 작업했습니다.

👍  여기서 다이머가 뭘까요?

2024-03-30 04:07 UTC, JeongBin0227 commented
스크롤시 하단에 점 표시 3개뜨는거 좋네요 👍

2024-03-30 04:08 UTC, JeongBin0227 commented
![image](https://github.com/woowacourse/javascript-movie-review/assets/45503248/5f1ec8b6-6ed3-4d66-9cbd-38260287de41)
영화가 다 불러왔음에도 불구하고 계속해서 하단 로딩중 표시가 있네요

2024-03-30 04:09 UTC, JeongBin0227 commented
> 새로운 데이터가 로드될 때 기존에 있던 스크롤 위치가 아니라 맨 위로 자동으로 올라갈 수 있도록 해보았습니다.

중간에 스크롤 하다가 새로고침하면 스크롤이 중간에 있는데 의도하신걸까요?

2024-03-30 05:11 UTC, JeongBin0227 commented
[질문]
별점 업데이트가 어떻게 되는지 궁금합니다.
별점을 넣으면 로컬스토리지에 저장하는걸로 보이는데 수정이 안되는거 같아서요~


https://github.com/woowacourse/javascript-movie-review/assets/45503248/a153d025-9937-43a4-a235-3dc635ef40b9

2024-03-30 05:33 UTC, JeongBin0227 requested changes
안녕하세요 헤일리~

항상 빠르게 리뷰 반영해주셔서 감사합니다. 덕분에 더 꼼꼼히 볼수 있었던거 같아요
그리고 사용자 경험을 여러 방면에서 고민해주셔서 결과물을 확인하면서 재밌었던거 같아요

2단계 미션하느라 고생하셨습니다 💯 👍

2024-03-30 05:33 UTC, JeongBin0227 commented on src/components/ItemCardList.ts
> +
movieList의 각 항목마다 DOM에 직접 접근하여 appendChild를 호출하는데, 지금은 몇개 없겠지만 많아지면 성능저하가 일어날수 있을거 같아요 
모든 아이템 카드를 먼저 생성하여 DocumentFragment에 추가한 후, 이를 한 번에 DOM에 추가하는 방식은 어떨까요?

2024-03-30 05:33 UTC, JeongBin0227 commented on src/components/ItemCardList.ts
> +
ItemCardList 가 자주쓰이니 더 개선하면 좋겠네요

2024-03-30 05:33 UTC, JeongBin0227 commented on src/components/LoadMore.ts
> +};
현재 구현에서는 addObserver 함수가 호출될 때마다 이전 IntersectionObserver 인스턴스의 연결을 끊고 새로운 인스턴스를 생성하는거 같은데 이런 이유가 있을까요?

2024-03-30 05:33 UTC, JeongBin0227 commented on src/components/LoadMore.ts
> +export default LoadMore;
무한 스크롤 관련 로직은 따로 util 로 분리하면 어떨까요?

2024-03-30 05:33 UTC, JeongBin0227 commented on src/components/MovieImg.ts
> +function SkeletonImg(className: string) {
함수는 컴포넌트를 반환하는 것처럼 보이지만, 실제로는 DOM 요소를 생성하고 반환하니까, 좀더 명확하게 createSkeletonImg 은 어떨까요?

2024-03-30 05:33 UTC, JeongBin0227 commented on src/components/MovieImg.ts
> +function PosterImg(posterPath: string, title: string, className: string) {
여기도 createPosterImg 가 좀더 명확해 보입니다

2024-03-30 05:33 UTC, JeongBin0227 commented on src/components/MovieOverview.ts
> +  if (overview.length !== 0) {
이 조건보다는 좀더 넓게 null 이거나 undefined.. 등등 모든걸 커버해보면 어떨까요?
위 값들은 falsy 값이니 

if (overview) {

이런식도 좋을거 같아요

2024-03-30 05:33 UTC, JeongBin0227 commented on src/components/StarRate.ts
> +};
각각 이벤트를 넣지않고 이벤트 위임 방식을 사용하신건 좋네요 👍

2024-03-30 05:33 UTC, JeongBin0227 commented on src/components/StarRate.ts
> +  setStarRate(movieId, clickedStarNumber);
아까 전체 코멘트에 적은 질문내용과 이어질수 있는데,
평점 데이터를 업데이트한 후 UI를 즉시 반영하는 방식으로 코드를 구성하는 것이 어떨까요?

2024-03-30 05:33 UTC, JeongBin0227 commented on src/model/RateDataStateStore.ts
> +export default rateDataStateStore;
여기는 #rateList가 undefined가 아닌 Rate[] 타입을 보장하면 (즉 undefined 가 없이 만들면 코드가 많이 간결해지겠네요)

그러기 위해서는 로컬 스토리지에 데이터가 없을 경우 undefined 대신 빈 배열 []을 할당하면 후속 로직에서 #rateList의 null 체크를 간소화할 수 있습니다.

2024-03-30 05:33 UTC, JeongBin0227 commented on src/model/RateDataStateStore.ts
> +export default rateDataStateStore;
updateRateList 함수도 : rateIndex가 undefined인 경우를 체크하는 로직은 불필요할거 같아요 Array.prototype.findIndex는 찾지 못했을 경우 -1을 반환합니다.

2024-03-31 13:18 UTC, healim01 commented on src/components/ItemCardList.ts
> +
DocumentFragment를 사용하는 방법은 몰랐던 방법인데 찾아보니 너무 좋은 기능인거같네요! 반영해서 수정하겠습니다!

2024-03-31 13:21 UTC, healim01 commented on src/components/LoadMore.ts
> +};
props 로 데이터 호출 타입인 listType 을 넘겨주고 있다보니 데이터 타입이 변경될 때 (==ItemView 가 새로 불러질 때) 이전 인스턴스를 지우고 새롭게 생성하게 했습니다!

2024-03-31 13:40 UTC, healim01 commented on src/components/CloseButton.ts
> +    handleCloseModal();
닫히면 버튼 엘리먼트(모달 엘리먼트)가 삭제되다 보니 생각하지 못했네요! 
다음번에 이벤트 리스너를 고려할 때는 염두하도록 하겠습니다!

2024-03-31 13:51 UTC, healim01 commented on src/components/CloseButton.ts
> +  document.body.style.overflow = "";
```
document.body.classList.add('modal-open');

.modal-open {
  overflow: hidden;
}
```

이런 형태로 변경해보았습니다만 어떻게 생각하시나요?

2024-03-31 13:56 UTC, healim01 commented on src/components/StarRate.ts
> +  setStarRate(movieId, clickedStarNumber);
말씀하시는 바가 로컬 스토리지가 업데이트되면 이를 가져와서 반영하시는 형식으로 말씀하시는걸까요?

일단은 지금은 평점 데이터가 수정되면 로컬에 저장될 수 있도록 해놨습니다!

2024-03-31 14:16 UTC, healim01 commented
안녕하세요 케빈 ! 주말 잘보내고 계신가요? 

적어주신 코멘트 반영해서 수정해보았습니다 ! 

별점 업데이트가 안되는 오류 수정했고, 추가적인 데이터가 없을 시 추가 로딩 스켈레톤 UI 가 발생하지 않도록 재작업했습니다! 
알려주신 DocumentFragment 도 사용해서 카드 엘리먼트를 fragment 에 추가한 후 한번에 리스트에 추가 할 수 있게 했습니다!

2024-03-31 14:16 UTC, healim01 commented
> 👍 여기서 다이머가 뭘까요?
dimmer 라고 해서 모달 창 뒤의 배경을 가리키는 용어로 알고 있는데 잘 사용하지 않는 용어일까요? 


> 중간에 스크롤 하다가 새로고침하면 스크롤이 중간에 있는데 의도하신걸까요?
이 부분에서는 찾아보았는데 개발자 도구로 검사를 킨 후 새로고침을 했을 때 맨 위로 이동하는거 같은데 검사를 도구를 끈 후 동일하게 작동하면 중간으로 이동하는 이상한 점을 발견했습니다.. 
코드가 바뀐 것도 아니고 검사 유무로 달라지다보니 이유를 알 수가 없어서 조금 더 찾아볼까 합니다.. 혹시 케빈은 이런 상황을 본적 있으실까요?

2024-03-31 14:17 UTC, healim01 commented on src/components/LoadMore.ts
> +export default LoadMore;
로직이 너무 많네요! 분리해보도록 하겠습니다!

2024-04-01 13:46 UTC, JeongBin0227 commented
<img width="1079" alt="image" src="https://github.com/woowacourse/javascript-movie-review/assets/45503248/31cd5aed-5832-483a-969c-069e9b146a33">

결과 로직이 어떻게 될까요? d 를 검색했는데 d 가 포함되지 않은것들도 나온거 같아서요!

2024-04-01 13:47 UTC, JeongBin0227 commented
> dimmer 라고 해서 모달 창 뒤의 배경을 가리키는 용어로 알고 있는데 잘 사용하지 않는 용어일까요?

아하 아닙니다 자주 사용하는 용어인데 보통 딤으로 말하는데, 다이머라고 하셔서 다른 단어의 오타인줄 알았습니다

2024-04-01 13:47 UTC, JeongBin0227 commented on src/components/CloseButton.ts
> +  document.body.style.overflow = "";
이런 형태도 좋아 보입니다 👍

2024-04-01 13:48 UTC, JeongBin0227 commented
> 현재 스크롤이 상단으로 이동하는거 같은데 케빈이 보는 화면에선 스크롤이 멈춰있는걸까요?

다시 확인해보니까 상단으로 이동하네요 👍

2024-04-01 13:49 UTC, JeongBin0227 commented
아직도 업데이트 로직에 대해서 궁금한게 많은데, 설명 한번부탁드려도 될까요?

로직이 변경된 후로 별점이 업데이트가 안되는 이슈는 없지만 속도가 느려진거 같아서 확인해보려고 합니다.

2024-04-01 14:01 UTC, JeongBin0227 requested changes
안녕하세요 헤일리 👍 

항상 빠르게 반영해주셔서 감사합니다.
지금도 충분히 머지할만큼 좋은 코드지만, 일찍 제출해주신 만큼 좀더 생각할수 있는 주제를 던저드리기 위해 세세하게 확인하고 궁금한것도 질문해봤어요.

리뷰 반영하느라 고생많으셨습니다 👍 💯

2024-04-01 14:01 UTC, JeongBin0227 commented on src/utils/IntersectionObserver.ts
> +};
이미 IntersectionObserver 내부에 적용되어있을 수 있지만,
만약 페이지에 많은 요소가 있고, 사용자가 빠르게 스크롤하는 경우, 데이터 요청이 너무 자주 발생할 수 있습니다. 이를 방지하기 위해, 스크롤 이벤트의 호출 빈도를 제한하는 디바운싱(debouncing)이나 쓰로틀링(throttling) 도 고민해보면 좋을거 같아요

2024-04-02 02:41 UTC, healim01 commented on src/utils/IntersectionObserver.ts
> +};
이전에 쓰로틀링으로 스크롤 작업을 하려고 했어서 작업해본 코드를 사용해서 추가해보았습니다!

2024-04-02 02:50 UTC, healim01 commented
안녕하세요 케빈! 

> 결과 로직이 어떻게 될까요? d 를 검색했는데 d 가 포함되지 않은것들도 나온거 같아서요!

해당 데이터는 TMDB 에서 받아오는 데이터를 그대로 사용하고 있는데 저도 개발 도중 종종 그런 영화들이 있어서 찾아봤습니다.
'Search for movies by their original, translated and alternative titles.' 라는 사이트 말에 따르면 검색 로직에서 본래의 영화 이름 (원래 영어 이름 제목) 과도 검색 결과가 일치하거나, 가제나 번역된 텍스트랑도 같으면 결과로 받아오는거 같습니다!
사진처럼 `러스트 앤 본`의 본래 명인 `Rust and Bone`에 d가 포함되어서 같이 전달되는거 같습니다! 

또한 나머지 코멘트 부분도 반영했습니다! 
그리고 별점 업데이트 로직에 대해서 작성해보았습니다! 길어서 다음 코멘트에 달아놓았습니다!

2024-04-02 02:52 UTC, healim01 commented
### **별점 저장 로직**

1. 별점 클릭 
2. 클릭 이벤트 감지로 클릭 핸들러 실행 
    
    ```jsx
    $rateContainer.addEventListener("click", (e) => {
        handleClickStar(e, movieId, $rateContainer);
     });
    ```
    
3. `handleClickStar` 내부에서 별점 업데이트 로직 실행 
    1. 이전 별점 엘리먼트 삭제 
        1. `handleRemovePreStar($rateContainer);`
    2. 클릭한 버튼 id 로 별점의 수 찾아서 업데이트 
        
        ```
         const clickedStarNumber = Number(target.closest("button")?.id) * 2;
          $rateContainer.appendChild(Stars(clickedStarNumber));
          $rateContainer.appendChild(rateStateContainer(clickedStarNumber));
        ```
        
4. `setStarRate(movieId, clickedStarNumber)` 호출하여 Rate 형식으로 변환 후 `rateDataStateStore` 저장 메서드 호출 
    
    ```jsx
    const setStarRate = (movieId: number, rate: number) => {
      const newRate: Rate = {
        movieId,
        rate,
      };
      rateDataStateStore.setNewRate(newRate);
    };
    ```
    
5. 별점 캐싱 데이터에서 해당 영화에 이전에 이미 별점을 준 적 있는지 찾는다
    
    ```jsx
    setNewRate(newRate: Rate) {
        const isExist = this.#rateList.find(
          (rate) => rate.movieId === newRate.movieId,
        );
    ```
    
6. 만약 존재한다면 `this.updateRateList(newRate);` 호출 
7. 업데이트 로직 
    
    ```jsx
    updateRateList(newRate: Rate) {
        const rateIndex = this.#rateList.findIndex(
          (rate) => rate.movieId === newRate.movieId,
        );
        this.#rateList[rateIndex].rate = newRate.rate; // 새로운 별점으로 업데이트 
        this.setRateList(); // 업데이트된 리스트 저장 
      }
    ```
    
8. 새로 추가 로직 
    
    ```jsx
     addNewRate(newRate: Rate) {
        this.#rateList.push(newRate); // 이전 데이터에 추가 
        this.setRateList(); // 추가된 리스트 저장 
      }
    ```
    
9. 바뀐 데이터 리스트 저장 
    
    ```jsx
      setRateList() {
        LocalStorageService.setData("rateList", this.#rateList);
      }
    ```
    
10. 로컬 스토리지에 저장 
    
    ```jsx
     setData(itemName: string, item: Rate[]) {
        localStorage.setItem(itemName, JSON.stringify(item));
      },
    ```

별점 추가 로직과 업데이트 로직 그리고 로컬 스토리지에 어떻게 저장되는지까지 작성해보았습니다!!

2024-04-03 02:16 UTC, JeongBin0227 commented
> 속도가 느려지는 부분에서는 랜더링 과정과 로컬 스토리지에 업데이트하는 과정이 따로 분리되어 있어서 수정한다고 별점 랜더링 과정에 바뀐 점이 없을거 같아서 이유를 모르겠네요..

네 전체적으로 문제가 없어 보이긴 합니다. 👍 

추가적으로 매번 별점을 업데이트할 때마다 전체 리스트를 로컬 스토리지에 저장하는 방식은 성능상 비효율적일 수 있으니, 가능하다면, 변화가 있는 부분만 업데이트하거나, 정기적으로 또는 필요할 때만 전체 리스트를 저장하는 방식을 고려해봐도 좋을거 같네요

2024-04-03 02:18 UTC, JeongBin0227 approved these changes
안녕하세요 헤일리!

코드도 잘 반영해주시고, 궁금점도 잘 해결해 주셔서 감사합니다 👍 
코드가 전체적으로 깔끔해서 보기 좋았습니다 💯 

미션하느라 고생많으셨습니다~ 여기서 미션 머지하겠습니다! 👍

2024-04-03 02:18 UTC, merged