[2단계 - 상세 정보 & UI/UX 개선하기] 바다(손해영) 미션 제출합니다.
woowacourse/javascript-movie-review pull request #144
Opened 2024-03-29 14:42 UTC by BadaHertz52

안녕하세요. 샐리! 잘 지내셨나요? 
저는 2단계 구현이 생각보다 할 일이 많아서 바쁘게 지냈어요. 😅

그리고 1단계에서 데이터를 받아오는 중에는 스켈레톤 ui를 보여주고, api 요청이 실패하면 오류를 보여주는  DataFetcher에서 스켈레톤 ui를 보여주는 함수를 파라미터로 받으면 유연성 측면에서 좋을 거라는 샐리의 조언이 이번에 정말 도움이 되었어요.  
2단계에서는 영화 상세 정보 모달을 띄울 때, 영화 상세 정보 데이터를 불러오는 중에도 해당 모달 내에 스켈레톤 ui를 보여주고 오류 시에는 오류 화면을 보여줬는데 1단계에서 샐리의 조언처럼 파라미터로 빼두니까 구현이 편했던 것 같아요.  👍

###  🍿 배포 
[배포 사이트 바로가기](https://badahertz52.github.io/javascript-movie-review/dist/)

###  💻 구현
- 2단계에서 추가된 무한 스크롤, 그리드와 입력창의 반응형, 영화 상세 정보 모달의 구현 모습 [보러가기](https://github.com/BadaHertz52/javascript-movie-review?tab=readme-ov-file#2%EB%8B%A8%EA%B3%84-%EC%B6%94%EA%B0%80-%EA%B8%B0%EB%8A%A5)

###  🙂 모듈 구조, 순서도 
- [변경된 모듈 구조, 무한 스크롤 프로세스 보러 가기](https://github.com/BadaHertz52/javascript-movie-review?tab=readme-ov-file#%EB%AA%A8%EB%93%88-%EA%B5%AC%EC%A1%B0-%EB%B0%8F-%ED%94%84%EB%A1%9C%EC%84%B8%EC%8A%A4)

###  😁 구현 설명
2단계 구현 시 아래의 것들을 좀 더 신경써봤어요.

#### 무한 스크롤
- 무한 스크롤 기능을 위해 Intersection Observer API를 사용했습니다
- 더 이상 불러올 영화가 없는 경우 "END"라는 문구를 보여줍니다.
-  스크롤이 짧은 시간 반복될 경우 불필요한 API요청이 있을 수 있다고 생각했습니다. 그래서 스크롤을 통한 API 요청에 디바운스를 적용해 일정 시간동안에 있던 마지막 스크롤 동작을 통해서만 API 요청을 하도록 했습니다.

#### 검색창
- 폰 사이즈의 모바일 환경에서 검색창에 대한 UX를 높이기 위해, CSS의  transition을 사용해봤습니다.
  <img src="https://github.com/woowacourse/javascript-movie-review/assets/69838872/7ae4961b-0f0e-45e0-bf55-70b8b3f14de3"  width="400px"/>
  - 아이콘 버튼을 누르면 입력창의 너비가 커지고, 입력값이 없는 상태에서 다시 아이콘 버튼을 누르면 입력창의 너비가 다시 작아집니다.
   -  입력창에 입력값이 있고 아이콘 버튼을 클릭하면 영화를 검색합니다.
   -  사용자가 쓰기 편한 입력창을 위해서 해당 모바일 사이즈에 사용하는 로고를 만들었습니다.

 #### 영화 상세 정보 모달
- 이미지, 영화 줄거리에 대한 데이터가 없는 경우를 위한 사진이나 문구를 만들었습니다.
- 영화 상세 정보 모달에도 스켈레톤 UI를 적용했습니다.
-  이전에 열었던 영화 정보에 대해서 다시 모달을 열 경우 불필요한 API요청을 막기위해 DataStateStore에서 이전에 열었던 영화 정보를 가지고 있게 했습니다.
- 영화 상세 정보에 대한 API 요청 오류 상황을 영화 상세 정보가 띄어지는 모달 내에서 확인 할 수 있도록 했습니다.
<img src="https://github.com/woowacourse/javascript-movie-review/assets/69838872/c06439db-9fcd-47f5-ab69-1722c72bf2fd" width="400px"/>

#### 내 별점
- 사용자 점수를 위해서 점수에 맞는 별을 모두 클릭하는 것이 아닌, 점수에 맞는 위치에 있는 별을 클릭하면 점수가 변경되게 했습니다.
 - 예를 들어 0점에서 4점으로 변경하고 싶다면 2번째 별을 클릭하면 되고, 반대로 4점에서 2점으로 변경하고 싶다면 첫번째 별을 클릭하면 됩니다.
-  점수를 초기화(=삭제)할 수 있는 reset 버튼을 추가했습니다.

2024-03-30 14:12 UTC, liswktjs requested changes
안녕하세요 바다 
2단계 미션도 수고 많으셨습니다 👏

전체적으로 코드도 깔끔하고 컴포넌트도 적절히 잘 분리해주신 것 같아요 
또 여러 케이스들을 고민해서 핸들링을 잘 해주시고 있어서 좋았습니다 👍
그리고 무엇보다도 바다의 꼼꼼한 문서화가 정말 멋진 것 같아요 💫
개발을 하면 할 수 록 문서화의 중요성을 깨닫고 있어서 지금 부터 꼼꼼하게 문서화를 하는 바다가 좋은 습관을 가지고 계신 것 같아요👍

몇 가지 코멘트 남겼으니 읽고 확인 부탁드립니다 ! 

추가적으로 직접 바다의 앱을 실행시켜보면서 발견한 점인 데요 
스크롤을 내리면서 skeleton이 나오다가 영화가 렌더링 될 때 덜커덩(?) 하는 느낌으로 보여지고 있어요 
이 부분이 개선될 수 있으면 좋을 것 같아요 
![case1](https://github.com/woowacourse/javascript-movie-review/assets/60773373/5965623c-9f9c-4425-96ef-4823127e3e6c)

2024-03-30 14:12 UTC, liswktjs commented on src/components/movie/UserScore.ts
> +    const TOTAL_START_LENGTH = 5;
이값은 상수화 해주면 좋을 것 같아요

2024-03-30 14:12 UTC, liswktjs commented on src/components/movie/UserScore.ts
> +    // 변경된 score - 로컬 스토리지에 업데이트
주석 처리 👍👍👍

2024-03-31 04:10 UTC, BadaHertz52 commented on src/styles/header.css
> +  z-index: 1;
동일한 z-index를 사용하는 경우도 생각해봐야 하네요. 조언 감사합니다.😄

2024-03-31 06:05 UTC, BadaHertz52 commented on src/components/movie/MovieListContainer.ts
>      }
✅ 수정완료 😊

ElementFinder라는 컨트롤러를 만들었어요. 
selector를 props로 받아오고 element를 찾은 후,  element가 있으면 제네릭으로 설정한 타입의 element를 반환하고 element가 없을 경우 alert나 alert modal을 화면에 띄워요.

2024-03-31 06:35 UTC, BadaHertz52 commented on src/controller/SearchBoxResponsiveHandler.ts
> +  },
✅ 업데이트 완료 😄

샐리의 조언을 듣고 어떻게 하면 재사용하기 좋은 유틸함수가 될 수 있을지에 대해 생각해봤어요.
위의` isOffClassName`처럼 이미 해당 element에 넣어주어야할 class가 있거나, 제거해야할 class가 없는 상황이라면 클래스 변경을 하지 않아야하는 조건처럼 width외의 부가적인 조건이 있을 수 도 있겠다 싶었어요.
그래서 조건에 따라 클래스를 변경하거나 제거하는 `changeElementClass `유틸함수를 만들어봤어요.

```ts
export interface changingElementClassProps {
  $targetElement: HTMLElement;
  className: string;
  conditionForClass: {
    /**
     * 클래스가 추가되는 조건
     */
    additionCondition: boolean;
    /**
     * 클래스가 제거되는 조건
     */
    removalCondition: boolean;
  };
}

/**
 * 조건에 따라 해당 element의 클래스를 추가 하거나 제거하는 기능
 */
export const changeElementClass = (props: changingElementClassProps) => {
  const { $targetElement, className, conditionForClass } = props;

  if (conditionForClass.additionCondition) {
    $targetElement.classList.add(className);
    return;
  }

  if (conditionForClass.removalCondition) {
    $targetElement.classList.remove(className);
    return;
  }
};
```
`classList.toggle(token, force)`의 force를 사용하는 것과 다른 점은, force는 하나의 조건의 boolean 값에 따라 class를 변경하지만, changeElementClass는 추가와 제거하는 조건이 서로의 참/거짓이 아닌 경우에 유용해요. 
위의 private_changeClassByWindowSize를 살펴보면, 클래스를 더하는 조건인 `width <= MOBILE_WIDTH && !isOffClassName` 의 반대는` width >MOBILE_WIDTH || isOffClassName` 로 클래스를 제거하는 조건인 `width > MOBILE_WIDTH && isOffClassName`와 같지 않아요.

2024-03-31 07:39 UTC, BadaHertz52 commented on src/controller/ScrollObserver.ts
> +class ScrollObserver {
✅ 수정완료 😊

ScrollObserver을 다른 곳에서도 사용할 수 있도록 다음 처럼 변경했어요.

1. ScrollObserver
- props로  callBack을 받는다.
- 인스턴스 생성 시, props로 받은 callBack을 실행하는 IntersectionObserver 옵져버를 만든다.
-   observeTarget($target: Element) 실행 시, 파라미터로 넘어준 타겟을 관찰해 디바운스가 적용된 callBack을 실행한다.

2. MovieList
-  스크롤 시 observer의 타켓이 scroll-observer-target가 보일 때 실행하는 함수(updateMovieData)를 MovieList내에서 관리한다.
-  인스턴스 생성 시,  scroll-observer-target 요소가 있다면 ScrollObeserver 인스턴스를 생성 해  scroll-observer-target에 대한 관찰을 시작한다.
- MovieList에서 생성된 옵져버는  scroll-observer-target가 보이면 callBack함수로 넣어준 updateMovieData를 실행 해 영화 리스트를 업데이트한다.

 ScrollObserver를 사용하는 곳에서 옵져버의 callBack 함수를 관리한다면, 샐리의 의견처럼 ScrollObeserver의 재사용성과 movie 변경 시 옵져버의 callBack도 함께 관리하기에 좋을 것 같아서 위에 처럼 변경했어요.

2024-03-31 08:11 UTC, BadaHertz52 commented on src/components/movie/UserScore.ts
> +    const TOTAL_START_LENGTH = 5;
기존의 상수처럼 constants폴더에서 관리하면 좋을 것 같다는 의미일까요?

제가 이해한 것이 맞다면 해당 부분에 대해서 질문이 있어요.  🙋‍♀️
관리해야하는 상수가 프로젝트의 사이즈와 비례해서 커질텐데 모든 상수들을 constants폴더안에서 관리해야하는 지 고민이 되었어요. 특정 모듈, 특정 함수내에서만 사용한다면 constants폴더가 아닌 해당 모듈/함수에서 관리해도 되지 않을까 생각했어요.

이에 대한 샐리의 의견이 궁금해요.

2024-03-31 08:12 UTC, BadaHertz52 commented on src/components/movie/UserScore.ts
> +    // 변경된 score - 로컬 스토리지에 업데이트
주석도 코드라서 필요없는 주석을 달지 않으려하고 있어요.
하지만 해당 주석이 다른 사람이 보기에도 필요한 지 그렇지 않은 지 판다하는 게  아직은 어려워요.
그래도 이번에 샐리에게 칭찬을 받았으니 잘 하고 있다는 자신감을 얻고 가요.ㅎㅎㅎ 😁

2024-03-31 10:26 UTC, BadaHertz52 commented on src/controller/ModalContainerController.ts
> +const ModalContainerController = {
✅ 수정완료 🙂

component 폴더에서 해당 component에 대한 controller를 넣을 수 있네요!! 오!!! 파일을 만들면서 이거를 어디에 넣어야하는 지 고민됐는데 알려주셔서 고마워요 샐리. 

미션을 하면서 폴더구조를 어떻게 잡아가야하나 고민이 되는데 혹시 샐리가 추천하는 이에 대한 리소스나 공부방식이 있을까요? 🤓

2024-03-31 10:34 UTC, BadaHertz52 commented
안녕하세요. 샐리 

아직은 재사용성을 어떻게 챙겨야하는지 막막한데, 예시를 들어서 설명해주는 샐리의 설명 덕분에 감을 잡아가고 있어요. 감사해요. 👍
그리고 문서화 칭찬도 진짜 감사해요. 🥺💕 
구현하는 것도 바쁜데, 누군가는 필요없다고 생각할 수 있는 문서화에 시간을 뺏기는 것은 아닐까하는 생각을 잠시 했었어요. 그런데 샐리가 칭찬해주시니까 제가 해왔던 대로 문서화 작업을 앞으로도 하려구요. 😄🌟 

샐리의 코멘트에 수정 사항에 대해 코멘트를 달아놨고 궁금한 점에 대해서도 [코멘트](https://github.com/woowacourse/javascript-movie-review/pull/144#discussion_r1545575982)를 남겨놨어요.
추가로 수정한 부분도 있고 새로 발견한 오류들도 고쳤어요.

점점 날씨가 좋아지는데,

2024-03-31 12:42 UTC, BadaHertz52 commented on src/model/LocalStorageHandlerForUserScore.ts
> +class LocalStorageHandlerForUserScore {
로컬 스토리지에 데이터를 저장하고 사용하는 클래스를 재사용할 수 있지 않을까 고민해봤지만 아래의 이유로 해당 클래스는 재사용보다는 사용자의 별점에 대한 클래스로 두기로 했어요.
 
### 재사용하지 않은 이유
- 인스턴스를 생성해, 해당 인스턴스로 scoreData 를 관리한다.
- 관리하려는 데이터에 따라 필요한 메서드나 필드가 달라질 가능성이 높아서 통일된 모듈의 구조를 아직은 잘 모르겠다. (관리해야하는 데이터가 있다면, 이에 대한 모듈을 만들어봐야 공통적으로 필요한 모듈의 구조를 알 수 있을 것 같다.)

2024-03-31 12:51 UTC, BadaHertz52 commented
안녕하세요. 샐리
점점 날씨가 좋아지고 있어요. 주말 잘 보내셨나요? 

저는 충분히 쉬면서 코드를 수정하는 주말을 보냈습니다.😁

수정한 부분에 대해서 설명하기 전에 샐리에게 감사인사부터 하고 싶어요. 
아직은 재사용성을 어떻게 챙겨야하는지 막막한데, 예시를 들어서 설명해주는 샐리의 설명 덕분에 감을 잡아가고 있어요. 감사해요. 👍
그리고 문서화 칭찬도 진짜 감사해요. 🥺💕 
구현하는 것도 바쁜데, 누군가는 필요없다고 생각할 수 있는 문서화에 시간을 뺏기는 것은 아닐까하는 생각을 잠시 했었어요. 그런데 샐리가 칭찬해주시니까 제가 해왔던 대로 문서화 작업을 앞으로도 하려구요. 😄🌟 

샐리의 코멘트에 수정 사항에 대해 코멘트를 달아놨고 궁금한 점에 대해서도 [코멘트](https://github.com/woowacourse/javascript-movie-review/pull/144#discussion_r1545575982)를 남겨놨어요.
추가로 수정한 부분도 있고 새로 발견한 오류들도 고쳤어요.

2024-03-31 12:59 UTC, BadaHertz52 commented on src/controller/ScrollObserver.ts
> +const APIHandlerForScroll = {
✅ 수정완료 😊

2024-04-01 02:32 UTC, liswktjs commented on src/controller/ModalContainerController.ts
> +const ModalContainerController = {
폴더 구조의 경우에는 프로젝트 규모와 다루는 도메인 등등으로 각각의 적합한 구조가 존재합니다! 
그래서 저는 여러 폴더 구조를 공부해보셔서 각 미션 마다 적용해보시고 장단점을 느껴보는 것도 추천드리고 싶어요! 
레벨 2 부터는 리액트를 하실 테니 그에 대비하여 react folder structure 키워드로 검색했을 때 나오는 폴더 구조를 미리 익혀보시는 것도 좋을 것 같아요 

최근에 인기 있는 구조는 fds인데요 
해당 폴더 구조는 규모가 큰 프로젝트에 적합하지만, 
그래도 도움이 될 것 같아서 링크를 공유합니다! 
https://emewjin.github.io/feature-sliced-design/

2024-04-01 02:40 UTC, liswktjs commented on src/utils/ScrollObserver.ts
> +  #callBackFun: () => void | Promise<void>;
👍👍👍

2024-04-01 02:40 UTC, liswktjs commented on src/components/movie/UserScore.ts
> +    const TOTAL_START_LENGTH = 5;
아하 제가 이 값의 경우 상수로 관리하면 좋겠다고 한 것은, 
도메인 정책과 깊게 관련되어 있는 값이여서 제안드린 것이였습니다! 

별점에서 별점의 개수는 기획에 따라 10개도 될 수 있고 하고 있기 때문에 따로 상수로 분리해서 컴포넌트 외부에서 관리하면 좋겠다고 생각했어요! 

따로 분리함으로써, 기획이 바뀔 때 컴포넌트를 따로 찾아갈 필요없이 해당 도메인이 있는 상수에서만 값을 바로 바꿔줄 수 있다고 생각했습니다! 
상단에 따로 분리하는 것도 좋은 것 같아요 하지만 도메인과 깊게 연관된 값들이여서 따로 분리해주는 것도 좋을 것 같아요!

2024-04-01 02:43 UTC, liswktjs commented on src/components/movie/UserScore.ts
> +    // 변경된 score - 로컬 스토리지에 업데이트
아하 저는 주석 다는  것 진~~~~짜 필요하다고 생각합니다
그래서 저 또한 회사 코드에서 주석으로 이게 어떤 의미인지 특히 기획과 직접적으로 닿아 있는 (즉 도메인과 연관이 깊은 것) 기능 인 경우에는 주석을 무조건 답니다 
물론 불필요하게 세세하게 주석을 달 필요도 없긴 하지만 바다의 현재 주석은 제가 볼 때는 적절해보여요! 

지금부터 좋은 습관을 가지고 계신 것 같아요 👍
현업에 오면 과거의 자신의 코드도 모를 수 있고 
다른 사람들이 만들어온 코드들을 이어 받아서 기능을 개발해야할 때가 있는데요 
이때 코드 단에서 문서화가 되어 있으면 정~~말 유지보수가 쉬워집니다

2024-04-01 02:56 UTC, liswktjs approved these changes
안녕하세요 바다 🐳
레벨 1 수고 많으셨습니다 👏👏👏

코멘트 내용들을 다 잘 반영해주셔서 이만 머지를 해도 좋을 것 같아요! 
추가로 바다가 질문해주신 내용들은 코멘트로 답변을 달았습니다! 한 번 확인해주세요 

이제 시작될 방학(?) 푹 쉬시고 레벨 2 리액트도 열심히 달려갈 바다 기대하고 있겠습니다 😎
레벨 2에서 또 다시 만나요 🎉 👋

2024-04-01 02:56 UTC, liswktjs commented on src/components/modal/ModalContainer.ts
> +      console.log('delete');
불필요한 console은 지우면 좋을 것 같아요!

2024-04-01 02:56 UTC, merged

2024-04-01 03:06 UTC, BadaHertz52 commented on src/components/modal/ModalContainer.ts
> +      console.log('delete');
오류 잡으면서 넣어둔 콘솔이 있었네요!!! 머지 되었지만 해당 부분 수정하겠습니다