[2단계 - 상세 정보 & UI/UX 개선하기] 낙타(송재석) 미션 제출합니다.
woowacourse/javascript-movie-review pull request #149
Opened 2024-03-31 14:33 UTC by Largopie

안녕하세요 하루 잘 지내셨나요!☺️
낙타🐫입니다. 먼저, step1에서 사소한 부분도 세세하게 리뷰해주셔서 무한히 감사드립니다!

## 배포 주소

[https://largopie.github.io/javascript-movie-review](https://largopie.github.io/javascript-movie-review/)

저번에 실행 방법도 같이 기재했었는데, 생각해보니 `.env`파일이 없으면 실행이 안되어서 배포한 주소만 올리도록 하겠습니다!

이번에 추가 구현한 사항은 크게 3가지 입니다.

- **영화 상세정보 조회**
- **무한 스크롤 구현**
- **별점 매기기**
- **UI/UX 개선하기**

각 구현 사항에 대해 간단하게 설명드리겠습니다.

### 📜 영화 상세 정보 조회

`Modal`을 사용하여 영화 정보를 조회할 수 있도록 구현했습니다. `Modal` 내부에 데이터를 불러와서 저장해야했기 때문에, 처음 데이터를 불러올 때는 로딩 화면임을 나타내기 위해 **Skeleton UI**가 나올 수 있도록 구현했습니다. 같은 영화 정보를 불러올 때마다 api를 여러 번 호출하는 것을 방지하기 위해 처음 불러온 영화 상세 정보는 `LocalStorage`에 저장하도록 했습니다.

### ♾️ 무한 스크롤 구현

많은 스크롤이 일어나는 것을 방지하기 위해 `throttle`을 이용해 무한 스크롤을 구현했습니다. 찾아본 결과 `Intersection Observer`로 구현하는 방법도 있었지만, 조금 더 정확히 알고 난 후에 기술을 도입해보고 싶어 `throttle`을 사용해 도입하게 되었습니다. `Intersection Observer`를 이용한 무한스크롤은 리뷰를 받고 난 이후나 레벨1이 끝나고 난 방학때 추가로 구현해보고 싶습니다.

### ⭐️ 별점 매기기

별점 값은 `LocalStorage`에 저장한 영화 정보에 `my_grade`라는 키를 추가해, 해당 점수를 클릭했을 때, LocalStorage에 `my_grade`가 업데이트 되도록 구현했습니다. 따라서 리뷰한 점수가 저장, 갱신될 수 있도록 구현했습니다.

### 🌌 UI/UX 개선

- **반응형 구현**

`mobile`, `tablet`, `desktop`에 대응될 수 있도록 반응형 UI로 구현했습니다.

- **TOP 버튼**

스크롤이 많이 내려갔을 때 한 번에 최상위로 올라올 수 있도록 우측 하단에 TOP버튼을 배치했습니다.

- **영화 hover**

영화에 마우스를 올렸을 때 요소를 더욱 잘 파악할 수 있도록 **그림자 및 포스터 움직임 효과**를 주었습니다.

## 🤔 어려웠던 점

### 📲 헤더 모바일 화면 구현에 대한 어려움

![Untitled](https://github.com/woowacourse/javascript-movie-review/assets/106071687/90a782ac-65ab-4c97-8eed-4113000babdf)

모바일 화면이 되었을 때 header에 있는 searchButton을 구현하는데 어려움이 있었습니다.

기존에 `mouseout`, `mouseover` 이벤트를 이용해서 구현하였으나 여러 이슈가 있어 `click`이벤트로 수정하게 되었습니다. `click`이벤트를 **서치박스의 width크기를 기준**으로 이벤트를 분기하여 구현했습니다. 이 방법 외에도 다른 좋은 방법이 있을까요?

### ⚠️ 에러 처리

[해당 커밋]기존에 추상화를 위해 Fetcher, Movies를 분리하여 구현한 부분에 의문점이 있었습니다. 에러처리를 `response.ok`를 통해 처리하게 되었는데, 서버 측에서 받아온 `response.json()`를 바탕으로 `Fetcher`클래스 내부에서 에러처리를 진행했습니다.

하지만 서버 측에서 받아온 `response`는 `Movies` 클래스의 책임이라는 생각이 들어 기존의 에러 처리 로직을 `Movies`클래스 로 옮긴 후 static 메서드로 구현하게 되었습니다.

추가적으로 고민을 더 해보았는데, 나중에 `Fetcher`클래스를 범용적으로 사용하기 위해 적절하지 않다는 생각이 들었습니다. 예를 들어 장바구니 기능이 추가됐다는 가정을 해봤을 때, 해당 `Fetcher`를 이용하게 된다면 에러 처리 로직이 `Movies`에 의존되어 있다는 생각이 들었습니다. 이에 대한 고민이 완벽하게 끝나지 않았지만, 추가적으로 고민해보고 수정해보도록 하겠습니다.

하루가 남겨주신 리뷰를 바탕으로 추가적인 고민을 더 해보겠습니다! 잘 부탁드리겠습니다 :) 🙇‍♂️

2024-04-01 12:27 UTC, 365kim commented
오 너무 완성도 높게 잘만들어주셨네요 👍

https://github.com/woowacourse/javascript-movie-review/assets/60066472/bf552a60-e62b-471a-a023-3f71f36e9e48

2024-04-01 12:28 UTC, 365kim commented on src/components/MovieItem/movie-item.css
> +}
오 너무 완성도 높게 잘만들어주셨네요 👍

https://github.com/woowacourse/javascript-movie-review/assets/60066472/bf552a60-e62b-471a-a023-3f71f36e9e48

2024-04-01 12:29 UTC, 365kim commented on src/MovieApp.ts
> +    gradeText.textContent = STAR_MESSAGE[grade];
호버만해도 레이블 미리 볼 수 있는 것 너무 좋네요 👍

https://github.com/woowacourse/javascript-movie-review/assets/60066472/dc27a86b-6eda-49e7-b50c-35d89aa31925

2024-04-01 12:34 UTC, 365kim commented on src/MovieApp.ts
> +  #onStarHover(event: Event) {
`#onStarClick`, `#onStarHover`를 MovieApp 이 아닌 Star 컴포넌트에서 정의해볼 수 있을까요?

비유를 해보면..
지금은 마치 송파구 루터회관 14F에서 일어나는 일(구체적인 일)을 서울시청(총괄하는 역할)에서 관리하는 느낌이 듭니다.

꼭 MovieApp.ts에서 관리해야할 이유가 있는 것이 아니라면 star와 관련된 로직은 Star 컴포넌트에서 관리할 수 있으면 좋겠습니다.

2024-04-01 12:43 UTC, 365kim commented on src/components/TopButton/TopButton.ts
> +const TopButton = () => {
사용성 고려 대박 👏

![Screenshot 2024-04-01 at 9 41 41 PM](https://github.com/woowacourse/javascript-movie-review/assets/60066472/3f22ef39-11f6-4263-9b9c-e92761d26b8e)

2024-04-01 12:43 UTC, 365kim commented on src/components/TopButton/TopButton.ts
> +const TopButton = () => {
참고: 지금은 항상 노출하고 있는데 scroll을 하나도 내리지 않았을 때는 0일 때는 숨겨주는 방법도 있습니다.

2024-04-01 12:48 UTC, 365kim commented on src/components/Alert/Alert.ts
> +    alert.remove();
https://github.com/woowacourse/javascript-movie-review/assets/60066472/d7a4794a-1353-4414-9a39-4d3548c5a84f

지금의 구조는 DOM에 복수의 Alert가 삽입될 수 있는 구조로 보여요.

의도하신 게 아니라면, 최초에 Alert 컴포넌트를 1개만 렌더링 시켜두고 원래처럼 className을 조작하는 방식은 어떨까요?

2024-04-01 12:50 UTC, 365kim commented on templates/common.css
> +  --grey-2: #f1f1f1;
👍

2024-04-01 13:01 UTC, 365kim commented on src/components/SearchBox/search-box.css
> +  }
사소한데, 반응형 동작도 엄연한 기능이니, chore/refactor 커밋보다는 feat 커밋이 적합해보여요.

2024-04-01 13:11 UTC, 365kim commented on src/controller/MovieRenderController.ts
> +  #infinityScroll() {
함수인 만큼 동사원형으로 시작하도록 이름을 지어주셔도 좋겠습니다.

2024-04-01 13:12 UTC, 365kim commented on src/controller/MovieRenderController.ts
> +    if (presentHeight / documentHeight > RULES.arriveScrollPercentage) {
`RULES.arriveScrollPercentage` 이 상수는 도메인 룰 상수에서 묶어서 관리하기보다, 그냥 이 모듈 안에서 상수로 선언해서 관리해도 좋을 것 같아요 :) (제게는 기존의 RULES 내부에 있는 상수들과 조금 결이 다르게 느껴졌어요.)

2024-04-01 13:17 UTC, 365kim commented on src/controller/MovieRenderController.ts
> +    }
스크롤 이벤트 핸들러를 반복해서 add 했다가 다시 remove 하고 있는 것으로 확인했어요.

add는 한번만 해두고 내부 로직에 따라 동작을 결정하는 방법도 가능할까요?

2024-04-01 13:18 UTC, 365kim commented on src/controller/MovieRenderController.ts
> +  }
> 찾아본 결과 Intersection Observer로 구현하는 방법도 있었지만, 조금 더 정확히 알고 난 후에 기술을 도입해보고 싶어 throttle을 사용해 도입하게 되었습니다.

낙타가 생각하시기에 각각의 방법은 어떤 차이가 있나요?

2024-04-01 13:21 UTC, 365kim commented on src/components/SearchBox/SearchBox.ts
> +  searchButton.addEventListener('click', (event: MouseEvent) => {
> 기존에 mouseout, mouseover 이벤트를 이용해서 구현하였으나 여러 이슈가 있어 click이벤트로 수정하게 되었습니다.

(단순 궁금) 어떤 이슈가 있었나요?

2024-04-01 13:24 UTC, 365kim commented on src/components/SearchBox/SearchBox.ts
> +    if (searchBox.clientWidth < RULES.searchBoxWidth) {
`searchBox.clientWidth < RULES.searchBoxWidth`이 의미가 searchBox가 현재 접혀있다는 의미인가요?

2024-04-01 13:30 UTC, 365kim commented on src/components/SearchBox/SearchBox.ts
> +    const searchBox = $('.search-box') as HTMLInputElement;
`e.currentTarget.closest('.search-box')`로도 얻어낼 수 있을 것 같아요

2024-04-01 13:30 UTC, 365kim commented on src/components/SearchBox/SearchBox.ts
> +    const searchBox = $('.search-box') as HTMLInputElement;
(box는 div인데 잘못 타이핑된 것 같아요)

2024-04-01 13:34 UTC, 365kim commented on src/components/SearchBox/SearchBox.ts
> +      title.classList.add('visibility-hidden', 'prevent-pointer-event');
> click이벤트를 서치박스의 width크기를 기준으로 이벤트를 분기하여 구현했습니다. 이 방법 외에도 다른 좋은 방법이 있을까요?

CSS만으로 엘리먼트의 크기를 알아내기 어려워 낙타가 해주신 것처럼 자바스크립트로 크기를 알아내는 경우도 왕왕있습니다. 제게는 지금의 방식도 좋아보여요. 

제가 코드를 작성한다면 접힌 상태를 나타내는 클래스 이름을 header에 추가/삭제하는 것만 자바스크립트로 제어하고, 나머지는 CSS로 제어하는 방식을 고려해볼 것 같아요.

```css
header.shrinked {
  .title {
    visibility: hidden;
  }
  .search-box {
    width: 320px;
  }
}

2024-04-01 13:38 UTC, 365kim commented on src/api/Fetcher.ts
> +    if (!response.ok) await Movies.handleErrorResponse(response);
> 하지만 서버 측에서 받아온 response는 Movies 클래스의 책임이라는 생각이 들어 기존의 에러 처리 로직을 Movies클래스 로 옮긴 후 static 메서드로 구현하게 되었습니다.

Fetcher 클래스에서 Movies 라는 도메인을 알고 있는 이상, 낙타의 말씀처럼 범용적으로 사용하기는 어려워 보입니다.

Fetcher 클래스에서 다시 도메인 의존적인 코드를 제거하는 방향은 어떠세요?

> 하지만 서버 측에서 받아온 response는 Movies 클래스의 책임이라는 생각이 들어 기존의 에러 처리 로직을 Movies클래스 로 옮긴 후 static 메서드로 구현하게 되었습니다.

낙타가 response를 Movies 클래스의 책임이라고 생각해주신 이유를 들어보고 싶습니다 :)

2024-04-01 13:44 UTC, 365kim commented on src/components/ModalWrapper/modal-wrapper.css
> +  }
breakpoint가 1px이라도 변경되면 코드 변경점이 너무 많아질 것 같아요. 이것도 CSS 변수로 만들어서 관리해볼 수 있을까요?

```css
max-width: var(--mobile-width)
```

2024-04-01 13:47 UTC, 365kim requested changes
안녕하세요 낙타~! 🐪
2단계 작업해주신 것 잘봤습니다. 👏👏👏

짧은 시간 동안 앱 사용자의 편의를 위해 다양한 고민과 구현을 해주시고, 또 반응형까지 유려하게 구현해주신 것으로 확인했어요. 특히 UX/UI 작업을 너무 멋지게 해주셔서, 리뷰하는 내내 즐거웠습니다. 😄

질문도 적극적으로 남겨주셔서 감사해요. 👍
답변 포함해서 코멘트 남겨두었는데 천천히 살펴보시고 반영 완료되시면 리뷰 재요청 부탁드릴게요:)

2024-04-03 08:45 UTC, Largopie reviewed
안녕하세요 하루!! 리뷰와 함께 많은 칭찬도 같이 해주셔서 영광이고 감사드립니다 😊😊

하루가 남겨주신 리뷰 외에도 이것 저것 추가한 사항이 몇 가지 있습니다.
### 1️⃣ 별점 mouseout 시, 저장되어 있는 별점 불러오기
기존에 mouseout 되었을 때는 커서에 올려놓은 별점 그대로 남아있는 부분이 아쉬웠습니다.
그래서 mouseout 되었을 때 저장되어있는 별점을 불러와서 바로 반영되도록 수정했습니다.

### 2️⃣ Modal 닫기 버튼 hover 디자인 추가
Modal 닫기 버튼에 커서를 올렸을 때, 식별하기 편하도록 디자인을 추가했습니다.

### 3️⃣ Modal이 열려있는 상태에서 스크롤되지 않도록 구현
`overflow: hidden`속성을 이용해서 Modal이 열려있는 상태에서 스크롤이 작동하지 않도록 구현햇습니다.

### 4️⃣ 리뷰남겨주신 내용 반영 사항

1. ESC keydown 시 모달 창 닫히도록 구현
2. TOP 버튼 최상위에 있을 때는 보이지 않도록 수정
3. MovieDetailModal 컴포넌트 클래스로 수정

이 외에도 궁금한 사항들은 리뷰로 남겨두었으니, 확인해주시면 감사드리겠습니다 🙇‍♂️

2024-04-03 08:45 UTC, Largopie commented on src/controller/MovieRenderController.ts
> +    }
이 부분은 하루의 의견을 듣고 반영하고 싶습니다!

기존에 이벤트 핸들러를 add, remove 하지 않게 설정했을 때, 인터넷 속도가 빠르다면 보통 문제가 되지 않았습니다.
하지만 인터넷 속도가 느려졌을 때 가령 `'더 보기' 버튼`을 연속적으로 클릭했을 때 비동기 처리가 되지 않은 상태에서 한 번 더 메서드를 불러오다 보니, page값이 증가되지 않은 상태로 같은 페이지의 데이터를 불러왔습니다.

또한, 무한스크롤도 마찬가지로 빠르게 스크롤을 내렸을 때 같은 페이지의 데이터를 여러 번 가져오는 문제를 발견했었습니다.
이를 해결하기 위해서 일시적으로 이벤트를 막을 방법을 생각해보았으나, 이벤트를 삭제/추가해주는 방법 외에는 다른 방법은 찾지 못한 상태입니다.. 🥲 (정확히는, 아직 addEvent, removeEvent보다 직관적인 코드를 찾지 못했습니다..)

([에어비앤비](https://www.airbnb.co.kr)같은 경우도 마찬가지로 데이터가 불러와지기 전까지, 스크롤이 바닥에 있어도 동작하지 않더라구요!)

마지막으로, 이벤트 핸들러를 반복해서 add ,remove하면 발생되는 문제점에 대해서 정확히 이해하지 못한 것 같습니다.

결론적으로 궁금한 점은
**1. 이벤트 핸들러를 반복해서 add ,remove하면 발생되는 문제점이 무엇인지 궁금합니다.**
메모리 누수의 관점으로 봐야할까요?

**2. _"add는 한번만 해두고 내부 로직에 따라 동작을 결정하는 방법도 가능할까요?"_ 에 대한 방법을 정확히 아직 모르겠습니다😭**
더 개선할 수 있는 코드라면 바로 반영하고 싶은 마음인데, 하루가 생각하시는 부분에 대한 힌트를 받고싶은 마음입니다!

2024-04-03 15:51 UTC, 365kim commented on src/api/Fetcher.ts
> +    if (!response.ok) await Movies.handleErrorResponse(response);
> 저는 여기에서 보내주는 status_message를 이용해 에러 메시지를 구성하고 싶었습니다. 그렇기 때문에 해당 resoponse에서 보내주는 에러 메시지가 Fetcher의 책임이 아니라 Movies의 책임이라고 생각했습니다.

에러 메시지를 가공하는 것이 `Movies`의 책임이어야 한다는 부분에서 아직 잘 설득이 되지 않은 것 같아요... 조금 더 부연 설명해주실 수 있을까요? (Movies의 역할이 ~이기 때문에, 거기에 에러 메시지 가공이 포함된다.)

더불어 낙타가 생각하시는 `Fetcher`의 책임도 공유해주시면 좋을 것 같습니다.

2024-04-03 15:54 UTC, 365kim commented on src/components/ModalWrapper/modal-wrapper.css
> +  }
앗 죄송합니다 😢 아하 scss에 너무 익숙해져서 css에서 지원안되는 거라고 상상도 못했네요...

2024-04-03 15:55 UTC, 365kim commented on src/components/ModalWrapper/modal-wrapper.css
> +  }
모아서 사용하는 것도 좋은데, 경험상 하나의 클래스의 동작끼리 모아보는 게 조금 더 편하더라고요. 그래서 원래 작성해주신 방식도 좋다고 생각합니다 :)

2024-04-03 16:05 UTC, 365kim commented on src/controller/MovieDetailController.ts
> +    this.#storage.setItem('movieDetails', JSON.stringify(movieDetails));
아하 저는 캐싱을 반대한 것이 아닙니다. 고려해주셔서 너무 좋다고 생각합니다. 

다만 `LocalStorage` 라는 저장소의 용량에 대해서도 생각해보면 좋겠다는 취지로 말씀드렸어요. 예를 들어 헤비유저여서 5,000개의 영화를 열람했다면, 그 후부터 저장이 안되는 상황이 벌어질지, 그 때 정말 중요한 다른 키값을 로컬스토리지에 저장을 시도했다가 실패하게 될지.. 그런... 저장소의 용량에 대한 고민이었습니다. 

캐시 전략은 레벨2에 가서도 계속 고민해주셔도 좋겠습니다 👍

2024-04-03 16:12 UTC, 365kim commented on src/controller/MovieRenderController.ts
> +    }
> 1. 이벤트 핸들러를 반복해서 add ,remove하면 발생되는 문제점이 무엇인지 궁금합니다.

remove만 잘된다면 메모리 누수 문제는 괜찮을 것 같아요. 다만 성능 저하 이슈와 더불어 (제가 코멘트를 드리게 된 이유인...) 코드 흐름에 복잡성이 추가된다는 점이 있겠습니다. 

> 2. "add는 한번만 해두고 내부 로직에 따라 동작을 결정하는 방법도 가능할까요?" 에 대한 방법

스크롤 이벤트 핸들러를 이미 호출해서 요청을 보내고 있는 중이라면 그것을 구분하는 플래그(boolean 변수)로 컨트롤해보면 어떨까 싶어요.

2024-04-03 16:14 UTC, 365kim commented on src/controller/MovieRenderController.ts
> +    }
요기 비스무리한 의도의 설명인 것 같아 첨부해봅니당

- 참고: https://dmswl98-dev.tistory.com/entry/Vanilla-Javascript-%EB%AC%B4%ED%95%9C-%EC%8A%A4%ED%81%AC%EB%A1%A4infinite-scroll-%EA%B5%AC%ED%98%84%ED%95%98%EA%B8%B0#%F0%9F%93%A3%20isLoading%EC%9D%98%20%EC%83%81%ED%83%9C%20%EC%A1%B4%EC%9E%AC%20%EC%9D%B4%EC%9C%A0-1

2024-04-03 16:17 UTC, 365kim commented on src/components/SearchBox/SearchBox.ts
> +  searchButton.addEventListener('click', (event: MouseEvent) => {
친절한 설명 감사합니다 낙타 👍 `mouse-*`이벤트와 더불어 `pointer-*`이벤트, `touch-*`이벤트도 함께 살펴보셔도 좋겠습니다 :)

2024-04-03 16:24 UTC, 365kim commented
정말.. 명작이네요 👍


https://github.com/woowacourse/javascript-movie-review/assets/60066472/71ae3465-d277-4425-8c3c-2135fd0fc1aa

2024-04-04 00:41 UTC, 365kim approved these changes
![1ec915eb76dcff7edf9e5c195b70363f](https://github.com/woowacourse/javascript-movie-review/assets/60066472/29a10d30-bd18-4e39-81a9-637c4fb262b0)

낙타, 영화리뷰 미션 2단계 완료 축하드립니다 🥳

질문도 적극적으로 해주시고 피드백도 적극적으로 반영해주셔서 너무 감사합니다 :) 감동의 탑버튼에 마우스 인터랙션까지... 너무 멋진 앱이 완성되었어요. 레벨3에서 낙타의 프로젝트가 기대되네요 🥰

혹시나 코멘트 중 궁금한 점이 남아있다면 슬랙으로 편하게 질문해주세요 :)

남은 기간과 방학동안 충전 잘 하시길 바라요. 레벨1 고생하셨습니다 👏👏👏

2024-04-04 00:41 UTC, merged

2024-04-04 06:07 UTC, Largopie commented on src/api/Fetcher.ts
> +    if (!response.ok) await Movies.handleErrorResponse(response);
### 🎬 Movies 클래스의 역할

- `TMDB API`가 `Netfilx API`로 변경될 수도 있다는 가능성을 염두해두고 추상화

저는 `Movies`의 역할은 영화 API와 관련된 것을 처리하는 역할이라고 생각했습니다. 영화와 관련된 데이터를 `Fetcher`를 통해서 받아오고, 이를 가공해서 UI로 보내주는 역할이 될 수 있겠네요. 즉, 서버에서 받아온 데이터를 가공할 책임이 `Movies`에 있다고 생각했습니다. 위의 에러 에러 이미지와 같이 클라이언트 측에서 발생한 오류(400, 401)등은 **서버의 API에서 받아온 `response`** 입니다.

따라서 저는 서버 측에서 보내준 `status_message` 역시 `서버에서 받아온 데이터를 가공할 책임`이라고 생각했고, 이를 `Movies`에서 처리하는 것이 옳다고 생각했습니다.

### 💽 Fetcher 클래스의 역할

- `fetch`가 `axios`로 대체될 수 있다는 가능성을 염두해두고 추상화

더불어 `Fetcher`를 추상화한 이유는 `fetch`라이브러리가 추후에 `axios`로 변경될 수도 있다는 가능성을 염두하고 진행한 추상화였습니다. 따라서 `Fetcher`에서는 해당 라이브러리를 이용해 데이터를 연결하는 역할을 한다고 생각했습니다. `CRUD`가 해당될 수 있겠네요!

여기서 저는 일반적으로 `response.ok`를 통해서 에러 처리를 한다고 생각했습니다. 하지만 서버 측에서 받아온 `response.json()`을 `if(!response.ok)` 내부 로직에 사용하기엔 적합하지 않다고 생각했고, 이를 `Movies`로 옮기게 되었습니다.

결론적으로 말하면, 서버 측에서 보내준 에러 메시지(`status_message`)를 사용하기 위해서는 에러 가공을 Movies에서 에러를 처리하는 것이 맞다라고 생각했습니다.

적절한 설명이 되었을 지 모르겠네요 ㅎㅎ...🤣 혹시나 더 궁금하신 사항 있으면 코멘트 남겨주시면 감사하겠습니다