[1단계 - 영화 목록 불러오기] 애슐리(허서영) 미션 제출합니다.
woowacourse/javascript-movie-review pull request #15
Opened 2023-03-16 08:26 UTC by ashleysyheo

작성중

2023-03-16 13:02 UTC, woowahan-cron commented
여러 OTT 서비스를 이용하면서 사용성에 대해 고민을 많이 해본 만큼 애슐리의 앱에서는 편리함이 돋보일 것 같습니다 (기대 기대)
리뷰는 리뷰어님이 해주실 거니까 마지막까지 파이팅~

2023-03-17 10:50 UTC, ashleysyheo commented
> 여러 OTT 서비스를 이용하면서 사용성에 대해 고민을 많이 해본 만큼 애슐리의 앱에서는 편리함이 돋보일 것 같습니다 (기대 기대) 리뷰는 리뷰어님이 해주실 거니까 마지막까지 파이팅~

앗.....ㅋㅋㅋ 이제부터 사용성을 조금 더 고민한 앱으로 만들어보겠습니다!

2023-03-18 11:28 UTC, bigsaigon333 requested changes
애슐리 안녕하세요~ 리뷰가 늦어져서 죄송해요 😭 

 영화 목록 불러오기 미션 1단계 구현 고생하셨습니다!
 
 깔끔하게 코드를 잘 작성해주셨네요 👍🏻 
 
 특별히 크게 말씀드릴 부분이 없는거 같아요!
 
 각 코드에 코멘트 남겼으니 확인 부탁드립니다 😄 


---

> 이전 미션에서는 App에서 도메인이랑 UI 로직을 연경하기 위해서 콜백을 넘겨줬는데, 그렇게 하니까 기능이 많아질수록 App이 방대해지고, 가독성이 떨어진다는 느낌이 들었습니다. 그래서 이번에는 도메인인 MovieList를 싱글톤으로 export 하고, 그 인스턴스를 컴포넌트에서 직접 사용하는 방식으로 구현해 봤습니다. 이 부분에 대해서 동동은 어떻게 생각하시는지 궁급합니다.

잘 구현하셨네요 👍🏻👍🏻

콜백함수가 많아지면 흐름을 쫓아가기가 어렵죠.. 언제 어떤 순서로 호출되는지 파악하기가 어렵고..

애슐리가 전에 느꼈던 단점이 이번에는 많이 해소가 되었다고 느껴지셨나요? 

그렇게 느껴지신다면 좋은 구현이라고 생각합니다 😄 




> cypress에서 데이터를 mocking한 다음에 테스트를 하려고 했습니다. 그런데 테스트 중에도 계속 리렌더링이 일어나고, 끝난 후에도 리렌더링이 일어나는 문제가 발생했습니다. 일단, 검색을 통해서 API 모킹을 해보려고 했는데, 제대로 한 것인지 잘 모르겠습니다. 이렇게 하는 게 맞는 건가요…?

방법자체는 맞는거 같은데요, intercept가 제대로 안되고 있는거 같네요? 

(실제로 api가 쏴줘서 network탭에 뜨고 있고, apiKey도 제대로 안불러와진  모양이에요)

![image](https://user-images.githubusercontent.com/31029000/226101278-d984b02f-1c7c-4484-befe-738e8dddd368.png)




> 좋은 컴포넌트 설계에 대한 동동의 의견이 궁금합니다. 이번 미션에서 컴포넌트를 나누어보려고 했는데 재사용성이 크지 않다고 느껴집니다. 그리고 서로 의존적인 경향이 없지 않다는 느낌도 듭니다… 그런데 뭔가 서로가 서로 연관이 되어있는데, 이 부분을 어떻게 해결하는 것이 좋은지 모르겠습니다. 전에는 App에서 중안 관리자의 역할을 하면서 콜백에서 도메인이랑 서로 다른 컴포넌트들을 연결해 줬는데, 이번에는 그런 역할을 하는 부분이 없어서 이렇게 구현하게 된 것 같습니다.

서로가 서로를 알고 있다는게 의존성이 있다는 얘기죠 ㅎㅎ
그럼 서로가 서로를 왜 알아야 할까요? 

- MovieListContainer는 왜 MovieListContent를 알아야 할까요? 
- MovieListContent는 왜 MovieItem을 알아야 할까요? 

다 각각의 이유가 있을거에요. 근데 그 이유를 다시 한번 고민해보는 것도 좋은 방법이에요.
A메소드 때문에 B와 C가 서로를 아는데, A메소드가 정말 이 위치에 선언될 필요가 있을까? 와 같이 말이에요.

근데 그렇게 하더라도, DOM 요소 때문에 의존성을 끊는데 한계가 있을거라고 생각해요. 
그런 한계를 **나중에** 프레임워크에서는 어떻게 극복하는지 찾아보면 좋을거 같아요~


그리고 제 개인적인 생각이지만, 바닐라JS에서 너무 완벽한 설계에 집착할 필요는 없다고 생각해요.
설계가 중요하지 않다는게 아니라, 그 결과물이 완벽할 필요는 없다는 뜻이에요.
고민을 많이 하는게 중요하고, 완벽한걸 찾지 못하거나 구현하지 못해도, 앞으로 나아가는게 중요하다고 생각합니다. 그러면서 JS 문법을 더 깊게 공부하는게 설계 그 이상으로 중요하다고 생각합니다 😄 


저는 지금 설계가 좋고, 코드도 깔끔하게 잘 짜신거 같아요. 
2단계 요구사항을 반영할 때 큰 변화가 없다면, 좋은 설계를 하신 거라고 자신을 가지셔도 돼요 👍🏻 👍🏻 


2023-03-18 11:28 UTC, bigsaigon333 commented on src/components/MovieListContent.ts
> +  },
```suggestion
  async loadMovies() {
    $<HTMLButtonElement>('#more-button').classList.remove('hide');
    this.clear();
    this.loadMoreMovies();
  },
```

(제안)  자주 `MovieListContent`가 반복되는데, 계속 import 해온 모듈인가? 하면서 코드를 읽게 되네요 ㅠㅠ
 
 위와 같이 하거나 class를 써보는건 어떨까요? (ES6+ 니까!!)
 
 아니면 반대로 왜 이렇게 코드를 작성하는게 좋다고 생각하셨는지 애슐리의 생각을 들려주세요!

2023-03-18 11:28 UTC, bigsaigon333 commented on src/components/MovieListContent.ts
> +    }
error가 HTTPError가 아니면, 슬그머니 무시하는게 좋은걸까요?!

2023-03-19 13:37 UTC, ashleysyheo commented on src/types/movie.ts
오😃 이렇게 하는지 몰랐어요!! 알려주셔서 감사합니다!

snake_case를 camelCase로 변경해 주는 유틸 함수를 만들고, `movieAPI`에서 전체 프로퍼티 키들을 변경해 주도록 했습니다.

수정 커밋: https://github.com/woowacourse/javascript-movie-review/pull/15/commits/0a8ae6cbdb1318b54f39e9af2e2f6655eb379ea9, https://github.com/woowacourse/javascript-movie-review/pull/15/commits/e678afc50f5805e07f6add9571cc155bac57632e

2023-03-19 13:43 UTC, ashleysyheo commented on src/App.ts
> +    MovieListContainer.onClick();
네이밍이 제일 어려운거 같아요🥲 

저도 네이밍이 살짝 어색한 거 같아서 바꿔야겠다 했었습니다! 처음에는 제네릭 하게 `addEvent`로 할까 했다가, `addEventToMoreButton`, `addEventToSearchInput`처럼 좀 더 구체적으로 이름을 변경해 봤습니다. 이벤트 리스너 관련 메서드 이름 짓는 게 매번 어렵고 어색한데 혹시 동동만의 팁이 있나요?

수정 커밋: https://github.com/woowacourse/javascript-movie-review/pull/15/commits/1db25a3d9e4b36f69afda0b2eda6adf0dbd03da6

2023-03-19 13:44 UTC, ashleysyheo commented on src/components/NavBar.ts
> +    $<HTMLFormElement>('.search-box').addEventListener('submit', async (event: Event) => {
알려주셔서 감사합니다!

수정 커밋: https://github.com/woowacourse/javascript-movie-review/pull/15/commits/19f0d065fb651e637f7bf39319773419e48227db

2023-03-19 13:49 UTC, ashleysyheo commented on src/api/movieAPI.ts
> +  const movieData: MovieDataType = await response.json();
이 부분에 대해서 생각해 본 적이 없었는데, 찾아보니까 서버에서 항상 JSON 응답이 온다는 보장이 없더라고요! 그래서 만약 응답이 JSON format이 아니면 `response.json()`이 에러를 던진다는 것을 알게 되었습니다.

그래서 `await response.json()`을 하기 전에 `Content-Type`이 없거나 JSON이 아닐 경우 에러를 던지도록 했습니다.

수정 커밋: https://github.com/woowacourse/javascript-movie-review/pull/15/commits/29c4987f38437beec8b184dfc043e81a26010caa

2023-03-19 13:54 UTC, ashleysyheo commented on src/api/movieAPI.ts
`fetchAPI`함수를 따로 만들어 봤습니다! 이렇게 하니까 반복적인 부분을 줄일 수 있고, 여기서 어떤 HTTP 에러를 던져 줄지 결정할 수 있어서 더 깔끔해진 것 같습니다. 

마찬가지로 `generateURL`이라는 함수를 만들어서 쿼리 파람을 조금 더 깔끔하게 넣고 중복을 없애보고자 했습니다! 

수정 커밋: https://github.com/woowacourse/javascript-movie-review/pull/15/commits/f987a1e36bab379bb349c765d306f83f5bb7ec03, https://github.com/woowacourse/javascript-movie-review/pull/15/commits/2b81443ef91808bbf61194ff338575160da46fd3

2023-03-19 13:58 UTC, ashleysyheo commented on src/components/InvalidMessage.ts
> +export default InvalidMessage;
처음에 `renderErrorMessage`와 `renderNoSearchMessage`를 `InvalidMessage`에 둔 이유는 같거나 비슷한 역할을 하는 메서드들을 묶으면 필요한 정보, 메서드를 한 번에 찾고, 좀 더 넓은 범위로 뭘 하는지 알기 더 편할 것이라고 생각해서입니다. 각각 함수로 만들어서 export 하는 것도 고려해 봤지만, 개인적으로는 뭔가 포괄적으로 이 둘을 정의하는 무언가가 있는 게 더 이해하기 쉬워서 이렇게 했습니다!

2023-03-19 14:05 UTC, ashleysyheo commented on src/components/MovieListContent.ts
> +    }
안 좋겠죠...하하 😅

위에 코드를 적을 때는 일단 예상 가능한 에러들에 대해서 화면에 좀 더 유저 프렌들리하게 보여주는 것만 생각해서 HTTPError에 대해서만 처리를 했습니다. 

리팩토링하면서, 위의 서버 응답 JSON에러에 대한 처리는 기존과 같게 하고 기타 에러는 `alert`로 처리했습니다. 
```javascript
if (error instanceof HTTPError) {
  this.render(HTTP_ERROR_CODE[error.statusCode]);
  return;
}

if (error.message === INVALID_JSON_RESPONSE) {
  this.render(INVALID_JSON_RESPONSE);
  return;
}

alert(error.message);
 ```

그런데 수많은 에러들이 생길 수 있는데, 뭔가 조금 더 사용자들이 봤을 때 깔끔하고 친절한 방식으로 에러를 보여주고 싶은데 어떻게 해야 할지 잘 모르겠습니다. 개인적으로 `alert`는 유저 언프렌들리 하다고 생각하거든요. 하지만 그렇다고 모든 에러를 다 예상할 수 있는 건 또 아닌 것 같고. 이럴 때는 어떻게 하는 게 좋은가요?

2023-03-19 14:30 UTC, ashleysyheo commented on src/utils/domSelector.ts
> +};
기존 코드는 `return <E>element`를 하는데 이게 query selecting 한 요소에 대해 타입 단언을 사용해서 요소를 E 타입으로 변환한 체 반환하고 있습니다. 그래서 이 경우에는 개발자가 반환되는 요소의 타입이 E 임을 확신하고 있어야 합니다.

반면에 동동이 적어주신 코드는 querySelector 호출 시점에 제네릭 타입을 사용해서 타입스크립트가 반환된 요소의 타입을 자동으로 추론할 수 있게 해주고 있습니다. 그래서 별도의 타입 단언이 필요하지 않고 개발자가 타입 단언을 사용하여 실수할 가능성을 줄일 수 있습니다.

`<E>`가 문맥에 따라 제네릭으로 사용될 수도 있고 타입 단언으로 사용될 수 있다는 것에 대해 자세히 몰랐는데, 이렇게 동동이 물어봐 주신 덕분에 알게 되었습니다!

수정 커밋: https://github.com/woowacourse/javascript-movie-review/pull/15/commits/1d24802ab4c46565b87ed4371fa230bda3188f34

2023-03-19 14:36 UTC, ashleysyheo commented on src/utils/domSelector.ts
> +};
1. 지금은 따로 target을 필요로 하는 상황이 없어서 안 했었는데, 재사용성을 생각하면 target을 받도록 추가하는 것이 더 좋은 것 같습니다!
2. `E[]`로 반환하는 거는 생각도 못 했는데 확실히 그렇게 하면 더 편하게 사용할 수 있을 것 같습니다!!


수정 커밋: https://github.com/woowacourse/javascript-movie-review/pull/15/commits/1d24802ab4c46565b87ed4371fa230bda3188f34

2023-03-19 14:46 UTC, ashleysyheo commented on src/components/MovieListContent.ts
> +  },
`pop`이 좀 헷갈리고 명확하지 않은 부분이 있는 것 같습니다. 원래도 이 부분이 조금 복잡하다는 생각이 들었었는데, 어떻게 하는 게 좋을지 잘 몰라서 위와 같이 적었었습니다.

>items의 length가 바뀌니까 로직 따라가기가 쉽지 않네요

그런데 제가 이 부분을 잘 이해하지 못한 것 같습니다... items의 길이가 바뀌니까 밑에 `slice`하는 코드에서 어떤 섹션을 어떻게 rendering 한다는 것인지 따라가기 쉽지 않다는 뜻인가요?

<br>

그래서 리팩토링할 때 처음에 이렇게 코드를 적어봤는데 오히려 이게 더 이해하기 어려운 것 같다는 생각이 들어서 

```javascript
const items = $$<HTMLUListElement>('.item-card');
const extraItems = MOVIE_MAX_COUNT - movies.length;

const itemsToRemove = items.slice(items.length - extraItems);
itemsToRemove.forEach((item) => item.remove());

const lastPageItems = items.slice(-MOVIE_MAX_COUNT);
const itemsToRender = lastPageItems.slice(0, movies.length);
itemsToRender.forEach((child, key) => {
  MovieItem.render(child, movies[key]);
})
```

<br>

일단 이렇게 작성해 봤습니다.

```javascript
const items = $$<HTMLUListElement>('.item-card');
const extraItems = MOVIE_MAX_COUNT - movies.length;

items.splice(items.length - extraItems).forEach((element) => {
  element.remove();
});

items.slice(-movies.length).forEach((child, key) => {
  MovieItem.render(child, movies[key]);
});
```

<br>

수정 커밋: https://github.com/woowacourse/javascript-movie-review/pull/15/commits/124a337fbfdb0732ea2217f8d8d7016234317a4d

2023-03-19 14:55 UTC, ashleysyheo commented on src/components/MovieListContent.ts
> +  },
처음에 객체로 작성한 이유는 페어랑 얘기하면서 굳이 클래스일 필요가 없다면 클래스로 작성할 필요가 없지 않을까라고 의견을 맞췄기 때문입니다. 그런데 저희가 제일 처음 작성한 컴포넌트가 `NavBar`여서 크게 클래스의 필요성을 느끼지 못했던 것 같습니다. 

조금 더 복잡한 컴포넌트들을 코딩하면서 동동이 말한 부분처럼 타입스크립트 객체에서는 `this`를 못 사용하고 계속 `MovieListContent`와 같이 다 적어줘야 하니까 조금 불편하다고 느꼈습니다. 거기에 컴포넌트들이 이름이 비슷하니까 더 한 번에 알아보기 힘들기도 했습니다. 그리고 반복적으로 같은 DOM 요소를 여러 메서드에서 셀렉팅하는 것도 비효율적이라고 느껴서 클래스 constructor에서 한 번만 셀렉팅 한 다음에 모든 메서드들이 사용하게 하는 것이 더 좋다고 느꼈습니다. 

그래서 리팩토링하면서 `NavBar`처럼 굳이 클래스일 필요가 없는 컴포넌트를 제외하고는 클래스로 변경해 봤습니다!

2023-03-19 15:18 UTC, ashleysyheo commented
안녕하세요 동동 😄

너무 좋은 피드백들 감사합니다!! 덕분에 알지 못하고 생각지 못했던 부분들을 생각하고 공부할 수 있어서 너무 좋았습니다!

---

### E2E 테스트
cypress 일부분 문제를 해결했습니다! 

기존에는 cypress.config.ts에 API KEY를 적어 둔 다음에 그 파일을 gitignore에 추가했어서 동동이 테스트를 돌려 봤을 때 API KEY가 안 불러와졌습니다. (제 실수입니다 🥲)

그래서 그냥 API KEY를 숨겨서 사용하는 대신 url을 정규식 표현으로 적어서 intercept하는 방식으로 변경했습니다!

> intercept가 제대로 안되고 있는거 같네요

그리고 intercept가 제대로 안된 이유는 `외계인`을 이렇게 `%EC%99%B8%EA%B3%84%EC%9D%B8` 안 적어서 그랬던 것 같습니다... 🧐

이제는 테스트가 정상적으로 돌아가고 또 예외 사항에 대한 테스트도 추가했습니다! 

<br>

### 단위 테스트
그리고 `MovieList` 도메인 로직에 대한 jest 테스트도 작성했습니다. 적다 보니 e2e에서 테스트한 거랑 거의 같다고 느끼기는 했는데, jest에서 모킹한 다음에 테스트를 해보고 싶어서 작성했습니다.

<br>

### 클래스 & 구조
위에 커멘트에서 `NavBar`를 제외하고는 클래스로 변경했다고 했는데, 변경하면서 문제가 생겼습니다... 

기존 코드에서, 예를 들어서 `MovieListContainer`랑 `MovieListContent`가 서로가 서로를 참조하는 상황이 있었습니다. 클래스로 변경하면서 요소 셀릭팅은 constructor에서 한 번에 하고 싶었습니다. 그런데 `MovieListContainer`가 렌더링 되어야 `MovieListContent`에서 `.item-list`를 constructor에서 한 번만 셀렉팅 할 수 있는데, `MovieListContainer`가 `MovieListContent.loadMoreMovies`를 참조하고 있어서 그렇게 하지 못하게 되었습니다. 

이 문제를 해결하고 싶기도 했고, 컴포너트들이 필요 이상으로 서로 복잡하게 엮여 있다는 생각이 들어서 구조를 조금 변경했습니다. 커스텀 이벤트를 사용해서 도메인에서 변화게 있을 때 이벤트를 dispatching하는 방식으로 바꿨습니다. `MovieList`에서 변화가 있을 때 `movieListLoading`, `movieListReset`, `movieListLoading`과 같은 커스텀 이벤트를 dispatch하고 컴포넌트들에 알고 있어야 하는 이벤트들을 등록하도록 했습니다. 이렇게 수정하니까 `MovieListContainer`는 `MovieListContent`를 부르는 대신 `MovieList.getMovieData`만 호출하면 돼서 제가 해결하고 싶었던 문제는 해결할 수 있었습니다. 


그런데 이런 방식으로 설계해 보는 것이 처음이고 그냥 이렇게 하면 내 문제를 해결할 수 있지 않을까라는 생각에서 비롯된 거여서 지금 설계가 괜찮은 건지 잘 모르겠습니다 🥲...

2023-03-20 13:10 UTC, bigsaigon333 approved these changes
애슐리 안녕하세요~ 

리뷰 하는거보다 답변다는데 더 시간을 오래 쓴거 같네요 ㅎㅎ
그만큼 많이 고민하시고 반영하신게 보여서 좋았습니다 👍🏻 
저도 답변 단다고 공부가 많이 되었어요 😄 

추가로 코멘트 단 부분은 2단계 구현하면서 반영해보시면 좋겠습니다!
아니면 요 PR에 궁금한 점 달아주시면 계속 답변 달게요 😺 

고생하셨습니다~~

2단계 PR에서 만나요 💪🏻 💪🏻 

---

> 위에 커멘트에서 NavBar를 제외하고는 클래스로 변경했다고 했는데, 변경하면서 문제가 생겼습니다...
> 
> 기존 코드에서, 예를 들어서 MovieListContainer랑 MovieListContent가 서로가 서로를 참조하는 상황이 있었습니다. 클래스로 변경하면서 요소 셀릭팅은 constructor에서 한 번에 하고 싶었습니다. 그런데 MovieListContainer가 렌더링 되어야 MovieListContent에서 .item-list를 constructor에서 한 번만 셀렉팅 할 수 있는데, MovieListContainer가 MovieListContent.loadMoreMovies를 참조하고 있어서 그렇게 하지 못하게 되었습니다.
> 
> 이 문제를 해결하고 싶기도 했고, 컴포너트들이 필요 이상으로 서로 복잡하게 엮여 있다는 생각이 들어서 구조를 조금 변경했습니다. 커스텀 이벤트를 사용해서 도메인에서 변화게 있을 때 이벤트를 dispatching하는 방식으로 바꿨습니다. MovieList에서 변화가 있을 때 movieListLoading, movieListReset, movieListLoading과 같은 커스텀 이벤트를 dispatch하고 컴포넌트들에 알고 있어야 하는 이벤트들을 등록하도록 했습니다. 이렇게 수정하니까 MovieListContainer는 MovieListContent를 부르는 대신 MovieList.getMovieData만 호출하면 돼서 제가 해결하고 싶었던 문제는 해결할 수 있었습니다.
> 
> 그런데 이런 방식으로 설계해 보는 것이 처음이고 그냥 이렇게 하면 내 문제를 해결할 수 있지 않을까라는 생각에서 비롯된 거여서 지금 설계가 괜찮은 건지 잘 모르겠습니다 🥲...


훌륭합니다~ 이벤트 드리븐이  DOM 비동기의 근-본이죠. 커스텀 이벤트 드리븐 저는 좋다고 생각합니다~
컴포넌트간의 의존성도 끊었으니 애슐리가 원하는 바를 달성하지 않으셨나요?!

모든 경우에 다 적합한 그런 silver bullet 설계는 없습니다 ㅎㅎ
자신감을 가지고, 본인이 불편하다고 생각했던걸 해결해나가는 방향으로 설계를 수정하시기를 바래요!
그런 과정에서 고민했던 점, 해결하지 못한 점을 공유해주시면 더 좋은 답변 드릴 수 있을거 같아요~

(미리 말씀드려보자면 요 패턴은 이벤트가 많아지면, 이벤트의 흐름을 쫓기가 어려워진다는 단점이 있습니다 .. 그리고 이벤트 발생 순서 추적도 어려워요.. 근데 지금 1단계에서는 꽤 괜찮았지 않나요?)

2023-03-20 13:12 UTC, merged

2023-03-24 04:16 UTC, ashleysyheo commented
> 요런 메소드의 호출은, 도메인과 무관한 low-level 단인 fetchAPI 레벨이 더 일반적인거 같아요.
실제 도메인 코드에서는 속성명이 snakeCase로 왔는지 camelCase로 왔는지도 모르고, 그냥 당연히 camelCase로 쓰는거죵..!

camelCase로 변경하는 것을 어디에 둬야 할지 고민이 많았습니다! 처음에는 `fetchAPI`에 두는 게 더 어울리다고 생각했습니다. 동동의 말씀대로 특정 api url에 대해 fetch 요청한 후 그냥 바로 사용할 수 있게요. 그런데 `movieApi` 파일에 뒀던 이유는 fetch 한 데이터가 snake_case가 아니라 처음부터 camelCase인 경우에는 불필요한 작업을 하게 되지 않을까라고 생각했기 때문입니다. 그런데 일단 이번 미션에서는 무조건 snake_case에 들어오기 때문에 `fetchAPI`에 둬도 무방하다고 생각해서 옮겼습니다!

> 에러 처리 

`자기가 처리할 수 있는 에러만 처리한다`라고 말씀해 주셨는데, 생각해 보니까 이게 더 맞는 것 같습니다. 리팩터링 했던 코드에서 `InvalidMessage`에서 모든 에러를 처리하고 있었습니다. 화면에 그려줄 수 있는 오류는 그려주고 아닌 것들은 `alert`하는 방식으로요. 그런데 생각해 보면 `InvalidMessage`의 역할은 말 그대로 오류 메시지를 화면에 표시해 주는 것이기 때문에, 그릴 수 없는 오류들에 대해서 `alert`까지 하는 것은 맞지 않다고 생각했습니다. 그래서 일단은 `fetchAPI`의 코드를 `try ... catch`에 넣고 HTTP 에러만 던져서 `InvalidMessage`에서 그리게 만들고, 다른 에러들은 직접 `alert`하게 하는 방식으로 변경했습니다.

> 네 pop 으로 인해 items를 접근할 때마다 length가 달라져서, 어떤걸 렌더링하는지 알기 어려웠어요!

짱이예요 👍 계속 보다 보니 머리가 안 돌아갔는데, 동동이 적어 주신 코드를 보니까 훨씬 명확해 보이고 이해하기 쉽네요!! 감사합니다! 
지금은 익숙하고 하던 대로 짜는 것 같은데, 다르게 할 수 있는 방법들에 대해서 더 생각해야겠네요 🧐