[2단계 - 상세 정보 & UI/UX 개선하기] 치코(이재민) 미션 제출합니다.
woowacourse/javascript-movie-review pull request #151
Opened 2024-03-31 17:20 UTC by jaeml06

안녕하세요 피터! 치코입니다.

step2에서도 자세한 리뷰 부탁드리겠습니다. 

---

### 배포 주소

[https://woowa-moviereview.netlify.app/](https://woowa-moviereview.netlify.app/)

---

### step2 추가 요구사항

- #### 영화 상세보기

  이 기능 구현을 위해 **modal** 컴포넌트를 추가했습니다

  - **emptyModal** : mdal 내부를 위해 container를 만드는 함수가 있습니다. 이곳에서 modal 내부의 element를 인자로 받아 모달을 생성합니다.

  - **datailModal** : 영화 상세보기 내용을 보여주기 위한 element를 구성합니다.

- #### 별점 매기기

  이 기능 구현을 위해 **recommendStar** 컴포넌트를 추가했습니다.

  - **RecommendStar** : 추천도에 따라 별점을 줄 수 있는 컴포넌트를 클래스로 구현했습니다. render함수를 통해 기본적인 UI를 그리고, setRecommendList함수를 통해 클릭한 별점을 localStorage에 저장합니다. getSavedRecommend을 통해 datailModal에서 호출되어 localStorage에 저장되어 있는 별점 정보를 가져옵니다.

- #### 무한 스크롤

  이 기능 구현을 위해 util의 InfiniteScroll 클래스를 만들었습니다.

  - **InfiniteScroll** : IntersectionObserver을 통해 웹페이지 하단에 존재하는 target을 감지하면 새로운 리스트를 받아온다. 리스트를 받아오기 전까지 '로딩중' 문구를 출력한다.

- ### 반응형 

  - css을 통해 미디어 쿼리를 통해 구현

  - 모바일 환경에서 header 구현. 검색 icon을 클릭 시, input 너비 확장.

  

---

### 부족했던 점

- 접근성 

  Step 1 리뷰에서 다른 태그들에도 접근성을 신경쓸 수 있는 부분이 있으면 한 번 적용해보는 것도 좋을 것 같다라는 피드백이 있었으나 적용하지 못함.

- 난잡함

  이번 step2를 진행하면서 구현해야할 기능을 구현하고 제출을 하기 위해 코드를 살펴보니 납잡함이 느껴졌습니다. 과연 내 코드를 처음 본 사람들이 알아 볼 수 있을까라는 의심이 들었습니다. 특히 header컴포넌트와 RecommendStar컴포넌트가 심하다는 느낌이 들었습니다. 태그의 동적 생성이 많아지다보니 생긴 문제 같은데 막상 뾰족한 해결 방법이 떠오르지 않네요.

2024-03-31 17:29 UTC, jaeml06 commented on src/components/modal/emptyModal.ts
> +    setTimeout(() => container.focus(), 0);
키보드의 입력을 받기 위해 container.focus()를 이용했습니다. 다만 focus()는 해당 요소가 더 이상 변경이 없어야만 정상적으로 작동을 해서 setTimeout을 이용했습니다. 이 경우가 일반적인지 궁금합니다.

2024-04-01 07:35 UTC, jaeml06 commented on src/View/View.ts
> +}
이 함수의 위치에 대해 고민이 있습니다. emtyModal에 있기에는 MovieDetailModal 특정 모달을 호출하므로 어울리지 않는 것 같고 detailModal안에 선언하자니 modal.create가 detailModal안에 있는 것에도 어울리지 않다고 생각합니다. detailModal은 modal안의 내용이고 , emptyModal안에 있기에는 추상적이지 않아서 문제가 있다고 생각합니다. 그렇다고 View에 존재하는 것도 뜬금없고....  어디에 선언하는 것이 가독성을 높이는데 도움이 될까요?

2024-04-01 18:27 UTC, iborymagic requested changes
안녕하세요 치코! 2단계 미션 고생 많았습니다. 👏👏
세심한 transition들이 군데군데 적용돼있어서 찾아보는 재미가 있었습니다.
말씀해주신 접근성 부분은 꼭 챙겨주면 좋은 부분이지만, 기능 구현에 치여서 챙기기 힘든 부분이기도 합니다. 
저한테도 약간 평생 숙제같은 느낌이 없지 않아 있네요.
그래도 다음 번에는 꼭 한 번 시도해보시면 좋을 것 같습니다.
코멘트로 달아드린 부분들 확인해주시고, 반영 완료되면 다시 리뷰 요청주세요~

2024-04-01 18:27 UTC, iborymagic commented on src/components/recommendStar/recommendStar.ts
> +    recommendMessage.className = 'recommend-message';
말씀해주신 요런 태그를 생성하는 코드들은 사실 좀 어쩔 수 없이 길어지는 면이 있습니다. 그래도 이런 부분들은 생각하신 것만큼 코드가 읽기 어렵진 않습니다. 대신, 다른 가독성을 챙길 수 있는 부분을 찾아보면 좋을 것 같습니다.

2024-04-01 18:27 UTC, iborymagic commented on src/components/recommendStar/recommendStar.ts
> +}
예를 들면, 요런 코드들은 도메인 로직에 가까우니, 분리해봐도 좋겠다는 생각이 듭니다!

2024-04-02 04:47 UTC, jaeml06 commented on src/components/modal/emptyModal.ts
> +    setTimeout(() => container.focus(), 0);
죄송합니다. 여러가지 시도했다가 지우는 것을 놓쳤네요. 저는 document.body에 달아주면 제 코드 상에서 모달이 생성될 때마다 이벤트 리스너가 부착되기 때문입니다. 또한 외분에 keydown이벤트를 받기에는 모달이 생성되지도 않았는데 이벤트를 감지하기 때문에 비효율적이라 생각되어 외부에 이벤트 리스너를 부착하지 않았습니다.

2024-04-02 04:59 UTC, jaeml06 commented on src/View/View.ts
> +}
> 혹시 closeModalCallback은 밖에서 주입해주는 방식으로 구현해주신 이유가 있을까요? 모달을 열고 닫는 로직은 modal 컴포넌트 안에 들어가도 되지 않을까 하는 생각이 들었습니다.

close-button click이벤트 시에 발생하는 콜백함수이기 때문에 외부에서 주입하자고 생각했습니다. 하지만 modal 컴포넌트에 이미 선언되어 있기 때문에 굳이 외부에서 주입할 필요는 없었겠네요

2024-04-02 07:11 UTC, jaeml06 commented on src/View/View.ts
> +}
> 그리고 dialog 태그를 사용하면 굳이 classname을 붙였다 뗐다 하지 않아도 opanModal, closeModal 메소드를 사용할 수 있답니다. (치코가 멋지게 구현해주신 transition도 적용할 수 있는 걸로 알고 있어요!)

넵 dialog태그도 있었습니다. 다만 개인적인 취향때문에 선택하지 않았습니다. 이유는 dialog 태그 자체는 지워지지 않고 존재하기 때문에 닫은 컴포넌트가 요소에 존재하는게 꺼려졌고 영화마다 dialog를 내용을 바꾸기 위해 내부 요소의 값들을 바꿔주는게 어색하다고 느껴졌습니다. 그래서 저는 modal 전체를 삭제했다가 영화가 클릭시, 다시 생성하는 방법을 취했습니다. 피터의 말대로 빈 Dialog를 먼저 생성하고 영화를 클릭 할때 마다 안의 값을 바꾸는게 더 효율적일까요?

2024-04-02 08:29 UTC, jaeml06 commented on src/utils/InfiniteScroll.ts
> +              this.isLoading = false;
loadingMessage 변수를 생성자에서 받는 방식으로 변경했습니다. 사용 경우에 따라 생성자에 loadingMessage를 넘겨주는 경우에만 textContent에 집어 넣습니다.

2024-04-02 08:31 UTC, jaeml06 commented on src/utils/InfiniteScroll.ts
> +          }, 150);
observerInterval 변수를 생성자에서 받는 방식으로 변경했습니다. 디폴트 매개변수로 설정하여 사용자가 생성자에서 넘겨주지 않는 경우 기본 150으로 설정됩니다.

2024-04-03 01:39 UTC, jaeml06 commented on src/components/header/header.ts
> +}
그렇네요! util로 분리하는게 추가 로직을 구현할 때 좋겠네요

2024-04-03 05:05 UTC, jaeml06 commented on src/components/recommendStar/recommendStar.ts
> +    recommendMessage.className = 'recommend-message';
넵 고민해보겠습니다.

2024-04-03 07:59 UTC, jaeml06 commented on src/components/recommendStar/recommendStar.ts
> +}
domain에 LocalStorage를 만들어 분리해보았습니다.

2024-04-04 15:50 UTC, iborymagic commented on src/utils/InfiniteScroll.ts
> +              this.isLoading = false;
인자가 조금 많아지겠지만, 로딩중일 때도 콜백함수를 인자로 받아서 처리해보는 건 어떨까요? target이 텍스트와 어울리지 않을 수도 있고, 로딩바나 스피너 등을 사용하고 싶을 수도 있으니까 좀 더 범용성을 챙겨보면 좋을 것 같다는 생각이었습니다.

2024-04-04 15:53 UTC, iborymagic commented on src/components/header/header.ts
> +}
handleResize의 재사용성을 조금 더 높일 수 있을 것 같습니다. 어차피 화면 너비의 분기 기준은 동일할거기 때문에(보통 모바일, 태블릿, PC의 기준으로 잡으니까요) 각 사이즈일 때 들어갈 로직을 인자로 받는다던가 하면 좀 더 편하게 resize 로직을 구현할 수 있지 않을까 생각했어요!

2024-04-04 15:58 UTC, iborymagic approved these changes
안녕하세요 치코! 2단계 미션 마무리 하시느라 고생 너무 많았습니다. 
리뷰 반영된 것들 중, 몇 가지 좀 더 개선해보면 좋을만한 것들은 코멘트로 달아놨습니다.
리뷰 자체도 열심히 반영해주셨고, 이제 방학 기간이기도 해서 리뷰 자체는 여기서 마무리하도록 하겠습니다.
일단 머지할테니, 추가적으로 개선해보고 싶으시면 개선해보셔도 될 것 같아요.
고생 많으셨고, 방학 잘 보내시길 바랍니다! 👋

2024-04-04 15:58 UTC, merged