[2단계 - 상세 정보 & UI/UX 개선하기] 웨디(박세현) 미션 제출합니다.
woowacourse/javascript-movie-review pull request #161
Opened 2024-04-01 08:09 UTC by pakxe

2024-04-03 10:00 UTC, iborymagic requested changes
안녕하세요 웨디! 2단계 미션 진행하시느라 고생 많았습니다 👏👏

재미있는 고민을 많이 하시는 것 같아서 저도 같이 흥미롭게 리뷰할 수 있었습니다. 특히 스켈레톤은 다른 사이트를 직접 관찰하시면서까지 열심히 구현해주셨는데, 개인적으로 사용을 해보고 나서 약간의 아쉬움이 느껴졌어서 그 부분에 관해서 말씀드려볼게요.

일단, 스켈레톤이 일부분만 화면에 보여도 바로 데이터를 불러온다면 조금 더 자연스럽게 느껴질 것 같다는 생각이 들었어요. 지금은 제법 많은 부분이 노출되는데도 데이터를 안불러와서, 사용하는 입장에서 '얘네는 왜 있는거지? 버그인가?' 하는 생각이 들었던 것 같습니다. 또,  말씀해주신대로 스크롤이 아래에만 붙어있는 것 때문에 부자연스러움이 더 크게 느껴지는 것 같아요. 그것만 아니어도 훨씬 자연스럽게 느껴질 것 같아서 아쉬웠습니다.

![weddy1](https://github.com/woowacourse/javascript-movie-review/assets/42052110/6db7cf8f-f325-436a-9aab-d8a4b9564c53)

하지만 재미있게 잘 구현해주셨고, 덕분에 저도 여러가지로 생각해보면서 리뷰를 할 수 있었습니다. 코멘트로 간단한 리뷰들 달아놓았으니 확인 후에 리뷰 다시 요청주세요~

2024-04-03 10:00 UTC, iborymagic commented on src/domain/MovieService.ts
> +class MovieService implements MovieServiceType {
여러 DB에서 데이터를 가져와야할 경우를 대비했다니 멋지네요~ 

혹시 여러 개의 DB를 사용하게되면, 각 DB에서 가져온 데이터들을 controller에서 취합하는 것과 별도의 레이어(MovieService 라던가)에서 처리해준 후에 controller로 내보내는 것 중 어떤 방법을 생각하고 계신걸까요?

언뜻 봐서는 MovieService는 각 DB 당 하나의 인스턴스로 처리될 것 같은데, 그렇게 되면 DB가 늘어날 때마다 controller단의 코드에 수정이 가해져야할 것 같다는 생각이 들어요.

2024-04-03 10:00 UTC, iborymagic commented on src/domain/MovieService.ts
> +class MovieService implements MovieServiceType {
그리고 혹시, import를 하게 될 경우에 예상되는 대규모 수정이 어떤 것인지 대략적으로 설명해주실 수 있나요? (궁금해요)

2024-04-04 07:36 UTC, pakxe commented on src/component/MovieContainer.ts
>    }
로더(빙글빙글 도는 gif)는 따로 컴포넌트로 분리하였습니다! 말씀하신대로 MovieContainer와 깊게 관련있지도 않았고 재사용을 위해서 분리해보았습니다

[feat: Loader를 컴포넌트로 분리](https://github.com/pakxe/javascript-movie-review/commit/bd94d1cb47873a91616b9ce5a6f677150aa86881)

2024-04-04 07:40 UTC, pakxe commented on src/util/fetchDataFromUrl.ts
>  ): Promise<T> {
네 맞습니다! 백엔드에서 반환하는 가공 전의 데이터의 타입을 따로 적어두고 사용하고 싶어서 위처럼 제네릭을 사용해서 구현해보았습니다 !

2024-04-04 07:41 UTC, pakxe commented on src/controller/controller.ts
유틸처럼 사용할 수 있도록 콜백과 타겟엘리먼트를 받아 무한 스크롤을 분리했습니다 !

[feat: 무한 스크롤를 컨트롤러에서 분리
](https://github.com/pakxe/javascript-movie-review/commit/e8837e0e6dabb3e772c52e082d13a20ab7aa5eee)

2024-04-04 07:42 UTC, pakxe commented on src/domain/Movie.ts
>  export default class Movie {
맞습니다..! 타입이 있어서 클래스로 따로 둘 필요가 없을 것 같습니다! 바로 제거했습니다.

2024-04-04 08:14 UTC, pakxe commented on src/component/ScoreStar.ts
> +    socketElement.parentNode!.replaceChild(this.$container, socketElement);
최대한 안쓰려고 했는데 미처 수정하지 못하고 남아있는 부분이 있었나봅니다..! 바로 수정했습니다 ㅎ.ㅎ

2024-04-04 08:14 UTC, pakxe commented on src/api/DB/TMDB.ts
> +    this.base = 'https://api.themoviedb.org/3';
따로 환경 변수로 이동했습니다. 감사합니다!

2024-04-04 13:33 UTC, pakxe commented on src/domain/MovieService.ts
> +class MovieService implements MovieServiceType {
말씀하신대로 DB를 여러 개 사용해야하는 경우 개수만큼의 MovieService 인스턴스가 늘어나게 되겠네요..!
여러개의 DB를 '쓸 수는 있게' 설계해두었지 '효율 좋게' 설계하는 방법까진 고민해보지 않은 것 같아 아쉽습니다.

그래서 이걸 컨트롤러의 변화를 최소화하고 어떻게 효율 좋게 다중 DB를 사용할 수 있을지 생각해보았는데요. 두 가지 정도로 추려지게 되었습니다.

## 1. 전략 패턴 사용
MovieService의 인스턴스를 늘리지 않으면서 컨트롤러의 가해지는 변경도 최소화한 방법입니다.
MovieService에서 `setApi`메서드를 두어 어떤 DB를 선택할 것인지 문자열로 받고 그 후 `fetch*`메서드들을 실행합니다.
인스턴스를 새로 생성하는게 아닌 동적으로 교체하는 방식이라 인스턴스를 하나로 유지할 수 있다는 점이 장점입니다.

다만 이 방법의 경우 하나의 페이지에서 만약 10개 DB에서 받아온 정보가 필요하다면 10개를 동적으로 교체하고 fetch하는 코드가 생기기 때문에 2줄 * 10줄로 20줄의 코드가 필요하게 됩니다.

## 2. apiName을 배열로 받아 `fetch*`를 실행할 때마다 이름을 넣어 수행하기
이 방법은 MovieService의 인자인 apiName을 현재의 단일 DB가 아닌 DB이름(문자열) 배열을 받습니다.
그리고 `fetch*`메서드를 실행할 때마다 어떤 DB를 선택할 지 이름을 넘겨줘서 사용하는 방식입니다.

이 방법의 경우 `fetch*(apiName, params)`형태의 호출모습으로 바뀌기 때문에 기존의 코드를 많이 수정해줘야한다는 단점이 있습니다. 

다만 이후 물어보신 `import를 하게 되어 생기는 대규모 수정`으로 인해 2번 방법을 개인적으로 더 선호할 것 같은데요! 
일단 지금의 apiName(string)을 넘겨주는게 아닌, DB객체 자체를 넘겨주는 식으로 MovieService가 설계되어있다고 가정해보겠습니다. 이 상황에선 DB 이름이 바뀌는 상황이 생긴다면 `TMDB` -> `PXDB` TMDB를 import해서 MovieService의 인자로 넘겨주는 모든 파일에서 import문을 수정해야하기 때문에 번거로울 수 있다고 생각했습니다. (지금 생각해보니 문자열을 검색해 다른 문자열로 대체시켜주는 기능을 이용하면 될 것 같기도 합니다...)

그래서 위 상황을 `import를 하게 되어 생기는 대규모 수정`으로 생각하며 문자열로 이름만 넘겨주게 구현했고, 내부에 팩토리와 비슷한 객체를 두어 사용했습니다. 

다만 이 MovieService를 제일 상위(원천)에서 인자로 넘겨주는 방식이라면 import를 수정할 곳이 원천뿐이라서 문자열로 api이름을 넘겨주는 방식이 아니어도 될 것 같습니다. 

결국 제일 큰 목표는 `객체(여기선 DB) 생성의 책임을 어디에 전가시키느냐`였습니다. 그리고 항상 저는 객체 생성의 책임을 지금처럼 호출해 사용하는 쪽에 위임하진 않았습니다. 다만 이런 설계가 좀 특이한 방식인지 항상 페어들에게 설명을 해줘야했던 것 같아요. 

혹시 이런 설계방식에 대해서 어떻게 생각하시는지 피터의 생각을 묻고 싶습니다. 제가 너무 한 가지 방법만 고집한다고 느껴지기도 해서요..! 🥺

2024-04-04 16:58 UTC, pakxe commented
안녕하세요 피터! 
피드백 받은 부분을 반영하고 몇 가지 기능을 더 추가해 재리뷰 요청을 보내드리게 되었습니다. 

여쭤보고 싶은 점들은 코멘트에 남겼으니 확인해주시면 너무 감사할 것 같습니다.

2024-04-04 16:58 UTC, closed without merging

2024-04-05 07:33 UTC, iborymagic commented
안녕하세요 웨디~ 일단 한 번 핑퐁이 되어서 레벨 수료 기준은 만족했으니, 업무 마치고 오늘 내로 리뷰해드릴게요!

2024-04-05 15:11 UTC, iborymagic commented
> 질문드리고 싶은게, 현재 컨트롤러에서 메인 페이지, 검색 페이지를 fetch해오기위한 로직을 두고 분기해서 사용했는데요. 이걸 MovieController로 옮기고 어떤 페이지를 준비할지를 인자로 받는 방법에 대해선 어떻게 생각하시는지 여쭤보고 싶습니다.

MovieContainer를 어떤 컴포넌트로 고려하셨냐가 중요할 것 같아요. 저는 사실 Controller가 존재하길래, MovieContainer 컴포넌트를 어느 정도 UI 로직만을 다루는 컴포넌트로 의도하셨다고 생각했어요. 그래서 fetch하는 로직을 MovieContainer에서 꺼낼려고 Controller를 만드신 줄 알았는데, MovieContainer 내부로 fetch 로직을 집어넣는 고민을 하고 계셨네요! 혹시 이 고민을 하게 된 계기가 무엇 때문인지 알 수 있을까요?

만약 MovieContainer를 일종의 페이지 컴포넌트처럼 생각하신다면(다른 컴포넌트들을 연결해주는 부모 컴포넌트 역할이랄까요..) 거기에 fetch 로직이 들어가도 상관없을 것 같은데, 그러면 또 controller의 포지션이 좀 애매해지지 않을까요?