[2단계 - 상세 정보 & UI/UX 개선하기] 빙봉(김윤경) 미션 제출합니다.
woowacourse/javascript-movie-review pull request #165
Opened 2024-04-01 08:24 UTC by Yoonkyoungme

케빈, 안녕하세요😊 요즘 날씨가 너무 좋네요🌸
step2 미션도 잘 부탁드립니다!

<br />

## 배포 주소 및 로컬 실행 방법
🚀 [배포 주소](https://yoonkyoungme.github.io/javascript-movie-review/dist/)

🔥 로컬 실행
```
npm run start 

npm run test-e2e
```
로컬 실행을 위해 .env 파일이 필요하면 DM 주세요~!

<br />
<br />

## 구현 사항
**- 무한 스크롤**
  - scroll 이벤트와 throttle을 사용

**- 반응형**
  - 영화 목록, 상세 모달, 검색 Header를 데스크탑, 테블릿, 모바일 사이즈에 대응

**- 영화 별점 매기기**
  - 영화 ID를 key로 하고 해당 영화에 대한 별점(1 ~ 5)을 값으로 하는 객체를 localStroage에 저장하여 별점 정보를 유지하고 관리

<br />
<br />

## 버그
**모바일 사이즈**에서 검색 기능 흐름
```
1. Header 영역의 검색 input은 안 보이고, 돋보기 button만 보인다.
2. 돋보기 button을 클릭했을 때 검색 input이 보이고, 검색이 가능하다.
```

### 개발자 도구 모바일 사이즈 테스트
개발자 도구로 모바일 사이즈에서 테스트 했을 때에는 위의 기능 흐름이 만족하였습니다.

https://github.com/woowacourse/javascript-movie-review/assets/100656920/8c8f8e3c-a69b-484f-83e9-5b789e5e414c

<br />

### 휴대폰 테스트
하지만 휴대폰에서 테스트 했을 때에는 돋보기 button을 클릭하고, input에 포커싱이 되면 다시 input 창이 사라지는 버그가 발생합니다😭

https://github.com/woowacourse/javascript-movie-review/assets/100656920/3f03474e-d8a5-403c-b57f-d3183e397097

2024-04-02 05:48 UTC, Yoonkyoungme commented
이번 리뷰 요청 때는 기본 요구사항을 구현하느라 적용하지 못했지만, 다음 리뷰 요청 시 고려하고 싶은 개선 사항은 다음과 같습니다😊

- 영화 상세 정보를 보여주는 모달 창이 열렸을 때, 배경의 영화 목록이 스크롤되지 않도록 한다.
- 영화 목록의 우측 하단에는 상단으로 빠르게 이동할 수 있는 플로팅 버튼을 추가한다.
- 영화 상세 정보가 로딩되기 전에는 스켈레톤 UI 또는 스피너와 같은 로딩 표시를 적용한다.

2024-04-02 06:37 UTC, JeongBin0227 commented
저는 개인적으로 반응형작업할때 https://responsively.app/ 툴을 자주 쓰는데 정말 좋습니다 추천드려요~

2024-04-02 06:39 UTC, JeongBin0227 commented
다른 영화를 눌렀을때, 이전영화가 잠깐 보여지는 버그가 있는거 같아요

https://github.com/woowacourse/javascript-movie-review/assets/45503248/5b616314-db3f-4014-b7fd-ee10023a263e

2024-04-02 07:23 UTC, JeongBin0227 requested changes
안녕하세요 빙봉!

2단계 미션 잘확인하였습니다 👍 
1차로 코드리뷰 해드렸고, 다음 개선하고 싶은 내용도 함께 올려주시면 같이 확인해보겠습니다.

지금 남겨드린 코멘트는 코드 전체적으로 해당내용이라고 생각해주시면 좋을거 같아요 
고생하셨습니다 👍 💯

2024-04-02 07:23 UTC, JeongBin0227 commented on src/components/templates/generateStarRating.ts
> +    ${scoreDescription}
createScoreDescription(count); 
이렇게 바로 사용해보면 어떨까요?

2024-04-02 09:31 UTC, Yoonkyoungme commented on src/components/modal/BaseModal.ts
> +    $<HTMLElement>("modal-backdrop")?.addEventListener(
유틸 함수 `$`는 아래의 코드처럼 `getElementById`를 기반으로 하기 때문에, #을 붙이지 않고 id 값을 직접 사용하였습니다!

```typescript
// utils/dom.ts

type Selector = string;

export const $ = <T extends HTMLElement = HTMLElement>(
  selector: Selector
): T | null => document.getElementById(selector) as T | null;

```

2024-04-03 16:13 UTC, Yoonkyoungme commented
안녕하세요, 케빈😊
케빈의 리뷰를 읽고 적용해봤어요! 반영한 내용은 🚀 이모티콘으로 표시해두었습니다.

## 버그 해결
PR에 올렸던 버그, '실제 모바일 환경에서 검색 입력창이 포커싱되면 입력창이 보이지 않는 문제'를 해결했습니다👏
문제의 원인은 휴대폰에서 검색 버튼을 클릭하면 검색 입력창이 활성화되고, 입력창이 포커싱되면서 키보드가 활성화되는데, 이때 발생하는 resize 이벤트 때문에 `$searchInput?.classList.add("hidden");`이 실행되어 입력창이 보이지 않게 되었던 것 같아요😭

resize 이벤트를 사용하는 대신, CSS 미디어 쿼리를 사용해 화면 크기에 따라 검색 입력창의 표시 여부를 자동으로 조정하도록 변경했습니다!

이 버그를 해결하는 과정에서, 같은 IP 주소를 사용하여 localhost에서 테스트하는 방법을 배울 수 있었습니다👍 (이 방법을 알기 전까지는 모바일 테스트를 하려면 배포한 후에 사이트에 접속해서 테스트하고 있었어요ㅜㅜ😂)

<br />

## UX 개선
- 영화 상세 정보를 보여주는 모달 창이 열렸을 때, 배경의 영화 목록이 스크롤되지 않도록 변경했습니다.
_관련 커밋: 1aadcdb3e404fe459f4b504efe30fab285cf1774_

<br />

- 영화 아이템 썸네일에 hover 효과를 추가했습니다. 
_관련 커밋: c8427639f1802360c70e8fae5afa9699d4d938a3_
<p align="center">
  <img src="https://github.com/woowacourse/javascript-movie-review/assets/100656920/d8eb052a-174f-414b-898d-adfaed5af27b" width="500">
</p>

<br />

- 모바일 사이즈에서는 홈 로고를 MovieList 이미지 중 'M'까지만 보이도록 변경했습니다. (CSS 속성 중 `clip-path`를 이용했습니다.) 
_관련 커밋: 3bf203aad90e5f1b4650d681d7d40842c5603979_
<p align="center">
  <img src="https://github.com/woowacourse/javascript-movie-review/assets/100656920/96ae2c89-c525-419b-bcf1-86e85da7720d" width="250">
</p>

<br />

- overview 데이터가 없는 경우 "overview 정보가 없습니다."라는 텍스트를 표시하게 변경했습니다.
_관련 커밋: 6855d17b5390fe0ec55196d1ae6222cb34cf1515_
<p align="center">
  <img src="https://github.com/woowacourse/javascript-movie-review/assets/100656920/200eef0b-3da9-4dc2-9a51-1e242df60db7" width="500">
</p>

<br />

- 영화 목록에서 평점 정보를 소수점 2째 자리에서 반올림하여 표시하였습니다. (첫 PR 때 작업)
_관련 커밋: 90eba23ee762c7913eebe8bd9a8974c8c3cb09cf_
<p align="center">
  <img width="1270" alt="image" src="https://github.com/woowacourse/javascript-movie-review/assets/100656920/8aba3474-042f-43ac-8212-21d751d437d8">
</p>

2024-04-03 16:14 UTC, Yoonkyoungme reviewed
안녕하세요, 케빈😊
이번에도 양질의 피드백 너무 감사합니다👍👍

케빈의 리뷰를 읽고 적용해봤어요! 반영한 내용은 🚀 이모티콘으로 표시해두었습니다.

## 버그 해결
PR에 올렸던 버그, '실제 모바일 환경에서 검색 입력창이 포커싱되면 입력창이 보이지 않는 문제'를 해결했습니다👏
문제의 원인은 휴대폰에서 검색 버튼을 클릭하면 검색 입력창이 활성화되고, 입력창이 포커싱되면서 키보드가 활성화되는데, 이때 발생하는 resize 이벤트 때문에 `$searchInput?.classList.add("hidden");`이 실행되어 입력창이 보이지 않게 되었던 것 같아요😭

resize 이벤트를 사용하는 대신, CSS 미디어 쿼리를 사용해 화면 크기에 따라 검색 입력창의 표시 여부를 자동으로 조정하도록 변경했습니다!

이 버그를 해결하는 과정에서, 같은 IP 주소를 사용하여 localhost에서 테스트하는 방법을 배울 수 있었습니다👍 (이 방법을 알기 전까지는 모바일 테스트를 하려면 배포한 후에 사이트에 접속해서 테스트하고 있었어요ㅜㅜ😂)

<br />

## UX 개선
- 영화 상세 정보를 보여주는 모달 창이 열렸을 때, 배경의 영화 목록이 스크롤되지 않도록 변경했습니다.
_관련 커밋: 1aadcdb3e404fe459f4b504efe30fab285cf1774_

<br />

- 영화 아이템 썸네일에 hover 효과를 추가했습니다. 
_관련 커밋: c8427639f1802360c70e8fae5afa9699d4d938a3_
<p align="center">
  <img src="https://github.com/woowacourse/javascript-movie-review/assets/100656920/d8eb052a-174f-414b-898d-adfaed5af27b" width="500">
</p>

<br />

- 모바일 사이즈에서는 홈 로고를 MovieList 이미지 중 'M'까지만 보이도록 변경했습니다. (CSS 속성 중 `clip-path`를 이용했습니다.) 
_관련 커밋: 3bf203aad90e5f1b4650d681d7d40842c5603979_
<p align="center">
  <img src="https://github.com/woowacourse/javascript-movie-review/assets/100656920/96ae2c89-c525-419b-bcf1-86e85da7720d" width="250">
</p>

<br />

- overview 데이터가 없는 경우 "overview 정보가 없습니다."라는 텍스트를 표시하게 변경했습니다.
_관련 커밋: 6855d17b5390fe0ec55196d1ae6222cb34cf1515_
<p align="center">
  <img src="https://github.com/woowacourse/javascript-movie-review/assets/100656920/200eef0b-3da9-4dc2-9a51-1e242df60db7" width="500">
</p>

<br />

- 영화 목록에서 평점 정보를 소수점 2째 자리에서 반올림하여 표시하였습니다. (첫 PR 때 작업)
_관련 커밋: 90eba23ee762c7913eebe8bd9a8974c8c3cb09cf_
<p align="center">
  <img width="1270" alt="image" src="https://github.com/woowacourse/javascript-movie-review/assets/100656920/8aba3474-042f-43ac-8212-21d751d437d8">
</p>

2024-04-04 17:29 UTC, JeongBin0227 commented
[개선해보면 좋은 UX] 
- 검색에 디바운스와 스로틀 등을 활용하여 엔터를 누르지 않고도 자동으로 검색되는 기능 만들기
- 방향키를 활용하여 한번 클릭한 영화 옮겨보기
- 제일 상단으로 올라가는 플로터 버튼만들기
- 서치바가 포함된 헤더 고정 시키기
- 각 영화단 메모 남길수 있게 하기

정도 있을거 같아요~

2024-04-04 17:35 UTC, JeongBin0227 approved these changes
안녕하세요 빙봉!

수정해주신 코드 모두 확인했습니다. 👍 
추가로 몇가지 ux 관점으로 시도해보면 좋을만한거 몇가지 더 적어봤어요

미션 하느라 고생많으셨습니다 알차고 재밌는 방학 보내세요~ 💯

2024-04-04 17:35 UTC, merged