Step1
woowacourse/javascript-movie-review pull request #22
Opened 2023-03-16 08:35 UTC by afds4567

2023-03-16 11:39 UTC, woowahan-cron commented
PR 메시지를 먼저 작성하고 피드백 요청을 눌러주세요.
크론이 검토하는 20시 39분이 지난 현재에도 작성되지 않았네요 🥲
이러면 정말 곤란합니다 ㅜㅜ

2023-03-18 12:28 UTC, ddongule requested changes
안녕하세요 아이크! 그루밍입니다  🤚🤚
드디어 api를 사용하면서 비동기를 사용하게 되었네요! 어떠셨나요~? ㅎㅎ
배포된 페이지도 잘 동작하는거 확인했습니다! 아쥬 멋찌던데욧!!!!!!

전체적인 프로젝트에서 non null assertion(`!`)이 많이 사용되고 있어요~! 
이렇게 작성해두면 컴파일러가 해당 값이 없어도 문제를 감지하지 못하기 때문에, 런타임 에러가 발생할 가능성이 높아요. optional chaining이나 `??` 연산자 등을 통해 null 체크를 해주는 것이 더 안전해보입니다. 
그리고 `as`나 `any` 등도 최대한 덜 사용할 수 있도록 연습해보시면 좋겠어요. 관련 내용은 코멘트로 더 남겨두었습니다 :) 

async-await의 경우에는 사용하지 않아도 되는 곳에 들어가 있는 경우가 조금 있어서 코멘트 남겨두었어요! 확인해주시면 좋을 것 같습니다 ㅎㅎ 

### QnA

#### 1. 
혹시 TotalMovieInfoType과 MovieInfoType을 나누어 사용하신 이유가 요 요구사항 때문이었을까용~? 
API에서 가져온 모든 데이터를 사용하시는게 아니라 convertMovieData 함수에서 필요한 데이터들만 뽑아내 사용하고있기 때문에 제대로 반영하셨다고 생각해요. 다만 dataManager의 역할에 대해서 조금 더 고민해보셔도 좋을 것 같아요~! 관련 내용은 코멘트로 달아두었어요 😉

#### 2.
함수형 컴포넌트와 클래스형 컴포넌트는 각각 장단점이 뚜렷해요. 처음에 함수형태로 구현해보시려고 했던 이유는 무엇일까요? 그리고 어떤 어려움이 생겨 클래스로 바꾸셨고, 그로인해 문제가 어떻게 해결되었는지도 함께 적어주시면 좋을 것 같아요 😎 
아무래도 일관성 있는 코드를 만드려면 일관적인 형태로 코드를 만드는 것이 좋겠죠! 하지만 필요하다면 현업에서도 클래스와 함수 컴포넌트를 섞어서 쓰는 경우도 있어요. 지금은 공부해나가는 과정이니 어렵다면 두가지를 혼용해 사용하셔도 괜찮을 것 같아요. 다만, 어떤 문제가 있었고 또 그 문제를 해결하기 위해 어떤 다양한 방법들이 있었으며 왜 그러한 선택을 했는지에 대해서 많이 생각해보시면 좋을 것 같아요 👍

이번 미션 어려우셨을텐데 고생 많으셨습니당!!
이야기나누면서 같이 조금 더 다듬어나가봐용!!!!
혹시 이해하기 어렵거나 궁금한 점이 생긴다면 언제든 알려주세요!!!!!!
화잇팅입니닷!!!!!! ꒰◍ˊ◡ˋ꒱੭⁾⁾ 🔥🎁🔥🎁🔥🎁🔥

2023-03-18 12:28 UTC, ddongule commented on src/domain/MovieDataManager.ts
> +    });
MovieInfoType과 TotalMovieInfoType이 분리된 이유가 있을까요? 🤔

movieItems가 `TotalMovieInfoType[]`이기 때문에 item은 굳이 type을 명시해주지 않아도 `TotalMovieInfoType`으로 자동추론이 될 것 같아요.

2023-03-18 12:28 UTC, ddongule commented on src/domain/MovieDataManager.ts
> +      .map((item: any) => {
any type보다는 명시적인 type을 지정해주는 편이 더 안전해요!

2023-03-18 12:28 UTC, ddongule commented on src/domain/MovieDataManager.ts
> +  async generateElement(
async는 왜 들어가있는 걸까용? 🤔

2023-03-18 12:28 UTC, ddongule commented on src/domain/MovieDataManager.ts
> +  }
dataManager가 알아야하는 내용인지 잘 모르겠어요! 요 부분이 들어간 이유가 있을까용~?

2023-03-21 05:38 UTC, afds4567 commented on src/@types/movieType.ts
> +}
서버에서 받아온 데이터는 snake_case였고 자바스크립트 파일에서는 camelCase를 따르고 있기 때문에 나누었는데 불필요한 것 같아 지웠습니다!

2023-03-21 05:57 UTC, afds4567 commented on src/domain/MovieDataManager.ts
> +  async generateElement(
async await에 대해 잘 모르고 남발했던것 같아요...😭 
전부 수정했습니다

2023-03-21 06:35 UTC, afds4567 commented on src/domain/MovieDataManager.ts
> +  }
여기가 아니라 영화 목록을 그리는 MovieItemList에 들어가야된다고 생각해서 수정했습니다!
[3546f0a](https://github.com/woowacourse/javascript-movie-review/pull/22/commits/3546f0a26721d09f725d01e72f2d12d7abe43915)

2023-03-21 06:38 UTC, afds4567 commented on src/domain/MovieDataManager.ts
> +    });
문법을 잘못 이해하고 item의 타입을 필요한 title,posterPath,voteAverage와 같이 재지정해줘야한다고 잘못생각했습니다…

2023-03-21 06:47 UTC, afds4567 commented on src/components/SearchBox.ts
> +    });
input!!
```const searchInput = document.querySelector(".search-input")```으로 수정했습니다

2023-03-21 07:01 UTC, afds4567 commented on src/App.ts
> +  });
알려주신 a 태그를 사용해서 수정했습니다~ [3b9d608](https://github.com/woowacourse/javascript-movie-review/pull/22/commits/3b9d6080dfd472187bb7d73c21cc6dc211d63eb0)

2023-03-21 07:13 UTC, afds4567 commented on src/api/keywordSearch.ts
> +  let currentPage = 1;
새로 배운 클로저를 미션에 적용해보고 싶어서 사용했는데 커멘트대로 해당 함수가 여러곳에서 사용하면 꼬일것 같네요...
한번 고쳐봤는데 어떨까요??

2023-03-21 07:49 UTC, afds4567 commented on src/api/keywordSearch.ts
> +};
키워드 검색시와 더보기 요청시 에러 처리 기능 구현했습니다 [d92a3ba](https://github.com/woowacourse/javascript-movie-review/pull/22/commits/d92a3bad23a5f68f12db8a8fa5e9dcbd29c33ab9)

2023-03-21 07:51 UTC, afds4567 commented on src/App.ts
> +  );
> popularMovieData가 없다면 early return을 하는 것도 좋아보여요~!

아래와 같은 방법으로 early return 했습니다
```
const currentPagePopularMovieData = await getPopularMovie(
    popularMovieCurrentPage
  );
  if (!currentPagePopularMovieData) return;
```

2023-03-21 07:52 UTC, afds4567 commented on src/App.ts
> +    );
😱😱

2023-03-21 07:54 UTC, afds4567 commented on src/components/MovieItem.ts
> +            alt="앤트맨과 와스프: 퀀텀매니아"
```alt={title}```로 수정

2023-03-21 07:59 UTC, afds4567 commented on index.html
> +        <h1><img src="./logo.png" alt="MovieList 로고" class="logo" /></h1>
제공하는 입장과 받아보는 입장에 차이가 있다는 것을 알게 되어 로고가 내용 전체의 주제 혹은 제목은 아니라고 생각해 h1 태그를 지웠습니다. 추가적으로 스크린 리더 사용자가 로고에 대한 설명을 들을 수 있게 aria-label로 로고라는 것을 알려주는 방식으로 수정했습니다.

2023-03-21 08:51 UTC, afds4567 commented on src/App.ts
> +    .addEventListener("searchButtonClicked", async (e: Event) => {
검색 버튼이 클릭 되었을 때 화면이 바뀌어야 하는데 화면 바꾸는 역할(showMoiveList)을 검색버튼 컴포넌트보다 App에서 하도록 하고 싶어서 커스텀이벤트를 사용했습니다. 제가 느끼기에는 showMoiveList를 넘길 때 보다 코드가 덜 복잡해져서 유지보수에도 좋다고 생각됩니다.😄 
아직 불편한점은 크게 못 느꼈습니다

2023-03-21 08:52 UTC, afds4567 commented on src/App.ts
> +    .querySelector(".search-input")!
```searchInput?.addEventListener("searchButtonClicked", async (e: Event) => {```
방식으로 수정했습니다

2023-03-22 02:44 UTC, afds4567 commented
안녕하세요 그루밍~ ✋ 
리뷰 남겨 주신 async-await, 타입스크립트 부분 최대한 고쳐 보았는데 아직은 쉽지 않은것 같아요...
그래도 as, 특히 any를 최대한 사용하지 않도록 수정해봤습니다. 

- dataManager의 역할에 대해서도 고민해보았는데요
미션 요구사항에서 "도메인객체를 만들어 사용한다"라는 문구가 없었으면 convertMovieData를 삭제하고, generateElement 함수를 App에서 정의하고 사용해도 된다고 생각합니다. 그래서 step1은 도메인 객체가 따로 없어도 된다고 생각하는데 그루밍은 어떻게 생각하시나요?

- 처음에 함수형태로 구현해보려 한 이유는 리액트에는 함수형태로 많이 사용한다고 알고 있어서 컴포넌트를 클래스와 함수형태로 만들때 장단점을 직접 비교해보려고 했어요. 리뷰를 반영하면서 movieItemList, searchBox를 우선 함수형태로 변형해 봤는데 시간이 충분해서 그런지 바꿀 수 있게 됐습니다. (제대로 바꾼거겠죠??) 더 고민해봐야겠지만 클래스에 있던 필드가 없어진게 코드를 덜 복잡하게해서 좋았단 것 같습니다. 

- 추가적으로 검색 기능에 새로 알게된 debounce [(해당 커밋)](https://github.com/woowacourse/javascript-movie-review/pull/22/commits/76edba57b3a8f5e8cec5b68eef20fa97ba87ce07)와 없는 이미지를 대체하는 기능[(해당 커밋)](https://github.com/woowacourse/javascript-movie-review/pull/22/commits/468b562b39c03e4176230573a91297b6e3a5f502)을 더했습니다 🎉

2023-03-22 17:02 UTC, ddongule requested changes

2023-03-23 16:36 UTC, merged