[1단계 - 영화 목록 불러오기] 레고(박정규) 미션 제출합니다.
woowacourse/javascript-movie-review pull request #24
Opened 2023-03-16 08:38 UTC by regularPark

안녕하세요 헤인티!👋 솔로스타와 영화 리뷰 - 웹 앱 페어프로그래밍을 한 레고입니다!

---

PR 메시지 작성 예정입니다
---
이번 미션의 

구조도
```
📦src
 ┣ 📂assets
 ┃ ┣ 📜common.css
 ┃ ┣ 📜logo.png
 ┃ ┣ 📜reset.css
 ┃ ┣ 📜search_button.png
 ┃ ┣ 📜star_empty.png
 ┃ ┗ 📜star_filled.png
 ┣ 📂components
 ┃ ┣ 📜MovieList.ts
 ┃ ┣ 📜MovieListItem.ts
 ┃ ┗ 📜Skeleton.ts
 ┣ 📜client.ts
 ┣ 📜index.ts
 ┗ 📜movies.type.ts
```

작성 예정

2023-03-16 12:48 UTC, woowahan-cron commented
비동기가 익숙하지 않고 많이 어려우셨죠?
내일 수업 시간에 힌트를 좀 더 드릴테니 이번 기회를 통해서 비동기와 친해지는 계기가 되셨으면 합니다!

2023-03-18 06:42 UTC, HyeonaKwon requested changes
안녕하세요 레고! 이번 미션의 리뷰어인 헤인티입니다. 리뷰가 너무 늦어져서 죄송해요! 🥲

상대적으로 적은 컴포넌트와 짧은 코드로 서비스를 구현하신게 신기하네요 ㅎㅎ 그런데 살짝 아쉬운건 엘리먼트를 다른 엘리먼트의 자식으로, 자식노드의 누구로 등등 이런식으로 구해와서 누구를 나타내는건지 파악이 안되는 곳들이 있었어요! 변수 이름에 잘 나타나있지도 않았구요! 고런 부분들을 좀 더 고민해보면 좋을 것 같습니다 ㅎㅎ

이외에는 코멘트 확인 부탁드립니다! 미션 구현하시느라 고생 많으셨어요 ㅎㅎ

(아 그리고 현업에서도 스켈레톤이나 로딩화면을 보여주기 위해 일부러 시간을 두는 경우도 있어요! 그런 부분은 걱정 안하셔도 될 것 같습니다!)

2023-03-18 06:42 UTC, HyeonaKwon commented on cypress/support/commands.ts
> +// }
cypress 의 command 를 이용해봐도 좋을 것 같네요!

2023-03-18 06:42 UTC, HyeonaKwon commented on src/assets/common.css
> +hr ~ * {
~ 은 어떤걸 의미하는 selector 일까요?

2023-03-18 06:42 UTC, HyeonaKwon commented on functions/tmdb.js
tmdb가 어떤 줄임말이에요??

2023-03-18 06:42 UTC, HyeonaKwon commented on functions/tmdb.js
아 themoviedb 줄임말이 tmdb 군요 ㅋㅋㅋ 이걸 파일명으로 쓴 이유가 있나요?

2023-03-18 06:42 UTC, HyeonaKwon commented on src/client.ts
> +export default client;
api 에서 server 와 client 여서 파일명이 client 일까요? 그렇게 따지면 이 프론트 서비스 전체가 client 가 아닐까요?!
파일명에 역할이 드러나도록 지어보면 좋을 것 같아요!

2023-03-18 06:42 UTC, HyeonaKwon commented on src/components/MovieList.ts
> +  constructor(private readonly fetchFn: MoviesGenerator, private readonly title: string) {
생성자의 파라미터에 접근제어자를 붙인 것과 붙이지 않은 것에는 어떤 차이가 있을까요?

2023-03-18 06:42 UTC, HyeonaKwon commented on src/components/MovieList.ts
> +  private async load() {
함수가 너무 길지는 않나요?

2023-03-18 06:42 UTC, HyeonaKwon commented on src/components/MovieList.ts
> +      });
요거는 왜 하는거에요?!

2023-03-18 06:42 UTC, HyeonaKwon commented on src/components/MovieList.ts
> +        const $fragment = document.createElement('div');
div element 인데 fragment 가 맞을까요?

2023-03-18 06:42 UTC, HyeonaKwon commented on src/components/MovieList.ts
> +      }, 5000);
movieList 가 popup 의 로직까지 가지고 있어야 할까요?

2023-03-18 06:42 UTC, HyeonaKwon commented on src/components/Skeleton.ts
> +</li>`;
depth 를 맞추면 좋을 것 같아요!

2023-03-18 08:47 UTC, regularPark commented on src/assets/common.css
> +hr ~ * {
한 페이지에서 보여줘야하는 20개의 `movieItem` 외 나머지 `li`를 화면에 보여주지 않기 위해서 `hr`에 뒤따르는(`~`) 모든(`*`) Element 들을 `display:none`해주었습니다!😄

2023-03-18 09:12 UTC, regularPark commented on src/components/MovieList.ts
> +  constructor(private readonly fetchFn: MoviesGenerator, private readonly title: string) {
접근제어자를 붙이지 않은 경우에는 
```typescript
private title:string = "";

constructor(fetchFn: MoviesGenerator, title:string) {
  this.title = title;
}
```
위와 같은 형태로 인자로 받아온 `title`을 할당해줘야했다면, 생성자의 파라미터에 접근제어자를 붙임으로써 인자를 받아옴과 동시에 this.title로 사용 가능해집니다!

2023-03-18 09:23 UTC, regularPark commented on src/components/MovieList.ts
> +  constructor(private readonly fetchFn: MoviesGenerator, private readonly title: string) {
접근제어자를 붙이지 않은 경우에는 
```typescript
private title:string = "";

constructor(fetchFn: MoviesGenerator, title: string) {
  this.title = title;
}
```
위와 같은 형태로 인자로 받아온 `title`을 할당해줘야했다면, 

생성자의 파라미터에 접근제어자를 붙인 경우에는 

```typescript

constructor(private fetchFn: MoviesGenerator, title: string) {
  // something without assign param
}

init() {
  console.log(this.title) // title 출력
}
```

인자를 받아옴과 동시에 클래스의 프로퍼티로 초기화하기 때문에 클래스 내부에서 this.title로 사용 가능해집니다!

2023-03-18 09:26 UTC, regularPark commented on src/components/MovieList.ts
> +      });
스켈레톤을 보여주기 위한 장치입니다! 로컬로 테스트해봤을 때 스켈레톤이 보이지 않을 만큼 fetch가 빠르게 진행돼서 의도적으로 설치해보았고, 배포 후에는 오히려 fetch가 느려서 자연스럽게 스켈레톤 UI를 보여드릴 수 있었는데요. 가능하다면 airbnb 사이트처럼 로딩이 된 이미지만 스켈레톤과 교체하도록 구현할 예정이라, 이후에는 삭제할 것 같습니다!😄

2023-03-18 10:13 UTC, regularPark commented on functions/tmdb.js
앗😱 이 파일은 api키를 숨기고 배포하기 위해서 여러 방법을 시도해보다가 지우는 것을 잊은 흔적이에요😅 마감시간이 임박했어서 네이밍에 신경을 쓰진 않았답니다.. 파일 삭제하도록 하겠습니다😅

2023-03-18 11:49 UTC, regularPark commented on src/components/MovieList.ts
> +  private async load() {
리팩토링하여 함수의 길이를 줄여봤습니다!

[067dd30](https://github.com/woowacourse/javascript-movie-review/pull/24/commits/067dd30ce7df88b345d79fce401ddf7787af99a7)

2023-03-18 11:54 UTC, regularPark commented on src/components/MovieList.ts
> +        const $fragment = document.createElement('div');
`$fragment`에 `movie` 관련 요소를 담아 쓴다고 생각하여 네이밍한 것인데, 굳이 그럴 필요까진 없었다는 생각이 드네요. `$div`로 변경하였습니다!😄

2023-03-18 11:56 UTC, regularPark commented on src/components/MovieList.ts
> +      }, 5000);
구현에 하느라 컴포넌트화하지 못한 부분이네요. popup관련 로직은 `ErrorPopup`으로 분리하였습니다!

2023-03-18 11:56 UTC, regularPark commented on src/components/Skeleton.ts
> +</li>`;
depth 수정하였습니다!😄

2023-03-18 12:30 UTC, regularPark commented on src/client.ts
> +export default client;
`MovieAPI`와 `FetchMovies` 중 고민하다가 일단은 `MovieAPI`로 변경해봤는데, 더 적합한 네이밍이 있을까요?🤔

2023-03-18 12:38 UTC, regularPark commented on cypress/support/commands.ts
> +// }
해당부분 학습하고 2단계에 적용해보도록 하겠습니다😇

2023-03-18 14:47 UTC, HyeonaKwon commented on src/assets/common.css
> +hr ~ * {
음 넵! ~ 셀렉터를 알고 사용하셨는지 궁금했습니다 ㅎㅎ

2023-03-18 14:48 UTC, HyeonaKwon commented on src/client.ts
> +export default client;
좋습니다!

2023-03-18 14:49 UTC, HyeonaKwon commented on src/components/MovieList.ts
> +  constructor(private readonly fetchFn: MoviesGenerator, private readonly title: string) {
굳! 잘 알고 계시는군요

2023-03-18 15:05 UTC, HyeonaKwon approved these changes
수정사항 확인했습니다 레고! 👍 2단계에서 봬요!

2023-03-18 15:05 UTC, merged