[1단계 - 영화 목록 불러오기] 헤다(윤다혜) 미션 제출합니다.
woowacourse/javascript-movie-review pull request #31
Opened 2023-03-16 08:47 UTC by Dahyeeee

2023-03-16 12:39 UTC, woowahan-cron commented
> 다만 시간이 너무 부족해서 코드가 개인적으로 정말 … 마음에 들지 않습니다. 페어와 더 많은 논의를 못하고 기능구현에 급급했던거 너무너무 아쉽고 어려웠습니다. 리팩토링으로 변화된 코드를 선보일(?) 수 있으면 좋겠습니다 ㅠㅠ

이번에 시간이 많이 부족했을 거예요. 
그렇지만, 프런트엔드에서 외부 API에 요청을 날리는 것부터가 진짜 시작이라고 할 수 있답니다~🥲
오늘의 두려움이 내일의 자신감이 될 수 있도록 크론이 응원할게요.

리뷰어님의 피드백으로 감당 가능한 만큼은 꼭 챙겨보시고 레벨1 마지막까지 힘내봅시다 💪

2023-03-17 15:01 UTC, Tanney-102 requested changes
안녕하세요 헤다!
리뷰어 브콜입니다~
미션 진행하시느라 정말정말 고생 많으셨어요!

마음에 들지 않는다고 말씀해주신 것 치곤 꽤나 잘 작성된 코드라고 생각해요.
특히 데이터를 관리하는 도메인이 아주 잘 분리 되어 있어 좋았습니다.
덕분에 단순한 앱 답게 컴포넌트도 단순하게 잘 작성될 수 있었던 것 같아요.

> 다만 컴포넌트마다 rerender에 필요한 인자값이 달라서 결국 subscribe가 3개가 되었는데 굉장히 마음에 안들어서 리팩토링 예정입니다. ㅠㅠ

데이터 변경에 반응하려는 이상 각 데이터 마다 subscriber가 있는 건 자연스러워 보입니다.

> 관심사를 분리한다고 했는데… 어떠신가요 브콜..ㅎㅎ

앞에서도 언급했지만 아주 잘 분리하셨다고 생각해요👍
Manager 안에서  데이터 변경 => publish 하는 흐름도 좋았고 각 UI 컴포넌트도는 데이터를 받아 잘 그려주기만 하도록 하신점이 좋았어요.

> 구조 변화에도 관심이 있으니.. 혹시 제안하고 싶으신게 있으시다면 제안해주시면 열심히 공부하고 알아봐서 리팩토링 해보겠습니다.

크게 변경해야할 지점은 없다고 생각합니다.
오히려 시도해보고 싶은 게 있으시다면 해보시고 리뷰 요청 주셔도 좋을 듯 합니다.

> 테스트, 못했습니다. 시간이 부족한 게 컸습니다. 하지만 사실 이번 미션의 도메인 로직이 많지가 않았고, UI 테스트는 개인적으로 유의미성을 느끼지 못하고 있습니다. 너무 오만한 생각을 하고 있는 걸까용..

UI가 되었든, 어떤 함수가 되었든 테스트는 항상 의미가 있습니다.
또 로직이 많지 않더라도 테스트 할 수 있는 부분은 충분히 있었다고 생각해요~
물론 어느 정도 이해는 갑니다.
간단한 기능이라면 테스트보다 QA가 빠를 수 있고, UI 테스트 몇가지 하는 게 얼마나 더 의미가 있을지도 모르겠고..
개발할 때 테스트가 어떤 의미를 갖는지 탐구해보시면 어떨까요?
테스트가 '누구'에게 '어떤' 신뢰를 주는지
테스트를 '작성하는 일' 그 자체에는 어떤 장점이 있는지
알아보고 고민해보시면 좋겠습니다.

2023-03-18 14:43 UTC, Dahyeeee commented on src/component/basic/CustomElement.js
> +class CustomElement extends HTMLElement {
movieManager 쪽에서 customElemenet를 subscriber로 넣어서 사용할 때 인터페이스가 필요해서 정의했습니다! 여기는 UI인 js파일이라서 따로 타입을 사용하지 않았습니다.

2023-03-18 14:43 UTC, Dahyeeee commented on src/component/movie/MovieListSkeleton.js
> +  }
skeleton가 가지고 있는 render가 template을 요소에 부착해주고, rerender하면 template을 제거하는 방식입니다.

manager쪽에서 데이터를 받아오기 전에 skeleton을 보여주고 데이터가 다 받아온 후에는 rerender를 호출해서 skeleton을 제거하는 형식으로 구현한 것인데 메소드명과 맞지 않는 행동을 하는 것 같습니다!

remove로 이름을 바꾸고 manager쪽에서 호출하도록 수정했습니다.

633790f0d763833f22d722d058d38b7a18d0cacb

2023-03-18 14:44 UTC, Dahyeeee commented on src/util/api.ts
오.. 깊게 생각해보지 못한 부분이네요! 
범용적으로 사용될 수 있는 함수를 util이라고 생각했는데 
이 앱에서는 request가 util에 속하고 url은 도메인에 속하는 것 같아서 분리했습니다. 
8e00269bf96675fc38cbbdb6eaa8f60004ead923

2023-03-18 14:46 UTC, Dahyeeee commented on src/util/api.ts
> +};
`추상적인 구현체에서 구체적인 정책은 가급적 피해주세요.`

이 부분도 생각해본적이 없는 것 같은데 앞으로 적용할 수 있는 지점이 많을 거 같습니다! 감사힙니다 :) 
8e00269bf96675fc38cbbdb6eaa8f60004ead923

2023-03-18 14:47 UTC, Dahyeeee commented on src/type/movieType.ts
> +export interface ModelData {
전반적으로 파일과 타입 네이밍을 변경했습니다.
fdb7c4530267178b8dda3c1cde932f7175165fb7

2023-03-18 14:48 UTC, Dahyeeee commented on src/type/componentType.ts
> +}
네네! 제네릭도 이번 기회에 다시 한 번 공부하면서 적용해봤습니다.
dae4f5397c0e26beeabb1d65e39872f7deae5de7

2023-03-18 14:49 UTC, Dahyeeee commented on src/domain/MovieModel.ts
> +  }
뭔가 버그가 나면 async await 붙여볼까..? 하며 해결했던 꼼수를 들켰네요! ㅠㅠㅎㅎ

여기서 필요없는 명령어라 삭제했습니다. async 동작원리를 좀 더 공부해야겠군요.

2023-03-18 14:52 UTC, Dahyeeee commented on src/domain/MovieModel.ts
> +  }
오호오호, 그렇군요!

이번 앱에서 사용한 api 정보는 매일 업데이트 된다고 나와있어서 괜찮지 않을까? 했는데 앱을 계속 켜놓는 경우와 자정에 페이지를 사용하는 경우 등을 고려했을 때 업데이트해주는 게 좋을 거 같네요!

2023-03-18 14:58 UTC, Dahyeeee commented on src/domain/MovieManager.ts
> +  }
boolean 값에 따라 버튼을 보여주고 안보여주고를 결정해서 toggle을 생각했던 것인데 적절하지 않았네요.
이 부분 로직은 rerender때 인자로 받은 page와 totalpage를 비교해서 숨기거나 안숨기도록 변경했습니다.

6a2741621b5b07b34ea7389983f273b194de59ba
06d48c4b839f152abd83369a63081a34ff70473d

2023-03-18 14:58 UTC, Dahyeeee commented on src/domain/MovieManager.ts
> +    });
아.. 아니요 ... 😓

2023-03-18 15:02 UTC, Dahyeeee commented on src/domain/MovieManager.ts
> +    });
publish는 manager 내부에서 사용하는 메소드이고 show는 외부에서 사용하는 메소드로 적용했습니다! 
그럼에도 아직 통일감이 없어서 좀 더 리팩토링 진행해보겠습니다.

633790f0d763833f22d722d058d38b7a18d0cacb

2023-03-18 15:07 UTC, Dahyeeee commented on src/domain/MovieManager.ts
> +  private skeleton: CustomElement[] = [];
엘리먼트의 하나의 메소드만 사용하는 게 아니라 'rerender' 'remove'등 UI 업데이트 상황에서 다양한 메소드를 불러줘야 해서 지금의 구조로서는 엘리먼트를 받아 메소드를 호출하는 게 좋아보입니다. 
또 엘리먼트끼리 가진 interface가 동일해서 rerender메소드를 foreach문을 돌며 한꺼번에 리랜더 시켜주는 게 괜찮은 로직으로 느껴지기도 합니다.

브콜 말대로 확장성이 없는 점이 아쉽지만 subscirbe로 메소드를 넘겨줄때 bind(this)나, 메소드를 화살표함수로 선언해줘야하는 부가적인 점보다는 현재의 방식이 조금 더 낫지 않을까 생각해봤습니다! 

어떠신가요 브콜? 😃

2023-03-18 15:07 UTC, Dahyeeee commented on src/component/head/SearchInput.js
> +  }
624f305c9c47677195e850db4499972c5d3bf221

2023-03-18 15:09 UTC, Dahyeeee commented on src/domain/MovieModel.ts
> +    });
이 코멘트 이해를 잘 못했습니당 ㅠㅠ
map으로 반환받는 값이 Movie type을 갖도록 명시해주는 걸까요?

2023-03-18 15:17 UTC, Dahyeeee commented
리뷰 감사합니다 브콜! 

테스트에 관한 의미있는 이야기 감사합니다! 
브콜이 말한대로 누구에게 어떤 의미가 있는지 고민해본적이 없네요. 이번 기회에 고민하고 적용해보고 제 나름의 정의를 내려갈 수 있으면 좋겠습니다. 👍 

큰 변경사항은 movie가 데이터(상태)를 가지고 있고 그 값을 가공, 변경, 제공해주는 class로 설계했고 movies 배열만 제공해주던 것을 page, totalPage등 모든 상태를 제공해주도록 했습니다.
그래서 값이 변화에 따라 리랜더가 필요한 컴포넌트에서는 모든 값을 받지만 필요한 값만 선택적으로 사용할 수 있도록 했습니다. 그래서 rerender 메소드 안에 동일한 data를 넘겨줄 수 있어서 코드가 간단해졌다고 느꼈습니다.
다만 각 컴포넌트에서 쓰이지 않는 값도 넘겨받아서 메모리 측면이나 성능측면에서 아쉽다고 느껴지는 지 궁금합니다. 

오류페이지를 만들고 manager 쪽에서 try/catch를 적용했더니 api 오류가 아닌 곳에서도 오류페이지만을 내보내서 디버깅이 어려워져서 일단 try/catch를 제거했습니다. movie쪽에서 해줘야할것 같아서 고민중에 있습니다!

2023-03-18 17:17 UTC, Tanney-102 commented on src/component/basic/CustomElement.js
> +class CustomElement extends HTMLElement {
아아 js 파일이군요~
넵 이해했습니다

2023-03-18 17:28 UTC, Tanney-102 commented on src/domain/MovieModel.ts
> +    });
설명이 부족했군요 죄송합니다🥲
map이 반환하는 타입을 강제하자는 취지 입니다.
지금 코드 상으로는 title 같은 거 하나 빠져도 타입에러를 내주지 않습니다.
물론 다른 곳에 제대로 타이핑 되어 있다면 거기서 에러가 나긴 하겠지만요..!
변수 할당 시마다 의도한 타입으로 정확하게 추론되도록 해주시면 좋겠습니다

2023-03-18 17:35 UTC, Tanney-102 commented on src/domain/MovieManager.ts
> +  private skeleton: CustomElement[] = [];
rerender, remove 같은 메서드가 필요한데 왜 Element 로 타이핑되어야하는지 잘 이해되지 않아요~
Manager에서 subscriber의 인터페이스를 정의하고 이 인터페이스를 기준으로 view에서 implement되어야 맞지 않을까요~?

2023-03-18 17:50 UTC, Tanney-102 requested changes
안녕하세요 헤다!
리뷰 반영뿐만아니라 리팩터링도 깔끔하게 잘 해주셨네요~
subscribe 방식이 나이스하게 잘 다듬어 진 것 같습니다!
두가지 정도 코멘트 더 남겨두었으니 확인 부탁드려요!

> 그래서 값이 변화에 따라 리랜더가 필요한 컴포넌트에서는 모든 값을 받지만 필요한 값만 선택적으로 사용할 수 있도록 했습니다. 그래서 rerender 메소드 안에 동일한 data를 넘겨줄 수 있어서 코드가 간단해졌다고 느꼈습니다.
다만 각 컴포넌트에서 쓰이지 않는 값도 넘겨받아서 메모리 측면이나 성능측면에서 아쉽다고 느껴지는 지 궁금합니다.

확실히 불필요하게 rerender 되는 곳이 있긴 하겠군요~
이를 해소하려면 각 데이터 마다 별개로 구독하는 방식이 되어야할텐데 지금 상황에서는 어느 게 더 좋다고 말씀드리기는 어렵겠네요😁
단순한 방식으로 rerender를 트리거 vs 필요한 만큼만 rerender 사이에서 트레이트 오프인듯합니다.
우선 지금 단계에서는 지금 구현해주신 걸로 충분할 것 같아요.

> 오류페이지를 만들고 manager 쪽에서 try/catch를 적용했더니 api 오류가 아닌 곳에서도 오류페이지만을 내보내서 디버깅이 어려워져서 일단 try/catch를 제거했습니다. movie쪽에서 해줘야할것 같아서 고민중에 있습니다!

manager에 error 상태를 하나 두고 rerender 할 때마다 전달하면 어떨까요?
manager는 의도한 에러에 대해 error 상태를 업데이트하고, 
view에서는 이 상태만 보고 error 를 보여줄지 말지 선택할 수 있도록!

2023-03-20 07:17 UTC, Dahyeeee commented on src/domain/MovieManager.ts
> +  private skeleton: CustomElement[] = [];
`Manager에서 subscriber의 인터페이스를 정의하고 이 인터페이스를 기준으로 view에서 implement되어야 맞지 않을까요~?`
오 이해가 갑니다!

데이터가 변경되었을 때 다 같이 리랜더 되는 컴포넌트(container, list, button)들의 rerender를 subscribers에 넣어줘서 호출해 줄 수 있겠네요. 
그렇게 변경을 해보았는데, skeletonSubscriber와 errorSubscriber는 hide와 show등 여러 메소드를 상황에 맞게 호출해줘야해서 컴포너트로 받아야 하는 상황입니다. 
그렇게 되면 subscriber는 함수를 갖고 있고, 나머지 필드는 컴포넌트를 들고 있는 상황이라 통일성이 떨어진다고 생각됩니다 ㅠㅠ 
어떻게 생각하시나요 브콜 😞

2023-03-20 11:19 UTC, Dahyeeee commented
오류처리가 생각보다 어려워서 오늘 하루 종일 고민하고 ㅠㅠ 브콜의 제안도 적용해보려고 했는데 이해가 부족했던 건지 잘 되지 않았습니다.

api 오류정보를 넘겨주는 함수를 만들어서 api오류일 때 error page(tag)를 랜더하도록 수정해봤습니다! 
throw로 오류를 던졌을 때 try catch를 어디서 해야할지 도저히 그림이 나오지 않아 지금의 방법으로 수정했습니다.
movie(data)쪽에서 하자니 화면을 다시 그려줄 수가 없고, mananger(domain)쪽에서 하자니 api오류가 아닌 다른 오류도 잡아버려서 난감했습니당..

아쥬 소소한 리팩토링 몇가지도 있는데 확인 부탁드려요 브콜!

2023-03-20 15:58 UTC, Tanney-102 commented on src/domain/MovieManager.ts
> +  private skeleton: CustomElement[] = [];
아하 그렇겠네요 ㅎㅎ
이렇게 놓고 생각해보니 슬슬 skeleton의 show여부를 도메인에서 관리하도록 한 게 어려움의 근원이지 않았을까 싶기도 해요.
도메인에서는 데이터를 fetch 중인지, 성공했는지, 실패했는지 정도만 가지고 있고 이 정보를 통해 view에서 skeleton을 그리든 다른 일을하든 했으면 어땠을까 싶네요!
우선 여기서 큰 변경은 하지말고 지금 잘 구현해주신 대로 우선 진행해보셔도 좋겠습니다~

2023-03-20 16:22 UTC, Tanney-102 approved these changes
안녕하세요 헤다~
하루종일 고민하셨다니..ㅠ
제가 필요이상의 고민을 안겨드린 것 같기도 하네요🥲
그래도 값진 시간이셨길.. 소망해봅니다.

그래도 제가 의도했던 바에 가깝게 접근 하신 것 같아요!
조금 더 아이디어를 드리자면
지금처럼 Manager에서 메뉴얼 하게 로딩(스켈레톤)이나 에러를 publish 하는 것도 좋지만 이걸 하나의 객체로 묶어 일관되게 publish 하는 방법도 있을 것 같아요.
```ts
interface SomeResult<T> {
  status: 'loading' | 'success' | 'failure''
  data: T
  error: Error
}
```

요런식으로 변경이 있을 때마다 던져주고 이를통해 스켈레톤을 보여주든 에러를 보여주든 view에서 알아서 하도록 해볼수 있습니다.
뭐 이렇게까지 하지 않고 Promise를 하나 던져줘도 될 것 같긴하지만요.

어디까지나 참고를 위한 예시이니 지금 코드에 적용은 고려만 해보셔요!
이미 충분히 좋은 코드를 작성해주셨습니다.
더 개선하고 싶은 욕심이 있으시겠지만 우선 이번 스텝은 여기서 머지할까합니다.
고생많으셨어요. 다음 스텝에서 뵙겠습니다!

2023-03-20 16:22 UTC, Tanney-102 commented on src/component/movie/MovieContainer.js
> +    }
오호 재밌는 접근 방식이네요~
여기서 더 나아가서 rerender의 인자로 들어오는 값중 실제 내가 그리려는 view와 관련한 정보가 변경되었는지 확인하는 방식으로 최적해봐도 재미있는 도전이 되겠네요! (당장 하시기를 기대하는 건 아닙니다. 다음 스텝 요구사항에 집중해주세요!)

2023-03-20 16:23 UTC, merged