[1단계 - 영화 목록 불러오기] 패트릭(박근철) 미션 제출합니다.
woowacourse/javascript-movie-review pull request #32
Opened 2023-03-16 08:47 UTC by GC-Park

안녕하세요 리트 !

이번에 타미와 같이 미션을 한 패트릭이라고 합니다 !

## 고민한 점
추후 작성

## 궁금한 점
추후 작성

## 홈페이지 링크
추후 작성

2023-03-16 12:37 UTC, woowahan-cron commented
리뷰어님의 의견은 다를 수 있지만, "성능적인 부분이 기능을 적용하지 않는 이유가 될 수 있을까요 ?!" -> Skeleton을 접목시키는 건 이번 미션의 요구사항이었답니다!

2023-03-17 15:49 UTC, lsw1164 requested changes
안녕하세요 패트릭, 코드 잘 봤습니다!  
컴포넌트에 대한 고민과 더 작은 단위로 쪼개는 시도 멋지군요👍   
전반적으로 코드 이해하기 좋았습니다 :)

코멘트 참고해주세요!

2023-03-17 15:49 UTC, lsw1164 commented on cypress/e2e/movieTest.cy.js
> +  it('API 요청을 보냈을 때 정상적으로 응답하는지 확인한다.', () => {
e2e 테스트 항목으로 단순 api 요청 테스트가 적절할까요?🤔  

사용자 관점에서 검증해본다면 api 호출이 정상 응답하는 지 보다는  
'영화 리스트가 잘 보이는 지'가 관심사일 거 같아요

2023-03-17 15:49 UTC, lsw1164 commented on cypress/e2e/movieTest.cy.js
> +      cy.get('.btn').should('have.class', 'button-close');
button-close가 버튼이 안보이는 다는 의미군요?

2023-03-17 15:49 UTC, lsw1164 commented on src/types.ts
> +  success: boolean;
내부적으로 또 성공과 실패가 나뉘는 걸까요? 🤔
- 실패 응답이지만 성공한
- 실패 응답이지만 실패한

2023-03-17 15:49 UTC, lsw1164 commented on src/fetch.ts
> +  `https://api.themoviedb.org/3${params}?api_key=${process.env.MOVIE_API_KEY}&language=ko-KR&page=${page}&query=${query}`;
API키를 환경값으로 관리하는군요👍

2023-03-17 15:49 UTC, lsw1164 commented on src/components/Skeleton/index.ts
> +  $movieItems: HTMLElement;
외부 접근을 허용한 걸까요?  
필드와 메서드 모두 내부 접근 요소인지 외부 접근을 허용할 지 고민해보면 좋을 거 같아요

2023-03-17 15:49 UTC, lsw1164 commented on src/components/MovieList/index.ts
> +    this.querySelector('h2')!.innerText = title;
태그로 요소를 찾으면 어떤 단점이 있을까요?  
또, !를 써주셨는데 만약 돔객체를 못찾은 경우 처리할 수 있는 다른 방법은 없을까요?

2023-03-17 15:49 UTC, lsw1164 commented on src/components/Skeleton/index.ts
> +    this.$movieItems = document.querySelector('.item-list')!;
item-list는 해당 컴포넌트 보다 상위 레벨의 UI 요소인가요?  
의존 관계가 어떻게 되는걸까요 🤔

2023-03-18 08:06 UTC, lsw1164 commented on src/components/Skeleton/index.html
> +</li>
스켈레톤UI 관련하여 구간을 나눠서 생각해보면 어떨까요?

### api 호출하여 데이터 받아오는 구간
- 스켈레톤을 적용하게 되면 컴포넌트 전체를 정적 스켈레톤으로 보여줄 수밖에 없을 거 같아요
  
### api 데이터는 받아왔지만 아직 이미지는 로드 되지 않은 시점
 - 텍스트 정보는 실제로 보여줄 수 있고 이미지 부분만 스켈레톤이 필요하겠군요

2023-03-19 06:39 UTC, GC-Park commented on cypress/e2e/movieTest.cy.js
> +describe('template spec', () => {
아이고 바꾼다는게 꼼꼼하지 못했네요 !  수정하였습니다 ! ㅎㅎ

2023-03-19 06:49 UTC, GC-Park commented on cypress/e2e/movieTest.cy.js
> +  it('API 요청을 보냈을 때 정상적으로 응답하는지 확인한다.', () => {
API 규격대로 서버에서 응답하고 있는지 직접 확인을 위해 단순 api 요청 테스트를 생성 했었습니다 !

리트의 이 리뷰를 통해 e2e테스트의 목적을 다시 생각하게 되었고, e2e테스트는 최대한 실제 사용자가 앱을 사용하듯 작성하여

실제 사용할 때 생길 수 있는 문제를 사전에 검증하는게 목적이라는 것을 리마인드 할 수 있었습니다.

리트의 말대로 단순 api 요청 테스트 보다는 영화 리스트가 잘 보이는 지에 대한 테스트로 수정하는 것이 좋을 것 같습니다.

감사합니다 ㅎㅎ !

2023-03-19 07:14 UTC, GC-Park commented on cypress/e2e/movieTest.cy.js
> +      cy.get('.btn').should('have.class', 'button-close');
네 맞습니다! 페이지 끝에 도달한 경우 '더 보기' 버튼이 사라지도록 하는 요구사항이 있었습니다 !

이것을 html 클래스 속성을 이용하여 구현하였고 e2e테스트를 할 때 이용한 것입니다 !

2023-03-19 07:33 UTC, GC-Park commented on src/types.ts
> +  success: boolean;
이 부분은 저희가 fetch를 할 때 에러들을 처리하기 위해 TMDB에서의 API Status Codes 형태를 따서 만든 interface 입니다 !

<img width="560" alt="스크린샷 2023-03-19 오후 4 24 27" src="https://user-images.githubusercontent.com/72205402/226160369-eb886be6-c462-46ff-b8b2-109277c6a93b.png">
이 사진을 보시면 TMDB에 api요청을 보냈을 때 에러가 발생할 경우 이런 형태로 온다는 것을 알 수 있습니다 !

저희가 따로 내부적으로 성공과 실패로 나눴다기 보다는 에러를 처리하기 위한 타입이 필요했고 위의 에러 응답을 참고해서 만들었습니다 !

2023-03-19 07:38 UTC, GC-Park commented on src/fetch.ts
> +  `https://api.themoviedb.org/3${params}?api_key=${process.env.MOVIE_API_KEY}&language=ko-KR&page=${page}&query=${query}`;
네 ! 깃헙에 올릴 때 api 값을 숨기기 위해 환경값을 사용했습니다.

좋은 경험이었고 네트워크에서도 api 값을 숨기는 방법을 적용해 보려고 했는데 아직 역량이 부족하여 실패하였습니다.

필요하다는 생각이 들면 다시 시도해보고 싶습니다 !

2023-03-19 08:04 UTC, GC-Park commented on src/fetch.ts
> +    if (error instanceof Error) alert(error.message);
api 호출이 하나가 아니고 여러개일 경우 확인하는데 어려움이 생길 것 같습니다 !

validation 파일을 만들고 UI 로직을 분리하도록 하겠습니다 !

생각하지 못했던 부분들을 알려주셔서 정말 감사합니다 ㅎㅎ

+추가
"api 호출이 하나가 아니고 여러개일 경우 확인하는데 어려움이 생길 것 같습니다 !"라고 생각하였는데 리트가 생각하는 것과 비슷할까요 ?!

리트의 생각도 궁금합니다 !!

2023-03-19 08:51 UTC, GC-Park commented on src/components/Skeleton/index.ts
> +  $movieItems: HTMLElement;
클래스 필드는 private으로 바꿔도 될 것 같고 메서드는 다른 파일에서 쓰이고 있어 접근을 허용해야할 것 같습니다 !

리트는 어떻게 보시나요 ?!!

2023-03-19 10:54 UTC, GC-Park commented on src/components/MovieList/index.ts
> +    this.querySelector('h2')!.innerText = title;
똑같은 태그들이 생겼을 때 구분하기가 어렵다는 단점이 있을 것 같습니다 !

타입 단언의 !를 썼는데 타입을 주입하는거라 아무것도 가져오지 않을 때도 실행이 되는 문제가 있습니다.

이를 해결하는 또 다른 방법으로는 옵셔널 체이닝과 if문 사용인데 옵셔널 체이닝은 할당과 같이 사용할 수 없어

이 문제를 처리하기 위해서는 if문을 사용해야 할 것 같습니다 !

태그로 요소를 찾는 단점과 타입 단언 말고 다른 방법을 설명하긴 했으나 확신이 안드네요 ... 허헣

리트의 의견도 들어볼 수 있을까요 ?!!

2023-03-19 11:11 UTC, GC-Park commented on src/components/MovieItem/index.ts
> +  }
타입 단언을 해주면서 에러가 뜨지 않게 하려고 썼던 것 같습니다.. 🥲

?? 문법을 써서 ?? 앞의 값이 null이거나 undefined일 때 뒤의 값을 반환해주는 식으로 바꿔주면 될 것 같습니다 !
ex)  .replaceAll('{title}', this.getAttribute('title') ?? '알 수 없음')

혹시 다른 방법이 있을까요 ?!

2023-03-19 11:30 UTC, GC-Park commented on src/App.ts
> +    this.store.getMovieList(this.store.searchWord).then(() => {
1. 메서드의 기능과 좀 더 맞는 allocateData로 이름을 변경하였습니다 !

2. 아 ! 반환된 값을 쓰는 경우가 아니기 때문에 then()보다는 async/await을 쓰면 메서드의 길이를 줄일 수 있을 것 같습니다 !  수정하도록 하겠습니다 ㅎㅎ

2023-03-19 11:34 UTC, GC-Park commented on src/components/Skeleton/index.ts
> +    this.$movieItems = document.querySelector('.item-list')!;
item-list의 자식 요소로 스켈레톤이 추가되거나 삭제됩니다 ! 

상위 레벨의 정확한 의미는 모르지만 자식 요소와 부모 요소의 관계라는 점에서 상위 레벨이라고 말할 수 있을 것 같습니다 !

2023-03-19 11:39 UTC, GC-Park commented on src/components/Skeleton/index.html
> +</li>
지금까지는 setTimeout을 써서 영화 목록을 보여주기 전 몇초는 스켈레톤이 나타나는 방식이었습니다. 

정적인 방식이고 비효율적이라고 생각해 '더 보기' 버튼에는 적용하지 않았었습니다.

그러나 리트의 리뷰 덕분에 구간을 나눠서 생각해보기와 로드 되는 시점을 기반으로 스켈레톤을 전체로 보지 않고 하나하나로 볼 수 있을 것 같다는 생각을 하였습니다.

사실 리트가 많은 정보를 주었지만 아직 방법을 확실히는 모르겠습니다. fetch한 것들을 어떻게 구분하여 로드가 된 것들만 먼저 스켈레톤을 지우고 로드 되지 않은 것들을 스켈레톤을 유지할지.. 아직 고민할 것들이 남은 것 같습니다.

리트, 이 부분에 대해서는 최대한 고민을 해보고 적용해 보도록 하겠습니다!

2023-03-20 01:49 UTC, GC-Park commented
안녕하세요 리트 !

저번에 DM으로 언제 리뷰 주실지 말씀해 주셔서 정말 감사했어요! 그리고 이렇게 정성스러운 리뷰까지..!

리트의 리뷰를 보면서 공부하고 이해한 후 적용하려고 하였습니다. 또한 궁금한 사항들은 코멘트로 남겨 두었습니다!

리트의 의견을 듣고 싶은 부분도 많고 아직 해결하지 못한 스켈레톤, 타입 단언 등이 있어 이렇게 먼저 리뷰 요청을 드립니다!

다시 리뷰 주실 때까지 계속 고민하고 시도해 보도록 하겠습니다 

이번 피드백 다시 한번 잘 부탁드립니다 !! 좋은 하루 되세요 !

2023-03-20 16:49 UTC, lsw1164 commented on src/types.ts
> +  success: boolean;
아 api 실패 응답인 경우에만 해당 인터페이스를 사용하는군요.  이해했습니다

2023-03-20 16:52 UTC, lsw1164 commented on src/fetch.ts
> +  `https://api.themoviedb.org/3${params}?api_key=${process.env.MOVIE_API_KEY}&language=ko-KR&page=${page}&query=${query}`;
물론, 실서비스에서는 api키를 숨겨야겠죠.  
하지만 그건 별도 서버가 필요하여 지금 미션에서 집중할 요소는 아닌 거 같아요😄

2023-03-20 16:57 UTC, lsw1164 commented on src/components/MovieList/index.ts
> +    this.querySelector('h2')!.innerText = title;
만약 반드시 필요한 돔객체라고 생각하신다면 못찾을 때 과감하게 에러를 throw 하는 것도 방법이라고 생각해요.  
개발 단계에서 에러가 발생해서 개발자가 빠르게 버그를 알아차리고 수정할 수 있죠.  
'빠른 피드백'의 장점을 활용하는 방법입니다.

2023-03-20 17:08 UTC, lsw1164 commented on src/components/Skeleton/index.ts
> +    this.$movieItems = document.querySelector('.item-list')!;
하위 컴포넌트가 상위 컴포넌트 요소에 직접 접근하는 방식을 권장하지 않는다는 얘기는 들어보셨을 거 같아요.  
그 이유를 한 번 고민해보시면 좋을 거 같습니다 🤔

2023-03-20 17:22 UTC, lsw1164 requested changes
패트릭, 피드백 반영해주신 거 확인했어요.  
타입스크립트에 점점 익숙해지는 거 같군요😄

그럼 다음 스텝으로 가기 위한 버그 픽스 요청드릴게요!

### 버그
'empty 이미지'가 한 번 생성되면 화면에서 사라지지 않아요😅  

![image](https://user-images.githubusercontent.com/39941911/226417260-81571579-31bd-4954-bf99-cd33bd0a1686.png)

2023-03-21 05:11 UTC, GC-Park commented on src/fetch.ts
> +  `https://api.themoviedb.org/3${params}?api_key=${process.env.MOVIE_API_KEY}&language=ko-KR&page=${page}&query=${query}`;
네 감사합니다 ㅎㅎ !!

2023-03-21 05:14 UTC, GC-Park commented on src/components/Skeleton/index.ts
> +    this.$movieItems = document.querySelector('.item-list')!;
고민하고 찾아보도록 하겠습니다 ! 감사합니다 !! 😊

2023-03-21 07:10 UTC, GC-Park commented
안녕하세요 리트 !

'더 보기' 버튼에 스켈레통을 입혀주면서 버그가 생겼던 것 같습니다. 각 상황에 맞게 스켈레톤이 생기도록 함수를 추가하여 해결하였습니다 !

또한 스켈레톤이 각 이미지의 로딩 순서에 맞게 스켈레톤이 나오고 없어지도록 하였습니다 !

addEventListner의 'load' 이벤트를 알게 되었고 페어의 도움을 받아 결국 해결할 수 있었습니다 !

좋은 제안 해주신거 감사하고 이번 피드백도 잘 부탁드립니다 좋은 하루 되세요 ㅎㅎ !

## 홈페이지 링크
https://gc-park.github.io/javascript-movie-review/dist/

2023-03-21 18:44 UTC, lsw1164 approved these changes
패트릭, 버그 픽스 확인했습니다! 스텝2 진행해주세요~

2023-03-21 18:44 UTC, lsw1164 commented on .github/workflows/deploy.yml
오 자동배포인가요? 👍

2023-03-21 18:44 UTC, lsw1164 commented on src/components/MovieItem/index.ts
> +    const b = this.querySelector('.skeleton');
급박함이 드러나는 네이밍일까요😅

2023-03-21 18:44 UTC, merged

2023-03-22 07:01 UTC, woowahan-cron commented on src/fetch.ts
> +  `https://api.themoviedb.org/3${params}?api_key=${process.env.MOVIE_API_KEY}&language=ko-KR&page=${page}&query=${query}`;
~~역량이 부족하여~~ 미션에서 요구하는 사항이 아니어서 실패하였습니다 <--

2023-03-22 08:37 UTC, GC-Park commented on src/components/MovieItem/index.ts
> +    const b = this.querySelector('.skeleton');
아이고..! 맞습니다... ㅋㅋㅋㅋ😂  2단계 제출할 때 꼭 수정하도록 하겠습니다 !

2023-03-23 12:19 UTC, lsw1164 commented on src/fetch.ts
> +    if (error instanceof Error) alert(error.message);
모든 호출부에서 alert가 뜰 필요는 없다고 생각했어요.   
각 호출부마다 에러를 핸들링하는 방식이 다를 수 있어요.     
어떤 호출부는 실패하더라도 유저도 모르게 조용히 처리하고 싶은 경우도 있을 거 같아요.

2023-03-23 12:22 UTC, lsw1164 commented on src/components/Skeleton/index.ts
> +  $movieItems: HTMLElement;
넵, 접근 제어자를 잘 활용하시는 게 좋습니다.
메서드가 외부 호출이 필요하면 public 유지해주시면 됩니다.
캡슐화👍