[1단계 - 영화 목록 불러오기] 아인(안근택) 미션 제출합니다.
woowacourse/javascript-movie-review pull request #46
Opened 2023-03-16 08:53 UTC by GEUNTAEK1013

파랑, 안녕하세요? 프론트엔드 5기 아인이라고 합니다.
이번에 제레미와 페어 진행하여 미션 제출합니다.

**학습 목표**

> API 연동을 위한 테스트 환경 경험
> 실제 동작하는 API를 통한 비동기 통신
> UX 경험 개선을 위한 더 보기(페이징) 구현
> 역할과 책임에 따라 관심사를 분리

**요구사항**

> 비동기 호출을 포함한 사용자 기능 플로우를 선정하고 기능을 포함하여 E2E 테스트를 작성한다.
> 특정한 패턴에 사고를 끼워 맞추지 않고 단지 역할과 책임에 따라 관심사를 분리한다.
> 도메인 영역을 TypeScript를 사용해 구현한다. (UI 영역은 선택)

위 조건에 따라 프로그래밍을 하였습니다.
부족한 부분이 많지만, 피가 되고 살이 되는 피드백 많이 부탁드립니다. 감사합니다🙋🏻‍♂️

2023-03-16 15:13 UTC, woowahan-cron commented
애니메이션의 아인처럼 불굴의 의지로 끝까지 성장하는 개발자가 되기길 바랄게요 🙏

2023-03-17 15:28 UTC, InSeong-So requested changes
안녕하세요, 아인! 리뷰어 파랑입니다😊

웹 컴포넌트를 적용하고, 커스텀 이벤트까지 알차게 사용하셨네요! 컴포넌트를 분리한 구조가 명확하여 폴더 구조가 잘 이해되었습니다.

비동기 쪽 플로우가 조금 아쉬운 감이 있는데, 이는 리뷰를 확인하시고 에러 핸들링에 대해 더 많은 명세를 작성하면 좋을 것 같아요.

배포된 기능을 확인한 결과, 아래의 기능은 개선하면 좋겠어요.
1. 첫 리스트를 로드할 때 스켈레톤이 적용되지 않음
2. 검색 시 해당 리스트가 없으면 검색 내용과 검은 화면만 나옴
3. 공백도 검색할 수 있음

공백을 입력하면 전체 리스트를 띄워주는 건 어떨까요? 아니면 유효성 검사도 좋을 것 같네요😊

리뷰 확인해주시고, 재요청주세요!

2023-03-17 15:28 UTC, InSeong-So commented on src/utils/fetch.ts
> +};
에러는 서버에서 메세지를 던질 수도, 더 많은 정보를 내포해야할 수 있습니다. 이 부분을 더 상세하게 작성하면 어떨까요?

2023-03-22 02:08 UTC, GEUNTAEK1013 commented on src/App.js
> +  async addPopularMoviesList() {
네 파랑 말씀대로 중복되는 로직이 있어 재사용 가능한 함수로 addMovieList()로 분리하였습니다.

2023-03-22 02:11 UTC, GEUNTAEK1013 commented on src/components/SkeletonList.js
> +    this.innerHTML = `
네, 중복되는 문자열 생성이 많아서 repeat로 처리하였습니다.

2023-03-22 02:11 UTC, GEUNTAEK1013 commented on src/index.js
> +import "./components/index";
실수로 제거하지 못했네요.😅
바로 수정하였습니다!!

2023-03-22 02:13 UTC, GEUNTAEK1013 commented on src/utils/Dom.ts
> +export const $ = (selector: string) => document.querySelector(selector);
네 타입 가드나, null이 반환되는 상황을 생각을 못했네요ㅜㅜ
if 조건문으로 간단하게 방어 코드를 작성하였는데, 혹시 이게 좋은 방법일까요?

2023-03-22 02:16 UTC, GEUNTAEK1013 commented on src/components/MovieSearch.js
> +    });
이번 미션에 custom element를 사용해 `this`가 가리키는것이 element라 `$`로 대체하였습니다.

2023-03-22 02:18 UTC, GEUNTAEK1013 commented on src/App.js
> +    `;
파랑 질문 있습니다.
내부 조건문들을 상수화가 아닌 변수화시키는 이유가 있을까요?
제 생각엔 변수화를 어떤 의도로 해야 할지 모르겠습니다ㅜㅜ

2023-03-22 02:23 UTC, GEUNTAEK1013 commented on src/components/MovieCardList.js
> +    const $movieList = $("#movie-list");
네 element을 가리키는 $movieList의 의미를 movieListElement로 변경하였습니다.

2023-03-22 02:25 UTC, GEUNTAEK1013 commented on src/components/MovieCardList.js
> +    $skeletonList.classList.toggle("none");
네 일관성을 갖추지 못했네요. display none을 삭제하고 classList로 통일하였습니다.

2023-03-22 02:30 UTC, GEUNTAEK1013 commented on src/utils/fetch.ts
> +};
네, 에러 처리를 조금 더 상세하게 작성하였습니다.
현재 기능에서 사용자에게 에러를 보여줄 수 있는 것이 서버 장애로 인한 메시지인데, 이외에 사용자에게 에러 메시지를 전달할 수 있는게 있을까요?

2023-03-22 07:15 UTC, GEUNTAEK1013 commented on cypress/e2e/app.cy.js
> +    cy.get(".search-button").click();
네 `custom command` 활용해서 테스트 코드 다시 만들었습니다.
command를 파일에 따로 분리해야 한다는 점을 몰라서 많이 헤맸네요ㅎㅎ
그런데 지금처럼 짧은 테스크 코드에서 custom command를 꼭 사용할 필요가 있는지 궁금합니다.🤔

2023-03-22 13:31 UTC, InSeong-So commented on src/App.js
> +    });
forEach를 통해 외부의 변수를 접근하여 직접 수정하는 것보다, 사본 배열을 반환하게 한 뒤 값을 추가하게 하면 어떨까요?

map API를 활용해보면 좋겠습니다.

2023-03-22 13:31 UTC, InSeong-So commented on src/components/MovieCardList.js
> +    if (this.#movieList.length < 20) moreButtonElement.classList.toggle("none");
20을 상수화하면 어떨까요?

2023-03-22 13:31 UTC, InSeong-So commented on src/components/MovieCardList.js
> +    if (null) return;
...????

2023-03-22 13:31 UTC, InSeong-So commented on src/constant/variables.ts
> +           <a href="#">
LIST 보다는 ITEM 또는 CARD가 맞을 것 같네요!

2023-03-22 13:31 UTC, InSeong-So commented on src/utils/Dom.ts
> +export const $ = (selector: string) => document.querySelector(selector);
방어 코드는 많으면 많을 수록, 검사하는 유효성이 많을 수록 좋습니다😄 호출하는 쪽이 아니라 `$` 함수 내부에 if문을 두면 어떨까요?

2023-03-22 13:32 UTC, InSeong-So commented on cypress/e2e/app.cy.js
> +    cy.get(".search-button").click();
custom command는 DX를 위한 것입니다. 짧은 코드에서도 여러 테스트 케이스에서 중복되는 코드가 많다면 만드는 게 좋지 않을까요?

2023-03-22 13:34 UTC, InSeong-So commented on src/App.js
> +    `;
현재 시점의 `내가` 읽는 게 아니라 다른 사람이 읽을 때 보기 좋은 코드가 가독성이 좋아야 직관성과 유지보수성이 올라가기 때문입니다.

`상수화가 아닌 변수화` 부분은 잘 이해가 안 되네요...

이 코드를 상수화 한다는 것일까요?
```js
this.#listState === LIST_STATE.POPULAR
        ? "지금 인기 있는 영화"
        : `"${this.#movieName}" 검색 결과`
```

2023-03-22 13:35 UTC, InSeong-So commented on src/utils/fetch.ts
> +};
network 에러와 서버에서 던져주는 유효성에 어긋날 때의 에러 두 가지 케이스가 있겠네요!

2023-03-22 13:38 UTC, InSeong-So approved these changes
코멘트에 대한 피드백 확인했습니다🤗
고생하셨어요!

나머지는 2단계 미션을 진행하면서 적용하면 좋겠네요.
데모에서의 UX 이슈는 계속 존재하는 것 같은데, 이것도 개선을 하면 좋겠습니다.

해당 미션은 머지하도록 할게요!

2023-03-22 13:38 UTC, merged

2023-03-23 02:07 UTC, GEUNTAEK1013 commented on src/utils/Dom.ts
> +export const $ = (selector: string) => document.querySelector(selector);
네, 저도 그게 맞는 것 같아 `$ `함수 내부에 방어 코드 작성하였습니다.

2023-03-23 02:09 UTC, GEUNTAEK1013 commented on cypress/e2e/app.cy.js
> +    cy.get(".search-button").click();
네 맞습니다. 다음부터는 custom command를 먼저 분리해서 작성하도록 하겠습니다.

2023-03-23 02:18 UTC, GEUNTAEK1013 commented on src/App.js
> +    `;
네, 삼항연산자 안에 있는 `인기있는 영화`, `검색 결과 `도 상수화 가능하지 않을까 합니다.
현재 시점의 내가 아니라 다른 사람이 읽기 좋은 코드를 작성해야 한다는 것을 간과했네요. 죄송합니다.
다음부턴 리펙터링을 하며 다른 사람이 이해하기 쉬운 코드, 가독성이 좋은 코드로 직관성을 올려보겠습니다.😄

2023-03-23 02:54 UTC, GEUNTAEK1013 commented on src/App.js
> +
죄송합니다. 의미 없는 코드라 삭제하였습니다.😅

2023-03-23 02:58 UTC, GEUNTAEK1013 commented on src/App.js
> +    }
그렇네요. 리펙터링이 부족했네요. 조건문을 하나로 수정하였습니다.

2023-03-23 06:30 UTC, GEUNTAEK1013 commented on src/App.js
> +  }
아 맞네요~!! 중복 코드 제거하고, initRender로 호출하고, 메서드명도 변경하였습니다.

2023-03-23 07:42 UTC, GEUNTAEK1013 commented on src/App.js
> +    });
네, 확실히 외부 변수에 접근해서 직접 건드리는 것보다 map으로 사본 배열을 반환한 뒤 값을 추가하는게 좋은 방법 같습니다.
감사합니다!!

2023-03-23 07:42 UTC, GEUNTAEK1013 commented on src/components/MovieCardList.js
> +    if (null) return;
의미 없는 코드임으로 삭제하였습니다ㅜㅜ

2023-03-23 07:46 UTC, GEUNTAEK1013 commented on src/constant/variables.ts
> +           <a href="#">
네 LIST보다는 list에 Item을 추가하는 템플릿이라 ITEM으로 변경하였습니다.

2023-03-23 07:47 UTC, GEUNTAEK1013 commented on src/utils/fetch.ts
> +  }
네, 의미없는 else 스코프 제거하였습니다.

2023-03-23 13:05 UTC, geuntaek1013 commented on src/App.js
> +    `;
아 그렇군요!! 잦은 변경이 필요한 도메인에 종속된 '동일한 문자'만 상수화가 필요했네요.
이 부분은 잘 몰랐습니다. 공부 더 해보도록 하겠습니다.🥲