[1단계 - 영화 목록 불러오기] 제레미(김민석) 미션 제출합니다.
woowacourse/javascript-movie-review pull request #47
Opened 2023-03-16 08:54 UTC by shackstack

안녕하세요 체프! 

이번 미션을 구현하기 앞서 페어와 함께 지난 미션에 대한 이야기를 나누었습니다. 저 같은 경우 템플릿 메서드를 통해 컴포넌트를 구현했었는데 렌더링 최적화를 구현하기 위해서는 각 컴포넌트의 render()메서드를 this바인딩하여 props로 넘겨주었습니다. 그렇게 하다보니 코드가 복잡해질 뿐더러 props Driling 문제가 발생하였습니다. 페어도 저와 비슷한 문제를 겪었고 이를 극복하기 위한 방안을 고민하다가 custom element를 활용하게 되었습니다. 

### 코드에 대한 설명...

App은 페이지, 영화 리스트 등의 상태를 관리하며 하위 컴포넌트에서 발생하는 이벤트들을 이벤트 버블링으로 처리해줍니다. 
- 컴포넌트를 다음과 같이 나누었습니다.
<img width="553" alt="스크린샷 2023-03-16 오후 5 52 43" src="https://user-images.githubusercontent.com/102432453/225564424-0b65a72a-51d2-4a61-aac3-d3429cd695f0.png">

- MovieSearch에서 검색 이벤트 발생시 App에서 영화리스트를 API로 요청하고, 받아온 데이터를 가공하여 MovieCardList로 넘겨주고 여기서 반복문을 돌려 MovieCard를 찍어냅니다. 
- 더보기 버튼 클릭시 App의 page상태가 +1로 변경되며 API로 변경된 페이지를 인자로 넘겨주어 요청하고 , 받아온 데이터를 가공하여 MovieCardList로 넘겨주고 여기서 반복문을 돌려 MovieCard를 append해줍니다. 

### 시도한 도전들

- Custom Element를 활용하여 웹 컴포넌트를 구현
- 환경변수 설정 

### 아쉬운 부분

- 환경변수를 뒤늦게 설정하는 바람에 커밋 기록에 API KEY가 노출되었습니다. 다음 미션부터는 초기에 환경변수 설정부터 해야겠네요..

2023-03-16 11:58 UTC, woowahan-cron commented
ㅠ_ㅠ
`API_KEY`를 이미 들켜버렸지만...
어떻게 감출 수 있을지 고민은 이어가 볼까요?

2023-03-18 07:43 UTC, Puterism commented
https://user-images.githubusercontent.com/2542730/226092399-eb214ab8-4b3c-48ff-990b-07042f60c23b.mp4

버그가 있는 것 같아요!

1. `팬더`라고 검색한다.
2. 메인으로 돌아온다.
3. [더 보기] 버튼을 누르면 `팬더`에 대한 결과가 뜬다.

2023-03-18 09:09 UTC, Puterism requested changes
제레미 안녕하세요! 이번 미션의 리뷰어를 맡게 된 체프라고 합니다
만나서 반갑습니다 😄 
API 호출과 응답까지 관리하는 진정한 프론트엔드 세계에 오신 것을 환영합니다 👏 👏 👏 

각 코드 라인에 피드백을 달아두었으니 확인 부탁드릴게요!

2023-03-18 09:09 UTC, Puterism commented on src/utils/fetch.ts
> +export const getSearchedMovies = async (movieName: string, page: number) => {
마찬가지로 getSearchedMovies도 `Promise<any>`로 추론될테니 영화 데이터에 대해서 타입을 꼭 지정해주세요.

2023-03-18 09:09 UTC, Puterism commented on src/App.ts
> +    this.toggleSkeletonList(); // remove skeleton list
toggle을 두 번 실행해서 주석으로 표시하는 것보다 addSkeletonList, removeSkeletonList를 만들어서 적용하는 것도 좋겠네요! toggle 되기 이전 상태가 어떤 상태인지 알 수 있는 방법이 없으니까요.

2023-03-18 09:09 UTC, Puterism commented on src/utils/fetch.ts
> +  const response = await fetch(
fetch API를 사용하면 이를 사용하는 곳에서 response.json()까지 반환해주어야 하는데요.
fetch하면 바로 data가 return 되도록 한 번 래핑해서 사용하면 더 사용성이 좋아질 것 같아요.

2023-03-18 09:09 UTC, Puterism commented on src/utils/fetch.ts
> +  alert("오류 발생");
어떤 오류가 발생한 건가요? 사용자가 볼 수도 있는 메시지이니 좀 더 상황을 잘 설명해주는 게 좋지 않을까요?

2023-03-18 10:52 UTC, shackstack commented on cypress/e2e/search.cy.ts
> +  })
검색 테스트를 app.cy.js에서 진행합니다. search.cy.ts를 지우는걸 깜빡했네요 😓

2023-03-18 10:54 UTC, shackstack commented on src/@types/global/index.d.ts
> +}
customElements에서 타입오류가 반복해서 발생하는 바람에 해결책을 찾다가 시도해본 흔적입니다... 지우는걸 깜빡했네요 😅

2023-03-18 10:55 UTC, shackstack commented on dist/bundle.js
넵 감사합니다. 😄

2023-03-18 10:59 UTC, shackstack commented on src/components/MoreButton.ts
> +          new CustomEvent("click-more-button", { bubbles: true }) //detail :
커스텀 이벤트에대해서 크루에게 도움을 받다가 안잊어버리려고 주석을 남겨두었는데 지우는걸 깜빡했네요 😅

2023-03-18 11:00 UTC, shackstack commented on src/components/MovieHeader.ts
> +    const $homeButtom = this.querySelector("h1");
아하! 좋습니다! :smile:

2023-03-18 11:01 UTC, shackstack commented on src/components/MovieSearch.ts
> +    $searchInput.addEventListener("keypress", (event) => {
keydown에서 버그가 발생해서 keypress로 바꿔봤더니 해결되었어요. 임시 방편으로 쓰고 있었는데 keydown으로 수정해서 버그고쳐보도록 하겠습니다.

2023-03-18 11:02 UTC, shackstack commented on src/utils/fetch.ts
> +  alert("오류 발생");
좋습니다...!

2023-03-18 11:03 UTC, shackstack commented on templates/index.html
>                      alt="앤트맨과 와스프: 퀀텀매니아"
템플릿 폴더에 제공된 index.html이라서 따로 건드리지 않았는데 수정할 필요가 있을까요?

2023-03-19 03:41 UTC, shackstack commented on src/utils/fetch.ts
> +  const response = await fetch(
좋습니다 👍 👍 👍

2023-03-19 03:44 UTC, shackstack commented on src/App.ts
> +    this.toggleSkeletonList(); // remove skeleton list
그쵸... 하나의 메서드로 관리하면 편하겠다 싶었는데 오히려 헷갈리게 되네요. 토글방식은 모달 컴포넌트나 별점 컴포넌트처럼 사용자가 쉽게 인지할 수 있는 데에 쓰는게 좋을 것 같습니다.

2023-03-19 03:46 UTC, shackstack commented on src/utils/fetch.ts
> +export const getPopularMovies = async (page: number) => {
좋습니다. 덕분에 타입스크립트랑 프로미스 두 가지를 어제 오늘 열심히 공부했습니다. 👍 👍

2023-03-19 04:04 UTC, shackstack commented on src/utils/fetch.ts
> +  alert("오류 발생");
좋습니다. 에러가 발생할 수 있는 상황을 더 고민해보고 추가해나가보도록 하겠습니다.

2023-03-19 04:04 UTC, shackstack commented on src/utils/fetch.ts
> +export const getSearchedMovies = async (movieName: string, page: number) => {
넵! 👍

2023-03-19 04:11 UTC, shackstack commented on dist/index.html
> +  <script defer src="bundle.js"></script></head>
async는 다른 자원들과 병렬로 다운로드되기 때문에, 다운로드 속도를 빠르게 만드는 데 유용합니다. defer는 스크립트 실행을 HTML 파싱 이후로 지연시켜 다른 자원들의 로딩을 빠르게 만드는 데 유용합니다. 그리고 아무 것도 없을 때 스크립트 다운로드와 실행이 다른 자원들과 순차적으로 진행되기 때문에, 다운로드가 느릴 경우 다른 자원들의 로딩 속도를 느리게 만들 수 있습니다. 잘몰라서 검색 자료 참고하여 답 드립니다. 덕분에 새로운 지식 하나 더 알게되었네요. 감삼돠 👍

2023-03-19 11:30 UTC, shackstack commented
체프! 즐거운 주말 되셨나요? 
보내주신 피드백 참고해서 수정해보았습니다. 

몇가지 궁금한 점이 있는데요. App의 메서드를 정렬할 때 저는 보통 실행 순서대로 정렬을 해왔습니다. 그런데 이전 미션들과는 달리 여러 시퀀스로 갈리다보니 정렬기준에 대한 혼란이 생겼습니다. 체프는 어떤 기준으로 메서드를 정렬하시는지 궁금합니다..! 

그리고 이번 미션을 정하면서 디자인 패턴에 대한 논의를 페어와 오래했었는데 결론이 나지 않아 일단 돌아가는 쓰레기를 만들고나서 리팩터링하면서 다시 고민해보기로 했었어요. 그런데 리팩터링을 하다보니 굳이 디자인 패턴을 적용할 필요가 있을까라는 의문이 들더라구요.. 이것에 대한 체프의 의견도 궁금합니다..!

2023-03-19 13:40 UTC, Puterism commented on templates/index.html
>                      alt="앤트맨과 와스프: 퀀텀매니아"
불필요한 더미 데이터 없이 템플릿 파일도 관리해주는 게 좋다고 생각합니다 :)

2023-03-19 13:55 UTC, Puterism commented on src/components/MoreButton.ts
> +          new CustomEvent("click-more-button", { bubbles: true }) //detail :
불필요한 주석이라면 잘 삭제해주세요 😃

2023-03-20 03:43 UTC, shackstack commented on src/components/MoreButton.ts
> +          new CustomEvent("click-more-button", { bubbles: true }) //detail :
넵!

2023-03-20 13:15 UTC, Puterism approved these changes
피드백 잘 반영해주셔서 감사합니다! 피드백은 각 코드 라인에 달아두었으니 2단계에서 이어가보시죠!
수고 많으셨습니다. 2단계도 화이팅입니다 💪 

---

> App의 메서드를 정렬할 때 저는 보통 실행 순서대로 정렬을 해왔습니다. 그런데 이전 미션들과는 달리 여러 시퀀스로 갈리다보니 정렬기준에 대한 혼란이 생겼습니다. 체프는 어떤 기준으로 메서드를 정렬하시는지 궁금합니다..!

상황에 따라서 다른 것 같아요. 웬만하면 실행 순서에 따라서 정렬하지만, 필요에 따라서 비슷한 도메인끼리 묶어서 정렬할 때도 있어요. 특히 클래스 같은 경우는 꼭 실행 순서에 따라서 정렬하지 않아도 되니까요. 여러 시퀀스로 갈린다는 말씀이 정확하게 무슨 뜻인지는 모르겠지만 실행 순서에 따라서 정렬하는 게 곤란해진다면 다른 정렬 기준을 세워서 배치해도 무방하다고 생각해요.

---

> 이번 미션을 정하면서 디자인 패턴에 대한 논의를 페어와 오래했었는데 결론이 나지 않아 일단 돌아가는 쓰레기를 만들고나서 리팩터링하면서 다시 고민해보기로 했었어요. 그런데 리팩터링을 하다보니 굳이 디자인 패턴을 적용할 필요가 있을까라는 의문이 들더라구요.. 이것에 대한 체프의 의견도 궁금합니다..!

돌아가는 코드가 가장 좋은 코드 아닐까요? 굳이 리팩토링해야 할 필요를 느끼지 못한다면 꼭 리팩토링하지 않아도 된다고 생각합니다. 학습 목적이 아니라면 디자인 패턴에 코드를 끼워 맞추는 실수를 하지 않기를 바랄게요.

2023-03-20 13:16 UTC, merged

2023-03-21 01:01 UTC, shackstack commented on src/components/MovieSearch.ts
> +    $searchInput.addEventListener("keyup", (event) => {
keydown을 적용할 때 이벤트가 두 번 발생해서 같은 영화목록이 중복되어 렌더링되어서요... 아직 정확한 원인을 찾지 못했는데 계속해서 고민해보겠습니다.