[2단계 - 영화 목록 불러오기] 에디(강상원) 미션 제출합니다.
woowacourse/javascript-movie-review pull request #54
Opened 2023-03-24 07:48 UTC by ksone02

# 안녕하세요! 에디입니다. ☀️

반갑습니다 유조!
1단계에 이어 잘부탁드립니다~

# 구현 기능
### 1. 📺 영화 상세정보 조회
  - API를 이용해 영화 정보를 불러와 모달창을 통해 영화 상세정보를 보여줍니다.
  - 기본적으로 `SPA`를 고려하고 모달을 `History API`를 이용해 구현했으며, 브라우저의 뒤로가기, 앞으로가기 버튼을 눌러도 링크가 그대로 살아있으면 모달이 유지됩니다.
  - 추가로 백스페이스 버튼을 눌러도 모달이 닫힙니다.
### 2. ⭐️ 별점 매기기
  - 사용자가 영화에 별점을 줄 수 있습니다.
  - 별점은 새로고침해도 유지가 됩니다. 이 부분은 `로컬스토리지`를 통해 구현했습니다.
### 3. 📐 UI / UX 개선
  - 더보기 버튼 대신, 무한 스크롤을 구현했습니다. 이 부분은 `IntersectionObserver` 객체를 통해 구현했습니다.
  - `반응형 레이아웃`을 구성했습니다.
  - `스켈레톤 UI`를 고도화 했습니다. 영화 리스트가 불러오는 부분과, 영화의 포스터가 불러오는 부분 두가지로 나누어 스켈레톤을 적용했습니다.
  - 추가로 모달 부분도 `스켈레톤 UI`를 구현했습니다. 모달 부분이 API로 데이터를 불러온 뒤 조금 늦게 뜨는게 마음에 들지 않아 스켈레톤 UI를 구현했습니다.
### 4. ☁️ SPA 구현
  - 앞에서 말씀드린 모달과, 메인페이지, 검색페이지 모두 `SPA`를 고려하고 구현했습니다.
  - 뒤로가기, 앞으로가기 모두 잘 되고, `Parameter`를 통해 검색 값과 영화의 데이터를 불러옵니다.
  - 같은 url이면 렌더링이 되지 않게 구현했습니다.

# 디자인(피그마)
https://www.figma.com/file/KcViH81qTQERbbJtBlTEqZ/%EB%A0%88%EB%B2%A81-%EB%AF%B8%EC%85%98-%EB%94%94%EC%9E%90%EC%9D%B8-(5%EA%B8%B0-%ED%81%AC%EB%A3%A8-%EA%B3%B5%EC%9C%A0%EC%9A%A9)?node-id=1%3A3&t=Qr1lURROp0hABEbG-1

# 배포 링크
https://641d54f0c33d540008305c97--astonishing-sorbet-71a8af.netlify.app/

2023-03-25 09:36 UTC, yujo11 requested changes
안녕하세요 에디~ 

다시 만나서 반갑습니다~

Modal도 잘 나오고 무한 스크롤도 잘 동작하네요~

Skeleton UI를 고도화 하신 부분은 아주 좋군요~ 👍 👍 👍 

>기본적으로 SPA를 고려하고 모달을 History API를 이용해 구현했으며, 브라우저의 뒤로가기, 앞으로가기 버튼을 눌러도 링크가 그대로 살아있으면 모달이 유지됩니다.

SPA를 고려하는 것과 모달을 Hisotry API로 구현하는 것에는 어떤 연관성이 있었을까요? 조금 더 자세하게 설명해주시면 좋을거 같아요~

그리고 추가로 현재 Modal을 열었다가 닫으면 화면이 깜박거리고 있는데요

![Mar-25-2023 18-09-40](https://user-images.githubusercontent.com/61097373/227709136-8ee3c4bb-4a1a-4a89-94d2-828030463543.gif)

평소 에디가 사용해오던 많은 SPA에서는 아마 이런 동작을 보지 못 하셨을거에요.

이 부분은 특히 스크롤을 내려서 추가로 영화 목록을 가져온 후 닫았을 때는 다시 그동안 호출했던 API들을 다시 호출하고 있는데요.

필요한 데이터만 서버로부터 가져오고, 렌더하도록 변경해보시면 좋을거 같네요!

고생 많으셨습니다 에디~~ 👍

2023-03-25 09:36 UTC, yujo11 commented on src/util/Router.ts
> +  const app = document.querySelector("app-component") as AppComponent;
이렇게 사용하고 app이 없을 때의 error 처리를 추가해봐도 좋겠네요

```suggestion
  const app = document.querySelector<AppComponent>("app-component");
```

2023-03-25 09:36 UTC, yujo11 commented on src/util/Router.ts
> +const closeModal = () => {
특정 페이지를 Modal로 보여주는거라면 해당 페이지의 주소를 url에 직접 입력했을 때 Modal이 떠있는 상태를 볼 수 있으면 좋겠네요~

지금은 모달이 열렸을 때 주소를 복사했다가 주소창에 붙여넣어서 이동하면 아래처럼 나오네요
<img width="1854" alt="image" src="https://user-images.githubusercontent.com/61097373/227708289-85badef8-ac82-47cb-98e7-f7019aa71345.png">

2023-03-25 09:36 UTC, yujo11 commented on src/util/Router.ts
> +const closeModal = () => {
그리고 `Modal`은 일반적으로 새 페이지로 이동하지 않고 현재 페이지 위에 새 레이어를 생성하여 정보를 표시할 때 많이 사용하는데요

어떤 페이지 자체가 `Modal`인게 조금 어색하게 느껴지네요

2023-03-25 09:36 UTC, yujo11 commented on src/components/modal/MovieModalComponent.js
Modal의 dimmed 영역을 클릭할 때도 Modal이 닫히도록 구현해보시면 좋을거 같네요

2023-03-25 09:36 UTC, yujo11 commented on src/components/modal/MovieModalComponent.js
> +    });
여기는 어떤 동작을 의도하신건지 잘 모르겠네요

2023-03-25 09:36 UTC, yujo11 commented on src/components/movie/ErrorComponent.js
> +    return /*html*/ `
👍👍👍

2023-03-25 09:36 UTC, yujo11 commented on src/util/Api.ts
> +};
fetchMovieDetails의 return type을 `MovieDetails`로 지정해놓는다면 이 과정도 필요없을거 같아요

2023-03-28 01:49 UTC, ksone02 commented on cypress/e2e/movie-e2e.cy.ts
> +// });
1단계 때의 흔적을 남기고 싶어서 남겨놨었는데, 지우겠습니다!

2023-03-28 01:52 UTC, ksone02 commented on src/components/modal/MovieModalComponent.js
> +    });
기능 요구 사항에 Backspace를 눌렀을 때 모달이 닫혀야 한다는 조건이 있었습니다!

2023-03-28 10:00 UTC, ksone02 commented on src/util/Router.ts
> +const closeModal = () => {
해당 부분 수정 완료했습니다!

2023-03-30 05:05 UTC, ksone02 commented on src/components/modal/MovieModalComponent.js
넵!

2023-03-30 05:09 UTC, ksone02 commented on src/components/AppComponent.js
> +    this.addEventListener("keypress", async (e) => {
keypress는 키를 누르고 있는 시점에 발생해 꾹 누르고 있다면 계속해서 발생할 수 있고,
keyup은 키에서 손을 뗄 때 발생합니다.

keyup으로 하니 왜인지 모르게 이벤트가 두번씩 발생하는 이슈가 있어서 쓰로틀링도 적용해보고 여러 방법을 써보았는데도 해결되지 않아 keypress로 변경했습니다.

2023-03-30 05:11 UTC, ksone02 commented on src/util/Router.ts
> +const closeModal = () => {
저도 동의합니다! '모달 창이 열렸을 때 뒤로가기로 모달을 닫을 수 있다'라는 요구 조건을 만족하려고 하다보니 이런식으로 설계하게 되었는데, 다시 생각해보니 요구 조건을 너무 과하게 해석했나 싶기도 하네요.

2023-03-30 05:15 UTC, ksone02 commented on src/util/Api.ts
> +};
구조적 타이핑을 사용해주면 개발자의 입장에서만 타입 지정이 되는거지, 실제로 log를 찍어보니 필요한 값만 반환되지 않고 모든 값이 그대로 나왔습니다.

저는 실제로 반환되는 값이 필요한 값만 반환 되었으면 좋겠다는 생각에 이런 로직을 굳이 만들어줬습니다.

2023-03-30 06:50 UTC, ksone02 commented
1. 모달 작동 방식을 변경했습니다. 저 역시 모달이 하나의 페이지로 구분되는 것이 어색하다고 느껴 router에서 삭제하고, 단순한 "모달"로 처리했습니다. 기능 요구조건이 변경되어 모달이 더 이상 뒤로가기로 닫아지게 하지 않아도 되더라구요.
2. 백스페이스를 누르면 모달이 닫힌다 -> dimmed 영역을 클릭하면 모달이 닫힌다 로 수정했습니다.

2023-03-30 17:29 UTC, yujo11 approved these changes
안녕하세요 에디~

벌써 레벨 1의 마지막 미션이고 제가 이 리뷰를 끝으로 이 PR을 머지할거기 때문에 마지막 리뷰가 되겠네요 ㅎㅎ

이번 미선을 진행하면서 에디는 하나를 얘기해도 둘을 생각하고 셋을 공부하는 크루라는 생각이 들었습니다 👍 👍 👍 

주제넘을 수 있지만 의사소통 부분에서 한 가지 첨언 드리고 싶은데요.

에디와 리뷰를 주고 받을 때 에디가 많이 딱딱한 사람처럼 느껴졌어요. 제가 에디라는 크루가 어떤 사람인지 모르고 비언어적 의사소통이 배제된 채로 에디가 남긴 PR본문과 코드, 코멘트로만 의사소통 하기 때문에 그렇게 느꼈을 수도 있는데요.

제가 우테코를 할 당시를 돌이켜보면 당시의 제가 에디와 같은 모습을 많이 보였고, 그로 인해 우테코 기간 동안 "조금 더 적극적으로 소통하면 좋았을걸..." 하는 아쉬움이 남기 때문에 조금 더 신경이 쓰였습니다 ㅎㅎ

에디가 앞으로 조금 더 유연하고 적극적으로 어떤 생각을 가지고 있는지 표현하면서 남은 우테코 기간을 진행하시면 좋을거 같다는 생각이 듭니다! 비단 우테코 기간 뿐만 아니라 앞으로 에디가 다니게 될 회사들도 대면하며 소통하는 일이 많지 않을 확률이 크니까요!

우테코 당시의 제 얘기를 조금만 더 해보면(TMI..) 당시 저는 완벽한 코드에 대한 갈망과 더불어 제가 작성한 코드에 대한 비판이 두려웠는데요. 조금 지나고보니 코드는 코드이고 저는 저일 뿐이더라구요. 호옥시나 에디가 이런 부분에서 스트레스를 받으신다면 코드에 대한 보다 열린 마음으로 수용하시면 더더욱 성장하시는 데 도움이 되실거라고 생각합니다~

레벨 1 기간 동안 정말 고생 많으셨습니다~ 앞으로도 더욱 성장해나가실 에디의 모습이 기대 되네요!! 👍 👍 👍

2023-03-30 17:29 UTC, yujo11 commented on cypress/e2e/movie-e2e.cy.ts
> -// });
👍👍

2023-03-30 17:29 UTC, yujo11 commented on src/util/Router.ts
>    }
이미 많이 들은 얘기일거 같지만 중첩된 조건문은 코드를 읽기 전부터 조금은 어지러운 느낌이 드는데요

early return 등을 적절히 활용해보셨으면 좋겠네요~

2023-03-30 17:35 UTC, merged