[2단계 - 영화 목록 불러오기] 고니(정우시) 미션 제출합니다.
woowacourse/javascript-movie-review pull request #82
Opened 2023-03-26 22:45 UTC by jeongwusi

체프 안녕하세요~! 즐거운 주말 보내셨나용? ㅎㅎ

코드를 다시 작성하다 보니 미션 제출이 늦어진 점 양해해 주시기 바랍니다. 🥲

저에게 있어서 이번 2단계 미션에 임하는 자세는 '최대한 구현과 e2e 테스트까지 해보자'라는 마음이었습니다. 이러한 점에 있어서 어느 정도는 한 거 같아서 나름 뿌듯합니다. 😅

이번 미션은 아래와 같은 사항을 염두에 두면서 미션을 진행하였습니다.

### 1. 컴포넌트

프론트엔드 분야에 있어서 컴포넌트라는 개념은 굉장히 중요하다고 생각합니다. 우테코 레벨 1에서도 3주차 미션부터 컴포넌트에 대한 개념에 대해서 고민의 화두로 던져주었습니다.

제가 생각하는 컴포넌트는 도메인 지식은 불필요합니다. 그리고 받아오는 데이터를 기반으로 그려주는 화면과 관련 이벤트 정도가 컴포넌트의 역할이라고 생각하였습니다.

또한 app 파일은 컴포넌트에서 발생한 이벤트를 받아서 데이터를 가공하고 있으며, render라는 객체를 분리하여 의존성을 낮추기 위해 노력하였습니다.

### 2. CustomEvent()

이번 미션에서는 커스텀 이벤트를 사용해보았습니다. 아무래도 커스텀 이벤트를 통해 가독성이 높아져 코드를 쉽게 이해할 수 있었습니다. 또한 오류 발생 시 이벤트의 발생 시점을 빠르게 파악할 수 있다보니 오류를 쉽게 파악할 수 있었습니다. 이러한 이유로 커스텀 이벤트를 사용해보았습니닷

### 3. 무한 스크롤
더보기 버튼을 없애고 무한 스크롤을 도입하기 위해 `IntersectionObserver`라는 기술을 도입하였습니다. 해당 기술에 대해서 완전히 학습을 한 상태는 아니지만... 추후 차근차근 알아보려고 합니다. ^^

그럼... 확인 부탁드립니다. 😁

감사합니다. 🙇🏻

2023-03-27 14:54 UTC, Puterism requested changes
코드를 처음부터 다시 작성하셨군요! 😮 새로 짠 코드는 마음에 드시나요?
전체적으로 구조적이고 일관성 있는 코드가 되어서 저는 좋다고 생각해요! 생각나는 피드백이 많이 없었네요. 수고 많으셨습니다 :)
각 코드 라인에 코멘트 달아두었으니 확인 부탁드릴게요!

2023-03-27 14:54 UTC, Puterism commented on src/types/fetchType.ts
> +export type FetchStandard = PopularFetchType | SearchFetchType;
FetchStandard라는 네이밍은 어떤 의미인가요?

2023-03-27 14:54 UTC, Puterism commented on src/render/init.ts
> +export default () => {
익명 함수를 그대로 export default해도 되지만, 해당 함수가 어떤 역할을 하는 함수인지 알기 위해서는 파일명까지 들여다 봐야 한다는 단점이 있을 것 같아요.
취향의 영역이라는 생각도 들지만 조금 마음에 걸려서 코멘트 남겨봅니다 :)

2023-03-27 14:54 UTC, Puterism commented on src/libs/handleLocalStorage.ts
> +};
localStorage도 그렇고 dataProcessors도 그렇고 관련된 로직을 한 번씩 wrapping해서 사용하기 좋게 정리해주셔서 좋네요 👍

2023-03-27 17:09 UTC, jeongwusi commented on src/render/init.ts
> +export default () => {
저도 체프의 리뷰를 보고 다시 생각을 해보니 익명 함수를 그대로 `export default`하는 것보다, 함수의 이름을 지정하고 `export default`문 다음에 함수를 호출하는 것이 더 명확하고 가독성이 있다고 느꼈습니다.

`init`이라는 이름을 가진 함수로 정의를 하였습니닷

2023-03-27 17:51 UTC, jeongwusi commented on src/components/SearchBox.ts
> +    this.$searchBoxLayout.addEventListener('mouseleave', this.mouseLeaveSearchIcon.bind(this));
감사합니다. ^^

2023-03-27 17:52 UTC, jeongwusi commented on src/libs/handleLocalStorage.ts
> +};
아핫 ㅎㅎ 감사합니다!

2023-03-27 17:57 UTC, jeongwusi commented on src/constant/constant.ts
> +export const SCREEN_WIDTH = 600;
모바일 환경을 의미하는 `SCREEN_MOBILE_WIDTH`으로 수정하였습니다!

2023-03-27 18:23 UTC, jeongwusi commented on src/domains/fetchJson.ts
> +const fetchJson: FetchJson = async (url: string) => {
이번에는 실제로 오는 데이터를 모두 정의한 후 이를 사용하기 위해 노력하였습니닷 😄

2023-03-27 18:28 UTC, jeongwusi commented on src/app.ts
> +    } = event as Event & { detail: { keyword: string } };
`Event` 대신 `CustomEvent<{ keyword: string }>`와 같이 사용자 정의 이벤트 타입을 지정 등 최대한 assertion을 안하는 방향으로 고치고 싶은데... 에러가 계속 나오네용 ^_^; 이 부분 추후 타입스크립트에 대한 공부를 조금 더 한 후 해결을 해보도록 하겠습니당...ㅎㅎ

2023-03-28 07:07 UTC, Puterism commented on src/app.ts
> +    } = event as Event & { detail: { keyword: string } };
아하... 그렇군요. 저도 `CustomEvent<{ keyword: string }>`을 생각했는데, addEventListener에서 EventListener 타입에 맞지 않는다는 에러가 나는군요.

```tsx
document.addEventListener('searchMovies', this.searchMovies.bind(this) as EventListener);
```

이렇게 쓰면 에러가 해소되긴 하지만 찝찝하네요 😅
요건 아직도 열려 있는 [이슈](
https://github.com/microsoft/TypeScript/issues/28357)가 있는 것을 보면 타입스크립트 자체의 문제에 조금 더 가까운 것 같습니다.
왜 CustomEvent를 허용하지 않았을까요 🤔 
현재로써는 declare module 이외의 방법은 없어보이네요. 넘어가셔도 좋을 것 같습니다!

2023-03-28 07:29 UTC, jeongwusi commented on src/app.ts
> +    } = event as Event & { detail: { keyword: string } };
아핫...! 관련된 이슈가 있었군요^^ 확인해주셔서 감사합니닷

2023-03-30 08:42 UTC, jeongwusi commented on src/components/SearchBox.ts
> +    this.$searchBoxLayout.addEventListener('mouseleave', this.mouseLeaveSearchIcon.bind(this));
`setTimeout()`를 이용하여 이벤트가 연속적으로 발생하는 문제를 해결하였습니닷❕

2023-03-30 08:46 UTC, jeongwusi commented
안녕하세요 체프~!

관련된 오류 수정 후 새롭게 배포하였습니당. 확인 부탁드립니다. 😊

감사합니다. 🙇🏻

---

### 배포 링크 

https://effulgent-biscochitos-6b50f5.netlify.app/

2023-03-30 10:10 UTC, Puterism approved these changes
> P.S. 체프 커피를 좋아하시는 거 같더라구여 ^^ 기회가 된다면 저랑도 커피 한잔 해욧 ☕️

언제든지 불러주세요! DM 기다리겠습니다 😃

---

그 동안 레벨 1 미션까지 수행하시느라 수고 많으셨습니다!
방학 잘 보내시구요. 레벨 2 미션도 화이팅입니다!

2023-03-30 10:10 UTC, merged

2023-04-01 15:40 UTC, jeongwusi commented on src/components/SearchBox.ts
> +    }, 500);
이벤트의 연속적인 발생이 문제라고 생각을 해서 조건문 등으로 코드 구성을 수정하기 위해 노력하였습니다. 다만 해당 오류가 계속 나와서... setTimeout을 통해 시간차를 이용하여 문제를 해결하였습니다. 🥲