[2단계 - 영화 목록 불러오기] 푸만능(황준승) 미션 제출합니다.
woowacourse/javascript-movie-review pull request #87
Opened 2023-03-27 06:30 UTC by turtle601

## 브콜에게

안녕하세요~ `브콜✨` 리뷰 요청이 늦어진 점 먼저 죄송하다고 말씀드리고 싶어요!!
브콜께서 구조적인 문제를 고려하지 말라고 했지만 구조적인 문제에 대한 고민하는 시간을 계속 보내서 PR을 늦게 보냈습니다!!
( 하지만 구조적으로 바뀐 점은 없어요!! )

이번 미션 성심성의껏 리뷰 남겨줘서 너무 좋았어요 `브콜✨` !! 
특히 `Observer 패턴`과 `Proxy`에 대한 전체적인 틀을 알려주셔서 재미있게 학습할 수 있었습니다!!

## 신경 쓴 점

1. `debounce` vs `throttle`

무한 스크롤 구현 시 fetching을 연속적으로 하는 것을 방지하기 위해 `throttle`을 사용하였습니다.

> 둘의 차이는 Throttle의 경우 일정 시간마다 이벤트가 실행되는 것을 보장한다는 것이고, Debounce는 그렇지 않다는 것이다. 풀어서 설명해보면, Debounce는 일정 시간 내에 다시 이벤트가 실행될 경우 타이머가 초기화 되어 다시 일정 시간만큼 기다리지만, Throttle은 이벤트가 다시 실행되는 것과는 상관 없이 일정 시간마다 이벤트를 발생시킨다. [throttle vs debounce](https://ye-yo.github.io/til/2022/03/29/debounce-throttle.html#:~:text=%EC%B0%A8%EC%9D%B4%EC%A0%90,Debounce%EB%8A%94%20%EA%B7%B8%EB%A0%87%EC%A7%80%20%EC%95%8A%EB%8B%A4%EB%8A%94%20%EA%B2%83%EC%9D%B4%EB%8B%A4.) 

그래서 여러 이벤트 발생 시 이벤트들을 묶어서 하나의 이벤트를 실행하는 `debounce` 보다 일정 시간 마다 이벤트를 발생시키는 `throttle`을 사용했습니다.

추가적으로 debounce와 throttle을 묶어서 사용할 수 있는 `delayHelper`라는 함수를 클로저를 사용해서 만들었습니다!! (이 코드에 대한 `브콜✨`에 생각이 궁금합니다!!)

---

2. `Observer API` vs `getBoundingClientRect()`

무한 스크롤을 구현하기 위한 두 가지 방법
1. `Observer API`를 사용해서 무한 스크롤을 구현하는 방식
2. `getBoundingClientRect()`를 사용해서 해당 dom이 노출된 것을 계산해서 무한 스크롤을 구현하는 방식

이 있다고 학습했고 두 메서드 사용 시 차이점에 대해 공부했습니다. 

getBoundingClientRect()의 경우 해당 dom의 위치를 일일이 계산을 하기 때문에 리플로우 리페인트 과정이 계속 반복됩니다. 

반면 Observer API의 경우 이 과정에서 최적화가 일어나서 최소한의 리플로우 리페인트 과정이 일어난다고 학습했습니다. 

자세한 내용을 [아래 블로그 글](https://velog.io/@turtle601/JS-%EC%8A%A4%ED%81%AC%EB%A1%A4-%EC%8B%9C-%ED%8E%98%EC%9D%B4%EB%93%9C-%EC%9D%B8Fade-IN-%EA%B5%AC%ED%98%84-feat.-%EC%84%B1%EB%8A%A5-%EB%B9%84%EA%B5%90-Intersection-Observer-API)에 정리했습니다. 

사실 성능 분석의 경우 아직 학습이 부족하여 블로그 글을 본  `브콜✨`에 생각과 의견이 너무 궁금해요!!

---

3. 에러 페이지에 대한 저의 생각

"저희가 만든 앱에서는 과연 404, 400관련 에러가 뜰까"에 대한 고민입니다.
처음 에러 페이지를 만들 때는 사용자 에러를 도출하는 `400~` 페이지와 서버 문제에 대한 에러를 도출하는 `500~`
를 만들려고 했으나 실제로 저희 앱에서 "400~에러가 나올까"에 대한 의문이 있습니다.

실제로 구현을 할 때 api 요청 url을 저희가 다 넣어주기 때문에 굳이 400관련 에러를 만들 필요가 있을까에 대한 의문이 있어서 500에러와 쿼리 입력 시 아무런 무비 데이터를 가져오지 않을 때 에러를 도출하도록 구현하였습니다.

`브콜✨`의 생각이 궁금합니다. 

## 아직 잘 모르겠는 점

2023-03-28 19:12 UTC, Tanney-102 requested changes
안녕하세요 푸만능~
레벨1 마지막 미션 고생 많으셨습니다!
함수들이 아주 깔끔해서 읽기 좋았어요~
지난 미션에서 잘 작성해주셔서 이번에는 크게 리뷰드릴만한 점이 없었습니다!
몇몇 소소한 코멘트 남겼으니 확인 부탁드려요.

> 추가적으로 debounce와 throttle을 묶어서 사용할 수 있는 delayHelper라는 함수를 클로저를 사용해서 만들었습니다!! (이 코드에 대한 브콜✨에 생각과 브콜이라면 throttle, debounce 어떤 로직을 사용하실 건가요??)

delayHelper에 대해서는 코멘트로 남겨두었습니다.
근본적으로는 지금 코드에서 throttle이나 debounce가 정말 필요했는지 고민해보시면 좋겠습니다.
이 두 유틸은 주로 짧은 시간에 같은 동작이 많이 반복될 때 사용되어요.
그런데 지금의 사용처를 보면 intersection observer에 의해 변경이 감지되었을 때만 throttle이 적용된 함수가 호출되고 있어요.
intersection observer의 callback 호출이 throttle의 대상이 되어야하는지 고민해보시면 좋겠습니다!

추가로..
만약 위 상황이 빠른 시간 안에 연속적으로 fetch를 하는 상황이고, 이를 해결하고자 했다면 debounce가 더 적절하지 않았나 싶기도 하네요!
debounce는 처리를 지연하는 것을 목적으로 하고 throttle은 처리하는 양을 줄이기 위해 사용합니다.
다음 페이지(보통 한 페이지겠죠?)를 fetch하는 게 하려는 동작이고 이를 위한 요청이 짦은 시간에 의도치 않게 여러번 발생하는 상황이라면 같은 요청들을 그룹화하고 이를 지연시켜 안정적으로 1회만 처리하는 게 더 기획에 맞지 않나 싶어요.

> 무한 스크롤을 구현하기 위한 두 가지 방법
Observer API를 사용해서 무한 스크롤을 구현하는 방식
getBoundingClientRect()를 사용해서 해당 dom이 노출된 것을 계산해서 무한 스크롤을 구현하는 방식
이 있다고 학습했고 두 메서드 사용 시 차이점에 대해 공부했습니다.

블로그 잘 봤습니다~
직접 성능 측정까지 하시다니 대단하네요👍
말씀해주신 것처럼 getBoundingClientRect는 리플로우를 유발합니다.
꼭 성능 문제가 아니더라도 직접 위치를 계산하는 것보다 intersection 여부를 observe 하는 편이 더 직관적이고 좋긴하겠죠~

> 실제로 구현을 할 때 api 요청 url을 저희가 다 넣어주기 때문에 굳이 400관련 에러를 만들 필요가 있을까에 대한 의문이 있어서 500에러와 쿼리 입력 시 아무런 무비 데이터를 가져오지 않을 때 에러를 도출하도록 구현하였습니다.

에러는 클라에서 어떤 요청을 하느냐가 아니라 서버에서 어떤 응답을 주느냐를 기준으로 처리해야하지 않을까요~? tmdb는 어떤 에러를 주던가요? 아래를 참고해보시면 좋겠네요.
https://www.themoviedb.org/documentation/api/status-codes

2023-03-30 00:09 UTC, turtle601 commented on src/components/MovieList/MovieListContainer.ts
> +      e.preventDefault();
MovieList 안에 있는 MovieItem의 a태그 이벤트를 막기 위함입니다!!

2023-03-30 00:26 UTC, turtle601 commented on src/utils/apiHelper.ts
> +  if (fetchingData.status !== 200) return null;
> 수정했습니다!!

2023-03-30 02:13 UTC, turtle601 commented on src/utils/cache.ts
> +};
> 수정했습니다!!

2023-03-30 02:16 UTC, turtle601 commented on src/utils/infiniteScroll.ts
> +        delayHelper().throttle(() => fn(), 900)();
`브콜✨`에 말씀하신대로 매번 새로운 delayHelper 함수를 호출, 매번 새로운 setTimeoutId를 생성하기 때문에 별로 좋은 방법은 아닌거 같아요!!

2023-03-30 02:29 UTC, turtle601 commented
> intersection observer의 callback 호출이 throttle의 대상이 되어야하는지 고민해보시면 좋겠습니다!
기존의 scroll 이벤트의 경우 조금만 움직여도 연속적인 호출이 발생하기 위해 함수 지연을 위해서 debounce나 throttle의 함수가 사용되었지만 Intersection observer의 경우 특정 구역에 도착했을 때 다음 이벤트가 한번만 생성되기 때문에 굳이 debounce나 throttle을 사용할 필요는 없었을 거 같습니다!!

하지만 제가 이전 코드에서 throttle을 사용한 이유는 정말 빠르게 스크롤을 날렸을 경우 서버 입장에서도 상당히 많은 요청을 한번에 보내기 때문에 이러한 점이 문제가 발생할 수도 있겠다고 판단하여 throttle을 사용했습니다. 

> 만약 위 상황이 빠른 시간 안에 연속적으로 fetch를 하는 상황이고, 이를 해결하고자 했다면 debounce가 더 적절하지 않았나 싶기도 하네요!
debounce는 처리를 지연하는 것을 목적으로 하고 throttle은 처리하는 양을 줄이기 위해 사용합니다.

아직 throttle과 debounce를 어떻게 언제 사용해야될지는 명확히 감이 오지는 않는 거 같아요... (현업에서는 어떤 식으로 사용하는지 자세한 예시를 듣고 싶어요!!)

2023-03-30 02:29 UTC, turtle601 commented on src/utils/infiniteScroll.ts
> +        delayHelper().throttle(() => fn(), 900)();
> intersection observer의 callback 호출이 throttle의 대상이 되어야하는지 고민해보시면 좋겠습니다!
기존의 scroll 이벤트의 경우 조금만 움직여도 연속적인 호출이 발생하기 위해 함수 지연을 위해서 debounce나 throttle의 함수가 사용되었지만 Intersection observer의 경우 특정 구역에 도착했을 때 다음 이벤트가 한번만 생성되기 때문에 굳이 debounce나 throttle을 사용할 필요는 없었을 거 같습니다!!

하지만 제가 이전 코드에서 throttle을 사용한 이유는 정말 빠르게 스크롤을 날렸을 경우 서버 입장에서도 상당히 많은 요청을 한번에 보내기 때문에 이러한 점이 문제가 발생할 수도 있겠다고 판단하여 throttle을 사용했습니다. 

> 만약 위 상황이 빠른 시간 안에 연속적으로 fetch를 하는 상황이고, 이를 해결하고자 했다면 debounce가 더 적절하지 않았나 싶기도 하네요!
debounce는 처리를 지연하는 것을 목적으로 하고 throttle은 처리하는 양을 줄이기 위해 사용합니다.

아직 throttle과 debounce를 어떻게 언제 사용해야될지는 명확히 감이 오지는 않는 거 같아요... (현업에서는 어떤 식으로 사용하는지 자세한 예시를 듣고 싶어요!!)

2023-03-30 02:50 UTC, turtle601 commented
안녕하세요 `브콜✨`!! 
에러 관련 궁금한 내용이 하나 더 있어서 질문드립니다!!

> 에러는 클라에서 어떤 요청을 하느냐가 아니라 서버에서 어떤 응답을 주느냐를 기준으로 처리해야하지 않을까요~? tmdb는 어떤 에러를 주던가요? 아래를 참고해보시면 좋겠네요.

서버에서 요청한 에러코드들을 프론트에서 무조건 보여줘야하는 의무가 있을까요?? (지금 같이 특정 기능만 사용하는 경우 굳이 다 만들 필요가 있을까요??)

에러 코드에 대한 각각의 에러 메세지들을 따로 다 만들어야 할까요??

`브콜✨`의 생각이 궁금합니다!!

2023-03-31 13:51 UTC, Tanney-102 requested changes
안녕하세요 푸만능~ 
반응이 늦었네요ㅠㅠ
반영해주신 내용 잘 확인했습니다.
추가로 드린 코멘트만 확인해주시면 될 것 같아요!
더 수정을 안하셔도 됩니다. 코멘트 확인 후에 알려주시면 바로 머지 하겠습니다!

> 하지만 제가 이전 코드에서 throttle을 사용한 이유는 정말 빠르게 스크롤을 날렸을 경우 서버 입장에서도 상당히 많은 요청을 한번에 보내기 때문에 이러한 점이 문제가 발생할 수도 있겠다고 판단하여 throttle을 사용했습니다.

넵 스크롤 이벤트를 통해 수행했다면 필요했을 것 같습니다!

> 아직 throttle과 debounce를 어떻게 언제 사용해야될지는 명확히 감이 오지는 않는 거 같아요... (현업에서는 어떤 식으로 사용하는지 자세한 예시를 듣고 싶어요!!)

현업이라고 하면 조금 거창하고.. 두 개념의 다른 점만 잘 이해하시면 될 것 같습니다.
결국 들어오는 요청들을 '하나의 일'을 수행하기 위한 여러개의 같은 요청들로 볼 것인지, 각각 독립적인 요청으로 볼 것인지 차이일 것 같아요.

푸만능이 친구랑 약속을 잡는다고 가정해볼까요?
디바운스는 변덕스러운 친구 한 명과 약속을 잡는 프로세스에 유용합니다.
이 친구는 너무 바빠서 약속된 날이 되기도 전에 약속을 취소하고 다시 일정을 잡습니다.
일정을 바꾸자는 요청이 올때마다 앞선 일정들은 필요가 없어집니다. 결국 만나는 건 마지막에 정한 일정 하루입니다.

디바운스 예시로는 키보드 입력을 통해 검색 요청을 하는 상황이 대표적입니다. 
'푸만능'을 검색한다고 가정합시다.
'ㅍ', '푸', '품', '푸마', '푸만', ... 순서로 검색 요청이 들어옵니다.
이 기능을 통해 얻기 원하는 건 '하나의 검색 결과 화면'입니다.
키보드가 변덕스럽게 키워드를 바꿔도 일일이 다 대응해줄 필요가 없습니다. 최종 키워드를 가지고 한 번만 검색하면 충분합니다.

이번에 구현하신 Infinite Scroll도 마찬가지입니다.
순간적으로 얼마나 많은 요청이 들어오든 원하는 건 '다음 한 페이지 분량의 컨텐츠' 입니다.
여러페이지를 보여줄 의도가 아니라면 마지막 요청에 대해 한 번만 get 요청을 보내면 충분합니다.
그래서 debounce를 제안 드렸습니다!

쓰로틀은 어떨까요?
쓰로틀은 여러 친구들과 약속을 잡을 때 유용합니다.
푸만능이 너무 인싸라서 매주 수십명의 친구에게 만나자는 요청이 들어온다고 가정해봅시다.
푸만능은 하루에 한 명만 만나기로합니다.
어느 하루 A를 만나기로했다면 그날은 다른 약속을 잡지 않습니다.
뒤에 잡힌 약속이 A와 만나기로한 약속에 영향을 주지도 않습니다.
이러한 예시처럼 각각의 요청이 독립적으로 모두 수행될 필요가 있을 때 쓰로틀을 고려해볼 수 있습니다.

드래그를 통해 특정 엘리먼트를 옮기는 기능을 구현한다고 가정해볼까요?
마우스 위치에 따라 그 엘리먼트의 위치를 조정할 것을 요청한다고 합시다.
마우스가 움직일 때마다 발생하는 이벤트는 모두 독립적으로 실행되어야합니다.
그래야 엘리먼트도 자연스럽게 움직이는 것처럼 보일테니까요.
여기서 성능을 고려한다고 디바운스를 사용하면 마우스가 멈추기 전까지 엘리먼트는 움직이지 않겠죠.
쓰로틀을 사용해 300ms 마다 실행되도록 하면 어떨까요? 뚝뚝 끊기기야 하겠지만 마우스가 움직임에 따라 엘리먼트도 지속적으로 움직이겠죠. 연속적으로 수행되는 일에 숱을 치는 일이 쓰로틀입니다.

> 서버에서 요청한 에러코드들을 프론트에서 무조건 보여줘야하는 의무가 있을까요??

무조건 다 보여줄 의무는 없습니다.
다만 적어도 사용하는 api에 대한 에러를 찾아보고 고민해보시기를 기대했습니다~
api 사용범위가 적어 따로 에러에 대해 더 고민하기 어려웠을 것 같긴하네요..!

> 추가적으로 apikey만 제대로 전송하게 되면 400에러는 발생하지 않고 서버 문제 500에러 관련만 발생하게 되는데 사용자 입장에서는 501, 502인지는 궁금하지 않을 거 같습니다!! 사용자 입장에서는 서버 잘못인지 사용자 잘못인지만 궁금할 거 같아서 거기에 대한 내용만 에러 페이지를 보여주면 괜찮을 거 같다는 개인적인 생각이 있습니다

사용자 입력을 통한 요청이 있지 않았던가요?(/search/movie)
사용자 입력이 서버로 전달되고 있는데 validation이 없는 게 더 이상해보여요..
400에러가 나지 않을 거라고 장담하는 건 위험해 보입니다.
실제 재현 경로는 잘 모르겠지만 [문서](https://developers.themoviedb.org/3/search/search-movies)에 나와있는 에러에 대해서만이라도 한 번 고려해봤으면 어땠을까해요.

물론 지금처럼 검색 결과가 오지 않을 때의 fallback만 있어도 충분할 것 같긴합니다.
나중에 더 복잡한 api를 사용하게 된다면 사용자 입력에 대해 server가 어떻게 validation을 하는지도 고려해보시면 좋겠습니다~

추가로 문서에 제대로 안나와 있긴하지만(이건 tmdb 잘못이긴합니다😁) 검색 키워드의 maxLength로 validation 하고 있네요! (minLength도 있는 것 같은데 이건 잘 처리해주고 계신 것 같군요!)
물론 극단적인 케이스(500 characters..)라 일반적으로는 발생하지 않을 에러같긴합니다 ㅎㅎ

<img width="574" alt="스크린샷 2023-03-31 오후 10 40 32" src="https://user-images.githubusercontent.com/57767891/229135871-25244d95-04bc-4569-9640-edaea3be9ebc.png">

2023-03-31 14:29 UTC, Tanney-102 approved these changes
미션 마감을 위해 머지합니다! 
앞서 드린 코멘트만 확인해주세요!
고생 많으셨습니다!!

2023-03-31 14:29 UTC, merged